package library_book_service.services.book_db;

import java.util.List;
import java.util.Optional;
import java.util.UUID;
import library_book_service.model.book_db.User;
import library_book_service.repositories.book_db.UserRepository;
import library_book_service.services.ServiceBase;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * User service -- request-scoped unit-of-work wrapper over {@link UserRepository }.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Service
public class UserService extends ServiceBase {

  private final UserRepository userRepository;

  public UserService(UserRepository userRepository) {
    this.userRepository = userRepository;
  }

  public Optional<User> get(UUID id) {
    return this.userRepository.findById(id);
  }

  public List<User> list() {
    return this.userRepository.findAll();
  }

  public Optional<User> getByEmail(String email) {
    return this.userRepository.findByEmail(email);
  }

  @Transactional
  public User create(User entity) {
    return this.userRepository.save(entity);
  }

  @Transactional
  public User update(User entity) {
    return this.userRepository.save(entity);
  }

  @Transactional
  public void delete(UUID id) {
    this.userRepository.deleteById(id);
  }
}
