package warehouse_warehouse_service.model.warehouse_db;

import jakarta.persistence.CheckConstraint;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import org.locationtech.jts.geom.Geometry;

/**
 * DeliveryZone JPA entity.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Entity
@Table(
    name = "delivery_zones",
    indexes = {},
    uniqueConstraints = {},
    check = {
      @CheckConstraint(
          name = "ck_delivery_zones_name_max_length",
          constraint = "length(name) <= 200"),
      @CheckConstraint(
          name = "ck_delivery_zones_zone_code_max_length",
          constraint = "length(zone_code) <= 50")
    })
public class DeliveryZone extends BaseEntity {

  @Column(name = "name", columnDefinition = "varchar(200)", nullable = false)
  private String name;

  @Column(name = "zoneCode", columnDefinition = "varchar(50)", nullable = false, unique = true)
  private String zoneCode;

  @Column(name = "coverageArea", columnDefinition = "geometry(Geometry,4326)", nullable = false)
  private Geometry coverageArea;

  @Column(name = "radiusNm", columnDefinition = "double precision", nullable = false)
  private Double radiusNm;

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getZoneCode() {
    return this.zoneCode;
  }

  public void setZoneCode(String zoneCode) {
    this.zoneCode = zoneCode;
  }

  public Geometry getCoverageArea() {
    return this.coverageArea;
  }

  public void setCoverageArea(Geometry coverageArea) {
    this.coverageArea = coverageArea;
  }

  public Double getRadiusNm() {
    return this.radiusNm;
  }

  public void setRadiusNm(Double radiusNm) {
    this.radiusNm = radiusNm;
  }

  /**
   * Build a new {@link DeliveryZone} from a DSL object-literal map, setting only the keys present
   * in {@code data} (a key absent from {@code data} leaves the corresponding field at its normal
   * Java default -- {@code null} unless the field declares its own initializer above). Keys are the
   * AS-AUTHORED DSL field name (Java's own object-literal emission, {@code _datrixOrderedMap(...)},
   * preserves author-declared spelling -- no case conversion), which for a camelCase-authored DSL
   * field is identical to this entity's own camelCase Java field name.
   *
   * <p>Backs {@code db.DeliveryZone.create({...})} lowering (`transpiler/
   * _entity_query_dispatch.py::transpile_entity_create`) -- entities have no `Map`-consuming
   * constructor, so the transpiled object literal is fed through this static factory instead of
   * `new DeliveryZone(...)`.
   */
  public static DeliveryZone fromMap(java.util.Map<String, Object> data) {
    DeliveryZone result = new DeliveryZone();
    if (data.containsKey("name")) {
      Object __v = data.get("name");
      result.setName((String) __v);
    }
    if (data.containsKey("zoneCode")) {
      Object __v = data.get("zoneCode");
      result.setZoneCode((String) __v);
    }
    if (data.containsKey("coverageArea")) {
      Object __v = data.get("coverageArea");
      result.setCoverageArea((Geometry) __v);
    }
    if (data.containsKey("radiusNm")) {
      Object __v = data.get("radiusNm");
      result.setRadiusNm(__v instanceof Double __n ? __n : ((Number) __v).doubleValue());
    }
    return result;
  }
}
