test:
  nosql:
    engine: mongodb
    port: 27017
    uri: mongodb://localhost:27017
    database: logistics_tracking
    docker_image: mongo:8.0
    volume_path: /data/db
    healthCheckCmd: '["CMD", "mongosh", "--eval", "db.runCommand(\"ping\").ok"]'
    platform: container

development:
  nosql:
    engine: mongodb
    port: 27017
    uri: mongodb://localhost:27017
    database: logistics_tracking
    docker_image: mongo:8.0
    volume_path: /data/db
    healthCheckCmd: '["CMD", "mongosh", "--eval", "db.runCommand(\"ping\").ok"]'
    platform: container

production:
  nosql:
    engine: mongodb
    port: 27017
    uri: ${SHIPMENT_NOSQL_URI}
    database: logistics_tracking
    docker_image: mongo:8.0
    volume_path: /data/db
    healthCheckCmd: '["CMD", "mongosh", "--eval", "db.runCommand(\"ping\").ok"]'
    platform: managed
