"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.create_table(
        "books",
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            "price",
            sa.Numeric(19, 4),
            nullable=False,
        ),
        sa.Column(
            "slug",
            sa.String(255),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "tags",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "weight",
            sa.Numeric(precision=10, scale=2),
            nullable=False,
        ),
        sa.Column(
            "publish_date",
            sa.Date(),
            nullable=False,
        ),
        sa.Column(
            "last_accessed_from",
            sa.String(45),
            nullable=True,
        ),
    )


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_table("books")
