"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "user_role" AS ENUM (\'customer\', \'admin\', \'support\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "user_status" AS ENUM (\'active\', \'inactive\', \'suspended\', \'pending\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(320),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "password_hash",
            sa.String(255),
            nullable=False,
        ),
        sa.Column(
            "first_name",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "last_name",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "phone_number",
            sa.String(20),
            nullable=True,
        ),
        sa.Column(
            "role",
            sa.Enum('customer', 'admin', 'support', name='user_role', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum('active', 'inactive', 'suspended', 'pending', name='user_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "email_verified_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "email_verification_token",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "password_reset_token",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "password_reset_expiry",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "shipping_address",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "billing_address",
            sa.JSON(),
            nullable=True,
        ),
    )
    op.create_table(
        "user_sessions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "token",
            sa.String(255),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "device_name",
            sa.String(500),
            nullable=True,
        ),
        sa.Column(
            "ip_address",
            sa.String(45),
            nullable=True,
        ),
        sa.Column(
            "user_agent",
            sa.String(255),
            nullable=True,
        ),
        sa.Column(
            "expires_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "last_activity_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "user_id",
            sa.Uuid,
            nullable=False,
        ),
    )
    op.create_table(
        "user_preferences",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.String(10),
            nullable=False,
        ),
        sa.Column(
            "timezone",
            sa.String(50),
            nullable=False,
        ),
        sa.Column(
            "email_notifications",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "sms_notifications",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "preferences",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "user_id",
            sa.Uuid,
            nullable=False,
        ),
    )
    op.create_index("ix_users_status_role", "users", ["status", "role"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_index("ix_user_sessions_user_id_expires_at", "user_sessions", ["user_id", "expires_at"], unique=False)
    op.create_index("ix_user_sessions_token", "user_sessions", ["token"], unique=False)


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_index("ix_user_sessions_token", table_name="user_sessions")
    op.drop_index("ix_user_sessions_user_id_expires_at", table_name="user_sessions")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_status_role", table_name="users")
    op.drop_table("user_preferences")
    op.drop_table("user_sessions")
    op.drop_table("users")
