// MemberDbQueryDurationInterceptor.cs -- EF Core DbCommandInterceptor recording real command
// execution duration into PersistenceMetrics.QueryDuration for RDBMS block
// "memberDb". Registered via
// `.AddInterceptors(new MemberDbQueryDurationInterceptor())` on this block's `AddDbContext<T>`
// call (program_generator.py::build_persistence_registration_block).
// CommandExecutedEventData.Duration is EF Core's own measured wall-clock
// duration for the just-completed command -- never a second, hand-rolled
// Stopwatch measurement.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.

using System.Data.Common;
using Microsoft.EntityFrameworkCore.Diagnostics;

namespace MemberService.Data.MemberDb;

public sealed class MemberDbQueryDurationInterceptor : DbCommandInterceptor
{
    public override DbDataReader ReaderExecuted(
        DbCommand command,
        CommandExecutedEventData eventData,
        DbDataReader result
    )
    {
        RecordDuration(eventData);
        return base.ReaderExecuted(command, eventData, result);
    }

    public override ValueTask<DbDataReader> ReaderExecutedAsync(
        DbCommand command,
        CommandExecutedEventData eventData,
        DbDataReader result,
        CancellationToken cancellationToken = default
    )
    {
        RecordDuration(eventData);
        return base.ReaderExecutedAsync(command, eventData, result, cancellationToken);
    }

    public override int NonQueryExecuted(
        DbCommand command,
        CommandExecutedEventData eventData,
        int result
    )
    {
        RecordDuration(eventData);
        return base.NonQueryExecuted(command, eventData, result);
    }

    public override ValueTask<int> NonQueryExecutedAsync(
        DbCommand command,
        CommandExecutedEventData eventData,
        int result,
        CancellationToken cancellationToken = default
    )
    {
        RecordDuration(eventData);
        return base.NonQueryExecutedAsync(command, eventData, result, cancellationToken);
    }

    public override object? ScalarExecuted(
        DbCommand command,
        CommandExecutedEventData eventData,
        object? result
    )
    {
        RecordDuration(eventData);
        return base.ScalarExecuted(command, eventData, result);
    }

    public override ValueTask<object?> ScalarExecutedAsync(
        DbCommand command,
        CommandExecutedEventData eventData,
        object? result,
        CancellationToken cancellationToken = default
    )
    {
        RecordDuration(eventData);
        return base.ScalarExecutedAsync(command, eventData, result, cancellationToken);
    }

    private static void RecordDuration(CommandExecutedEventData eventData)
    {
        PersistenceMetrics
            .QueryDuration.WithLabels("memberDb")
            .Observe(eventData.Duration.TotalSeconds);
    }
}
