package library_loan_service.security;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.JWSHeader;
import com.nimbusds.jose.crypto.RSASSASigner;
import com.nimbusds.jose.jwk.JWKSet;
import com.nimbusds.jose.jwk.RSAKey;
import com.nimbusds.jose.jwk.gen.RSAKeyGenerator;
import com.nimbusds.jwt.JWTClaimsSet;
import com.nimbusds.jwt.SignedJWT;
import com.sun.net.httpserver.HttpServer;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.Executors;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.server.ServerHttpRequest;
import org.springframework.http.server.ServerHttpResponse;
import org.springframework.http.server.ServletServerHttpRequest;
import org.springframework.http.server.ServletServerHttpResponse;
import org.springframework.mock.web.MockHttpServletRequest;
import org.springframework.mock.web.MockHttpServletResponse;

/**
 * Generated proof (D9): {@link IdentityWebSocketConfig .AuthHandshakeInterceptor#beforeHandshake}
 * REJECTS a tokenless upgrade with HTTP 401 -- before any protocol switch is even attempted -- and
 * ACCEPTS an upgrade carrying a token that validates through the SAME {@link DatrixJwtDecoder} the
 * REST {@code SecurityFilterChainConfig} guards use (asymmetric-only, audience-enforced,
 * fail-closed JWKS refresh).
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class IdentityWebsocketAuthTest {

  private static final String ISSUER = "https://auth.identity-ws-it.example.test";
  private static final String AUDIENCE = "identity-ws-it";
  private static final String SUBJECT = "ws-test-subject";

  private static HttpServer jwksServer;
  private static RSAKey rsaKey;

  @BeforeAll
  static void setUpAll() throws Exception {
    rsaKey = new RSAKeyGenerator(2048).keyID("kid-ws-it-1").generate();

    jwksServer = HttpServer.create(new InetSocketAddress("127.0.0.1", 0), 0);
    jwksServer.createContext(
        "/jwks",
        exchange -> {
          // JWKSet.toString() serializes to valid JSON; toJSONObject()
          // returns a java.util.Map whose OWN toString() is NOT JSON
          // (DatrixJwtDecoderIT already caught this).
          byte[] body =
              new JWKSet(rsaKey.toPublicJWK()).toString().getBytes(StandardCharsets.UTF_8);
          exchange.getResponseHeaders().add("Content-Type", "application/json");
          exchange.sendResponseHeaders(200, body.length);
          exchange.getResponseBody().write(body);
          exchange.getResponseBody().close();
        });
    // A cached pool, NOT a single thread: each DatrixJwtDecoder builds its
    // own JWKSource with its own connection, and the JDK HttpServer holds
    // keep-alive connections open. A single-threaded executor is starved by
    // the first idle keep-alive connection, so a later handshake's JWKS
    // fetch times out and the upgrade is rejected for the wrong reason.
    jwksServer.setExecutor(Executors.newCachedThreadPool());
    jwksServer.start();

    writePlan("http://127.0.0.1:" + jwksServer.getAddress().getPort() + "/jwks");
  }

  @AfterAll
  static void tearDownAll() {
    jwksServer.stop(0);
  }

  /**
   * Overwrite the classpath identity provider plan with a test-only, self-contained provider entry
   * pointing at the local JWKS server -- mirrors {@code DatrixJwtDecoderIT.writePlan}. Independent
   * of whatever the fixture's real {@code .dcfg}-derived plan bakes in; this test proves the
   * INTERCEPTOR's control flow, not a specific provider configuration.
   */
  private static void writePlan(String jwksUri) throws Exception {
    String json =
        "{"
            + "\"application\":\"test\",\"environment\":\"test\",\"providers\":{"
            + "\"wsTestProvider\":{"
            + "\"name\":\"wsTestProvider\",\"issuer\":\""
            + ISSUER
            + "\","
            + "\"allowedAudiences\":[\""
            + AUDIENCE
            + "\"],\"allowedAlgorithms\":[\"RS256\"],"
            + "\"jwksUri\":\""
            + jwksUri
            + "\",\"jwksCacheTtlSeconds\":3600,"
            + "\"roleSource\":{\"claimPath\":\"roles\"},\"roleMappings\":{},"
            + "\"localIdentity\":{\"mode\":\"subjectText\"}"
            + "}}}";
    Path targetClasses =
        Path.of(
            IdentityWebsocketAuthTest.class
                .getProtectionDomain()
                .getCodeSource()
                .getLocation()
                .toURI());
    Path planPath = targetClasses.resolve("config").resolve("identity-provider-plan.json");
    Files.createDirectories(planPath.getParent());
    Files.writeString(planPath, json, StandardCharsets.UTF_8);
  }

  private static String signedToken() throws Exception {
    JWTClaimsSet claims =
        new JWTClaimsSet.Builder()
            .issuer(ISSUER)
            .audience(AUDIENCE)
            .subject(SUBJECT)
            .expirationTime(new Date(System.currentTimeMillis() + 3_600_000))
            .claim("roles", List.of())
            .build();
    JWSHeader header = new JWSHeader.Builder(JWSAlgorithm.RS256).keyID(rsaKey.getKeyID()).build();
    SignedJWT jwt = new SignedJWT(header, claims);
    jwt.sign(new RSASSASigner(rsaKey));
    return jwt.serialize();
  }

  private static ServerHttpRequest requestTo(String path) {
    return new ServletServerHttpRequest(new MockHttpServletRequest("GET", path));
  }

  @Test
  void unauthenticatedUpgradeRejectedBeforeProtocolSwitch() {
    DatrixJwtDecoder decoder = new DatrixJwtDecoder();
    IdentityWebSocketConfig.AuthHandshakeInterceptor interceptor =
        new IdentityWebSocketConfig.AuthHandshakeInterceptor(decoder);

    ServerHttpRequest request = requestTo(IdentityWebSocketConfig.IDENTITY_WS_PATH);
    MockHttpServletResponse mockResponse = new MockHttpServletResponse();
    ServerHttpResponse response = new ServletServerHttpResponse(mockResponse);
    Map<String, Object> attributes = new HashMap<>();

    boolean proceed =
        interceptor.beforeHandshake(
            request, response, new IdentityWebSocketConfig.IdentityWebSocketHandler(), attributes);

    assertFalse(proceed, "a tokenless upgrade must be rejected at handshake time");
    assertEquals(HttpStatus.UNAUTHORIZED.value(), mockResponse.getStatus());
    assertTrue(attributes.isEmpty(), "no principal attribute may be set on a rejected handshake");
  }

  @Test
  void authenticatedUpgradeSucceedsThroughTheSameValidatorAsRestGuards() throws Exception {
    String token = signedToken();
    DatrixJwtDecoder decoder = new DatrixJwtDecoder();
    IdentityWebSocketConfig.AuthHandshakeInterceptor interceptor =
        new IdentityWebSocketConfig.AuthHandshakeInterceptor(decoder);

    MockHttpServletRequest mockRequest =
        new MockHttpServletRequest("GET", IdentityWebSocketConfig.IDENTITY_WS_PATH);
    mockRequest.addHeader(HttpHeaders.AUTHORIZATION, "Bearer " + token);
    ServerHttpRequest request = new ServletServerHttpRequest(mockRequest);
    MockHttpServletResponse mockResponse = new MockHttpServletResponse();
    ServerHttpResponse response = new ServletServerHttpResponse(mockResponse);
    Map<String, Object> attributes = new HashMap<>();

    boolean proceed =
        interceptor.beforeHandshake(
            request, response, new IdentityWebSocketConfig.IdentityWebSocketHandler(), attributes);

    assertTrue(proceed, "a validly authenticated upgrade must be accepted");
    assertEquals(
        SUBJECT, attributes.get(IdentityWebSocketConfig.AuthHandshakeInterceptor.ATTR_PRINCIPAL));
  }
}
