package library_book_service.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import java.util.List;
import java.util.UUID;
import library_book_service.dto.book_db.BookCreateRequest;
import library_book_service.dto.book_db.BookResponse;
import library_book_service.dto.book_db.BookUpdateRequest;
import library_book_service.model.book_db.Book;
import library_book_service.services.book_db.BookService;
import org.springframework.http.HttpStatus;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseStatus;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;

/**
 * BookServiceAPI REST controller.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@RestController
@RequestMapping("/api/v1")
@Tag(name = "BookServiceAPI")
public class BookServiceAPIController {
  private final BookService bookService;

  public BookServiceAPIController(BookService bookService) {
    this.bookService = bookService;
  }

  @Operation(summary = "list_books")
  @ApiResponse(responseCode = "200")
  @GetMapping("/books")
  public List<BookResponse> listBooks(
      @RequestParam(name = "page", defaultValue = "0") int page,
      @RequestParam(name = "size", defaultValue = "20") int size) {
    List<Book> allResults = bookService.list();
    int fromIndex = Math.min(page * size, allResults.size());
    int toIndex = Math.min(fromIndex + size, allResults.size());
    List<Book> pageResults = allResults.subList(fromIndex, toIndex);
    return pageResults.stream()
        .map(
            item ->
                new BookResponse(
                    item.getCreatedAt(),
                    item.getUpdatedAt(),
                    item.getId(),
                    item.getTitle(),
                    item.getAuthor()))
        .toList();
  }

  @Operation(summary = "create_book")
  @ApiResponse(responseCode = "201")
  @ResponseStatus(HttpStatus.CREATED)
  @PostMapping("/books")
  public BookResponse createBook(@Valid @RequestBody BookCreateRequest dto) {
    Book entity = new Book();
    entity.setTitle(dto.title());
    entity.setAuthor(dto.author());
    Book saved = bookService.create(entity);
    return new BookResponse(
        saved.getCreatedAt(),
        saved.getUpdatedAt(),
        saved.getId(),
        saved.getTitle(),
        saved.getAuthor());
  }

  @Operation(summary = "get_book")
  @ApiResponse(responseCode = "200")
  @GetMapping("/books/{id}")
  public BookResponse getBook(@PathVariable("id") UUID id) {
    Book entity =
        bookService
            .get(id)
            .orElseThrow(
                () -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Book not found: " + id));
    return new BookResponse(
        entity.getCreatedAt(),
        entity.getUpdatedAt(),
        entity.getId(),
        entity.getTitle(),
        entity.getAuthor());
  }

  @Operation(summary = "update_book")
  @ApiResponse(responseCode = "200")
  @PutMapping("/books/{id}")
  public BookResponse updateBook(
      @PathVariable("id") UUID id, @Valid @RequestBody BookUpdateRequest dto) {
    Book entity =
        bookService
            .get(id)
            .orElseThrow(
                () -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Book not found: " + id));
    entity.setTitle(dto.title());
    entity.setAuthor(dto.author());
    Book saved = bookService.update(entity);
    return new BookResponse(
        saved.getCreatedAt(),
        saved.getUpdatedAt(),
        saved.getId(),
        saved.getTitle(),
        saved.getAuthor());
  }

  @Operation(summary = "delete_book")
  @ApiResponse(responseCode = "204")
  @ResponseStatus(HttpStatus.NO_CONTENT)
  @DeleteMapping("/books/{id}")
  public void deleteBook(@PathVariable("id") UUID id) {
    bookService.delete(id);
  }
}
