test:
  tags: [api, library, notifications, v1]
  meta: {}
  healthCheck: { type: http, path: /health, interval: 10s }

development:
  tags: [api, library, notifications, v1]
  meta: {}
  healthCheck: { type: http, path: /health, interval: 10s }

production:
  tags: [api, library, notifications, v1]
  meta: {}
  healthCheck: { type: http, path: /health, interval: 10s }
