CREATE TABLE "books" (
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,    "id" UUID NOT NULL DEFAULT gen_random_uuid(),    "title" VARCHAR(200) NOT NULL,    "author" VARCHAR(100) NOT NULL,    CONSTRAINT pk_books PRIMARY KEY (id));
