"""Cross-language artifact-role parity gate: the G-A closure.

Detects a language silently emitting nothing for a construct another
language realizes, WITHOUT GENERATING ANYTHING -- it reads the generation
pipeline's own file manifests (``.datrix/manifests/<target>.json``, one per
generator target, each carrying the ``files`` it wrote and a ``generated_at``
stamp) from the example trees ``generate.ps1`` writes under
``<workspace>/.generated/<language>/<runtime>/<provider>/<example>/``.

THERE IS NO STORED BASELINE. The repo commits no snapshot of generated output
and nothing is ever "blessed": every run reads whatever the generator most
recently produced, so a stale committed manifest cannot exist and no
re-recording step exists to skip. The trade is that this gate is only as
current as the local corpus -- it prints every tree's ``generated_at`` stamp
and REFUSES to run (exit 2) when any registered language's corpus is
incomplete (a registered example with no tree and no entry in
parity-known-nongenerating.json), naming exactly which pairs to generate.
Generate the full corpus first, once per registered language:
``generate.ps1 -All -L <language>`` (Jon runs this; it is blocked for agents).

For every (example, runtime, provider) generated in >= 2 languages:
  1. Load each language's path list from that tree's pipeline manifests.
  2. Classify each path by domain ROLE using that language's OWN derived
     DomainDeclaration.structural_pattern set (derive_domain_declarations
     over the plugin's own registered specs -- the same fnmatch globs the
     domain self-consistency gate uses). A path matching no pattern goes to
     an "unclassified" bucket, reported but never compared (template-level
     naming differs by design across languages; the ROLE set is the
     contract, not the literal path shape).
  3. The set of roles with >= 1 matching path must be IDENTICAL across the
     example's generated languages, EXCLUDING one kind of non-drift: any
     domain the "missing" language realizes by a structural_pattern that
     nonetheless matches ZERO files across that language's ENTIRE generated
     footprint (every example, not just the one being compared) -- an
     EMPIRICAL corpus-wide fact derived from the same manifests this gate
     already reads (never DSL source, never a declaration): the domain's
     triggering construct simply never occurs anywhere in the corpus for this
     language, so a single-example "missing" verdict against it carries no
     information. That skip is silent no longer: every corpus-vacuous
     (language, domain) must carry a typed record in
     corpus-vacuity-records.json saying WHY nothing exercises it, and the
     gate fails both on an unrecorded pair and on a record whose pair is no
     longer vacuous (see check_corpus_vacuity_records). A generator no
     reference example reaches has no end-to-end signal at all -- silence
     about which of those generators CANNOT be reached and which merely ARE
     NOT is the state this file's records end.
     Nothing else excuses a missing role: no declaration and no committed
     per-example file sets a language aside. A language that emits a domain
     under a different DSL trigger than another language (only for some
     construct, where the other emits it for more) diverges in what the same
     source produces, and the gate reports it. A language that realizes a
     domain by NO structural_pattern has no declaration to read an absence
     from: the capability gap is recorded once, as a `capability_gaps` row on
     the language's own capability declaration and counted by the
     capability-gap ledger gate, and this gate reports the missing role as a
     failure regardless of whether such a row exists.

  4. The same role-set comparison runs ACROSS PROVIDERS for a fixed language:
     for every (language, example, runtime) generated under >= 2 providers,
     the set of roles each provider's tree carries must be identical -- a role
     present under one provider and absent under another is a failure on
     its own line (`ARTIFACT-ROLE CROSS-PROVIDER DRIFT`). The same corpus
     vacuity skip applies. Below two providers there is nothing to compare,
     so the provider axis is a no-op over a single-provider corpus -- its
     self-test is what proves it live.

This gate pins PRESENCE across languages and providers. Whether the CONTENT of a generated
file is right is proven where it can be decided: each language package's own
suite, and the generated project's own build and tests (``generate.ps1`` at
STANDARD, ``run-complete.ps1``). No gate compares generated bytes against a
stored snapshot -- see docs/architecture/generated-output-stability.md.

Built-in non-vacuity self-test, every invocation, one ``[OK]`` line per case:
proves compare_role_sets detects a forced mismatch and does not false-positive
a matching pair, proves classify_paths correctly buckets a synthetic manifest
against synthetic declarations (including the unclassified bucket), proves a
missing role is a failure unless the corpus vacuity skip excuses it, and proves
the provider axis detects a planted role present under one provider and absent
under another while reporting nothing for identical sets or a single provider.
Refuses to pass vacuously: zero (example, runtime, provider) groups generated
in >= 2 languages is exit 2, never a silent 0-example pass.

Usage:
    python artifact_role_parity.py
    python artifact_role_parity.py --generated-root D:/datrix/.generated
    python artifact_role_parity.py --debug
    python artifact_role_parity.py --self-test
    python artifact_role_parity.py --census
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import logging
import os
import shutil
import sys
from collections.abc import Callable, Iterable, Mapping, Sequence
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Final, cast

from datrix_codegen_kernel.parity.derived_declarations import DerivationError
from datrix_codegen_kernel.parity.domain_declaration import (
    DomainDeclaration,
    DomainDeclarations,
)

from datrix_scripts.paths import SHOWCASE_DIR, WORKSPACE_DIR
from datrix_scripts.registered_targets import registered_language_names

logger = logging.getLogger(__name__)

DATRIX_DIR: Path = SHOWCASE_DIR
WORKSPACE_ROOT: Path = WORKSPACE_DIR

EXAMPLES_ROOT: Path = DATRIX_DIR / "examples"
#: Where ``generate.ps1`` writes example trees by default (its ``-OutputBase``):
#: ``<workspace>/.generated/<language>/<runtime>/<provider>/<example relpath>``
#: -- see ``shared/test_projects.py::build_output_path``. Overridable per run
#: with ``--generated-root``.
DEFAULT_GENERATED_ROOT: Path = WORKSPACE_ROOT / ".generated"
#: Inside every generated project: one JSON manifest per generator target,
#: written by the pipeline's ``write:{target}`` stage, listing exactly the
#: files that target wrote (``files``) and when (``generated_at``).
MANIFESTS_RELPATH: Path = Path(".datrix") / "manifests"
#: Registered examples the real generator cannot build today, with a reason
#: each -- the only sanctioned gap in a language's corpus (see
#: :func:`load_known_non_generating`).
KNOWN_NON_GENERATING_PATH: Path = (
    DATRIX_DIR / "scripts" / "config" / "parity-known-nongenerating.json"
)
CORPUS_VACUITY_RECORDS_PATH: Path = (
    DATRIX_DIR / "scripts" / "config" / "corpus-vacuity-records.json"
)

_MIN_LANGUAGES_FOR_COMPARISON: Final[int] = 2
#: Fewer providers than this under one (language, example, runtime) leave
#: nothing to compare: most examples generate under one provider profile, so
#: the provider axis is a no-op for them rather than a refusal.
_MIN_PROVIDERS_FOR_COMPARISON: Final[int] = 2
#: Separator in a language-qualified parity-known-nongenerating.json key
#: (``"<example_id>::<language>"``); a bare ``example_id`` key parks the
#: example for every registered language.
_LANGUAGE_KEY_SEP: Final[str] = "::"

EXIT_OK = 0
EXIT_FAIL = 1
EXIT_USAGE = 2

_SELF_TEST_LANGUAGE_A: Final[str] = "self_test_lang_a"
_SELF_TEST_LANGUAGE_B: Final[str] = "self_test_lang_b"
_SELF_TEST_DOMAIN_SHARED: Final[str] = "self_test_order"
_SELF_TEST_DOMAIN_FORCED_GAP: Final[str] = "self_test_shipment"

#: A corpus-vacuity record's `status`: NO reference example can produce a file
#: matching this pattern, whatever it declares and whatever it targets, because
#: something outside the example's control gates the emission (the generation
#: pipeline's own configuration, a realization the language deliberately routes
#: to a different file family). Adding an example is never the remedy; the
#: record's `reason` names what the remedy actually is.
VACUITY_UNREACHABLE: Final[str] = "unreachable-by-design"

#: A corpus-vacuity record's `status`: reachable ONLY by an example whose
#: deployment profile resolves to a cloud provider. Every reference example
#: resolves `provider = "local"`, so this is not a DSL block an example is
#: missing -- it is the corpus having no cloud-targeting example at all, which
#: swaps that example's ENTIRE infrastructure output and is a materially larger
#: decision than adding a block.
VACUITY_CLOUD_ONLY: Final[str] = "cloud-platform-only"

#: A corpus-vacuity record's `status`: reachable under the corpus's own
#: local/docker shape -- nothing structural stands between a reference example
#: and this output -- and no example declares the triggering construct.
#: Ordinary corpus-coverage debt: the remedy is one DSL addition to an existing
#: example, and the record is deleted when one lands.
VACUITY_UNEXERCISED: Final[str] = "unexercised"

_VACUITY_STATUSES: Final[frozenset[str]] = frozenset(
    {VACUITY_UNREACHABLE, VACUITY_CLOUD_ONLY, VACUITY_UNEXERCISED}
)


@dataclass(frozen=True)
class CorpusVacuityRecord:
    """One reviewed (language, domain) corpus-vacuity record.

    Attributes:
        language: A registered `datrix.languages` entry-point name.
        domain: A domain id that language realizes by a structural pattern.
        status: One of `VACUITY_UNREACHABLE`, `VACUITY_CLOUD_ONLY`,
            `VACUITY_UNEXERCISED` -- never interchangeable, since each carries
            a different remedy (see each constant's own docstring).
        reason: The concrete structural fact, with the coordinates that prove
            it. Used verbatim in this gate's error messages.
    """

    language: str
    domain: str
    status: str
    reason: str


# ---------------------------------------------------------------------------
# Generated-corpus discovery + pipeline-manifest reading
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class GeneratedTree:
    """One generated example project found under the generated root.

    Attributes:
        example: The example's posix path relative to ``EXAMPLES_ROOT``
            (e.g. ``02-features/03-infrastructure-blocks/jobs``).
        language: The registered ``datrix.languages`` target it was generated in.
        runtime: The deployment runtime path segment (e.g. ``docker-compose``).
        provider: The provider path segment (e.g. ``local``).
        root: Absolute path of the generated project.
        generated_at: The newest ``generated_at`` stamp across the tree's
            pipeline manifests -- reported so a reader can see how current
            the compared corpus is.
        paths: Every relative path any generator target wrote, sorted.
    """

    example: str
    language: str
    runtime: str
    provider: str
    root: Path
    generated_at: str
    paths: tuple[str, ...]

    @property
    def group_key(self) -> tuple[str, str, str]:
        """The cross-language comparison group this tree belongs to."""
        return (self.example, self.runtime, self.provider)

    @property
    def provider_group_key(self) -> tuple[str, str, str]:
        """The cross-provider comparison group this tree belongs to."""
        return (self.language, self.example, self.runtime)


def example_id(example_relpath: str) -> str:
    """The kebab id parity-known-nongenerating.json keys an example by.

    Args:
        example_relpath: Posix path relative to ``EXAMPLES_ROOT``.

    Returns:
        The path's segments joined by ``-`` (e.g.
        ``02-features-03-infrastructure-blocks-jobs``).
    """
    return "-".join(PurePosixPath(example_relpath).parts)


def registered_example_relpaths() -> list[str]:
    """Every example under ``EXAMPLES_ROOT`` (a directory holding ``system.dtrx``).

    Returns:
        Sorted posix paths relative to ``EXAMPLES_ROOT``.

    Raises:
        ValueError: If no example exists -- an empty corpus would make every
            completeness check pass vacuously.
    """
    relpaths = sorted(
        p.parent.relative_to(EXAMPLES_ROOT).as_posix()
        for p in EXAMPLES_ROOT.rglob("system.dtrx")
    )
    if not relpaths:
        raise ValueError(
            f"No system.dtrx found under {EXAMPLES_ROOT}; the artifact-role gate "
            f"has no example corpus to check."
        )
    return relpaths


def load_known_non_generating() -> dict[str, str]:
    """Load and validate parity-known-nongenerating.json.

    Each key is either a bare ``example_id`` (parks the example for every
    registered language) or ``"example_id::language"`` (parks that one
    language only). A parked pair is the only sanctioned reason for a
    registered example to have no generated tree.

    Returns:
        Mapping of key -> reason string.

    Raises:
        ValueError: If the file is missing, malformed, has an empty reason,
            names an unregistered language, or names an example that does
            not exist under ``EXAMPLES_ROOT``.
    """
    if not KNOWN_NON_GENERATING_PATH.exists():
        raise ValueError(
            f"Missing {KNOWN_NON_GENERATING_PATH}. It records the registered "
            f"examples the real generator cannot build today. Restore it from git; "
            f"the gate never creates it."
        )
    data = json.loads(KNOWN_NON_GENERATING_PATH.read_text(encoding="utf-8"))
    examples = data.get("examples")
    if not isinstance(examples, dict):
        raise ValueError(
            f"Malformed {KNOWN_NON_GENERATING_PATH}: expected an object with "
            f"'examples' (object of example_id[::language] -> reason)."
        )
    registered_languages = registered_language_names()
    registered_ids = {example_id(rel) for rel in registered_example_relpaths()}
    for key, reason in examples.items():
        if not isinstance(reason, str) or not reason.strip():
            raise ValueError(
                f"Entry {key!r} in {KNOWN_NON_GENERATING_PATH.name} has an empty "
                f"reason. Every entry must state the defect and a tracking identifier."
            )
        ex_id, _, language = key.partition(_LANGUAGE_KEY_SEP)
        if ex_id not in registered_ids:
            raise ValueError(
                f"Entry {key!r} in {KNOWN_NON_GENERATING_PATH.name} names example id "
                f"{ex_id!r}, which is not under {EXAMPLES_ROOT}. Delete the entry if "
                f"the example was removed, or fix the id."
            )
        if language and language not in registered_languages:
            raise ValueError(
                f"Entry {key!r} in {KNOWN_NON_GENERATING_PATH.name} names language "
                f"{language!r}, which is not in the registered datrix.languages set "
                f"({', '.join(sorted(registered_languages))}). Fix the typo or the key."
            )
    return {str(k): str(v) for k, v in examples.items()}


def known_non_generating_reason(
    known: Mapping[str, str], example_relpath: str, language: str
) -> str | None:
    """The parked reason for this (example, language) pair, or ``None``.

    A language-qualified entry takes precedence over a bare one for the same
    example.
    """
    ex_id = example_id(example_relpath)
    qualified = known.get(f"{ex_id}{_LANGUAGE_KEY_SEP}{language}")
    if qualified is not None:
        return qualified
    return known.get(ex_id)


def read_pipeline_manifests(manifests_dir: Path) -> tuple[tuple[str, ...], str]:
    """Read every generator target's manifest under one generated project.

    Args:
        manifests_dir: The project's ``.datrix/manifests`` directory.

    Returns:
        ``(paths, generated_at)``: the sorted union of every target's ``files``
        list, and the newest ``generated_at`` stamp among the manifests.

    Raises:
        ValueError: If the directory holds no manifest, or a manifest lacks a
            ``files`` list or a ``generated_at`` string.
    """
    manifest_files = sorted(manifests_dir.glob("*.json"))
    if not manifest_files:
        raise ValueError(
            f"No pipeline manifest under {manifests_dir}; the tree was not written "
            f"by the generation pipeline. Regenerate it with generate.ps1."
        )
    paths: set[str] = set()
    stamps: list[str] = []
    for manifest_file in manifest_files:
        data = json.loads(manifest_file.read_text(encoding="utf-8"))
        files = data.get("files")
        stamp = data.get("generated_at")
        if not isinstance(files, list) or not all(isinstance(f, str) for f in files):
            raise ValueError(
                f"Malformed pipeline manifest {manifest_file}: expected a 'files' "
                f"list of relative path strings."
            )
        if not isinstance(stamp, str) or not stamp:
            raise ValueError(
                f"Malformed pipeline manifest {manifest_file}: expected a non-empty "
                f"'generated_at' string."
            )
        paths.update(files)
        stamps.append(stamp)
    return tuple(sorted(paths)), max(stamps)


def discover_generated_trees(
    generated_root: Path, languages: Iterable[str]
) -> list[GeneratedTree]:
    """Find every generated example project under *generated_root*.

    The layout is ``<language>/<runtime>/<provider>/<example relpath>``; a
    directory is a generated tree iff it carries pipeline manifests. Anything
    else at those depths (a formatter cache, a stray directory) is ignored.

    Args:
        generated_root: The ``generate.ps1`` output base.
        languages: The registered language names to look for.

    Returns:
        Every tree found, sorted by (language, example, runtime, provider).
    """
    trees: list[GeneratedTree] = []
    examples = registered_example_relpaths()
    for language in sorted(languages):
        language_root = generated_root / language
        if not language_root.is_dir():
            continue
        for runtime_dir in sorted(p for p in language_root.iterdir() if p.is_dir()):
            for provider_dir in sorted(p for p in runtime_dir.iterdir() if p.is_dir()):
                trees.extend(
                    _trees_under_provider(language, runtime_dir.name, provider_dir, examples)
                )
    return sorted(trees, key=lambda t: (t.language, t.example, t.runtime, t.provider))


def _trees_under_provider(
    language: str, runtime: str, provider_dir: Path, examples: Sequence[str]
) -> list[GeneratedTree]:
    """Every registered example generated under one ``<runtime>/<provider>``."""
    found: list[GeneratedTree] = []
    for example in examples:
        manifests_dir = provider_dir / example / MANIFESTS_RELPATH
        if not manifests_dir.is_dir():
            continue
        paths, generated_at = read_pipeline_manifests(manifests_dir)
        found.append(
            GeneratedTree(
                example=example,
                language=language,
                runtime=runtime,
                provider=provider_dir.name,
                root=provider_dir / example,
                generated_at=generated_at,
                paths=paths,
            )
        )
    return found


def missing_corpus_pairs(
    trees: Sequence[GeneratedTree],
    languages: Iterable[str],
    known: Mapping[str, str],
) -> tuple[list[tuple[str, str]], list[tuple[str, str]]]:
    """Compare the generated corpus against the registered example set.

    Args:
        trees: Every discovered tree.
        languages: The registered language names.
        known: The parked pairs (:func:`load_known_non_generating`).

    Returns:
        ``(missing, stale_parks)``: ``missing`` is every (example, language)
        pair with no tree and no park entry -- the corpus is incomplete for
        that language until it is generated; ``stale_parks`` is every parked
        pair that DOES have a tree -- the defect the entry records is fixed
        and the entry must be deleted.
    """
    generated = {(t.example, t.language) for t in trees}
    missing: list[tuple[str, str]] = []
    stale: list[tuple[str, str]] = []
    for language in sorted(languages):
        for example in registered_example_relpaths():
            parked = known_non_generating_reason(known, example, language) is not None
            present = (example, language) in generated
            if present and parked:
                stale.append((example, language))
            elif not present and not parked:
                missing.append((example, language))
    return missing, stale


def comparison_groups(
    trees: Sequence[GeneratedTree],
) -> dict[tuple[str, str, str], dict[str, GeneratedTree]]:
    """Group trees by (example, runtime, provider) and keep the multi-language ones.

    Returns:
        ``{group_key: {language: tree}}`` for every group generated in at
        least ``_MIN_LANGUAGES_FOR_COMPARISON`` languages, sorted by key.
    """
    by_key: dict[tuple[str, str, str], dict[str, GeneratedTree]] = {}
    for tree in trees:
        by_key.setdefault(tree.group_key, {})[tree.language] = tree
    return {
        key: languages
        for key, languages in sorted(by_key.items())
        if len(languages) >= _MIN_LANGUAGES_FOR_COMPARISON
    }


def provider_comparison_keys(
    trees: Sequence[GeneratedTree],
) -> list[tuple[str, str, str]]:
    """Every ``(language, example, runtime)`` generated under >= 2 providers.

    The provider axis groups the SAME already-discovered trees the language axis
    does, one level over: it holds the language fixed and varies the provider.

    Returns:
        Sorted ``(language, example, runtime)`` keys whose trees span at least
        ``_MIN_PROVIDERS_FOR_COMPARISON`` distinct providers.
    """
    providers_by_key: dict[tuple[str, str, str], set[str]] = {}
    for tree in trees:
        providers_by_key.setdefault(tree.provider_group_key, set()).add(tree.provider)
    return sorted(
        key
        for key, providers in providers_by_key.items()
        if len(providers) >= _MIN_PROVIDERS_FOR_COMPARISON
    )


def corpus_footprint(trees: Sequence[GeneratedTree]) -> dict[str, list[str]]:
    """Every generated path per language, across the whole corpus.

    This is the footprint :func:`_is_corpus_vacuous_for_language` judges a
    domain against -- every example the language generated, not just the
    groups this gate compares.
    """
    footprint: dict[str, list[str]] = {}
    for tree in trees:
        footprint.setdefault(tree.language, []).extend(tree.paths)
    return footprint


# ---------------------------------------------------------------------------
# Role classification
# ---------------------------------------------------------------------------


def language_domain_declarations(language: str) -> DomainDeclarations:
    """Fresh, derived DomainDeclarations for *language*.

    Computed independently of whatever mechanism the plugin's OWN
    `.domain_declarations` attribute currently uses in production -- calling
    `derive_domain_declarations` directly guarantees one consistent
    structural-pattern basis across every registered language for this gate, rather
    than trusting each package's own wiring to already route through it.

    Args:
        language: A registered `datrix.languages` entry-point name.

    Returns:
        `domain_id -> DomainDeclaration`, derived fresh from the plugin's
        registered sub-generator specs. A structural domain the language
        realizes by no sub-generator is absent from the result: the gate reads
        absence as "no role", never as an excuse.

    Raises:
        DerivationError: If a structural domain is neither realized by a
            registered sub-generator nor tracked by a ``domain:<id>`` row in the
            language's own ``capability_gaps``. The rows are read ONLY to
            satisfy that completeness check -- no comparison, skip or exemption
            in this module consults them.
    """
    from datrix_codegen_kernel.generation.discovery import get_language_plugin
    from datrix_codegen_kernel.parity.derived_declarations import (
        derive_domain_declarations,
    )
    from datrix_common.plugin.capability_resolution import declaration_for_language
    from datrix_testing.conformance.domain_self_consistency import (
        DomainDeclaringPlugin,
    )

    plugin = cast(DomainDeclaringPlugin, get_language_plugin(language))
    specs = plugin.generator.get_sub_generators()
    return derive_domain_declarations(
        specs,
        capability_gaps=declaration_for_language(language).capability_gaps,
    )


#: Package-init marker basenames: language package-structure boilerplate
#: (e.g. Python's `__init__.py`, created wherever a package directory exists
#: for ANY reason) rather than domain-specific generated content. A trailing
#: `*.py`-shaped structural_pattern trivially matches this marker for every
#: domain whose files happen to share that directory, manufacturing a false
#: "domain present" signal with no bearing on what the DSL actually declared.
#: Excluded from classification entirely (routed to "unclassified") rather
#: than credited to any domain.
_PACKAGE_MARKER_BASENAMES: Final[frozenset[str]] = frozenset({"__init__.py"})


def _pattern_specificity(pattern: str) -> int:
    """Number of '/'-separated segments in a structural_pattern glob.

    `fnmatch.fnmatch`'s `*` spans `/` (by design -- the leading `*/` absorbs
    a variable-depth service-directory prefix). A side effect: when one
    domain's pattern is a strict directory-shallower generalization of a
    sibling domain's pattern (e.g. struct's `*/src/*/schemas/*.py` vs
    schema's `*/src/*/schemas/*/*.py`), the shallower pattern also matches
    files that structurally belong to the deeper, more specific sibling.
    Segment count is the tie-break: the pattern requiring more path segments
    is the more specific match for a path both patterns accept.
    """
    return pattern.count("/")


def classify_paths(
    paths: list[str], declarations: Mapping[str, DomainDeclaration]
) -> tuple[frozenset[str], list[str]]:
    """Classify each manifest path by domain role via fnmatch against every
    pattern-bearing declaration's structural_pattern -- the same glob shape
    `domain_self_consistency._pattern_mismatch_violations` uses. A domain is
    credited only through a pattern it carries: presence of the pattern is
    what "the language realizes this domain" means here.

    When a path matches more than one domain's pattern, only the most
    SPECIFIC match (see `_pattern_specificity`) is credited -- this is a
    property of this gate's own aggregation, not a different fnmatch rule:
    each candidate is still tested with the exact same `fnmatch.fnmatch`
    call domain_self_consistency uses. A package-init marker basename (see
    `_PACKAGE_MARKER_BASENAMES`) is routed to `unclassified` before any
    pattern is even tried -- it is package-structure boilerplate, never
    domain-specific content.

    Args:
        paths: Relative paths from one generated tree's pipeline manifests.
        declarations: `domain_id -> DomainDeclaration`.

    Returns:
        `(role_set, unclassified_paths)`. `role_set` is every domain id with
        >= 1 matching path (after the most-specific tie-break).
        `unclassified_paths` is reported by the caller but never compared --
        template-level naming legitimately differs by language; the role set
        is the contract, not the literal path shape.
    """
    patterned: list[tuple[str, str]] = [
        (domain_id, decl.structural_pattern)
        for domain_id, decl in declarations.items()
        if decl.structural_pattern is not None
    ]
    roles: set[str] = set()
    unclassified: list[str] = []
    for path in paths:
        if PurePosixPath(path).name in _PACKAGE_MARKER_BASENAMES:
            unclassified.append(path)
            continue
        matches = [
            (domain_id, pattern)
            for domain_id, pattern in patterned
            if fnmatch.fnmatch(path, pattern)
        ]
        if not matches:
            unclassified.append(path)
            continue
        most_specific = max(_pattern_specificity(pattern) for _, pattern in matches)
        for domain_id, pattern in matches:
            if _pattern_specificity(pattern) == most_specific:
                roles.add(domain_id)
    return frozenset(roles), unclassified


def compare_role_sets(
    per_language: Mapping[str, frozenset[str]],
) -> dict[str, frozenset[str]]:
    """Compare every language's role set against the union of all, for one example.

    Mirrors `supported_domain_parity.compare_supported_domain_sets` exactly
    (same union-minus-own shape) -- reuse that reasoning rather than
    reinventing a comparison rule.

    Args:
        per_language: {language: role_set} for one example's generated languages.

    Returns:
        {language: missing_role_ids} -- empty per language iff every
        language's role set is identical (D7's POSITIVE acceptance property
        for that example).

    Raises:
        ValueError: If *per_language* has fewer than
            `_MIN_LANGUAGES_FOR_COMPARISON` entries.
    """
    if len(per_language) < _MIN_LANGUAGES_FOR_COMPARISON:
        raise ValueError(
            f"compare_role_sets requires at least {_MIN_LANGUAGES_FOR_COMPARISON} "
            f"languages to compare, got {len(per_language)} ({sorted(per_language)})."
        )
    union_ids: frozenset[str] = frozenset[str]().union(*per_language.values())
    return {name: union_ids - ids for name, ids in per_language.items()}


# ---------------------------------------------------------------------------
# The one skip: corpus vacuity
# ---------------------------------------------------------------------------


def _domain_ever_matches(pattern: str, all_paths: Iterable[str]) -> bool:
    """Whether *pattern* matches at least one path in *all_paths* -- the pure
    predicate `_is_corpus_vacuous_for_language` delegates to, taking an
    already-resolved path list so the self-test can exercise it directly
    against synthetic data without touching a real generated corpus.
    """
    return any(fnmatch.fnmatch(path, pattern) for path in all_paths)


def _is_corpus_vacuous_for_language(
    language: str,
    domain_id: str,
    declarations: Mapping[str, DomainDeclaration],
    footprint: Mapping[str, Sequence[str]],
) -> bool:
    """Whether *domain_id* is a domain *language* realizes by a structural
    pattern that matches ZERO files anywhere in *language*'s ENTIRE generated
    footprint -- not just the one example currently being compared.

    A `True` result means the domain's triggering DSL construct simply never
    occurs anywhere in the reference-example corpus for this language (e.g.
    a `requires feature extern_services`-gated generator when no example
    anywhere declares an `extern service`): a corpus-wide fact, not a
    per-example one, so a single-example 'missing' verdict against it carries
    no information and is not drift. It is an EMPIRICAL fact about the
    language's own generated output, derived from the same manifests this gate
    already reads, never from DSL source. A language that realizes the domain
    by NO structural pattern is never corpus-vacuous: the question presupposes
    a pattern, and without one the role is simply missing -- which fails.

    Args:
        language: The language whose footprint to scan.
        domain_id: The domain to check.
        declarations: `language`'s own `domain_id -> DomainDeclaration`.
        footprint: ``{language: every generated path}`` over the whole corpus
            (:func:`corpus_footprint`). A language absent from it has no
            footprint, so every patterned domain reads as vacuous -- which is
            why :func:`check_artifact_role_parity` refuses to run on an
            incomplete corpus before this predicate is ever consulted.
    """
    declaration = declarations.get(domain_id)
    if declaration is None or not declaration.structural_pattern:
        return False
    return not _domain_ever_matches(declaration.structural_pattern, footprint.get(language, ()))


def unexcused_missing_domains(
    missing: Iterable[str],
    *,
    language: str,
    declarations: Mapping[str, DomainDeclaration],
    footprint: Mapping[str, Sequence[str]],
) -> list[str]:
    """The domain ids in *missing* that nothing excuses, sorted.

    Exactly one skip exists, and it reads no declaration and no committed
    exemption: the domain's own structural pattern matches zero files across
    the language's whole generated footprint (held to a reviewed record). A
    language that emits a domain only for some DSL construct while another
    language emits it for more is NOT excused -- the same source produces a
    different artifact set, and that is the drift this gate exists to report.
    A domain the language realizes by NO structural pattern is never excused
    either: its role is missing, and that fails here.

    Args:
        missing: Domain ids absent from *language*'s role set for one tree.
        language: The language whose tree is missing them.
        declarations: *language*'s own `domain_id -> DomainDeclaration`.
        footprint: ``{language: every generated path}`` (:func:`corpus_footprint`).

    Returns:
        The sorted domain ids that remain failures.
    """
    return [
        domain_id
        for domain_id in sorted(missing)
        if not _is_corpus_vacuous_for_language(language, domain_id, declarations, footprint)
    ]


# ---------------------------------------------------------------------------
# Provider axis: the role-set comparison, one level down
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CrossProviderDrift:
    """One role present under some providers and absent under another, for one
    (language, example, runtime).

    Attributes:
        language: The language every compared tree was generated in.
        example: The example's posix path relative to ``EXAMPLES_ROOT``.
        runtime: The deployment runtime path segment shared by the trees.
        provider: The provider whose tree lacks the role.
        domain: The missing domain role.
        present_under: The providers whose trees carry the role, sorted.
        tree_root: The generated project of the provider lacking the role.
    """

    language: str
    example: str
    runtime: str
    provider: str
    domain: str
    present_under: tuple[str, ...]
    tree_root: Path

    def report_line(self) -> str:
        """The failure line, naming the language, example, runtime, the provider
        missing the role and the providers that have it."""
        return (
            f"ARTIFACT-ROLE CROSS-PROVIDER DRIFT language={self.language} "
            f"example={self.example} runtime={self.runtime} "
            f"provider={self.provider} missing_domain={self.domain} (present "
            f"under provider(s) {', '.join(self.present_under)} for the same "
            f"language, example and runtime; {self.provider}'s generated tree "
            f"{self.tree_root} matches no file to this domain's "
            f"structural_pattern)"
        )


def _provider_trees(
    trees: Sequence[GeneratedTree], *, language: str, example: str, runtime: str
) -> dict[str, GeneratedTree]:
    """``{provider: tree}`` for every already-discovered tree of one
    (language, example, runtime); trees of any other language, example or
    runtime are ignored."""
    return {
        tree.provider: tree
        for tree in trees
        if tree.provider_group_key == (language, example, runtime)
    }


def role_sets_across_providers(
    trees: Sequence[GeneratedTree],
    *,
    language: str,
    example: str,
    runtime: str,
    declarations: Mapping[str, DomainDeclaration],
) -> dict[str, frozenset[str]]:
    """``{provider: roles with >= 1 matching path}`` for every already-discovered
    tree of one (language, example, runtime).

    Classifies each tree with `classify_paths` against the language's own
    declarations -- no new generation, no new manifest read, no second
    discovery pass.
    """
    per_provider: dict[str, frozenset[str]] = {}
    for provider, tree in _provider_trees(
        trees, language=language, example=example, runtime=runtime
    ).items():
        roles, _unclassified = classify_paths(list(tree.paths), declarations)
        per_provider[provider] = roles
    return per_provider


def cross_provider_role_gaps(
    per_provider: Mapping[str, frozenset[str]],
) -> dict[str, frozenset[str]]:
    """``{provider: roles present under some OTHER provider and absent here}``,
    only for providers with a non-empty difference -- the language-axis
    `compare_role_sets` shape one level down (fixed language, provider axis).

    Below two providers there is nothing to compare, so the result is empty:
    most examples generate under one provider profile, and a minimum-provider
    refusal belongs to gates comparing registered target sets, not to a
    per-example grouping.
    """
    if len(per_provider) < _MIN_PROVIDERS_FOR_COMPARISON:
        return {}
    union: frozenset[str] = frozenset[str]().union(*per_provider.values())
    return {
        provider: union - roles for provider, roles in per_provider.items() if union - roles
    }


def cross_provider_drifts(
    trees: Sequence[GeneratedTree],
    *,
    language: str,
    example: str,
    runtime: str,
    declarations: Mapping[str, DomainDeclaration],
    footprint: Mapping[str, Sequence[str]],
) -> list[CrossProviderDrift]:
    """Every role-set difference across the providers of one (language, example,
    runtime) that nothing excuses.

    Each provider's gap set runs through `unexcused_missing_domains`, the
    same corpus-vacuity skip the language axis applies. A provider-specific
    hole is a failure until it is fixed.

    Returns:
        One drift per unexcused (provider, role), sorted by provider then role;
        empty when the group has fewer than two providers.
    """
    provider_trees = _provider_trees(trees, language=language, example=example, runtime=runtime)
    per_provider = role_sets_across_providers(
        trees, language=language, example=example, runtime=runtime, declarations=declarations
    )
    drifts: list[CrossProviderDrift] = []
    for provider, gap in sorted(cross_provider_role_gaps(per_provider).items()):
        for domain_id in unexcused_missing_domains(
            gap,
            language=language,
            declarations=declarations,
            footprint=footprint,
        ):
            present_under = tuple(
                sorted(name for name, roles in per_provider.items() if domain_id in roles)
            )
            drifts.append(
                CrossProviderDrift(
                    language=language,
                    example=example,
                    runtime=runtime,
                    provider=provider,
                    domain=domain_id,
                    present_under=present_under,
                    tree_root=provider_trees[provider].root,
                )
            )
    return drifts


def provider_axis_drifts(
    trees: Sequence[GeneratedTree],
    *,
    declarations_by_language: Mapping[str, Mapping[str, DomainDeclaration]],
    footprint: Mapping[str, Sequence[str]],
) -> list[CrossProviderDrift]:
    """The provider axis over every (language, example, runtime) the corpus
    generated under >= 2 providers.

    Groups the SAME already-discovered trees the language axis consumes -- no
    second discovery pass. A corpus generated under one provider yields no
    group and no drift.
    """
    drifts: list[CrossProviderDrift] = []
    for language, example, runtime in provider_comparison_keys(trees):
        drifts.extend(
            cross_provider_drifts(
                trees,
                language=language,
                example=example,
                runtime=runtime,
                declarations=declarations_by_language[language],
                footprint=footprint,
            )
        )
    return drifts


# ---------------------------------------------------------------------------
# Corpus-vacuity census + reviewed records
# ---------------------------------------------------------------------------


def corpus_vacuous_pairs(footprint: Mapping[str, Sequence[str]]) -> list[tuple[str, str]]:
    """Census every `(language, domain)` this gate would skip as corpus-vacuous.

    `_is_corpus_vacuous_for_language` is consulted per (example, language,
    missing domain) triple, so the pairs it actually silences depend on which
    examples happen to be generated in >= 2 languages. This census does not:
    it asks the question over EVERY registered language and EVERY domain that
    language realizes by a structural pattern, so the reviewed-record set below
    is complete regardless of how the generated matrix grows.

    Args:
        footprint: ``{language: every generated path}`` (:func:`corpus_footprint`).

    Returns:
        Sorted `(language, domain_id)` pairs whose declared structural_pattern
        matches zero paths anywhere in that language's generated footprint.
    """
    pairs: list[tuple[str, str]] = []
    for language in sorted(registered_language_names()):
        declarations = language_domain_declarations(language)
        pairs.extend(
            (language, domain_id)
            for domain_id in sorted(declarations)
            if _is_corpus_vacuous_for_language(language, domain_id, declarations, footprint)
        )
    return pairs


def _parse_vacuity_record(index: int, raw: object) -> CorpusVacuityRecord:
    """Validate and build one record from its raw JSON object.

    Args:
        index: Position in the `records` array, for error messages.
        raw: The decoded JSON value at that position.

    Returns:
        The validated record.

    Raises:
        ValueError: If the entry is not an object, has an empty or non-string
            field, or names a `status` outside `_VACUITY_STATUSES`.
    """
    if not isinstance(raw, dict):
        raise ValueError(f"records[{index}] is not an object: {raw!r}")
    fields: dict[str, str] = {}
    for key in ("language", "domain", "status", "reason"):
        value = raw.get(key)
        if not isinstance(value, str) or not value.strip():
            raise ValueError(
                f"records[{index}] must have a non-empty string {key!r} field; "
                f"got {raw!r}."
            )
        fields[key] = value
    if fields["status"] not in _VACUITY_STATUSES:
        raise ValueError(
            f"records[{index}] has status {fields['status']!r}, which is not one "
            f"of {sorted(_VACUITY_STATUSES)}. The three carry different "
            f"remedies and are never interchangeable: "
            f"'{VACUITY_UNREACHABLE}' = no example can produce it at all; "
            f"'{VACUITY_CLOUD_ONLY}' = only a cloud-targeting example could, "
            f"and the corpus has none; '{VACUITY_UNEXERCISED}' = an ordinary "
            f"example could and none declares the construct. Recording a "
            f"weaker claim as a stronger one hides a corpus-coverage gap."
        )
    return CorpusVacuityRecord(
        language=fields["language"],
        domain=fields["domain"],
        status=fields["status"],
        reason=fields["reason"],
    )


def load_corpus_vacuity_records() -> list[CorpusVacuityRecord]:
    """Load and validate corpus-vacuity-records.json.

    Raises:
        ValueError: If the file is missing or malformed, an entry is invalid
            (see `_parse_vacuity_record`), or two entries name the same
            `(language, domain)`.
    """
    if not CORPUS_VACUITY_RECORDS_PATH.exists():
        raise ValueError(
            f"Missing corpus-vacuity record file {CORPUS_VACUITY_RECORDS_PATH}. "
            f"Restore it from git; the gate never creates it."
        )
    data = json.loads(CORPUS_VACUITY_RECORDS_PATH.read_text(encoding="utf-8"))
    raw_records = data.get("records")
    if not isinstance(raw_records, list):
        raise ValueError(
            f"Malformed {CORPUS_VACUITY_RECORDS_PATH}: expected an object with "
            f"'records' (array of {{language, domain, status, reason}})."
        )
    records = [_parse_vacuity_record(i, raw) for i, raw in enumerate(raw_records)]
    seen: set[tuple[str, str]] = set()
    for record in records:
        key = (record.language, record.domain)
        if key in seen:
            raise ValueError(
                f"{CORPUS_VACUITY_RECORDS_PATH} names ({record.language!r}, "
                f"{record.domain!r}) more than once. One (language, domain) "
                f"carries exactly one record."
            )
        seen.add(key)
    return records


def compare_vacuity_records(
    pairs: Iterable[tuple[str, str]], records: Iterable[CorpusVacuityRecord]
) -> list[str]:
    """Two-directional comparison of the census against the reviewed records.

    Pure over its arguments so the self-test can exercise it on synthetic
    coordinates without touching real baselines or plugins.

    Args:
        pairs: `(language, domain)` pairs the census found corpus-vacuous.
        records: The reviewed records.

    Returns:
        One problem description per unrecorded pair (a domain this gate would
        silently skip with nothing on the record saying why) and one per stale
        record (a pair that is no longer vacuous, so the record must be
        deleted and the pinned count decremented). Empty means the two agree.
    """
    censused = set(pairs)
    recorded = {(record.language, record.domain) for record in records}
    problems: list[str] = []
    problems.extend(
        f"UNRECORDED CORPUS VACUITY language={language} domain={domain}: this "
        f"language realizes the domain by a structural_pattern that "
        f"matches zero paths anywhere in its generated footprint, and "
        f"{CORPUS_VACUITY_RECORDS_PATH.name} says nothing about it. Add a "
        f"record naming the structural reason and its status (one of "
        f"{sorted(_VACUITY_STATUSES)}), or add a reference example that "
        f"exercises it."
        for language, domain in sorted(censused - recorded)
    )
    problems.extend(
        f"STALE CORPUS-VACUITY RECORD language={language} domain={domain}: the "
        f"generated corpus now matches this domain's structural_pattern, so the "
        f"record no longer describes anything. Delete it."
        for language, domain in sorted(recorded - censused)
    )
    return problems


def check_corpus_vacuity_records(footprint: Mapping[str, Sequence[str]]) -> bool:
    """Hold every corpus-vacuous `(language, domain)` to a reviewed record.

    A corpus-vacuous domain is skipped SILENTLY by
    `check_artifact_role_parity` -- correctly, since a single-example
    "missing" verdict over a construct no example declares carries no
    information. Silence is the problem: a generator no example reaches has
    no end-to-end signal at all, and nothing distinguishes "no example CAN
    reach this" from "no example HAPPENS to". This turns each skip into a
    typed, counted, reviewed record.

    Args:
        footprint: ``{language: every generated path}`` over the COMPLETE
            corpus (:func:`corpus_footprint`); the caller has already refused
            an incomplete one.

    Returns:
        True when the census and the records agree in both directions.
    """
    records = load_corpus_vacuity_records()
    pairs = corpus_vacuous_pairs(footprint)
    logger.info(
        "corpus_vacuity_census pairs=%d records=%d", len(pairs), len(records),
    )
    problems = compare_vacuity_records(pairs, records)
    if problems:
        for problem in problems:
            logger.error("%s", problem)
        return False
    by_status = {
        status: sum(1 for record in records if record.status == status)
        for status in sorted(_VACUITY_STATUSES)
    }
    logger.info("corpus_vacuity_records_ok recorded=%d by_status=%s", len(records), by_status)
    return True


# ---------------------------------------------------------------------------
# Non-vacuity self-test
# ---------------------------------------------------------------------------


_SELF_TEST_DOMAIN_SHALLOW: Final[str] = "self_test_order_shallow"
_SELF_TEST_DOMAIN_DEEP: Final[str] = "self_test_order_deep"
_SELF_TEST_ORDERS_PATTERN: Final[str] = "*/orders/*.txt"
_SELF_TEST_SHIPMENTS_PATTERN: Final[str] = "*/shipments/*.txt"
_SELF_TEST_NEVER_PATTERN: Final[str] = "*/never_matches_anything/*.txt"
#: One language's generated footprint for the excuse cases: the orders pattern
#: matches a file in it, the never-matching pattern does not.
_SELF_TEST_FOOTPRINT: Final[Mapping[str, Sequence[str]]] = {
    _SELF_TEST_LANGUAGE_A: ("svc/orders/order.txt", "svc/unrelated/readme.md"),
}
_SELF_TEST_PROVIDER_ONE: Final[str] = "self_test_provider_one"
_SELF_TEST_PROVIDER_TWO: Final[str] = "self_test_provider_two"
_SELF_TEST_RUNTIME: Final[str] = "rt"
_SELF_TEST_OTHER_RUNTIME: Final[str] = "rt_other"
_SELF_TEST_STAMP: Final[str] = "2026-01-01T00:00:00Z"


class _SelfTestLedger:
    """Collects the self-test's outcomes and logs one ``[OK]`` or ``[FAIL]``
    line per named case, so a reader sees which behaviours were proven."""

    def __init__(self) -> None:
        self.problems: list[str] = []

    def absorb(self, case: str, problems: Sequence[str]) -> None:
        """Record *case* as passed when *problems* is empty, else keep every problem."""
        if problems:
            self.problems.extend(problems)
            logger.error("[FAIL] %s", case)
            return
        logger.info("[OK] %s", case)

    def expect(self, case: str, condition: bool, failure: str) -> None:
        """Record *case* as passed when *condition* holds, else as *failure*."""
        self.absorb(case, () if condition else (f"self-test: {case}: {failure}",))


def _patterned(domain_id: str, pattern: str) -> DomainDeclaration:
    """A realized declaration: the domain id and the glob its generator emits to."""
    return DomainDeclaration(domain_id=domain_id, structural_pattern=pattern)


def _value_error_message(call: Callable[[], object]) -> str | None:
    """The message of the ``ValueError`` *call* raises, or ``None`` when it
    returns normally -- the self-test's way of asking "did the guard reject?"."""
    try:
        call()
    except ValueError as exc:
        return str(exc)
    return None


def run_self_test() -> list[str]:
    """Prove the comparators, classifier and the one excuse rule are
    non-vacuous before any real comparison is trusted.

    Logs one ``[OK]`` (or ``[FAIL]``) line per case.

    Returns:
        Problem descriptions; empty means the gate is sound.
    """
    ledger = _SelfTestLedger()
    _self_test_role_set_comparison(ledger)
    _self_test_classification(ledger)
    _self_test_unexcused_missing_domains(ledger)
    _self_test_language_axis(ledger)
    _self_test_vacuity_predicate(ledger)
    ledger.absorb("generated-corpus discovery reader", _self_test_corpus_discovery())
    _self_test_provider_axis(ledger)
    ledger.absorb("corpus-vacuity record comparison", _self_test_vacuity_records())
    return ledger.problems


def _self_test_role_set_comparison(ledger: _SelfTestLedger) -> None:
    """The language-axis comparator detects a forced mismatch and does not
    false-positive a matching pair."""
    matching = {
        _SELF_TEST_LANGUAGE_A: frozenset({_SELF_TEST_DOMAIN_SHARED}),
        _SELF_TEST_LANGUAGE_B: frozenset({_SELF_TEST_DOMAIN_SHARED}),
    }
    ledger.expect(
        "compare_role_sets reports nothing for a matching pair",
        not any(compare_role_sets(matching).values()),
        "reported a divergence for a synthetic MATCHING pair",
    )
    mismatched = compare_role_sets(
        {
            _SELF_TEST_LANGUAGE_A: frozenset(
                {_SELF_TEST_DOMAIN_SHARED, _SELF_TEST_DOMAIN_FORCED_GAP}
            ),
            _SELF_TEST_LANGUAGE_B: frozenset({_SELF_TEST_DOMAIN_SHARED}),
        }
    )
    ledger.expect(
        "compare_role_sets detects a forced mismatch",
        mismatched[_SELF_TEST_LANGUAGE_B] == frozenset({_SELF_TEST_DOMAIN_FORCED_GAP})
        and not mismatched[_SELF_TEST_LANGUAGE_A],
        f"expected exactly {_SELF_TEST_DOMAIN_FORCED_GAP!r} missing from "
        f"{_SELF_TEST_LANGUAGE_B!r} and nothing missing from {_SELF_TEST_LANGUAGE_A!r}, "
        f"got {mismatched}",
    )
    ledger.expect(
        "compare_role_sets refuses a single-language mapping",
        _value_error_message(lambda: compare_role_sets({_SELF_TEST_LANGUAGE_A: frozenset()}))
        is not None,
        "accepted a single-language mapping",
    )


def _self_test_classification(ledger: _SelfTestLedger) -> None:
    """`classify_paths` credits a domain through the pattern it carries and
    nothing else: matched vs unclassified paths, the package-init marker and
    the most-specific tie-break."""
    declarations: DomainDeclarations = {
        _SELF_TEST_DOMAIN_SHARED: _patterned(_SELF_TEST_DOMAIN_SHARED, _SELF_TEST_ORDERS_PATTERN),
    }
    roles, unclassified = classify_paths(
        ["svc/orders/order.txt", "svc/unrelated/readme.md"], declarations
    )
    ledger.expect(
        "classify_paths credits a pattern-bearing declaration (the pattern is the only input)",
        roles == frozenset({_SELF_TEST_DOMAIN_SHARED}),
        f"role mismatch: {roles}",
    )
    ledger.expect(
        "classify_paths routes a path matching no pattern to unclassified",
        unclassified == ["svc/unrelated/readme.md"],
        f"unclassified mismatch: {unclassified}",
    )
    # __init__.py sitting in a domain's own matching directory is package-structure
    # boilerplate, never credited, even though its bare name satisfies a trailing `*` glob.
    marker_roles, marker_unclassified = classify_paths(
        ["svc/orders/__init__.py"],
        {_SELF_TEST_DOMAIN_SHARED: _patterned(_SELF_TEST_DOMAIN_SHARED, "*/orders/*.py")},
    )
    ledger.expect(
        "classify_paths never credits a package-init marker to a domain",
        marker_roles == frozenset() and marker_unclassified == ["svc/orders/__init__.py"],
        f"credited {marker_roles}, unclassified {marker_unclassified}",
    )
    # A shallow pattern that also matches a sibling's deeper path must NOT be
    # credited for that path.
    overlap_roles, _unclassified = classify_paths(
        ["svc/orders/archive/order.txt", "svc/orders/order.txt"],
        {
            _SELF_TEST_DOMAIN_SHALLOW: _patterned(
                _SELF_TEST_DOMAIN_SHALLOW, _SELF_TEST_ORDERS_PATTERN
            ),
            _SELF_TEST_DOMAIN_DEEP: _patterned(_SELF_TEST_DOMAIN_DEEP, "*/orders/*/*.txt"),
        },
    )
    ledger.expect(
        "classify_paths credits each path to its most specific pattern",
        overlap_roles == frozenset({_SELF_TEST_DOMAIN_SHALLOW, _SELF_TEST_DOMAIN_DEEP}),
        f"expected both domains credited (one per path, at its own most-specific "
        f"match), got {overlap_roles}",
    )


def _self_test_unexcused(
    declarations: Mapping[str, DomainDeclaration],
    *,
    missing: Iterable[str] = (_SELF_TEST_DOMAIN_FORCED_GAP,),
) -> list[str]:
    """`unexcused_missing_domains` over the self-test's one language and footprint."""
    return unexcused_missing_domains(
        missing,
        language=_SELF_TEST_LANGUAGE_A,
        declarations=declarations,
        footprint=_SELF_TEST_FOOTPRINT,
    )


def _self_test_unexcused_missing_domains(ledger: _SelfTestLedger) -> None:
    """A missing role is a failure unless the corpus vacuity skip excuses it."""
    forced = _SELF_TEST_DOMAIN_FORCED_GAP
    realized: DomainDeclarations = {
        forced: _patterned(forced, _SELF_TEST_ORDERS_PATTERN),
    }
    zero_match: DomainDeclarations = {
        forced: _patterned(forced, _SELF_TEST_NEVER_PATTERN),
    }
    no_declaration = _self_test_unexcused({})
    ledger.expect(
        "a missing role is a failure for a language holding no declaration for the domain",
        no_declaration == [forced],
        f"expected [{forced!r}] (the absence of a declaration excuses nothing), got {no_declaration}",
    )
    nothing_excuses = _self_test_unexcused(realized)
    ledger.expect(
        "a missing role in a domain the language realizes, and emits elsewhere in its footprint, is a failure",
        nothing_excuses == [forced],
        f"expected [{forced!r}] (no declaration or per-example file can excuse it), got {nothing_excuses}",
    )
    vacuous_excused = _self_test_unexcused(zero_match)
    ledger.expect(
        "a pattern matching zero files in the footprint excuses a missing role",
        vacuous_excused == [],
        f"a corpus-vacuous domain was still reported: {vacuous_excused}",
    )
    ordered = _self_test_unexcused({}, missing={"b_domain", "a_domain"})
    ledger.expect(
        "unexcused_missing_domains returns the surviving ids sorted",
        ordered == ["a_domain", "b_domain"],
        f"got {ordered}",
    )


def _self_test_language_axis(ledger: _SelfTestLedger) -> None:
    """The language-axis wiring: a role one language emits and another lacks is
    a failure even when the lacking language holds no declaration for the
    domain (the former declared-absence case), and identical sets pass."""
    shared = _SELF_TEST_DOMAIN_SHARED
    forced = _SELF_TEST_DOMAIN_FORCED_GAP
    language_a = _SELF_TEST_LANGUAGE_A
    language_b = _SELF_TEST_LANGUAGE_B
    declarations_by_language: dict[str, DomainDeclarations] = {
        language_a: {
            shared: _patterned(shared, _SELF_TEST_ORDERS_PATTERN),
            forced: _patterned(forced, _SELF_TEST_SHIPMENTS_PATTERN),
        },
        language_b: {shared: _patterned(shared, _SELF_TEST_ORDERS_PATTERN)},
    }

    def gaps(roles: Mapping[str, frozenset[str]]) -> dict[str, list[str]]:
        return language_axis_gaps(
            roles,
            declarations_by_language=declarations_by_language,
            footprint=_SELF_TEST_FOOTPRINT,
        )

    planted = {language_a: frozenset({shared, forced}), language_b: frozenset({shared})}
    planted_gaps = gaps(planted)
    ledger.expect(
        "the language axis fails a role absent from a language that holds no declaration for it",
        planted_gaps == {language_b: [forced]},
        f"expected {{{language_b!r}: [{forced!r}]}}, got {planted_gaps}",
    )
    identical_gaps = gaps({language_a: frozenset({shared}), language_b: frozenset({shared})})
    ledger.expect(
        "the language axis reports nothing for identical role sets",
        identical_gaps == {},
        f"got {identical_gaps}",
    )


def _self_test_vacuity_predicate(ledger: _SelfTestLedger) -> None:
    """`_is_corpus_vacuous_for_language` against a synthetic footprint (never a
    real generated tree): a pattern matching nothing is vacuous, the same
    pattern shape matching a path is not, and a domain with no declaration is
    never vacuous -- its role is missing, which fails."""
    domain = _SELF_TEST_DOMAIN_SHARED
    language = _SELF_TEST_LANGUAGE_A
    ledger.expect(
        "a pattern matching zero paths in the language's footprint is corpus-vacuous",
        _is_corpus_vacuous_for_language(
            language,
            domain,
            {domain: _patterned(domain, _SELF_TEST_NEVER_PATTERN)},
            _SELF_TEST_FOOTPRINT,
        ),
        "did not flag a domain whose pattern matches zero paths anywhere in the footprint",
    )
    ledger.expect(
        "a pattern matching a path elsewhere in the footprint is not corpus-vacuous",
        not _is_corpus_vacuous_for_language(
            language,
            domain,
            {domain: _patterned(domain, _SELF_TEST_ORDERS_PATTERN)},
            _SELF_TEST_FOOTPRINT,
        ),
        "flagged a domain whose pattern DOES match a path in the footprint",
    )
    ledger.expect(
        "a domain with no declaration is never corpus-vacuous",
        not _is_corpus_vacuous_for_language(language, domain, {}, _SELF_TEST_FOOTPRINT),
        "flagged a domain the language holds no declaration for as corpus-vacuous",
    )


#: Scratch root for the discovery self-test's synthetic generated corpus --
#: workspace-level per the temp-file policy, PID-scoped so two concurrent
#: gate runs never share a directory.
_SELF_TEST_SCRATCH_ROOT: Path = WORKSPACE_ROOT / ".test-output" / "artifact-role-self-test"


def _write_synthetic_tree(
    root: Path, language: str, runtime: str, provider: str, example: str,
    manifests: Mapping[str, tuple[str, list[str]]],
) -> None:
    """Write one synthetic generated project with the given pipeline manifests.

    Args:
        manifests: ``{target: (generated_at, files)}``.
    """
    manifests_dir = root / language / runtime / provider / example / MANIFESTS_RELPATH
    manifests_dir.mkdir(parents=True, exist_ok=True)
    for target, (stamp, files) in manifests.items():
        (manifests_dir / f"{target}.json").write_text(
            json.dumps({"target": target, "generated_at": stamp, "files": files}),
            encoding="utf-8",
        )


def _self_test_corpus_discovery() -> list[str]:
    """Prove the generated-corpus reader sees what is there and nothing else.

    Builds a synthetic ``.generated`` layout under a PID-scoped scratch root
    against ONE real registered example path (so the discovery walk is the
    production walk), then proves: two targets' manifests union into one
    path list with the newest stamp; a directory without pipeline manifests
    is not a tree; a tree generated in one language only forms no comparison
    group while a two-language tree does; and the corpus-completeness check
    names a missing pair and a stale park entry.
    """
    problems: list[str] = []
    example = registered_example_relpaths()[0]
    other_example = registered_example_relpaths()[-1]
    scratch = _SELF_TEST_SCRATCH_ROOT / str(os.getpid())
    if scratch.exists():
        shutil.rmtree(scratch)
    try:
        _write_synthetic_tree(
            scratch, _SELF_TEST_LANGUAGE_A, "rt", "prov", example,
            {
                "svc": ("2026-01-01T00:00:00Z", ["svc/a.txt", "svc/b.txt"]),
                "infra": ("2026-01-02T00:00:00Z", ["compose.yml", "svc/a.txt"]),
            },
        )
        _write_synthetic_tree(
            scratch, _SELF_TEST_LANGUAGE_B, "rt", "prov", example,
            {"svc": ("2026-01-03T00:00:00Z", ["svc/a.txt"])},
        )
        _write_synthetic_tree(
            scratch, _SELF_TEST_LANGUAGE_A, "rt", "prov", other_example,
            {"svc": ("2026-01-04T00:00:00Z", ["svc/z.txt"])},
        )
        # A directory at tree depth with no manifests is not a generated tree.
        (scratch / _SELF_TEST_LANGUAGE_B / "rt" / "prov" / other_example).mkdir(parents=True)

        languages = (_SELF_TEST_LANGUAGE_A, _SELF_TEST_LANGUAGE_B)
        trees = discover_generated_trees(scratch, languages)
        by_key = {(t.language, t.example): t for t in trees}
        if set(by_key) != {
            (_SELF_TEST_LANGUAGE_A, example),
            (_SELF_TEST_LANGUAGE_B, example),
            (_SELF_TEST_LANGUAGE_A, other_example),
        }:
            problems.append(
                f"self-test: discover_generated_trees found {sorted(by_key)}, expected "
                f"exactly the three synthetic trees carrying pipeline manifests"
            )
            return problems
        merged = by_key[(_SELF_TEST_LANGUAGE_A, example)]
        if merged.paths != ("compose.yml", "svc/a.txt", "svc/b.txt"):
            problems.append(
                f"self-test: read_pipeline_manifests did not union two targets' "
                f"files into a sorted, de-duplicated list: {merged.paths}"
            )
        if merged.generated_at != "2026-01-02T00:00:00Z":
            problems.append(
                f"self-test: read_pipeline_manifests did not keep the newest "
                f"generated_at stamp: {merged.generated_at}"
            )
        groups = comparison_groups(trees)
        if list(groups) != [(example, "rt", "prov")]:
            problems.append(
                f"self-test: comparison_groups returned {sorted(groups)}, expected only "
                f"the group generated in two languages"
            )
        footprint = corpus_footprint(trees)
        if footprint.get(_SELF_TEST_LANGUAGE_A) != [
            "compose.yml", "svc/a.txt", "svc/b.txt", "svc/z.txt",
        ]:
            problems.append(
                f"self-test: corpus_footprint did not concatenate every tree of a "
                f"language: {footprint.get(_SELF_TEST_LANGUAGE_A)}"
            )
        known = {f"{example_id(other_example)}{_LANGUAGE_KEY_SEP}{_SELF_TEST_LANGUAGE_A}": "self-test park"}
        missing, stale = missing_corpus_pairs(trees, languages, known)
        expected_missing = sorted(
            (ex, lang)
            for lang in languages
            for ex in registered_example_relpaths()
            if (lang, ex) not in by_key
        )
        if sorted(missing) != expected_missing:
            problems.append(
                f"self-test: missing_corpus_pairs reported {len(missing)} missing "
                f"pairs, expected {len(expected_missing)}"
            )
        if stale != [(other_example, _SELF_TEST_LANGUAGE_A)]:
            problems.append(
                f"self-test: missing_corpus_pairs did not flag the parked pair that "
                f"has a generated tree as stale: {stale}"
            )
    finally:
        shutil.rmtree(scratch, ignore_errors=True)
    return problems


def _write_provider_axis_scratch(scratch: Path, example: str, other_example: str) -> None:
    """Write the synthetic multi-provider corpus the provider-axis cases read.

    ``self_test_lang_a`` is generated under two providers for one example (the
    first carries an extra role the second lacks), and the layout also holds a
    tree of every kind the comparison must ignore: another language, another
    example generated under one provider only, and another runtime whose
    provider tree carries the extra role (which would mask the planted gap if
    the runtime were not part of the group key).
    """
    orders = ["svc/orders/order.txt"]
    with_shipments = [*orders, "svc/shipments/ship.txt"]
    layout = (
        (_SELF_TEST_LANGUAGE_A, _SELF_TEST_RUNTIME, _SELF_TEST_PROVIDER_ONE, example, with_shipments),
        (_SELF_TEST_LANGUAGE_A, _SELF_TEST_RUNTIME, _SELF_TEST_PROVIDER_TWO, example, orders),
        (_SELF_TEST_LANGUAGE_A, _SELF_TEST_RUNTIME, _SELF_TEST_PROVIDER_ONE, other_example, orders),
        (_SELF_TEST_LANGUAGE_A, _SELF_TEST_OTHER_RUNTIME, _SELF_TEST_PROVIDER_TWO, example, with_shipments),
        (_SELF_TEST_LANGUAGE_B, _SELF_TEST_RUNTIME, _SELF_TEST_PROVIDER_ONE, example, orders),
    )
    for language, runtime, provider, tree_example, files in layout:
        _write_synthetic_tree(
            scratch, language, runtime, provider, tree_example,
            {"svc": (_SELF_TEST_STAMP, files)},
        )


def _self_test_provider_axis(ledger: _SelfTestLedger) -> None:
    """Prove the provider axis is live and not vacuously always-failing.

    Reads a synthetic multi-provider ``.generated`` layout through the
    production discovery walk, then proves: only a group generated under >= 2
    providers is compared; the per-provider role sets ignore every other
    language, example and runtime; a planted role present under one provider
    and absent under another is reported against exactly the provider lacking
    it, on a line naming both providers; identical role sets and a single
    provider report nothing; and the one skip, corpus vacuity, excuses a role
    on the provider axis exactly as on the language axis.
    """
    example = registered_example_relpaths()[0]
    other_example = registered_example_relpaths()[-1]
    scratch = _SELF_TEST_SCRATCH_ROOT / f"{os.getpid()}-provider-axis"
    if scratch.exists():
        shutil.rmtree(scratch)
    try:
        _write_provider_axis_scratch(scratch, example, other_example)
        trees = discover_generated_trees(scratch, (_SELF_TEST_LANGUAGE_A, _SELF_TEST_LANGUAGE_B))
        _expect_provider_axis(ledger, trees, example, other_example)
    finally:
        shutil.rmtree(scratch, ignore_errors=True)


def _expect_provider_axis(
    ledger: _SelfTestLedger,
    trees: Sequence[GeneratedTree],
    example: str,
    other_example: str,
) -> None:
    """The provider-axis assertions over the discovered synthetic corpus."""
    language = _SELF_TEST_LANGUAGE_A
    runtime = _SELF_TEST_RUNTIME
    provider_one = _SELF_TEST_PROVIDER_ONE
    provider_two = _SELF_TEST_PROVIDER_TWO
    shared = _SELF_TEST_DOMAIN_SHARED
    forced = _SELF_TEST_DOMAIN_FORCED_GAP
    declarations: DomainDeclarations = {
        shared: _patterned(shared, _SELF_TEST_ORDERS_PATTERN),
        forced: _patterned(forced, _SELF_TEST_SHIPMENTS_PATTERN),
    }
    footprint = corpus_footprint(trees)

    def axis_drifts(axis_footprint: Mapping[str, Sequence[str]]) -> list[CrossProviderDrift]:
        return provider_axis_drifts(
            trees,
            declarations_by_language={language: declarations},
            footprint=axis_footprint,
        )

    keys = provider_comparison_keys(trees)
    ledger.expect(
        "the provider axis compares only (language, example, runtime) groups generated under >= 2 providers",
        keys == [(language, example, runtime)],
        f"expected exactly {[(language, example, runtime)]}, got {keys}",
    )
    per_provider = role_sets_across_providers(
        trees, language=language, example=example, runtime=runtime, declarations=declarations
    )
    ledger.expect(
        "role_sets_across_providers returns one role set per provider and ignores other "
        "languages, examples and runtimes",
        per_provider
        == {provider_one: frozenset({shared, forced}), provider_two: frozenset({shared})},
        f"got {per_provider}",
    )
    gaps = cross_provider_role_gaps(per_provider)
    ledger.expect(
        "cross_provider_role_gaps reports exactly the planted role against exactly the provider lacking it",
        gaps == {provider_two: frozenset({forced})},
        f"got {gaps}",
    )
    drifts = axis_drifts(footprint)
    line = drifts[0].report_line() if len(drifts) == 1 else ""
    ledger.expect(
        "the provider-axis report line names the language, the role, the provider missing it "
        "and the provider that has it",
        len(drifts) == 1
        and drifts[0].provider == provider_two
        and drifts[0].present_under == (provider_one,)
        and line.startswith("ARTIFACT-ROLE CROSS-PROVIDER DRIFT")
        and all(
            part in line
            for part in (language, example, runtime, forced, f"provider={provider_two}", provider_one)
        ),
        f"expected one drift against {provider_two!r} present under {provider_one!r}, got {drifts}",
    )
    identical = frozenset({shared})
    ledger.expect(
        "cross_provider_role_gaps reports nothing for identical role sets",
        cross_provider_role_gaps({provider_one: identical, provider_two: identical}) == {},
        "reported a gap between two providers carrying the same roles",
    )
    single_provider = cross_provider_drifts(
        trees,
        language=language,
        example=other_example,
        runtime=runtime,
        declarations=declarations,
        footprint=footprint,
    )
    ledger.expect(
        "a single provider reports no gap and raises nothing",
        cross_provider_role_gaps({provider_one: identical}) == {} and single_provider == [],
        f"a group generated under one provider produced {single_provider}",
    )
    vacuous_drifts = axis_drifts({language: ()})
    ledger.expect(
        "a role whose pattern matches nothing in the language's footprint is not reported on the "
        "provider axis",
        vacuous_drifts == [],
        f"got {vacuous_drifts}",
    )


def _self_test_vacuity_records() -> list[str]:
    """Prove the corpus-vacuity record comparison is non-vacuous.

    Fully synthetic coordinates -- never a real language, domain, or record
    file. Three properties: an agreeing census/record pair reports nothing; a
    censused pair with NO record is reported (the silence this comparison
    exists to end); and a record whose pair is no longer censused is reported
    stale. Plus: `_parse_vacuity_record` accepts both declared statuses and
    refuses a third, so "unexercised" can never be spelled as something the
    loader waves through.

    Returns:
        Problem descriptions; empty means the comparison is sound.
    """
    problems: list[str] = []
    record = CorpusVacuityRecord(
        language=_SELF_TEST_LANGUAGE_A,
        domain=_SELF_TEST_DOMAIN_SHARED,
        status=VACUITY_UNREACHABLE,
        reason="self-test: synthetic record, never a real coordinate",
    )
    agreeing = compare_vacuity_records([(_SELF_TEST_LANGUAGE_A, _SELF_TEST_DOMAIN_SHARED)], [record])
    if agreeing:
        problems.append(
            f"self-test: compare_vacuity_records reported problems for an "
            f"agreeing census/record pair: {agreeing}"
        )
    unrecorded = compare_vacuity_records(
        [
            (_SELF_TEST_LANGUAGE_A, _SELF_TEST_DOMAIN_SHARED),
            (_SELF_TEST_LANGUAGE_A, _SELF_TEST_DOMAIN_FORCED_GAP),
        ],
        [record],
    )
    if not any(_SELF_TEST_DOMAIN_FORCED_GAP in problem for problem in unrecorded):
        problems.append(
            f"self-test: compare_vacuity_records did not report a censused "
            f"pair with no reviewed record: {unrecorded}"
        )
    stale = compare_vacuity_records([], [record])
    if not any(_SELF_TEST_DOMAIN_SHARED in problem for problem in stale):
        problems.append(
            f"self-test: compare_vacuity_records did not report a record whose "
            f"pair is no longer corpus-vacuous: {stale}"
        )

    for status in sorted(_VACUITY_STATUSES):
        parsed = _parse_vacuity_record(
            0,
            {
                "language": _SELF_TEST_LANGUAGE_A,
                "domain": _SELF_TEST_DOMAIN_SHARED,
                "status": status,
                "reason": "self-test: declared status must parse",
            },
        )
        if parsed.status != status:
            problems.append(
                f"self-test: _parse_vacuity_record mangled a declared status: "
                f"{parsed.status!r} != {status!r}"
            )
    refused_undeclared_status = False
    try:
        _parse_vacuity_record(
            0,
            {
                "language": _SELF_TEST_LANGUAGE_A,
                "domain": _SELF_TEST_DOMAIN_SHARED,
                "status": "self_test_undeclared_status",
                "reason": "self-test: should be rejected",
            },
        )
    except ValueError:
        refused_undeclared_status = True
    if not refused_undeclared_status:
        problems.append(
            "self-test: _parse_vacuity_record accepted a status outside the "
            "declared set"
        )
    return problems


# ---------------------------------------------------------------------------
# Commands
# ---------------------------------------------------------------------------


class IncompleteCorpusError(ValueError):
    """The generated corpus under the given root is not complete for every
    registered language (or a park entry is stale), so no comparison over it
    can be trusted. Every offending pair has already been logged by name."""


def load_complete_corpus(generated_root: Path) -> list[GeneratedTree]:
    """Discover the generated corpus and refuse an incomplete or stale-parked one.

    Args:
        generated_root: The ``generate.ps1`` output base to read.

    Returns:
        Every discovered tree, when the corpus is complete for every registered
        language.

    Raises:
        IncompleteCorpusError: After logging every missing (example, language)
            pair with the command that generates it, and every stale park
            entry. Fail-closed: a partial corpus would make every absent
            example's domains read as corpus-vacuous and silently shrink the
            comparison.
    """
    languages = sorted(registered_language_names())
    known = load_known_non_generating()
    trees = discover_generated_trees(generated_root, languages)
    for language in languages:
        stamps = sorted(t.generated_at for t in trees if t.language == language)
        logger.info(
            "generated_corpus language=%s trees=%d oldest=%s newest=%s",
            language, len(stamps), stamps[0] if stamps else "-", stamps[-1] if stamps else "-",
        )
    missing, stale = missing_corpus_pairs(trees, languages, known)
    for example, language in stale:
        logger.error(
            "STALE PARK ENTRY example=%s language=%s: %s parks this pair, but a "
            "generated tree exists for it -- the recorded defect is fixed. Delete "
            "the entry.",
            example, language, KNOWN_NON_GENERATING_PATH.name,
        )
    if missing:
        by_language: dict[str, list[str]] = {}
        for example, language in missing:
            by_language.setdefault(language, []).append(example)
        for language, examples in sorted(by_language.items()):
            logger.error(
                "INCOMPLETE CORPUS language=%s: %d registered example(s) have no "
                "generated tree under %s and no entry in %s: %s. Generate the full "
                "corpus first: generate.ps1 -All -L %s",
                language, len(examples), generated_root, KNOWN_NON_GENERATING_PATH.name,
                examples, language,
            )
    if missing or stale:
        raise IncompleteCorpusError(
            f"ARTIFACT-ROLE GATE CANNOT RUN: the generated corpus under {generated_root} "
            f"is not complete for every registered language ({len(missing)} missing "
            f"pair(s), {len(stale)} stale park entr{'y' if len(stale) == 1 else 'ies'}; "
            f"see above)."
        )
    return trees


def language_axis_gaps(
    per_language_roles: Mapping[str, frozenset[str]],
    *,
    declarations_by_language: Mapping[str, Mapping[str, DomainDeclaration]],
    footprint: Mapping[str, Sequence[str]],
) -> dict[str, list[str]]:
    """``{language: roles missing from it that nothing excuses}`` for one
    (example, runtime, provider) group, only for languages with a non-empty
    list.

    Compares every language's role set against the union of all, then runs each
    language's missing roles through `unexcused_missing_domains` -- the same
    excuse rule the provider axis applies.

    Args:
        per_language_roles: ``{language: role_set}`` for the group.
        declarations_by_language: Each language's own derived declarations.
        footprint: ``{language: every generated path}`` (:func:`corpus_footprint`).
    """
    gaps: dict[str, list[str]] = {}
    for language, missing in sorted(compare_role_sets(per_language_roles).items()):
        unexcused = unexcused_missing_domains(
            missing,
            language=language,
            declarations=declarations_by_language[language],
            footprint=footprint,
        )
        if unexcused:
            gaps[language] = unexcused
    return gaps


def _language_axis_group_ok(
    example: str,
    runtime: str,
    provider: str,
    language_trees: Mapping[str, GeneratedTree],
    *,
    declarations_by_language: Mapping[str, DomainDeclarations],
    footprint: Mapping[str, Sequence[str]],
) -> bool:
    """Compare one (example, runtime, provider) group's role sets across its
    languages, logging every un-excused missing role as drift.

    Returns:
        True when every language's role set matches the union modulo the
        corpus vacuity skip.
    """
    per_language_roles: dict[str, frozenset[str]] = {}
    for language, tree in sorted(language_trees.items()):
        roles, unclassified = classify_paths(list(tree.paths), declarations_by_language[language])
        per_language_roles[language] = roles
        if unclassified:
            logger.info(
                "artifact_role_unclassified example=%s language=%s count=%d "
                "(reported, not compared): %s",
                example, language, len(unclassified), unclassified[:5],
            )
    gaps = language_axis_gaps(
        per_language_roles,
        declarations_by_language=declarations_by_language,
        footprint=footprint,
    )
    for language, domain_ids in gaps.items():
        for domain_id in domain_ids:
            logger.error(
                "ARTIFACT-ROLE DRIFT example=%s runtime=%s provider=%s language=%s "
                "missing_domain=%s (present in >= 1 other language generated for "
                "this example; %s's generated tree %s matches no file to this "
                "domain's structural_pattern)",
                example, runtime, provider, language, domain_id, language,
                language_trees[language].root,
            )
    clean = not gaps
    if clean:
        logger.info(
            "artifact_role_example_clean example=%s runtime=%s provider=%s languages=%s",
            example, runtime, provider, sorted(language_trees),
        )
    return clean


def check_artifact_role_parity(generated_root: Path) -> int:
    """Run the gate over every (example, runtime, provider) generated in >= 2
    languages, then over every (language, example, runtime) generated under
    >= 2 providers.

    A role missing from one language's tree (or one provider's) is a failure.
    Exactly one kind of "missing" is never drift, and it reads no declaration
    and no committed exemption: the language realizes the domain by a
    structural_pattern that matches zero files anywhere across that language's
    ENTIRE generated footprint (see `_is_corpus_vacuous_for_language`) -- an
    empirical, corpus-wide fact (the triggering construct never occurs in the
    corpus for this language) rather than something particular to this
    example.

    That kind is skipped but never silent: `check_corpus_vacuity_records`
    holds every corpus-vacuous `(language, domain)` to a reviewed record
    stating WHY nothing exercises it, and refuses both an unrecorded pair and
    a record whose pair is no longer vacuous. A language that emits a domain
    under a narrower DSL trigger than another language is not excused, and
    neither is a language that realizes a domain by no structural_pattern: the
    latter's gap is tracked once on its own capability declaration and counted
    by the capability-gap ledger gate, and this gate reports the missing role
    regardless.

    Args:
        generated_root: The ``generate.ps1`` output base to read.

    Returns:
        Exit code (0 = every group's role sets agree modulo recorded
        corpus-vacuous domains, on both the language and the provider
        axis; 1 = an un-excused role difference was found on either axis, or a
        corpus-vacuous domain has no reviewed record (or a record has no
        corpus-vacuous domain); 2 = the corpus is incomplete for some language,
        a park entry is stale, or zero groups are generated in >= 2 languages
        -- a vacuous comparison).
    """
    trees = load_complete_corpus(generated_root)
    groups = comparison_groups(trees)
    if not groups:
        logger.error(
            "ARTIFACT-ROLE GATE CANNOT RUN: no (example, runtime, provider) under %s "
            "is generated in >= 2 languages -- a cross-language comparison over "
            "< 2 languages is vacuous.",
            generated_root,
        )
        return EXIT_USAGE

    provider_keys = provider_comparison_keys(trees)
    logger.info(
        "artifact_role_parity_start trees=%d groups=%d provider_groups=%d",
        len(trees), len(groups), len(provider_keys),
    )

    footprint = corpus_footprint(trees)
    vacuity_ok = check_corpus_vacuity_records(footprint)
    corpus_languages = sorted({tree.language for tree in trees})
    declarations_by_language = {
        language: language_domain_declarations(language) for language in corpus_languages
    }
    group_results = [
        _language_axis_group_ok(
            example, runtime, provider, language_trees,
            declarations_by_language=declarations_by_language,
            footprint=footprint,
        )
        for (example, runtime, provider), language_trees in groups.items()
    ]
    provider_drifts = provider_axis_drifts(
        trees,
        declarations_by_language=declarations_by_language,
        footprint=footprint,
    )
    for drift in provider_drifts:
        logger.error("%s", drift.report_line())

    if vacuity_ok and all(group_results) and not provider_drifts:
        logger.info(
            "ARTIFACT-ROLE GATE PASSED: %d group(s) generated in >= 2 languages and %d "
            "(language, example, runtime) group(s) generated under >= 2 providers, role "
            "sets identical modulo recorded corpus-vacuous domains.",
            len(groups), len(provider_keys),
        )
        return EXIT_OK
    return EXIT_FAIL


def _parse_args(argv: list[str]) -> argparse.Namespace:
    """Parse CLI arguments."""
    parser = argparse.ArgumentParser(
        description=(
            "Artifact-role parity gate: for every (example, runtime, provider) "
            "generated in >= 2 languages, and for every (language, example, "
            "runtime) generated under >= 2 providers, the set of domain roles "
            "with >= 1 matching file must be identical across the languages "
            "(respectively providers). Reads the pipeline's own manifests from "
            "the generated trees -- generates nothing and stores nothing."
        ),
    )
    parser.add_argument("--debug", action="store_true", help="Enable DEBUG logging")
    parser.add_argument(
        "--generated-root",
        type=Path,
        default=DEFAULT_GENERATED_ROOT,
        help=(
            "The generate.ps1 output base holding <language>/<runtime>/<provider>/"
            f"<example> trees (default: {DEFAULT_GENERATED_ROOT})"
        ),
    )
    parser.add_argument(
        "--self-test",
        action="store_true",
        help="Run only the non-vacuity self-test and skip the real comparison",
    )
    parser.add_argument(
        "--census",
        action="store_true",
        help=(
            "Print every (language, domain) the generated corpus exercises "
            "nowhere, with its reviewed record status, and exit -- the "
            "measurement corpus-vacuity-records.json is authored against"
        ),
    )
    return parser.parse_args(argv)


def print_corpus_vacuity_census(generated_root: Path) -> int:
    """Report the corpus-vacuity census next to the reviewed records.

    Args:
        generated_root: The ``generate.ps1`` output base to read.

    Returns:
        Exit code: 0 -- this is a measurement, not a gate; the gate's own
        verdict on the same data is `check_corpus_vacuity_records`.

    Raises:
        IncompleteCorpusError: When the corpus is incomplete, since a census
            over a partial corpus would misreport vacuity (`main` maps it to
            exit 2).
    """
    trees = load_complete_corpus(generated_root)
    records = load_corpus_vacuity_records() if CORPUS_VACUITY_RECORDS_PATH.exists() else []
    by_pair = {(record.language, record.domain): record for record in records}
    pairs = corpus_vacuous_pairs(corpus_footprint(trees))
    patterns_by_language: dict[str, DomainDeclarations] = {}
    for language, domain in pairs:
        record = by_pair.get((language, domain))
        if language not in patterns_by_language:
            patterns_by_language[language] = language_domain_declarations(language)
        declaration = patterns_by_language[language][domain]
        logger.info(
            "corpus_vacuous language=%s domain=%s pattern=%s status=%s",
            language, domain, declaration.structural_pattern,
            record.status if record else "UNRECORDED",
        )
    for language, domain in sorted(set(by_pair) - set(pairs)):
        logger.info("record_without_census language=%s domain=%s", language, domain)
    logger.info("corpus_vacuity_census_total pairs=%d records=%d", len(pairs), len(records))
    return EXIT_OK


def main(argv: list[str] | None = None) -> int:
    """Entry point.

    Returns:
        Process exit code: 0 = gate passed (or a successful `--self-test`),
        1 = an un-excused role drift was found on the language or provider
        axis, 2 = self-test failure, an
        incomplete generated corpus, zero comparable groups, a malformed
        config file, or an underivable domain declaration.
    """
    args = _parse_args(argv if argv is not None else sys.argv[1:])
    logging.basicConfig(
        level=logging.DEBUG if args.debug else logging.INFO,
        format="%(levelname)s: %(message)s",
    )

    problems = run_self_test()
    if problems:
        logger.error("NON-VACUITY SELF-TEST FAILED -- aborting before any real comparison:")
        for problem in problems:
            logger.error("  %s", problem)
        return EXIT_USAGE
    logger.info("non-vacuity self-test: PASS")

    if args.self_test:
        return EXIT_OK

    try:
        if args.census:
            return print_corpus_vacuity_census(args.generated_root)
        return check_artifact_role_parity(args.generated_root)
    except (ValueError, DerivationError) as exc:
        logger.error("%s", exc)
        return EXIT_USAGE


if __name__ == "__main__":
    sys.exit(main())
