"""add index.

Revision ID: 0005_add_index
Revises: 0004_add_index

Auto-generated by datrix-codegen-python. Do not edit manually.
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0005_add_index"
down_revision = "0004_add_index"
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Apply incremental schema changes."""
    op.create_index("ix_order_items_order_id", "order_items", ["order_id"], unique=False)


def downgrade() -> None:
    """Reverse incremental schema changes."""
    op.drop_index("ix_order_items_order_id", table_name="order_items")
