package library_book_service.nosql.docdb;

import com.mongodb.client.MongoDatabase;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.stereotype.Component;

/**
 * Session/handle accessor for this NoSQL block's mongodb connection.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Component
public class DocdbNosqlSession {

  private final MongoDatabase database;

  public DocdbNosqlSession(@Qualifier("docdbMongoDatabase") MongoDatabase database) {
    this.database = database;
  }

  public MongoDatabase getDatabase() {
    return database;
  }
}
