// Category.cs -- generated POCO entity model.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using System.Collections.Generic;

namespace BookService.Models.BookDb;

public class Category : BaseEntity
{
    public string Name { get; set; } = "";
    public string? Description { get; set; }
    public ICollection<Book> Books { get; set; } = new List<Book>();
}
