package library_member_service.member_db;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import javax.sql.DataSource;
import library_member_service.config.RemoteConfig;
import library_member_service.security.SecretsResolver;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

/**
 * HikariCP {@code DataSource} configuration for the 'memberDb' RDBMS block (postgres). Every RDBMS
 * block gets its own explicitly-named bean -- no {@code @Primary} guess across multi-block
 * services.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Configuration
public class MemberDbDataSourceConfig {

  @Bean(name = "member_dbDataSource")
  public DataSource member_dbDataSource(
      RemoteConfig remoteConfig, SecretsResolver secretsResolver) {
    String host = remoteConfig.getMemberDbHost();
    int port = remoteConfig.getMemberDbPort();
    String database = remoteConfig.getMemberDbDatabase();
    String username = remoteConfig.getMemberDbUser();

    String jdbcUrl = "jdbc:postgresql://" + host + ":" + port + "/" + database;

    HikariConfig hikariConfig = new HikariConfig();
    hikariConfig.setJdbcUrl(jdbcUrl);
    hikariConfig.setDriverClassName("org.postgresql.Driver");
    hikariConfig.setUsername(username);
    hikariConfig.setPassword(secretsResolver.getSecret("member_db_password"));
    hikariConfig.setMaximumPoolSize(20);

    return new HikariDataSource(hikariConfig);
  }
}
