package library_member_service.api;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.UUID;
import library_member_service.dto.member_db.MemberCreateRequest;
import library_member_service.dto.member_db.MemberUpdateRequest;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.WebApplicationContext;

/**
 * Generated HTTP CRUD round-trip test for Member -- real requests via {@link MockMvc} against the
 * real Spring context and DB.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
@Rollback
class MemberRoutesTest {

  @Autowired private WebApplicationContext webApplicationContext;

  @Autowired private ObjectMapper objectMapper;

  private MockMvc mockMvc;

  @BeforeEach
  void setUpMockMvc() {
    this.mockMvc = MockMvcBuilders.webAppContextSetup(this.webApplicationContext).build();
  }

  @Test
  void crudLifecycleThroughHttp() throws Exception {
    MemberCreateRequest createBody =
        new MemberCreateRequest("test_value", "user@example.com", "test_value");
    MvcResult createResult =
        this.mockMvc
            .perform(
                post("/api/v1/members/members")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content(this.objectMapper.writeValueAsString(createBody)))
            .andExpect(status().isCreated())
            .andReturn();
    JsonNode created = this.objectMapper.readTree(createResult.getResponse().getContentAsString());
    UUID id = UUID.fromString(created.get("id").asText());

    this.mockMvc.perform(get("/api/v1/members/members/" + id)).andExpect(status().isOk());

    this.mockMvc.perform(get("/api/v1/members/members")).andExpect(status().isOk());

    MemberUpdateRequest updateBody =
        new MemberUpdateRequest("alt_value", "alt@example.com", "alt_value");
    this.mockMvc
        .perform(
            put("/api/v1/members/members/" + id)
                .contentType(MediaType.APPLICATION_JSON)
                .content(this.objectMapper.writeValueAsString(updateBody)))
        .andExpect(status().isOk());

    this.mockMvc.perform(delete("/api/v1/members/members/" + id)).andExpect(status().isNoContent());

    this.mockMvc.perform(get("/api/v1/members/members/" + id)).andExpect(status().isNotFound());
  }
}
