/**
 * PubSub producer service for kafka.
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */
import { Injectable, Inject } from '@nestjs/common';
import { ClientKafka } from '@nestjs/microservices';

@Injectable()
export class PubsubProducerService {
  constructor(@Inject('PUBSUB_SERVICE') private readonly client: ClientKafka) {}

}
