/**
 * Event payload schemas.
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */

export interface OrderPlacedPayload {
  orderId: string;
  amount: number;
}

export interface OrderCancelledPayload {
  orderId: string;
}

