// BookConfiguration.cs -- generated EF Core fluent configuration.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
// Explicit fluent column config only -- no data annotations, no runtime
// schema/model-diffing calls, no engine/provider selection. Schema DDL
// is owned exclusively by the migration adapter.
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace BookService.Data.Configurations.BookDb;

public class BookConfiguration : IEntityTypeConfiguration<global::BookService.Models.BookDb.Book>
{
    public void Configure(EntityTypeBuilder<global::BookService.Models.BookDb.Book> builder)
    {
        builder.ToTable(
            "books",
            t =>
            {
                t.HasCheckConstraint("ck_books_title_max_length", "length(title) <= 200");
                t.HasCheckConstraint("ck_books_isbn_min_length", "length(isbn) >= 10");
                t.HasCheckConstraint("ck_books_isbn_max_length", "length(isbn) <= 13");
                t.HasCheckConstraint("ck_books_author_max_length", "length(author) <= 100");
                t.HasCheckConstraint(
                    "ck_books_catalog_number_max_length",
                    "length(catalog_number) <= 50"
                );
            }
        );

        builder.HasKey(e => e.Id);

        builder.Property(e => e.Id).HasColumnType("uuid").IsRequired().ValueGeneratedOnAdd();

        builder
            .Property(e => e.CreatedAt)
            .HasColumnType("timestamptz")
            .IsRequired()
            .ValueGeneratedOnAdd();

        builder
            .Property(e => e.UpdatedAt)
            .HasColumnType("timestamptz")
            .IsRequired()
            .ValueGeneratedOnAddOrUpdate();

        builder.Property(e => e.Title).HasColumnType("varchar(200)").IsRequired();

        builder.Property(e => e.Isbn).HasColumnType("varchar(13)").IsRequired();

        builder.Property(e => e.Author).HasColumnType("varchar(100)").IsRequired();

        builder.Property(e => e.PublicationYear).HasColumnType("integer").IsRequired();

        builder.Property(e => e.Status).HasColumnType("book_status").IsRequired();

        builder.Property(e => e.Format).HasColumnType("book_format").IsRequired();

        builder.Property(e => e.CatalogNumber).HasColumnType("varchar(50)");

        builder.Property(e => e.Keywords).HasColumnType("jsonb").IsRequired();

        builder.Property(e => e.Rating).HasColumnType("numeric(3, 2)").IsRequired();

        builder.HasIndex(e => e.CategoryId).HasDatabaseName("ix_books_category_id");

        builder
            .HasOne(e => e.Category)
            .WithMany()
            .HasForeignKey(e => e.CategoryId)
            .OnDelete(DeleteBehavior.Restrict);
    }
}
