"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "book_format" AS ENUM (\'hardcover\', \'paperback\', \'e_book\', \'audiobook\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "book_status" AS ENUM (\'available\', \'checked_out\', \'reserved\', \'maintenance\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "user_role" AS ENUM (\'member\', \'librarian\', \'admin\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "categories",
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(100),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "description",
            sa.String(500),
            nullable=True,
        ),
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(255),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "password_hash",
            sa.String(255),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum('member', 'librarian', 'admin', name='user_role', native_enum=True, _create_events=False),
            nullable=False,
        ),
    )
    op.create_table(
        "books",
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            "isbn",
            sa.String(13),
            nullable=False,
        ),
        sa.Column(
            "author",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "publication_year",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum('available', 'checked_out', 'reserved', 'maintenance', name='book_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "format",
            sa.Enum('hardcover', 'paperback', 'e_book', 'audiobook', name='book_format', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "catalog_number",
            sa.String(50),
            nullable=True,
        ),
        sa.Column(
            "keywords",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "rating",
            sa.Numeric(precision=3, scale=2),
            nullable=False,
        ),
        sa.Column(
            "category_id",
            sa.Uuid,
            nullable=False,
        ),
    )


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_table("books")
    op.drop_table("users")
    op.drop_table("categories")
