/**
 * Serverless job handler: DailyOrderReport.
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */

export async function daily_order_report(): Promise<void> {
  console.info('daily_order_report_running');
}
