package library_book_service.model.book_db;

import jakarta.persistence.CheckConstraint;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.OneToMany;
import jakarta.persistence.Table;
import java.util.ArrayList;
import java.util.List;

/**
 * Tag JPA entity.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Entity
@Table(
    name = "tags",
    indexes = {},
    uniqueConstraints = {},
    check = {
      @CheckConstraint(name = "ck_tags_name_max_length", constraint = "length(name) <= 50"),
      @CheckConstraint(
          name = "ck_tags_description_max_length",
          constraint = "length(description) <= 200")
    })
public class Tag extends BaseEntity {

  @Column(name = "name", columnDefinition = "varchar(50)", nullable = false, unique = true)
  private String name;

  @Column(name = "description", columnDefinition = "varchar(200)", nullable = true)
  private String description;

  @OneToMany(mappedBy = "tag", fetch = FetchType.LAZY)
  private List<BookTag> bookTags = new ArrayList<>();

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public List<BookTag> getBookTags() {
    return this.bookTags;
  }

  public void setBookTags(List<BookTag> bookTags) {
    this.bookTags = bookTags;
  }

  /**
   * Build a new {@link Tag} from a DSL object-literal map, setting only the keys present in {@code
   * data} (a key absent from {@code data} leaves the corresponding field at its normal Java default
   * -- {@code null} unless the field declares its own initializer above). Keys are the AS-AUTHORED
   * DSL field name (Java's own object-literal emission, {@code _datrixOrderedMap(...)}, preserves
   * author-declared spelling -- no case conversion), which for a camelCase-authored DSL field is
   * identical to this entity's own camelCase Java field name.
   *
   * <p>Backs {@code db.Tag.create({...})} lowering (`transpiler/
   * _entity_query_dispatch.py::transpile_entity_create`) -- entities have no `Map`-consuming
   * constructor, so the transpiled object literal is fed through this static factory instead of
   * `new Tag(...)`.
   */
  public static Tag fromMap(java.util.Map<String, Object> data) {
    Tag result = new Tag();
    if (data.containsKey("name")) {
      Object __v = data.get("name");
      result.setName((String) __v);
    }
    if (data.containsKey("description")) {
      Object __v = data.get("description");
      result.setDescription((String) __v);
    }
    return result;
  }
}
