// BookTagDtoTests.cs -- generated xUnit.v3 DataAnnotations validation tests.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using System.ComponentModel.DataAnnotations;
using BookService.Dtos.BookDb;
using BookService.Tests.Factories.BookDb;
using Xunit;

namespace BookService.Tests.DtoTests.BookDb;

public sealed class BookTagDtoTests
{
    [Fact]
    public void CreateRequest_FromFactoryValues_PassesValidation()
    {
        var entity = BookTagFactory.Create();
        var request = new CreateBookTagRequest { BookId = entity.BookId, TagId = entity.TagId };

        var context = new ValidationContext(request);
        var results = new List<ValidationResult>();
        var isValid = Validator.TryValidateObject(
            request,
            context,
            results,
            validateAllProperties: true
        );

        Assert.True(isValid, string.Join("; ", results.Select(r => r.ErrorMessage)));
    }

    [Fact]
    public void UpdateRequest_FromFactoryValues_PassesValidation()
    {
        var entity = BookTagFactory.Create();
        var request = new UpdateBookTagRequest { BookId = entity.BookId, TagId = entity.TagId };

        var context = new ValidationContext(request);
        var results = new List<ValidationResult>();
        var isValid = Validator.TryValidateObject(
            request,
            context,
            results,
            validateAllProperties: true
        );

        Assert.True(isValid, string.Join("; ", results.Select(r => r.ErrorMessage)));
    }
}
