// UserDtoTests.cs -- generated xUnit.v3 DataAnnotations validation tests.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using System.ComponentModel.DataAnnotations;
using BookService.Dtos.BookDb;
using BookService.Tests.Factories.BookDb;
using Xunit;

namespace BookService.Tests.DtoTests.BookDb;

public sealed class UserDtoTests
{
    [Fact]
    public void CreateRequest_FromFactoryValues_PassesValidation()
    {
        var entity = UserFactory.Create();
        var request = new CreateUserRequest
        {
            Email = entity.Email,
            PasswordHash = entity.PasswordHash,
            Role = entity.Role,
        };

        var context = new ValidationContext(request);
        var results = new List<ValidationResult>();
        var isValid = Validator.TryValidateObject(
            request,
            context,
            results,
            validateAllProperties: true
        );

        Assert.True(isValid, string.Join("; ", results.Select(r => r.ErrorMessage)));
    }

    [Fact]
    public void UpdateRequest_FromFactoryValues_PassesValidation()
    {
        var entity = UserFactory.Create();
        var request = new UpdateUserRequest
        {
            Email = entity.Email,
            PasswordHash = entity.PasswordHash,
            Role = entity.Role,
        };

        var context = new ValidationContext(request);
        var results = new List<ValidationResult>();
        var isValid = Validator.TryValidateObject(
            request,
            context,
            results,
            validateAllProperties: true
        );

        Assert.True(isValid, string.Join("; ", results.Select(r => r.ErrorMessage)));
    }
}
