// BookComputedTests.cs -- generated xUnit.v3 computed-field getter tests.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using BookService.Enums;
using BookService.Models.BookDb;
using BookService.Tests.Factories.BookDb;
using Xunit;

namespace BookService.Tests.ComputedTests.BookDb;

public sealed class BookComputedTests
{
    [Fact]
    public void IsAvailable_TrueOnlyForAvailable()
    {
        var value1 = new Book { Status = BookStatus.Available };
        Assert.True(value1.IsAvailable);
        var value2 = new Book { Status = BookStatus.CheckedOut };
        Assert.False(value2.IsAvailable);
        var value3 = new Book { Status = BookStatus.Reserved };
        Assert.False(value3.IsAvailable);
        var value4 = new Book { Status = BookStatus.Maintenance };
        Assert.False(value4.IsAvailable);
    }

    [Fact]
    public void DisplayTitle_FormatsCorrectly()
    {
        var instance = new Book { Title = "test_value", PublicationYear = 1 };

        Assert.Equal("test_value (1)", instance.DisplayTitle);
    }

    [Fact]
    public void IsOldBook_ComparesAgainstThreshold()
    {
        var below = new Book { PublicationYear = 1999 };
        Assert.True(below.IsOldBook);
        var at = new Book { PublicationYear = 2000 };
        Assert.False(at.IsOldBook);
        var above = new Book { PublicationYear = 2001 };
        Assert.False(above.IsOldBook);
    }

    [Fact]
    public void TitleLower_ReturnsTypeCorrectValue()
    {
        var instance = BookFactory.Create();
        var result = instance.TitleLower;

        Assert.IsAssignableFrom<string>(result);
        Assert.Equal(result, instance.TitleLower);
    }

    [Fact]
    public void TitleLength_ReturnsTypeCorrectValue()
    {
        var instance = BookFactory.Create();
        var result = instance.TitleLength;

        Assert.IsAssignableFrom<int>(result);
        Assert.Equal(result, instance.TitleLength);
    }

    [Fact]
    public void TitleWords_ReturnsTypeCorrectValue()
    {
        var instance = BookFactory.Create();
        var result = instance.TitleWords;

        Assert.IsAssignableFrom<List<string>>(result);
        Assert.Equal(result, instance.TitleWords);
    }

    [Fact]
    public void KeywordCount_ReturnsTypeCorrectValue()
    {
        var instance = BookFactory.Create();
        var result = instance.KeywordCount;

        Assert.IsAssignableFrom<int>(result);
        Assert.Equal(result, instance.KeywordCount);
    }

    [Fact]
    public void KeywordsJoined_ReturnsTypeCorrectValue()
    {
        var instance = BookFactory.Create();
        var result = instance.KeywordsJoined;

        Assert.IsAssignableFrom<string>(result);
        Assert.Equal(result, instance.KeywordsJoined);
    }

    [Fact]
    public void RatingRounded_ReturnsTypeCorrectValue()
    {
        var instance = BookFactory.Create();
        var result = instance.RatingRounded;

        Assert.IsAssignableFrom<decimal>(result);
        Assert.Equal(result, instance.RatingRounded);
    }
}
