// <auto-generated>
// Generated by datrix-codegen-dotnet. Do not edit by hand.
// </auto-generated>
#nullable enable

using Quartz;
using BookService.Data;
using BookService.Enums;
using BookService.Messaging.Mq;
using BookService.Models.BookDb;
using Microsoft.EntityFrameworkCore;

namespace BookService.Jobs;

public sealed class CheckOverdueBooksJob : IJob
{
    private readonly BookServiceDbContext bookServiceDbContext;
    private readonly MqProducer mqProducer;

    public CheckOverdueBooksJob(BookServiceDbContext bookServiceDbContext, MqProducer mqProducer)
    {
        this.bookServiceDbContext = bookServiceDbContext;
        this.mqProducer = mqProducer;
    }

    public async Task Execute(IJobExecutionContext context)
    {
        // Quartz provides no public constructor for IJobExecutionContext, so
        // the one-shot `job:{name}`/`serverless:job:{name}` dispatch (Program.cs's
        // RunOneShotJobAsync) never constructs one -- it calls RunAsync()
        // directly instead. Execute() (the Quartz-hosted scheduled path)
        // simply delegates to the SAME work method.
        _ = context;
        await RunAsync();
    }

    public async Task RunAsync()
    {
            List<Book> checkedOut = await bookServiceDbContext.Books.Where(x => x.Status == BookStatus.CheckedOut).ToListAsync();
            int processed = 0;
            foreach (var book in checkedOut) {
                Console.WriteLine($"Checking overdue status for book {book.Id}");
                processed = (processed + 1);
            }
            await mqProducer.PublishOverdueBooksProcessedAsync(new OverdueBooksProcessedPayload(Count: processed)).ConfigureAwait(false);
    }
}
