test:
  type: consul
  host: localhost
  port: 8500
  datacenter: dc1

development:
  type: consul
  host: localhost
  port: 8500
  datacenter: dc1

production:
  type: kubernetes
  namespace: default
  labelSelector: app=food-delivery
