package library_book_service.pubsub.mq;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.UUID;
import library_book_service.enums.BookStatus;

/**
 * Payload schema for the BookStatusChanged event.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record BookStatusChanged(
    @JsonProperty("bookId") UUID bookId,
    @JsonProperty("oldStatus") BookStatus oldStatus,
    @JsonProperty("newStatus") BookStatus newStatus) {}
