package library_book_service.pubsub.mq;

import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;
import library_book_service.enums.BookStatus;
import library_book_service.errors.ContractViolationError;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * Event contract validation functions, auto-generated from {@code ensure} clauses in event
 * declarations. Each function validates preconditions before publication.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public final class MqPubsubContracts {

  private static final Logger logger = LoggerFactory.getLogger(MqPubsubContracts.class);

  private MqPubsubContracts() {}

  /** Validate contracts for the BookAdded event. */
  public static void validateBookAdded(UUID bookId, String title) {
    if (!((title.length() > 0))) {
      Map<String, Object> actual = new LinkedHashMap<>();
      actual.put("title", title);
      logger.error(
          "contract_violation event={} clause={} actual={}", "BookAdded", "ensure_0", actual);
      throw new ContractViolationError("BookAdded", "ensure_0", actual);
    }
  }

  /** Validate contracts for the BookStatusChanged event. */
  public static void validateBookStatusChanged(
      UUID bookId, BookStatus oldStatus, BookStatus newStatus) {
    if (!((!Objects.equals(oldStatus, newStatus)))) {
      Map<String, Object> actual = new LinkedHashMap<>();
      actual.put("newStatus", newStatus);
      actual.put("oldStatus", oldStatus);
      logger.error(
          "contract_violation event={} clause={} actual={}",
          "BookStatusChanged",
          "ensure_0",
          actual);
      throw new ContractViolationError("BookStatusChanged", "ensure_0", actual);
    }
  }

  /** Validate contracts for the OverdueBooksProcessed event. */
  public static void validateOverdueBooksProcessed(Integer count) {
    if (!((count >= 0))) {
      Map<String, Object> actual = new LinkedHashMap<>();
      actual.put("count", count);
      logger.error(
          "contract_violation event={} clause={} actual={}",
          "OverdueBooksProcessed",
          "ensure_0",
          actual);
      throw new ContractViolationError("OverdueBooksProcessed", "ensure_0", actual);
    }
  }
}
