package library_book_service.nosql.docdb;

import com.mongodb.client.MongoCollection;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import org.bson.Document;
import org.springframework.stereotype.Component;

/**
 * Typed raw-document access to the reading-activity MongoDB collection.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Component
public class ReadingActivityCollectionAccess {

  public static final String COLLECTION_NAME = "reading-activity";

  private final MongoCollection<Document> collection;

  public ReadingActivityCollectionAccess(DocdbNosqlSession session) {
    this.collection = session.getDatabase().getCollection(COLLECTION_NAME);
  }

  public Optional<Document> findById(String id) {
    return Optional.ofNullable(collection.find(new Document("_id", id)).first());
  }

  public String insert(Map<String, Object> document) {
    Document doc = new Document(document);
    collection.insertOne(doc);
    return String.valueOf(doc.get("_id"));
  }

  public List<Document> findAll() {
    List<Document> results = new ArrayList<>();
    collection.find().forEach(results::add);
    return results;
  }

  public List<Document> findByBookId(Object bookId) {
    List<Document> results = new ArrayList<>();
    collection.find(new Document("bookId", bookId)).forEach(results::add);
    return results;
  }

  public List<Document> findByMemberId(Object memberId) {
    List<Document> results = new ArrayList<>();
    collection.find(new Document("memberId", memberId)).forEach(results::add);
    return results;
  }
}
