// LoanConfiguration.cs -- generated EF Core fluent configuration.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
// Explicit fluent column config only -- no data annotations, no runtime
// schema/model-diffing calls, no engine/provider selection. Schema DDL
// is owned exclusively by the migration adapter.
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace LoanService.Data.Configurations.LoanDb;

public class LoanConfiguration : IEntityTypeConfiguration<global::LoanService.Models.LoanDb.Loan>
{
    public void Configure(EntityTypeBuilder<global::LoanService.Models.LoanDb.Loan> builder)
    {
        builder.ToTable("loans");

        builder.HasKey(e => e.Id);

        builder.Property(e => e.Id).HasColumnType("uuid").IsRequired().ValueGeneratedOnAdd();

        builder
            .Property(e => e.CreatedAt)
            .HasColumnType("timestamptz")
            .IsRequired()
            .ValueGeneratedOnAdd();

        builder
            .Property(e => e.UpdatedAt)
            .HasColumnType("timestamptz")
            .IsRequired()
            .ValueGeneratedOnAddOrUpdate();

        builder.Property(e => e.BookId).HasColumnType("uuid").IsRequired();

        builder.Property(e => e.MemberId).HasColumnType("uuid").IsRequired();

        builder.Property(e => e.Status).HasColumnType("loan_status").IsRequired();

        builder.Property(e => e.DueDate).HasColumnType("timestamptz").IsRequired();

        builder.Property(e => e.ReturnedAt).HasColumnType("timestamptz");

        builder.HasIndex(e => e.BookId).HasDatabaseName("ix_loans_book_id");

        builder.HasIndex(e => e.MemberId).HasDatabaseName("ix_loans_member_id");
    }
}
