package library_notification_service.model.notif_db;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import java.util.Set;
import java.util.UUID;
import library_notification_service.dto.notif_db.NotificationDeliveryLogCreateRequest;
import org.hibernate.validator.HibernateValidator;
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator;
import org.junit.jupiter.api.Test;

/**
 * Generated tests for NotificationDeliveryLog: field round-trip, update-assertion, relationship
 * navigation, and (when the entity's CreateRequest DTO carries at least one @NotNull field) Bean
 * Validation constraint-violation tests.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class NotificationDeliveryLogTest {

  @Test
  void fieldRoundTripAssignsAndReturnsSameValue() {
    NotificationDeliveryLog instance = NotificationDeliveryLogTestFactory.create();
    instance.setBookId(UUID.fromString("550e8400-e29b-41d4-a716-446655440000"));
    assertEquals(UUID.fromString("550e8400-e29b-41d4-a716-446655440000"), instance.getBookId());
    instance.setRecipientEmail("user@example.com");
    assertEquals("user@example.com", instance.getRecipientEmail());
    instance.setMessagePreview("test_value");
    assertEquals("test_value", instance.getMessagePreview());
  }

  @Test
  void fieldUpdateAssignsDistinctValue() {
    NotificationDeliveryLog instance = NotificationDeliveryLogTestFactory.create();
    instance.setBookId(UUID.fromString("550e8400-e29b-41d4-a716-446655440000"));
    instance.setRecipientEmail("user@example.com");
    instance.setMessagePreview("test_value");
    instance.setBookId(UUID.fromString("650e8400-e29b-41d4-a716-446655440001"));
    assertEquals(UUID.fromString("650e8400-e29b-41d4-a716-446655440001"), instance.getBookId());
    instance.setRecipientEmail("alt@example.com");
    assertEquals("alt@example.com", instance.getRecipientEmail());
    instance.setMessagePreview("alt_value");
    assertEquals("alt_value", instance.getMessagePreview());
  }

  private static Validator buildValidator() {
    return Validation.byProvider(HibernateValidator.class)
        .configure()
        .messageInterpolator(new ParameterMessageInterpolator())
        .buildValidatorFactory()
        .getValidator();
  }

  @Test
  void requiredFieldLeftNullFailsBeanValidation() {
    Validator validator = buildValidator();
    NotificationDeliveryLogCreateRequest invalid =
        new NotificationDeliveryLogCreateRequest(null, "user@example.com", "test_value");
    Set<ConstraintViolation<NotificationDeliveryLogCreateRequest>> violations =
        validator.validate(invalid);
    assertFalse(violations.isEmpty(), "expected a violation for a null required field");
  }

  @Test
  void allRequiredFieldsPresentPassesBeanValidation() {
    Validator validator = buildValidator();
    NotificationDeliveryLogCreateRequest valid =
        new NotificationDeliveryLogCreateRequest(
            UUID.fromString("550e8400-e29b-41d4-a716-446655440000"),
            "user@example.com",
            "test_value");
    Set<ConstraintViolation<NotificationDeliveryLogCreateRequest>> violations =
        validator.validate(valid);
    assertTrue(violations.isEmpty(), "expected no violations, got: " + violations);
  }
}
