package library_member_service.dto.member_db;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.Size;
import library_member_service.enums.MembershipType;

/**
 * Member update-request DTO. Every field is optional-to-provide (PATCH semantics) -- no field
 * carries a not-null requirement.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record MemberUpdateRequest(
    @Size(max = 100) String firstName,
    @Size(max = 100) String lastName,
    @Email String email,
    @Size(max = 20) String membershipNumber,
    MembershipType membershipType) {}
