// <auto-generated>
// Generated by datrix-codegen-dotnet. Do not edit by hand.
// </auto-generated>
#nullable enable

namespace MemberService.Config.RemoteConfig;

/// <summary>
/// Backend contract for the runtime config-store client: bulk per-profile
/// read plus single-key targeted read. Every value returned is RAW and
/// untyped -- <c>RemoteConfigClient</c> validates and coerces
/// against the declared key type; a backend never coerces itself (matches
/// python's <c>ConfigBackend</c> Protocol exactly).
/// </summary>
public interface IRemoteConfigBackend
{
    /// <summary>Return the remote scalar values for <paramref name="profile"/> keyed by config key name.</summary>
    Task<Dictionary<string, object?>> FetchProfileAsync(string profile);

    /// <summary>Fetch exactly one config key for a targeted per-key TTL re-read.</summary>
    Task<object?> FetchKeyAsync(string profile, string key);
}

/// <summary>
/// <see cref="Microsoft.Extensions.Options.IOptions{TOptions}"/>-bound
/// settings for the runtime config-store backend -- ONE shared options class
/// for every engine: never duplicate a separate options class per backend.
/// This SAME class is extended with the AWS AppConfig/Azure App
/// Configuration backends' own fields
/// (<see cref="Endpoint"/>, <see cref="AppConfigMinimumPollSeconds"/>) rather
/// than inventing a second options type.
/// </summary>
public sealed class RemoteConfigOptions
{
    public const string SectionName = "RemoteConfig";

    /// <summary>File engine only: baked path to the mounted JSON config file.</summary>
    public string? FilePath { get; init; }

    /// <summary>
    /// Consul engine: KV path application-name segment used for every
    /// profile except "connections".
    /// </summary>
    public required string ApplicationName { get; init; }

    /// <summary>
    /// Consul engine: KV path application-name segment used for the
    /// "connections" profile only. Falls back to <see cref="ApplicationName"/>
    /// when unset.
    /// </summary>
    public string? ConnectionsApplicationName { get; init; }

    /// <summary>Consul engine: KV path environment segment.</summary>
    public required string Environment { get; init; }

    /// <summary>
    /// Azure App Configuration engine only: the store's endpoint URL (e.g.
    /// <c>https://my-store.azconfig.io</c>), matching
    /// <c>ConfigStoreConfig.endpoint</c>.
    /// </summary>
    public string? Endpoint { get; init; }

    /// <summary>
    /// AWS AppConfig engine only: <c>RequiredMinimumPollIntervalInSeconds</c>
    /// for <c>StartConfigurationSession</c>. AWS enforces a 15-second floor.
    /// </summary>
    public int AppConfigMinimumPollSeconds { get; init; } = 15;
}
