package library_book_service.enums;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

/**
 * Generated tests for UserRole: member count, declaration order, and (when applicable)
 * explicit-value round-trip via the code accessor.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class UserRoleTest {

  @Test
  void valuesContainsExactlyDeclaredMembersInOrder() {
    UserRole[] values = UserRole.values();
    assertEquals(3, values.length);
    assertEquals(UserRole.MEMBER, values[0]);
    assertEquals(UserRole.LIBRARIAN, values[1]);
    assertEquals(UserRole.ADMIN, values[2]);
  }

  @Test
  void valueOfMember0ReturnsDeclaredMember() {
    assertEquals(UserRole.MEMBER, UserRole.valueOf("MEMBER"));
  }

  @Test
  void valueOfMember1ReturnsDeclaredMember() {
    assertEquals(UserRole.LIBRARIAN, UserRole.valueOf("LIBRARIAN"));
  }

  @Test
  void valueOfMember2ReturnsDeclaredMember() {
    assertEquals(UserRole.ADMIN, UserRole.valueOf("ADMIN"));
  }
}
