package library_loan_service.repositories.loan_db;

import java.util.List;
import java.util.UUID;
import library_loan_service.model.loan_db.Loan;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

/**
 * Loan Spring Data JPA repository.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public interface LoanRepository extends JpaRepository<Loan, UUID>, JpaSpecificationExecutor<Loan> {

  List<Loan> findByBookId(UUID bookId);

  List<Loan> findByMemberId(UUID memberId);
}
