openapi: 3.1.0
info:
  title: social.PostService API
  version: 1.0.0
paths:
  /api/v1/posts/posts:
    get:
      operationId: list_posts
      summary: list_posts
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
    post:
      operationId: create_post
      summary: create_post
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
  /api/v1/posts/posts/:id:
    get:
      operationId: get_post
      summary: get_post
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
    put:
      operationId: update_post
      summary: update_post
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
    delete:
      operationId: delete_post
      summary: delete_post
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        authorId:
          type: string
          format: uuid
        content:
          type: string
        likeCount:
          $ref: '#/components/schemas/Integer'
      required:
      - id
      - createdAt
      - updatedAt
      - authorId
      - content
      - likeCount
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
