package library_book_service.services.book_db;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import library_book_service.model.book_db.Category;
import library_book_service.repositories.book_db.CategoryRepository;
import library_book_service.services.ServiceBase;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Category service -- request-scoped unit-of-work wrapper over {@link CategoryRepository }.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Service
public class CategoryService extends ServiceBase {

  private final CategoryRepository categoryRepository;

  @PersistenceContext private EntityManager entityManager;

  public CategoryService(CategoryRepository categoryRepository) {
    this.categoryRepository = categoryRepository;
  }

  public Optional<Category> get(UUID id) {
    return this.categoryRepository.findById(id);
  }

  public List<Category> list() {
    return this.categoryRepository.findAll();
  }

  public Optional<Category> getByName(String name) {
    return this.categoryRepository.findByName(name);
  }

  @Transactional
  public Category create(Category entity) {
    return this.categoryRepository.save(entity);
  }

  @Transactional
  public Category update(Category entity) {
    return this.categoryRepository.save(entity);
  }

  @Transactional
  public void delete(UUID id) {
    if (((Number)
                this.entityManager
                    .createNativeQuery("SELECT COUNT(*) FROM books WHERE category_id = ?1")
                    .setParameter(1, id)
                    .getSingleResult())
            .longValue()
        > 0) {
      throw new IllegalStateException(
          "Cannot delete Category " + id + ": referenced by Book(s) via books");
    }
    this.categoryRepository.deleteById(id);
  }
}
