package library_book_service.spec;

import static library_book_service.support.MapSupport._datrixOrderedMap;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Objects;
import library_book_service.EventSpyRecorder;
import library_book_service.model.book_db.Book;
import library_book_service.model.book_db.Category;
import library_book_service.repositories.book_db.BookRepository;
import library_book_service.repositories.book_db.CategoryRepository;
import library_book_service.repositories.book_db.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated from this service's {@code test("...")} DSL blocks. Exercises the service through the
 * real Spring context -- {@code assert}/{@code throws} lower to JUnit 5 assertions, {@code
 * emitted(...)} asserts against the real, non-mocked {@link EventSpyRecorder}.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@SpringBootTest
@Import(BookServiceSpecTestSupport.class)
@ActiveProfiles("test")
@Transactional
@Rollback
class BookServiceSpecTest {

  @Autowired private CategoryRepository categoryRepository;

  @Autowired private UserRepository userRepository;

  @Autowired private BookRepository bookRepository;

  @Autowired private EventSpyRecorder eventSpy;

  @BeforeEach
  void resetEventSpy() {
    eventSpy.reset();
  }

  /** computed isAvailable is true for Available status */
  @Test
  @DisplayName("computed isAvailable is true for Available status")
  void computedIsavailableIsTrueForAvailableStatus() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatAvail")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Test Book",
                    "isbn",
                    "9780000000001",
                    "author",
                    "Test Author",
                    "publicationYear",
                    2020,
                    "categoryId",
                    cat.id())));
    bookRepository.saveAndFlush(book);
    assertTrue((Objects.equals(book.isAvailable(), true)));
  }

  /** computed displayTitle formats title and year */
  @Test
  @DisplayName("computed displayTitle formats title and year")
  void computedDisplaytitleFormatsTitleAndYear() {
    var cat =
        categoryRepository.saveAndFlush(Category.fromMap(_datrixOrderedMap("name", "SpecCatDisp")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Clean Code",
                    "isbn",
                    "9780000000002",
                    "author",
                    "Robert Martin",
                    "publicationYear",
                    2008,
                    "categoryId",
                    cat.id())));
    bookRepository.saveAndFlush(book);
    assertTrue((Objects.equals(book.displayTitle(), "Clean Code (2008)")));
  }

  /** validation rejects empty title */
  @Test
  @DisplayName("validation rejects empty title")
  void validationRejectsEmptyTitle() {
    var cat =
        categoryRepository.saveAndFlush(Category.fromMap(_datrixOrderedMap("name", "SpecCatValQ")));
    categoryRepository.saveAndFlush(cat);
    assertThrows(
        ValidationError.class,
        () -> {
          var __datrixThrowsResult =
              bookRepository.saveAndFlush(
                  Book.fromMap(
                      _datrixOrderedMap(
                          "title",
                          "",
                          "isbn",
                          "9780000000003",
                          "author",
                          "Test Author",
                          "publicationYear",
                          2020,
                          "categoryId",
                          cat.id())));
        });
  }

  /** validation rejects future publication year */
  @Test
  @DisplayName("validation rejects future publication year")
  void validationRejectsFuturePublicationYear() {
    var cat =
        categoryRepository.saveAndFlush(Category.fromMap(_datrixOrderedMap("name", "SpecCatFutQ")));
    categoryRepository.saveAndFlush(cat);
    assertThrows(
        ValidationError.class,
        () -> {
          var __datrixThrowsResult =
              bookRepository.saveAndFlush(
                  Book.fromMap(
                      _datrixOrderedMap(
                          "title",
                          "Future Book",
                          "isbn",
                          "9780000000004",
                          "author",
                          "Test Author",
                          "publicationYear",
                          2099,
                          "categoryId",
                          cat.id())));
        });
  }

  /** beforeCreate generates catalogNumber */
  @Test
  @DisplayName("beforeCreate generates catalogNumber")
  void beforecreateGeneratesCatalognumber() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatCatNo")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Catalog Test",
                    "isbn",
                    "9780000000005",
                    "author",
                    "Test Author",
                    "publicationYear",
                    2020,
                    "categoryId",
                    cat.id())));
    bookRepository.saveAndFlush(book);
    assertTrue((!Objects.equals(book.catalogNumber(), null)));
  }

  /** afterCreate dispatches IndexBook task */
  @Test
  @DisplayName("afterCreate dispatches IndexBook task")
  void aftercreateDispatchesIndexbookTask() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatQueue")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Domain-Driven Design",
                    "isbn",
                    "9780321125217",
                    "author",
                    "Eric Evans",
                    "publicationYear",
                    2003,
                    "categoryId",
                    cat.id())));
    bookRepository.saveAndFlush(book);
    assertTrue(dispatched(indexBook(book.id(), book.title(), book.author())));
  }

  /** afterCreate dispatches GenerateBookCover task */
  @Test
  @DisplayName("afterCreate dispatches GenerateBookCover task")
  void aftercreateDispatchesGeneratebookcoverTask() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatCover")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Clean Code",
                    "isbn",
                    "9780132350884",
                    "author",
                    "Robert Martin",
                    "publicationYear",
                    2008,
                    "categoryId",
                    cat.id())));
    bookRepository.saveAndFlush(book);
    assertTrue(dispatched(generateBookCover(book.id(), book.title())));
  }
}
