package library_book_service.observability;

import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Tag;
import java.util.List;
import java.util.concurrent.atomic.AtomicLong;
import org.springframework.stereotype.Component;

/**
 * Alert metrics for library_book_service.observability. One Micrometer meter per declared {@code
 * alert}.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Component
public class AlertMetrics {

  private final MeterRegistry registry;
  private final AtomicLong mqConsumerLagValue = new AtomicLong(0);

  public AlertMetrics(MeterRegistry registry) {
    this.registry = registry;
    registry.gauge(
        "mq_consumer_lag",
        List.of(Tag.of("service", "library_book_service")),
        this.mqConsumerLagValue);
  }

  /** Set the {@code mq_consumer_lag} gauge value. */
  public void setMqConsumerLag(long value) {
    mqConsumerLagValue.set(value);
  }
}
