package warehouse_warehouse_service.dto.warehouse_db;

import jakarta.validation.constraints.Size;
import org.locationtech.jts.geom.Geometry;

/**
 * DeliveryZone update-request DTO. Every field is optional-to-provide (PATCH semantics) -- no field
 * carries a not-null requirement.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record DeliveryZoneUpdateRequest(
    @Size(max = 200) String name,
    @Size(max = 50) String zoneCode,
    Geometry coverageArea,
    Double radiusNm) {}
