package warehouse_warehouse_service.dto.warehouse_db;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.OffsetDateTime;
import java.util.UUID;
import org.locationtech.jts.geom.Geometry;

/**
 * Warehouse response DTO. Hidden/sensitive fields are absent.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record WarehouseResponse(
    @NotNull UUID id,
    @NotNull OffsetDateTime createdAt,
    @NotNull OffsetDateTime updatedAt,
    @NotNull @Size(max = 200) String name,
    @NotNull @Size(max = 100) String code,
    @NotNull Geometry boundary,
    @NotNull Geometry centerPoint,
    @NotNull Integer capacitySquareMeters) {}
