"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "audit_action" AS ENUM (\'created\', \'updated\', \'deleted\', \'checked_out\', \'returned\', \'condition_changed\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "book_audit_logs",
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "book_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.Enum('created', 'updated', 'deleted', 'checked_out', 'returned', 'condition_changed', name='audit_action', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "performed_by",
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            "changes",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )
    op.create_table(
        "daily_book_stats",
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "report_date",
            sa.DateTime(timezone=True),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "total_checkouts",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "total_returns",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "new_books",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "active_members",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )
    op.create_index("ix_book_audit_logs_book_id_occurred_at", "book_audit_logs", ["book_id", "occurred_at"], unique=False)


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_index("ix_book_audit_logs_book_id_occurred_at", table_name="book_audit_logs")
    op.drop_table("daily_book_stats")
    op.drop_table("book_audit_logs")
