#!/usr/bin/env node
/**
 * Docker Deployment Test Runner.
 *
 * Manages full Docker Compose lifecycle: build → up → test → down.
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 *
 * Usage:
 *   node tests/deploy-test.js                    # Run deployment tests (minimal output)
 *   node tests/deploy-test.js --verbose          # Show detailed progress (INFO level logs)
 *   node tests/deploy-test.js --fresh-build      # Force fresh build (--no-cache, no layer cache)
 *   node tests/deploy-test.js --keep-running     # Keep containers running after tests
 *   node tests/deploy-test.js --debug            # Enable debug logging
 *   node tests/deploy-test.js --results-dir X    # Custom results directory
 *
 * Environment variables:
 *   DEPLOY_TEST_FRESH_BUILD=true                 # Same as --fresh-build flag
 */
'use strict';

const { execSync, spawn, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');
const http = require('http');

/**
 * One workspace ``pnpm install`` at ``.generated/typescript``; Jest runs via ``node …/jest/bin/jest.js``.
 */
const PNPM_CMD = 'pnpm';

const SERVICES = [
  {
    name: 'examples.IngestionService',
    dir: 'examples_ingestion_service',
    port: 8002  },
  {
    name: 'examples.OrderService',
    dir: 'examples_order_service',
    port: 8001,
    dbContainers: [{"env_var": "DB_DATABASE_URL_EXAMPLES_ORDER_SERVICE", "internal_port": 5432, "key": "examples-order-service-db-db"}]  },
];

const COMPOSE_PROJECT_NAME = 'examples_serverless_demo_system_test';
const DEFAULT_HEALTH_TIMEOUT_SECONDS = 120;

// ANSI color helpers
const GREEN = '\x1b[92m';
const CYAN = '\x1b[96m';
const YELLOW = '\x1b[93m';
const RED = '\x1b[91m';
const RESET = '\x1b[0m';

let logFilePath = null;
let verboseLogging = false;
let debugLogging = false;

function log(level, msg) {
  const timestamp = new Date().toISOString();
  const formattedMsg = `${timestamp} ${level} ${msg}`;

  // Console output based on log level and mode:
  // - ERROR/WARNING: always shown
  // - INFO: shown only in verbose or debug mode
  // - DEBUG: shown only in debug mode
  const shouldShowInConsole =
    level === 'ERROR' ||
    level === 'WARNING' ||
    (level === 'INFO' && (verboseLogging || debugLogging)) ||
    (level === 'DEBUG' && debugLogging);

  if (shouldShowInConsole) {
    console.log(formattedMsg);
  }

  // Always write to log file
  if (logFilePath) {
    fs.appendFileSync(logFilePath, formattedMsg + '\n', 'utf-8');
  }
}

function logInfo(msg) { log('INFO', msg); }
function logError(msg) { log('ERROR', msg); }
function logDebug(msg) { log('DEBUG', msg); }

function stripAnsi(str) {
  return str.replace(/\x1b\[[0-9;]*m/g, '');
}

/**
 * Find Docker Compose command (docker compose plugin vs standalone).
 */
function getDockerComposeCmd() {
  try {
    execSync('docker compose version', { stdio: 'ignore' });
    return ['docker', 'compose'];
  } catch {
    try {
      execSync('docker-compose version', { stdio: 'ignore' });
      return ['docker-compose'];
    } catch {
      throw new Error('Docker Compose not found. Install Docker Desktop or docker-compose.');
    }
  }
}

/**
 * Load optional test-config.json.
 */
function loadConfig() {
  const configPath = path.join(__dirname, 'test-config.json');
  if (!fs.existsSync(configPath)) return {};
  try {
    return JSON.parse(fs.readFileSync(configPath, 'utf-8'));
  } catch (err) {
    logError(`config_load_failed path=${configPath} error=${err.message}`);
    return {};
  }
}

/**
 * Wait for /health endpoint to return 200.
 */
function waitForHealth(baseUrl, timeoutSeconds) {
  const healthUrl = `${baseUrl}/health`;
  const deadline = Date.now() + timeoutSeconds * 1000;

  return new Promise((resolve) => {
    const check = () => {
      if (Date.now() >= deadline) {
        resolve(false);
        return;
      }

      const req = http.get(healthUrl, { timeout: 5000 }, (res) => {
        // Consume response body to free the socket
        res.resume();
        if (res.statusCode === 200) {
          resolve(true);
        } else {
          setTimeout(check, 2000);
        }
      });
      req.on('error', () => {
        setTimeout(check, 2000);
      });
      req.on('timeout', () => {
        req.destroy();
        setTimeout(check, 2000);
      });
    };
    check();
  });
}

/**
 * Check all containers for failed exit codes.
 *
 * Init containers should have exited with code 0.
 * Service containers should be running.
 * Returns true if all containers are healthy, false if any failures detected.
 */
function checkContainerExitCodes(compose, { cwd = null } = {}) {
  const psCmd = [...compose, 'ps', '-a', '--format', 'json'].join(' ');
  let psOutput;
  try {
    psOutput = execSync(psCmd, { cwd: cwd || undefined, encoding: 'utf-8', timeout: 30000 });
  } catch (err) {
    logError(`docker_compose_ps_failed error=${err.message}`);
    return false;
  }

  if (!psOutput || !psOutput.trim()) {
    logInfo('docker_compose_ps_no_containers');
    return true;
  }

  const containers = [];
  for (const line of psOutput.trim().split('\n')) {
    const trimmed = line.trim();
    if (!trimmed) continue;
    try {
      containers.push(JSON.parse(trimmed));
    } catch {
      logDebug(`docker_compose_ps_invalid_json line=${trimmed}`);
    }
  }

  let failed = false;
  for (const container of containers) {
    const name = container.Name || container.Names || 'unknown';
    const state = (container.State || '').toLowerCase();
    const exitCode = container.ExitCode ?? 0;

    if (state === 'exited' && exitCode !== 0) {
      logError(`container_failed name=${name} state=${state} exit_code=${exitCode}`);
      failed = true;
    } else if (state === 'running' || state === 'healthy') {
      logDebug(`container_healthy name=${name} state=${state}`);
    } else if (state === 'exited' && exitCode === 0) {
      logDebug(`container_completed name=${name}`);
    } else {
      logInfo(`container_unexpected_state name=${name} state=${state} exit_code=${exitCode}`);
    }
  }

  return !failed;
}

/**
 * Run Docker command, capturing output unless verbose.
 */
function runDockerCmd(cmd, { verbose = false, label = '', cwd = null } = {}) {
  const cmdStr = cmd.join(' ');
  if (verbose) {
    logInfo(`running_command cmd="${cmdStr}"`);
  }

  try {
    const result = execSync(cmdStr, {
      cwd: cwd || undefined,
      encoding: 'utf-8',
      stdio: verbose ? 'inherit' : 'pipe',
    });
    if (!verbose && logFilePath) {
      fs.appendFileSync(logFilePath, stripAnsi(result), 'utf-8');
    }
    return { success: true, output: result };
  } catch (err) {
    const output = err.stdout || err.stderr || '';
    if (label) {
      logError(`${label}_failed cmd="${cmdStr}"`);
      if (output && logFilePath) {
        fs.appendFileSync(logFilePath, stripAnsi(output), 'utf-8');
      }
    }
    return { success: false, output, code: err.status || 1 };
  }
}

/**
 * Save Docker container logs to results-dir/docker-logs/.
 */
function saveDockerLogs(compose, resultsDir, { cwd = null } = {}) {
  const dockerLogsDir = path.join(resultsDir, 'docker-logs');
  if (!fs.existsSync(dockerLogsDir)) {
    fs.mkdirSync(dockerLogsDir, { recursive: true });
  }

  const psCmd = [...compose, 'ps', '-a', '--format', '{{.Name}}'].join(' ');
  let containers = [];
  try {
    const result = execSync(psCmd, { cwd: cwd || undefined, encoding: 'utf-8', timeout: 30000 });
    containers = result.split('\n').map(s => s.trim()).filter(Boolean);
  } catch (err) {
    logError(`docker_compose_ps_failed error=${err.message}`);
    return;
  }

  for (const containerName of containers) {
    const safeName = containerName.replace(/[\/\\:*?"<>|]/g, '_');
    const logFile = path.join(dockerLogsDir, `${safeName}.log`);
    try {
      const logs = execSync(`docker logs ${containerName}`, {
        encoding: 'utf-8',
        timeout: 60000,
        stdio: 'pipe',
      });
      fs.writeFileSync(logFile, logs, 'utf-8');
      logInfo(`docker_log_saved container=${containerName} path=${logFile}`);
    } catch (err) {
      logError(`docker_log_timeout container=${containerName}`);
    }
  }
}

/**
 * Parse Jest test statistics from output (aligned with tests/unit-tests.js).
 */
function parseJestStats(output) {
  const result = {
    passed: 0,
    failed: 0,
    skipped: 0,
    errors: 0,
    suiteFailures: 0,
  };
  if (!output) return result;

  const suitesLine = output.match(/Test Suites:\s+(.+total)/);
  let suitesFailed = 0;
  if (suitesLine) {
    const suiteFailedMatch = suitesLine[1].match(/(\d+) failed/);
    if (suiteFailedMatch) {
      suitesFailed = parseInt(suiteFailedMatch[1], 10);
    }
  }
  result.suiteFailures = suitesFailed;

  const testsLine = output.match(/Tests:\s+(.+total)/);
  if (testsLine) {
    const tail = testsLine[1];
    const passedMatch = tail.match(/(\d+) passed/);
    const failedMatch = tail.match(/(\d+) failed/);
    const skippedMatch = tail.match(/(\d+) skipped/);
    const totalMatch = tail.match(/(\d+)\s*total/);
    if (passedMatch) result.passed = parseInt(passedMatch[1], 10);
    if (failedMatch) result.failed = parseInt(failedMatch[1], 10);
    if (skippedMatch) result.skipped = parseInt(skippedMatch[1], 10);
    const total = totalMatch
      ? parseInt(totalMatch[1], 10)
      : result.passed + result.failed + result.skipped;
    if (total === 0 && suitesFailed > 0) {
      result.errors = suitesFailed;
    }
    return result;
  }

  if (suitesFailed > 0) {
    result.errors = suitesFailed;
  }
  return result;
}

function stripKnownLogNoise(text) {
  return text
    .split('\n')
    .filter(
      (line) => !line.includes('Local package.json exists, but node_modules missing'),
    )
    .join('\n');
}

function getPnpmVersion() {
  try {
    const pnpmCmd = PNPM_CMD;
    return execSync(`${pnpmCmd} --version`, { encoding: 'utf-8' }).trim();
  } catch (_) {
    return null;
  }
}

function resolveDatrixRepoSha() {
  const raw = process.env.DATRIX_REPO_SHA || process.env.DATRIX_CODEGEN_SHA;
  if (!raw) return null;
  const s = String(raw).trim();
  return s || null;
}

function writeDeployEnvironmentJson(resultsDir, projectPath) {
  const payload = {
    project: projectPath,
    generatedAt: new Date().toISOString(),
    nodeVersion: process.version,
    pnpmVersion: getPnpmVersion(),
    platform: process.platform,
    arch: process.arch,
    runner: 'tests/deploy-test.js',
    logNotes: [
      'docker-logs/ has container output captured before compose teardown.',
      'A trailing pnpm note about parent node_modules may appear after Jest; it is not necessarily a failure.',
      'Triage: read failures.json first; open jest-spec-results.json / jest-deploy-results.json for full stacks.',
    ],
  };
  const sha = resolveDatrixRepoSha();
  if (sha) {
    payload.datrixRepoSha = sha;
  }
  fs.writeFileSync(
    path.join(resultsDir, 'environment.json'),
    `${JSON.stringify(payload, null, 2)}\n`,
    'utf-8',
  );
}

function collectFailuresFromJestJson(jsonPath, serviceLabel) {
  if (!fs.existsSync(jsonPath)) return [];
  let data;
  try {
    data = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  } catch (_) {
    return [];
  }
  const out = [];
  for (const tr of data.testResults || []) {
    const testFile = tr.name || '';
    for (const ar of tr.assertionResults || []) {
      if (ar.status !== 'failed') continue;
      const msg = (ar.failureMessages && ar.failureMessages[0]) || '';
      out.push({
        service: serviceLabel,
        testFilePath: testFile,
        fullName: ar.fullName || ar.title,
        line: ar.location ? ar.location.line : undefined,
        column: ar.location ? ar.location.column : undefined,
        message: msg.trim(),
      });
    }
  }
  return out;
}

function buildFailuresOnlyText(failures) {
  if (!failures.length) return '';
  return `${failures.map((f) => {
    const loc = f.line ? `:${f.line}` : '';
    const head = `${f.testFilePath}${loc} — ${f.fullName}`;
    const body = (f.message || '').split('\n').slice(0, 14).join('\n');
    return `${head}\n${body}`;
  }).join('\n\n---\n\n')}\n`;
}

function writeFailuresJsonDeploy(resultsDir, projectPath, failures) {
  const payload = {
    project: projectPath,
    generatedAt: new Date().toISOString(),
    failures,
  };
  fs.writeFileSync(
    path.join(resultsDir, 'failures.json'),
    `${JSON.stringify(payload, null, 2)}\n`,
    'utf-8',
  );
}

function finalizeDeployTestArtifacts(resultsDir, projectPath, services) {
  if (!resultsDir || !fs.existsSync(resultsDir)) return;
  const failures = [];
  for (const svc of services) {
    const p = path.join(resultsDir, svc.dir, 'jest-spec-results.json');
    failures.push(...collectFailuresFromJestJson(p, svc.dir));
  }
  failures.push(
    ...collectFailuresFromJestJson(
      path.join(resultsDir, 'jest-deploy-results.json'),
      'jest-deploy',
    ),
  );
  writeFailuresJsonDeploy(resultsDir, projectPath, failures);
  if (failures.length) {
    fs.writeFileSync(
      path.join(resultsDir, 'deploy-failures-only.log'),
      buildFailuresOnlyText(failures),
      'utf-8',
    );
  }
}

/**
 * Retry a function with exponential backoff.
 * @param {Function} fn - Function to retry (should throw on failure)
 * @param {number} maxAttempts - Maximum number of attempts (default: 3)
 * @param {number} initialDelayMs - Initial delay in milliseconds (default: 2000)
 * @returns {boolean} - true if succeeded, false if all attempts failed
 */
function retryWithBackoff(fn, maxAttempts = 3, initialDelayMs = 2000) {
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      fn();
      return true;
    } catch (err) {
      if (attempt === maxAttempts) {
        // Last attempt failed, give up
        throw err;
      }
      // Calculate delay with exponential backoff: 2s, 4s, 8s
      const delayMs = initialDelayMs * Math.pow(2, attempt - 1);
      logInfo(`retry_attempt=${attempt} max_attempts=${maxAttempts} next_delay_ms=${delayMs}`);
      // Synchronous sleep using busy-wait (not ideal but works for short delays)
      const start = Date.now();
      while (Date.now() - start < delayMs) {
        // Busy wait
      }
    }
  }
  return false;
}

/**
 * Walk up until the TypeScript pnpm workspace root (pnpm-workspace.yaml + package.json).
 */
function findTypescriptWorkspaceRoot(projectPath) {
  let dir = path.resolve(projectPath);
  const fsRoot = path.parse(dir).root;
  while (dir !== fsRoot) {
    const ws = path.join(dir, 'pnpm-workspace.yaml');
    const pkg = path.join(dir, 'package.json');
    if (fs.existsSync(ws) && fs.existsSync(pkg)) {
      return dir;
    }
    dir = path.dirname(dir);
  }
  return null;
}

function envWithWorkspaceBin(workspaceRoot, baseEnv) {
  const env = { ...baseEnv };
  const bin = path.join(workspaceRoot, 'node_modules', '.bin');
  if (!fs.existsSync(bin)) {
    return env;
  }
  const sep = process.platform === 'win32' ? ';' : ':';
  const pathKey = Object.keys(process.env).find((k) => k.toUpperCase() === 'PATH') || 'PATH';
  env[pathKey] = `${bin}${sep}${env[pathKey] || ''}`;
  return env;
}

function jestCliPath(workspaceRoot) {
  return path.join(workspaceRoot, 'node_modules', 'jest', 'bin', 'jest.js');
}

/**
 * One ``pnpm install`` at ``.generated/typescript`` when Jest is missing from the workspace tree.
 */
function ensureWorkspaceInstall(workspaceRoot, opts) {
  opts = opts || {};
  if (!workspaceRoot) {
    return false;
  }
  const jestJs = jestCliPath(workspaceRoot);
  if (fs.existsSync(jestJs)) {
    return true;
  }
  logInfo(`pnpm_install_workspace_started root=${workspaceRoot}`);
  try {
    const runInstall = () => {
      const r = spawnSync(`${PNPM_CMD} install`, {
        cwd: workspaceRoot,
        encoding: 'utf-8',
        maxBuffer: 50 * 1024 * 1024,
        shell: true,
        stdio: ['ignore', 'pipe', 'pipe'],
        env: { ...process.env, CI: 'true' },
      });
      const combined = [r.stdout || '', r.stderr || ''].join('');
      if (opts.installLogPath) {
        fs.writeFileSync(opts.installLogPath, combined, 'utf-8');
      }
      if (r.error) throw r.error;
      if (r.status !== 0 && r.status !== null) {
        const tail = combined.trim().slice(-4000);
        throw new Error(`pnpm install exited with code ${r.status}${tail ? `\n${tail}` : ''}`);
      }
    };
    retryWithBackoff(runInstall, 3, 2000);
    logInfo('pnpm_install_workspace_completed');
  } catch (err) {
    logError(`pnpm_install_workspace_failed error=${err.message}`);
    return false;
  }
  return fs.existsSync(jestJs);
}

/**
 * Resolve TEST_DATABASE_URL from Docker Compose port mapping.
 * Reads DATABASE_URL from .env and rewrites it to use host-mapped port.
 */
function resolveTestDatabaseUrl(compose, dbContainers, { cwd = null } = {}) {
  if (!dbContainers || dbContainers.length === 0) {
    return null;
  }

  const dbInfo = dbContainers[0];
  const containerKey = dbInfo.key;
  const internalPort = dbInfo.internal_port;
  const envVar = dbInfo.env_var;

  // Read DATABASE_URL from .env
  const envFile = path.join(cwd || __dirname, '..', '.env');
  if (!fs.existsSync(envFile)) {
    logInfo(`env_file_not_found path=${envFile}`);
    return null;
  }

  let databaseUrl = null;
  const envContent = fs.readFileSync(envFile, 'utf-8');
  for (const line of envContent.split('\n')) {
    const trimmed = line.trim();
    if (trimmed.startsWith(`${envVar}=`)) {
      databaseUrl = trimmed.split('=', 2)[1];
      break;
    }
  }

  if (!databaseUrl) {
    logInfo(`database_url_not_found env_var=${envVar}`);
    return null;
  }

  // Get host-mapped port from docker compose
  const portCmd = [...compose, 'port', containerKey, String(internalPort)].join(' ');
  let hostMapping;
  try {
    hostMapping = execSync(portCmd, {
      cwd: cwd || undefined,
      encoding: 'utf-8',
      timeout: 10000,
    }).trim();
  } catch (err) {
    logInfo(`docker_compose_port_failed container=${containerKey} port=${internalPort}`);
    return null;
  }

  const hostPort = hostMapping.split(':').pop();

  // Parse and rewrite URL
  const url = new URL(databaseUrl);
  url.hostname = 'localhost';
  url.port = hostPort;

  return url.toString();
}

/**
 * Run specification tests for a single service.
 * Returns { passed, failed, skipped } statistics.
 */
function runServiceSpecTests(service, compose, { cwd = null, resultsDir = null, workspaceRoot = null } = {}) {
  const serviceName = service.name;
  const serviceDir = service.dir;
  const specDir = path.join(cwd || __dirname, '..', serviceDir, 'test', 'spec');

  if (!fs.existsSync(specDir)) {
    logInfo(`spec_tests_skipped service=${serviceName} reason=no_spec_directory`);
    return { passed: 0, failed: 0, skipped: 0 };
  }

  logInfo(`spec_tests_started service=${serviceName}`);

  // Resolve TEST_DATABASE_URL if service has database containers
  let env = { ...process.env };
  // Enable payment gateway test mode for integration tests (mock Stripe/payment SDKs)
  env.PAYMENT_TEST_MODE = 'true';
  if (service.dbContainers && service.dbContainers.length > 0) {
    const testDbUrl = resolveTestDatabaseUrl(compose, service.dbContainers, { cwd });
    if (testDbUrl) {
      env.TEST_DATABASE_URL = testDbUrl;
      logInfo(`test_database_url_resolved service=${serviceName} url=${testDbUrl}`);
    }
  }
  if (workspaceRoot) {
    env = envWithWorkspaceBin(workspaceRoot, env);
  }

  const jestJs = workspaceRoot ? jestCliPath(workspaceRoot) : '';
  if (!jestJs || !fs.existsSync(jestJs)) {
    logError(`spec_tests_aborted service=${serviceName} reason=jest_cli_missing path=${jestJs || 'null'}`);
    return { passed: 0, failed: 0, skipped: 0, errors: 1, suiteFailures: 1 };
  }

  const jestArgv = [specDir, '--forceExit', '--no-cache', '--verbose'];
  if (resultsDir) {
    const jsonPath = path.join(resultsDir, service.dir, 'jest-spec-results.json');
    fs.mkdirSync(path.dirname(jsonPath), { recursive: true });
    const jsonArg = jsonPath.replace(/\\/g, '/');
    jestArgv.push('--json', `--outputFile=${jsonArg}`, '--testLocationInResults');
  }

  const result = spawnSync(process.execPath, [jestJs, ...jestArgv], {
    cwd: path.join(cwd || __dirname, '..', serviceDir),
    encoding: 'utf-8',
    timeout: 300_000,
    shell: false,
    env,
  });

  const allOutput = (result.stdout || '') + (result.stderr || '');
  if (allOutput) {
    console.log(allOutput);
  }
  if (logFilePath && allOutput) {
    fs.appendFileSync(logFilePath, stripKnownLogNoise(stripAnsi(allOutput)) + '\n', 'utf-8');
  }

  const stats = parseJestStats(allOutput);
  const exitCode = result.status ?? 1;
  const hasFailed = exitCode !== 0 || stats.failed > 0 || stats.errors > 0 || stats.suiteFailures > 0;

  if (!hasFailed && stats.passed > 0) {
    logInfo(`spec_tests_passed service=${serviceName} passed=${stats.passed}`);
  } else if (stats.failed > 0 || stats.errors > 0 || stats.suiteFailures > 0) {
    logError(
      `spec_tests_failed service=${serviceName} passed=${stats.passed} failed=${stats.failed} `
      + `suiteFailures=${stats.suiteFailures} errors=${stats.errors}`,
    );
  } else {
    logInfo(`spec_tests_skipped service=${serviceName} reason=no_tests`);
  }

  return stats;
}

/**
 * Run specification tests for all services.
 * Returns number of failures (0 = all passed).
 */
function runAllSpecTests(compose, { cwd = null, resultsDir = null, workspaceRoot = null } = {}) {
  logInfo('spec_tests_phase_started');
  let failures = 0;
  let totalPassed = 0;
  let totalFailed = 0;
  let totalSkipped = 0;

  for (const service of SERVICES) {
    const stats = runServiceSpecTests(service, compose, { cwd, resultsDir, workspaceRoot });
    totalPassed += stats.passed;
    totalFailed += stats.failed;
    totalSkipped += stats.skipped;
    if (stats.failed > 0 || stats.errors > 0 || stats.suiteFailures > 0) {
      failures++;
    }
  }

  if (failures > 0) {
    logError(`spec_tests_phase_failed failures=${failures} passed=${totalPassed} failed=${totalFailed}`);
  } else if (totalPassed > 0) {
    logInfo(`spec_tests_phase_passed passed=${totalPassed} skipped=${totalSkipped}`);
  } else {
    logInfo('spec_tests_phase_skipped reason=no_spec_tests');
  }

  return failures;
}

/**
 * Run Jest deployment tests (integration tests).
 */
function runJestTests(resultsDir, workspaceRoot) {
  logInfo('jest_tests_started');
  const jestJs = workspaceRoot ? jestCliPath(workspaceRoot) : '';
  if (!jestJs || !fs.existsSync(jestJs)) {
    logError(`jest_tests_aborted reason=jest_cli_missing path=${jestJs || 'null'}`);
    return false;
  }

  const jestArgv = ['--config', 'jest-deploy.config.ts', '--forceExit', '--no-cache', '--verbose'];
  if (resultsDir) {
    const jsonPath = path.join(resultsDir, 'jest-deploy-results.json');
    fs.mkdirSync(path.dirname(jsonPath), { recursive: true });
    const jsonArg = jsonPath.replace(/\\/g, '/');
    jestArgv.push('--json', `--outputFile=${jsonArg}`, '--testLocationInResults');
  }

  // Jest writes results to stderr, not stdout. Use spawnSync to capture both
  // streams reliably regardless of exit code (execSync discards stderr on success).
  let allOutput = '';
  let exitCode = 0;

  const env = envWithWorkspaceBin(workspaceRoot, { ...process.env, CI: 'true' });
  const result = spawnSync(process.execPath, [jestJs, ...jestArgv], {
    cwd: __dirname,
    encoding: 'utf-8',
    timeout: 300_000,
    shell: false,
    env,
  });
  allOutput = (result.stdout || '') + (result.stderr || '');
  exitCode = result.status ?? 1;

  // Always write Jest output to stdout so run_complete.py can parse test statistics
  if (allOutput) {
    console.log(allOutput);
  }

  // Always write to log file
  if (logFilePath && allOutput) {
    fs.appendFileSync(logFilePath, stripKnownLogNoise(stripAnsi(allOutput)) + '\n', 'utf-8');
  }

  // Parse statistics
  const stats = parseJestStats(allOutput);
  const hasFailed = exitCode !== 0 || stats.failed > 0 || stats.errors > 0 || stats.suiteFailures > 0;

  if (!hasFailed && stats.passed > 0) {
    logInfo(`jest_tests_completed passed=${stats.passed} skipped=${stats.skipped}`);
    return true;
  } else if (stats.failed > 0 || stats.errors > 0 || stats.suiteFailures > 0) {
    logError(
      `jest_tests_failed passed=${stats.passed} failed=${stats.failed} `
      + `suiteFailures=${stats.suiteFailures} errors=${stats.errors}`,
    );
    return false;
  } else if (exitCode !== 0) {
    logError(`jest_tests_failed exit_code=${exitCode}`);
    return false;
  } else {
    logError('jest_tests_failed reason=no_tests_collected');
    return false;
  }
}

/**
 * Ensure pnpm is available by checking if it exists, and enabling corepack if needed.
 * Returns true if pnpm is available, false if it could not be made available.
 */
function ensurePnpmAvailable() {
  try {
    const pnpmCmd = PNPM_CMD;
    execSync(`${pnpmCmd} --version`, { stdio: 'pipe' });
    return true; // pnpm already available
  } catch (err) {
    // pnpm not found, try enabling corepack
    try {
      logInfo('pnpm not found, enabling corepack...');
      execSync('corepack enable', { stdio: 'pipe' });
      // Verify it worked
      const pnpmCmd = PNPM_CMD;
      execSync(`${pnpmCmd} --version`, { stdio: 'pipe' });
      logInfo('corepack enabled successfully');
      return true;
    } catch (corepackErr) {
      logError('Failed to enable corepack or pnpm is still unavailable');
      logError(`Error: ${corepackErr.message}`);
      logError('Please run: corepack enable');
      return false;
    }
  }
}

/**
 * Main deployment test flow.
 */
async function main() {
  const args = process.argv.slice(2);
  const keepRunning = args.includes('--keep-running');
  const debug = args.includes('--debug');
  const verbose = args.includes('--verbose');
  const freshBuild = args.includes('--fresh-build') || process.env.DEPLOY_TEST_FRESH_BUILD === 'true';

  // Set global logging mode (used by log() function)
  debugLogging = debug;
  verboseLogging = verbose || debug; // debug mode implies verbose

  let resultsDir;
  const resultsDirIdx = args.indexOf('--results-dir');
  if (resultsDirIdx >= 0 && args[resultsDirIdx + 1]) {
    resultsDir = args[resultsDirIdx + 1];
  } else {
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    resultsDir = path.join(__dirname, '..', '.test_results', `deploy-test-${timestamp}`);
  }

  if (!fs.existsSync(resultsDir)) {
    fs.mkdirSync(resultsDir, { recursive: true });
  }

  logFilePath = path.join(resultsDir, 'deploy-test-output.log');
  fs.writeFileSync(logFilePath, '', 'utf-8'); // Clear log file

  logInfo(`deployment_tests_started project=${COMPOSE_PROJECT_NAME}`);
  logInfo(`results_directory=${resultsDir}`);

  // Ensure pnpm is available (enable corepack if needed)
  if (!ensurePnpmAvailable()) {
    logError('Cannot proceed without pnpm. Exiting.');
    process.exit(1);
  }

  const config = loadConfig();
  const healthTimeout = (config.deploy && config.deploy.health_check_timeout) || DEFAULT_HEALTH_TIMEOUT_SECONDS;
  const compose = [...getDockerComposeCmd(), '-p', COMPOSE_PROJECT_NAME];
  const projectDir = path.join(__dirname, '..');
  const typescriptWorkspaceRoot = findTypescriptWorkspaceRoot(projectDir);
  if (!typescriptWorkspaceRoot) {
    logError('typescript_workspace_not_found expected_pnpm-workspace.yaml_under_.generated/typescript');
    process.exit(1);
  }

  writeDeployEnvironmentJson(resultsDir, path.resolve(projectDir));

  // Ensure .env exists
  const envFile = path.join(projectDir, '.env');
  const envExample = path.join(projectDir, '.env.example');
  if (fs.existsSync(envExample)) {
    fs.copyFileSync(envExample, envFile);
    logInfo(`copied_env_example path=${envFile}`);
  }

  // Generate ephemeral RSA keypair for asymmetric JWT tests.
  // The private key is used by tests/helpers.ts to sign JWTs.
  // The public key is injected into .env as JWT_SECRET so the
  // containerised NestJS app can verify the test tokens.
  logInfo('rsa_keypair_generation_started');
  const { publicKey: rsaPublicKey, privateKey: rsaPrivateKey } =
    require('crypto').generateKeyPairSync('rsa', {
      modulusLength: 2048,
      publicKeyEncoding: { type: 'spki', format: 'pem' },
      privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
    });
  const rsaPrivateKeyPath = path.join(__dirname, '.test-jwt-private-key.pem');
  fs.writeFileSync(rsaPrivateKeyPath, rsaPrivateKey, 'utf-8');
  logInfo(`rsa_private_key_written path=${rsaPrivateKeyPath}`);

  // Replace JWT_SECRET in .env with the PEM public key.
  // Newlines are escaped as literal \n for .env format; the app's
  // configuration restores them via .replace(/\\n/g, '\n').
  if (fs.existsSync(envFile)) {
    let envContent = fs.readFileSync(envFile, 'utf-8');
    const escapedPubKey = rsaPublicKey.trimEnd().replace(/\n/g, '\\n');
    if (/^JWT_SECRET=/m.test(envContent)) {
      envContent = envContent.replace(/^JWT_SECRET=.*$/m, `JWT_SECRET=${escapedPubKey}`);
    } else {
      envContent += `\nJWT_SECRET=${escapedPubKey}\n`;
    }
    fs.writeFileSync(envFile, envContent, 'utf-8');
    logInfo('jwt_secret_updated_with_rsa_public_key');
  }

  // Pre-cleanup
  logInfo('docker_pre_cleanup_started');
  runDockerCmd([...compose, 'down', '-v', '--remove-orphans'], { verbose: verboseLogging, cwd: projectDir });

  // Remove orphaned volumes
  try {
    const volResult = execSync(
      `docker volume ls --filter name=${COMPOSE_PROJECT_NAME} --quiet`,
      { encoding: 'utf-8' }
    );
    const volumes = volResult.split('\n').map(s => s.trim()).filter(Boolean);
    for (const vol of volumes) {
      execSync(`docker volume rm ${vol}`, { stdio: 'ignore' });
      logInfo(`removed_orphan_volume name=${vol}`);
    }
  } catch {}

  // Build
  logInfo('docker_build_started');
  const buildFlags = freshBuild ? ['--no-cache'] : [];
  const build = runDockerCmd([...compose, 'build', ...buildFlags], { verbose: verboseLogging, label: 'docker_build', cwd: projectDir });
  if (!build.success) {
    logError(`docker_build_failed exit_code=${build.code}`);
    finalizeDeployTestArtifacts(resultsDir, path.resolve(projectDir), SERVICES);
    return 1;
  }
  logInfo('docker_build_completed');

  // Start containers
  let testsPassed = false;
  try {
    logInfo('docker_up_started');
    let up = runDockerCmd([...compose, 'up', '-d'], { verbose: verboseLogging, label: 'docker_up', cwd: projectDir });
    if (!up.success) {
      // Infrastructure containers with restart policies may recover from
      // transient startup failures (e.g. MongoDB port-bind race in
      // docker-entrypoint.sh).  Wait for restarts, then retry once.
      logInfo('docker_up_retrying reason=dependency_may_need_restart');
      spawnSync('node', ['-e', 'setTimeout(()=>{},15000)'], { stdio: 'ignore' });
      up = runDockerCmd([...compose, 'up', '-d'], { verbose: verboseLogging, label: 'docker_up_retry', cwd: projectDir });
    }
    if (!up.success) {
      logError(`docker_up_failed exit_code=${up.code}`);
      return 1;
    }
    logInfo('docker_up_completed');

    // Check for crashed containers before waiting for health.
    // Catches immediate startup failures (DI errors, missing modules, etc.)
    // instead of polling /health for 120s only to get a generic timeout.
    let failures = 0;
    logInfo('docker_container_health_check_started');
    if (!checkContainerExitCodes(compose, { cwd: projectDir })) {
      logError('docker_container_health_check_failed');
      failures++;
    }

    // Wait for health checks
    for (const service of SERVICES) {
      const baseUrl = `http://localhost:${service.port}`;
      logInfo(`service_waiting name=${service.name} base_url=${baseUrl}`);
      const healthy = await waitForHealth(baseUrl, healthTimeout);
      if (!healthy) {
        logError(`service_health_timeout name=${service.name} timeout_seconds=${healthTimeout}`);
        failures++;
        continue;
      }
      logInfo(`service_healthy name=${service.name}`);
    }

    if (failures === 0) {
      if (!ensureWorkspaceInstall(typescriptWorkspaceRoot, {
        installLogPath: path.join(resultsDir, 'pnpm-install-deploy-tests.log'),
      })) {
        logError('test_deps_install_failed');
        return 1;
      }

      // Run spec tests first (per-service tests against database)
      const specFailures = runAllSpecTests(compose, {
        cwd: projectDir,
        resultsDir,
        workspaceRoot: typescriptWorkspaceRoot,
      });
      failures += specFailures;

      // Run integration tests (API endpoint tests)
      if (failures === 0) {
        testsPassed = runJestTests(resultsDir, typescriptWorkspaceRoot);
      } else {
        logError(`spec_tests_failed count=${specFailures}`);
        testsPassed = false;
      }
    } else {
      logError(`health_checks_failed count=${failures}`);
    }
  } finally {
    // Save Docker logs before teardown
    saveDockerLogs(compose, resultsDir, { cwd: projectDir });

    if (!keepRunning) {
      logInfo('docker_teardown_started');
      runDockerCmd(
        [...compose, 'down', '-v', '--rmi', 'local', '--remove-orphans'],
        { verbose: verboseLogging, cwd: projectDir }
      );
      logInfo('docker_teardown_completed');
    }
    finalizeDeployTestArtifacts(resultsDir, path.resolve(projectDir), SERVICES);
  }

  if (testsPassed) {
    logInfo('deployment_tests_passed');
    return 0;
  } else {
    logError('deployment_tests_failed');
    return 1;
  }
}

main().then(code => process.exit(code)).catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
