package library_book_service.schemas;

/**
 * BookNotifyRequest value object.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record BookNotifyRequest(String recipientEmail, String message) {}
