package library_book_service.model.book_db;

import jakarta.persistence.PrePersist;
import library_book_service.support.CryptoHelpers;

/**
 * Lifecycle listener for User.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public class UserLifecycleListener {

  @PrePersist
  public void onPrePersist(User target) {
    target.setPasswordHash(CryptoHelpers.bcryptHash(target.getPasswordHash()));
  }
}
