// BookServiceApiFunctionTests.cs -- generated xUnit.v3 API-function existence/arity tests.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using System.Reflection;
using BookService.Controllers;
using Xunit;

namespace BookService.Tests.ApiFunctionTests;

public sealed class BookServiceApiFunctionTests
{
    private const BindingFlags MethodFlags =
        BindingFlags.Instance | BindingFlags.NonPublic | BindingFlags.Public;

    private static MethodInfo? FindApiFunction(string name)
    {
        return typeof(BookServiceAPIController).GetMethod(name, MethodFlags);
    }

    [Fact]
    public void FindBooksByFilter_IsDeclaredWithExpectedArity()
    {
        MethodInfo? method = FindApiFunction("FindBooksByFilter");
        Assert.NotNull(method);
        Assert.Equal(2, method!.GetParameters().Length);
    }
}
