test:
  platform: container
  defaults:
    timeout: 300
    memory: 512
  handlers:
    ProcessShipment:
      timeout: 120
      memory: 256

development:
  platform: container

production:
  platform: lambda
  defaults:
    timeout: 300
    memory: 512
  handlers:
    ProcessShipment:
      timeout: 180
      memory: 512
