test:
  platform: container
  defaults:
    timeout: 900
    memory: 2048
  handlers:
    DailyOrderReport: {}

development:
  platform: container

production:
  platform: lambda
  defaults:
    timeout: 900
    memory: 2048
  handlers:
    DailyOrderReport: {}
