test:
  platform: compose
  port: 8020
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  healthCheck:
    type: http
    path: /health
    initialDelay: 10s
    period: 5s
    failureThreshold: 3
    successThreshold: 1

development:
  platform: compose
  port: 8020
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  healthCheck:
    type: http
    path: /health
    initialDelay: 10s
    period: 5s
    failureThreshold: 3
    successThreshold: 1

staging:
  platform: compose
  port: 8020
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  healthCheck:
    type: http
    path: /health
    initialDelay: 10s
    period: 5s
    failureThreshold: 3
    successThreshold: 1

production:
  platform: ecs-fargate
  port: 8020
  strategy:
    rolling:
      maxUnavailable: 25%
      maxSurge: 25%
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  healthCheck:
    type: http
    path: /health
    initialDelay: 10s
    period: 5s
    failureThreshold: 3
    successThreshold: 1
