test:
  name: blog-service
  host: localhost
  port: 8020
  tags: [blog, api]

development:
  name: blog-service
  host: localhost
  port: 8020
  tags: [blog, api]

staging:
  name: blog-service
  host: localhost
  port: 8020
  tags: [blog, api]

production:
  name: blog-service
  port: 8020
  tags: [blog, api]
