package library_book_service.dto.book_db;

import jakarta.validation.constraints.Size;

/**
 * Category update-request DTO. Every field is optional-to-provide (PATCH semantics) -- no field
 * carries a not-null requirement.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record CategoryUpdateRequest(
    @Size(max = 100) String name, @Size(max = 500) String description) {}
