"""Integration tests for library.BookService standard endpoints.

Auto-generated by datrix-codegen-python. Do not edit manually.
"""

from __future__ import annotations

import pytest
from httpx import AsyncClient


@pytest.mark.integration
@pytest.mark.asyncio
class TestStandardEndpoints:
    """Test standard service endpoints (live, ready, health, docs, openapi)."""

    async def test_health_returns_200(self, client: AsyncClient) -> None:
        """Liveness endpoint returns 200 with status 'up' (process liveness)."""
        response = await client.get("/live")
        assert response.status_code == 200
        data = response.json()
        assert data["status"] == "up"

    async def test_ready_returns_status(self, client: AsyncClient) -> None:
        """Readiness endpoint returns 200 or 503 with a status field."""
        response = await client.get("/ready")
        assert response.status_code in (200, 503)
        data = response.json()
        assert data["status"] in ("up", "down")

    async def test_health_reports_checks(self, client: AsyncClient) -> None:
        """Detailed health endpoint returns an aggregate status and checks map."""
        response = await client.get("/health")
        assert response.status_code in (200, 503)
        data = response.json()
        assert data["status"] in ("up", "degraded", "down")
        assert "checks" in data

    async def test_docs_returns_200(self, client: AsyncClient) -> None:
        """Swagger docs endpoint returns 200."""
        response = await client.get("/docs", timeout=60.0)
        assert response.status_code == 200

    async def test_openapi_json_returns_200(self, client: AsyncClient) -> None:
        """OpenAPI JSON schema returns valid JSON with expected fields."""
        response = await client.get("/openapi.json", timeout=60.0)
        assert response.status_code == 200
        data = response.json()
        assert "info" in data
        assert "paths" in data
