test:
  tags: [api, records, clinical, phi, v1]

  meta: { team: "clinical", compliance: "hipaa" }

  healthCheck: { type: http, path: /health, interval: 10s }

development:
  tags: [api, records, clinical, phi, v1]

  meta: { team: "clinical", compliance: "hipaa" }

  healthCheck: { type: http, path: /health, interval: 10s }

production:
  tags: [api, records, clinical, phi, v1]

  meta: { team: "clinical", compliance: "hipaa" }

  healthCheck: { type: http, path: /health, interval: 10s }
