package library_book_service.security;

import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.core.convert.converter.Converter;
import org.springframework.http.HttpMethod;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ProblemDetail;
import org.springframework.security.access.AccessDeniedException;
import org.springframework.security.authentication.AbstractAuthenticationToken;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.config.http.SessionCreationPolicy;
import org.springframework.security.core.AuthenticationException;
import org.springframework.security.core.GrantedAuthority;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.server.resource.authentication.JwtAuthenticationToken;
import org.springframework.security.web.AuthenticationEntryPoint;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.security.web.access.AccessDeniedHandler;

/**
 * Spring Security {@link SecurityFilterChain} + JWT resource-server config for library.BookService.
 *
 * <p>Authorization decisions derive ONLY from each endpoint's {@code auth_contract} (DSL-owned) --
 * never from a Java-side hardcoded path list, except the fixed framework-owned infra paths (health,
 * actuator, OpenAPI docs), the SAME "framework-owned infra paths are the ONLY exception" rule
 * python's gateway_generator.py follows.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Configuration
@EnableWebSecurity
public class SecurityFilterChainConfig {

  private static final Logger LOG = LoggerFactory.getLogger(SecurityFilterChainConfig.class);
  private static final ObjectMapper MAPPER = new ObjectMapper();

  @Bean
  public SecurityFilterChain securityFilterChain(
      HttpSecurity http, DatrixJwtDecoder datrixJwtDecoder) throws Exception {
    http.csrf(csrf -> csrf.disable())
        .sessionManagement(sm -> sm.sessionCreationPolicy(SessionCreationPolicy.STATELESS))
        .authorizeHttpRequests(
            auth ->
                auth.requestMatchers("/health")
                    .permitAll()
                    .requestMatchers("/actuator/**")
                    .permitAll()
                    .requestMatchers("/v3/api-docs/**")
                    .permitAll()
                    .requestMatchers("/swagger-ui/**")
                    .permitAll()
                    .requestMatchers("/swagger-ui.html")
                    .permitAll()
                    .requestMatchers(HttpMethod.GET, "/api/v1/books")
                    .permitAll()
                    .requestMatchers(HttpMethod.GET, "/api/v1/books/available")
                    .permitAll()
                    .requestMatchers(HttpMethod.GET, "/api/v1/books/by-tag/{tagId}")
                    .permitAll()
                    .requestMatchers(HttpMethod.GET, "/api/v1/books/catalog")
                    .permitAll()
                    .requestMatchers(HttpMethod.GET, "/api/v1/books/category/{categoryId}")
                    .permitAll()
                    .requestMatchers(HttpMethod.GET, "/api/v1/books/filter")
                    .permitAll()
                    .requestMatchers(HttpMethod.GET, "/api/v1/books/search")
                    .permitAll()
                    .requestMatchers(HttpMethod.GET, "/api/v1/books/{id}")
                    .permitAll()
                    .requestMatchers(HttpMethod.GET, "/api/v1/categories")
                    .permitAll()
                    .requestMatchers(HttpMethod.GET, "/api/v1/categories/{id}")
                    .permitAll()
                    .requestMatchers(HttpMethod.GET, "/api/v1/categories/{id}/books")
                    .permitAll()
                    .requestMatchers(HttpMethod.POST, "/api/v1/books")
                    .hasAnyAuthority("librarian")
                    .requestMatchers(HttpMethod.PUT, "/api/v1/books/{id}")
                    .hasAnyAuthority("librarian")
                    .requestMatchers(HttpMethod.DELETE, "/api/v1/books/{id}")
                    .hasAnyAuthority("librarian")
                    .requestMatchers(HttpMethod.POST, "/api/v1/categories")
                    .hasAnyAuthority("librarian")
                    .requestMatchers(HttpMethod.PUT, "/api/v1/categories/{id}")
                    .hasAnyAuthority("librarian")
                    .requestMatchers(HttpMethod.DELETE, "/api/v1/categories/{id}")
                    .hasAnyAuthority("librarian")
                    .anyRequest()
                    .authenticated())
        .oauth2ResourceServer(
            oauth2 ->
                oauth2.jwt(
                    jwt ->
                        jwt.decoder(datrixJwtDecoder)
                            .jwtAuthenticationConverter(jwtAuthenticationConverter())))
        .exceptionHandling(
            ex ->
                ex.authenticationEntryPoint(new OpaqueAuthenticationEntryPoint())
                    .accessDeniedHandler(new OpaqueAccessDeniedHandler()));
    return http.build();
  }

  /**
   * Maps the decoder's {@code roles} claim (a plain string list, populated by {@link
   * DatrixJwtDecoder}'s role extraction) directly onto {@link GrantedAuthority}s -- no {@code
   * ROLE_} prefix, no scope-string parsing (Spring's default {@code JwtGrantedAuthoritiesConverter}
   * assumes an OAuth2 {@code scope}/{@code scp} claim, which this identity model does not use).
   */
  @Bean
  public Converter<Jwt, AbstractAuthenticationToken> jwtAuthenticationConverter() {
    return (Jwt jwt) -> {
      List<GrantedAuthority> authorities = new ArrayList<>();
      Object rolesClaim = jwt.getClaim("roles");
      if (rolesClaim instanceof List<?> roles) {
        for (Object role : roles) {
          authorities.add(new SimpleGrantedAuthority(String.valueOf(role)));
        }
      }
      return new JwtAuthenticationToken(jwt, authorities);
    };
  }

  /**
   * Opaque 401: NEVER echoes the underlying {@link AuthenticationException} message (which may
   * carry a {@code DatrixJwtDecoder.JwksValidationException} whose message is diagnostic-only) into
   * the response body. The reason code -- when the cause chain carries one -- is logged server-side
   * only (RFC 7807 opacity, D9).
   */
  static class OpaqueAuthenticationEntryPoint implements AuthenticationEntryPoint {
    @Override
    public void commence(
        HttpServletRequest request,
        HttpServletResponse response,
        AuthenticationException authException)
        throws IOException {
      AuthReasonCode reasonCode = reasonCodeFrom(authException);
      LOG.warn("identity_auth_failed path={} reason_code={}", request.getRequestURI(), reasonCode);
      writeProblem(
          response,
          HttpStatus.UNAUTHORIZED,
          "Unauthorized",
          "urn:datrix:error:unauthorized",
          request.getRequestURI());
    }

    private static AuthReasonCode reasonCodeFrom(AuthenticationException authException) {
      Throwable cause = authException;
      while (cause != null) {
        if (cause instanceof DatrixJwtDecoder.JwksValidationException jve) {
          return jve.reasonCode();
        }
        cause = cause.getCause();
      }
      return AuthReasonCode.MISSING_TOKEN;
    }
  }

  /**
   * Opaque 403: a stable, role-detail-free message -- never leaks which role(s) were required or
   * which the principal actually carried.
   */
  static class OpaqueAccessDeniedHandler implements AccessDeniedHandler {
    @Override
    public void handle(
        HttpServletRequest request,
        HttpServletResponse response,
        AccessDeniedException accessDeniedException)
        throws IOException {
      LOG.warn(
          "identity_authz_denied path={} reason_code={}",
          request.getRequestURI(),
          AuthReasonCode.ROLE_DENIED);
      writeProblem(
          response,
          HttpStatus.FORBIDDEN,
          "Forbidden",
          "urn:datrix:error:forbidden",
          request.getRequestURI());
    }
  }

  private static void writeProblem(
      HttpServletResponse response, HttpStatus status, String title, String type, String path)
      throws IOException {
    ProblemDetail body = ProblemDetail.forStatusAndDetail(status, title);
    body.setType(URI.create(type));
    body.setTitle(title);
    body.setInstance(URI.create(path));
    response.setStatus(status.value());
    response.setContentType(MediaType.APPLICATION_PROBLEM_JSON_VALUE);
    response.getWriter().write(MAPPER.writeValueAsString(body));
  }
}
