// BookDbConnectionOptions.cs -- generated ADO.NET connection-string builder for RDBMS
// block "bookDb". Pure function of IConfiguration ->
// ADO.NET connection string. Does NOT select an EF Core engine provider and
// does NOT register any DI/session lifecycle -- Program.cs's own
// AddDbContext<T> call (build_persistence_registration_block,
// generators/service/program_generator.py) owns both of those.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.

namespace BookService.Data.BookDb;

public static class BookDbConnectionOptions
{
    // Configured EF Core connection-pool size for this block (used in
    // metrics: read by BookDbConnectionOptions's own health check to refresh
    // PersistenceMetrics.ConnectionPoolSize on every successful probe). Kept
    // as a standalone method (not folded into BuildConnectionString) so a
    // health-check/metrics caller never has to parse a connection string
    // back apart to recover the pool size.
    public static int ResolvePoolSize(IConfiguration configuration)
    {
        return 20;
    }

    public static string BuildConnectionString(IConfiguration configuration)
    {
        var overrideUrl = configuration["BOOK_DB_DATABASE_URL"];
        if (!string.IsNullOrEmpty(overrideUrl))
        {
            return overrideUrl;
        }

        // Zero-env deployment: host/port/database/user come from the mounted
        // config-store.json "connections" namespace (connections:book_db_*),
        // and the password from a docker secret (a file under /run/secrets
        // surfaced as the flat config key "book_db_password" by
        // AddKeyPerFile). Each scalar falls back to its baked literal/env default
        // for local development without a mounted config store.
        var host = configuration["connections:book_db_host"] ?? "localhost";
        var port = configuration["connections:book_db_port"] ?? "5432";
        var database = configuration["connections:book_db_database"] ?? "library_books";
        var user = configuration["connections:book_db_user"] ?? "postgres";
        var password = configuration["book_db_password"] ?? string.Empty;
        var poolSize = 20;
        var ssl = false;

        return $"Host={host};Port={port};Database={database};Username={user};Password={password};Maximum Pool Size={poolSize};SSL Mode={(ssl ? "Require" : "Disable")}";
    }
}
