openapi: 3.1.0
info:
  title: learning.EnrollmentService API
  version: 1.0.0
paths:
  /api/v1/enrollments/enrollments:
    get:
      operationId: list_enrollments
      summary: list_enrollments
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
    post:
      operationId: create_enrollment
      summary: create_enrollment
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
  /api/v1/enrollments/enrollments/:id:
    get:
      operationId: get_enrollment
      summary: get_enrollment
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
    put:
      operationId: update_enrollment
      summary: update_enrollment
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
    delete:
      operationId: delete_enrollment
      summary: delete_enrollment
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Enrollment:
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        studentId:
          type: string
          format: uuid
        courseId:
          type: string
          format: uuid
        enrolledAt:
          type: string
          format: date-time
      required:
      - id
      - createdAt
      - updatedAt
      - studentId
      - courseId
      - enrolledAt
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
