package library_book_service.queue;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.UUID;

/**
 * Payload for the send-book-notification queue.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record SendBookNotificationPayload(
    @JsonProperty("bookId") UUID bookId,
    @JsonProperty("recipientEmail") String recipientEmail,
    @JsonProperty("message") String message) {}
