package library_book_service.spec;

import static library_book_service.support.MapSupport._datrixOrderedMap;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.Objects;
import library_book_service.EventSpyRecorder;
import library_book_service.enums.BookStatus;
import library_book_service.model.book_db.Book;
import library_book_service.model.book_db.Category;
import library_book_service.pubsub.mq.BookAdded;
import library_book_service.pubsub.mq.BookStatusChanged;
import library_book_service.repositories.book_db.BookRepository;
import library_book_service.repositories.book_db.CategoryRepository;
import library_book_service.repositories.book_db.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated from this service's {@code test("...")} DSL blocks. Exercises the service through the
 * real Spring context -- {@code assert}/{@code throws} lower to JUnit 5 assertions, {@code
 * emitted(...)} asserts against the real, non-mocked {@link EventSpyRecorder}.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@SpringBootTest
@Import(BookServiceSpecTestSupport.class)
@ActiveProfiles("test")
@Transactional
@Rollback
class BookServiceSpecTest {

  @Autowired private CategoryRepository categoryRepository;

  @Autowired private UserRepository userRepository;

  @Autowired private BookRepository bookRepository;

  @Autowired private EventSpyRecorder eventSpy;

  @BeforeEach
  void resetEventSpy() {
    eventSpy.reset();
  }

  /** computed displayTitle formats title and year */
  @Test
  @DisplayName("computed displayTitle formats title and year")
  void computedDisplaytitleFormatsTitleAndYear() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatDisplay")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Domain-Driven Design",
                    "isbn",
                    "9780321125217",
                    "author",
                    "Eric Evans",
                    "publicationYear",
                    2003,
                    "categoryId",
                    cat.getId())));
    bookRepository.saveAndFlush(book);
    assertTrue((Objects.equals(book.getDisplayTitle(), "Domain-Driven Design (2003)")));
  }

  /** computed isAvailable is true when status is Available */
  @Test
  @DisplayName("computed isAvailable is true when status is Available")
  void computedIsavailableIsTrueWhenStatusIsAvailable() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatAvail")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Clean Code",
                    "isbn",
                    "9780132350884",
                    "author",
                    "Robert Martin",
                    "publicationYear",
                    2008,
                    "categoryId",
                    cat.getId())));
    bookRepository.saveAndFlush(book);
    assertTrue((Objects.equals(book.getIsAvailable(), true)));
  }

  /** computed isOldBook is true for pre-2000 books */
  @Test
  @DisplayName("computed isOldBook is true for pre-2000 books")
  void computedIsoldbookIsTrueForPre2000Books() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatOldBook")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Design Patterns",
                    "isbn",
                    "9780201633610",
                    "author",
                    "Gang of Four",
                    "publicationYear",
                    1994,
                    "categoryId",
                    cat.getId())));
    bookRepository.saveAndFlush(book);
    assertTrue((Objects.equals(book.getIsOldBook(), true)));
  }

  /** validation rejects empty title */
  @Test
  @DisplayName("validation rejects empty title")
  void validationRejectsEmptyTitle() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatValTitle")));
    categoryRepository.saveAndFlush(cat);
    assertThrows(
        ValidationError.class,
        () -> {
          var __datrixThrowsResult =
              bookRepository.saveAndFlush(
                  Book.fromMap(
                      _datrixOrderedMap(
                          "title",
                          "",
                          "isbn",
                          "1234567890",
                          "author",
                          "Author",
                          "publicationYear",
                          2020,
                          "categoryId",
                          cat.getId())));
        });
  }

  /** validation rejects future publication year */
  @Test
  @DisplayName("validation rejects future publication year")
  void validationRejectsFuturePublicationYear() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatValYear")));
    categoryRepository.saveAndFlush(cat);
    assertThrows(
        ValidationError.class,
        () -> {
          var __datrixThrowsResult =
              bookRepository.saveAndFlush(
                  Book.fromMap(
                      _datrixOrderedMap(
                          "title",
                          "Future Book",
                          "isbn",
                          "1234567890",
                          "author",
                          "Author",
                          "publicationYear",
                          20999,
                          "categoryId",
                          cat.getId())));
        });
  }

  /** beforeCreate generates catalogNumber */
  @Test
  @DisplayName("beforeCreate generates catalogNumber")
  void beforecreateGeneratesCatalognumber() {
    var cat =
        categoryRepository.saveAndFlush(Category.fromMap(_datrixOrderedMap("name", "SpecCatHook")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Refactoring",
                    "isbn",
                    "9780201485677",
                    "author",
                    "Martin Fowler",
                    "publicationYear",
                    1999,
                    "categoryId",
                    cat.getId())));
    bookRepository.saveAndFlush(book);
    assertTrue((!Objects.equals(book.getCatalogNumber(), null)));
  }

  /** afterCreate emits BookAdded event */
  @Test
  @DisplayName("afterCreate emits BookAdded event")
  void aftercreateEmitsBookaddedEvent() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatEvent")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Clean Architecture",
                    "isbn",
                    "9780134494166",
                    "author",
                    "Robert Martin",
                    "publicationYear",
                    2017,
                    "categoryId",
                    cat.getId())));
    bookRepository.saveAndFlush(book);
    assertTrue(
        eventSpy.recordedEvents().stream()
            .anyMatch(
                __e ->
                    __e instanceof BookAdded __evt
                        && java.util.Objects.equals(__evt.bookId(), book.getId())
                        && java.util.Objects.equals(__evt.title(), book.getTitle())));
  }

  /** status change emits BookStatusChanged on update */
  @Test
  @DisplayName("status change emits BookStatusChanged on update")
  void statusChangeEmitsBookstatuschangedOnUpdate() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatStatus")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Patterns of Enterprise Application Architecture",
                    "isbn",
                    "9780321127426",
                    "author",
                    "Martin Fowler",
                    "publicationYear",
                    2002,
                    "categoryId",
                    cat.getId())));
    bookRepository.saveAndFlush(book);
    book.setStatus(BookStatus.CHECKED_OUT);
    bookRepository.saveAndFlush(book);
    assertTrue(
        eventSpy.recordedEvents().stream()
            .anyMatch(
                __e ->
                    __e instanceof BookStatusChanged __evt
                        && java.util.Objects.equals(__evt.bookId(), book.getId())
                        && java.util.Objects.equals(__evt.oldStatus(), BookStatus.AVAILABLE)
                        && java.util.Objects.equals(__evt.newStatus(), BookStatus.CHECKED_OUT)));
  }

  /** title update does not dispatch BookStatusChanged */
  @Test
  @DisplayName("title update does not dispatch BookStatusChanged")
  void titleUpdateDoesNotDispatchBookstatuschanged() {
    var cat =
        categoryRepository.saveAndFlush(
            Category.fromMap(_datrixOrderedMap("name", "SpecCatNoEvent")));
    categoryRepository.saveAndFlush(cat);
    var book =
        bookRepository.saveAndFlush(
            Book.fromMap(
                _datrixOrderedMap(
                    "title",
                    "Working Effectively with Legacy Code",
                    "isbn",
                    "9780131177055",
                    "author",
                    "Michael Feathers",
                    "publicationYear",
                    2004,
                    "categoryId",
                    cat.getId())));
    bookRepository.saveAndFlush(book);
    book.setTitle("Updated Title");
    bookRepository.saveAndFlush(book);
    assertTrue((Objects.equals(book.getStatus(), BookStatus.AVAILABLE)));
  }
}
