// PaginationTests.cs -- generated xUnit.v3 required-field/equality tests.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using LoanService.Schemas;
using Xunit;

namespace LoanService.Tests.StructTests;

public sealed class PaginationTests
{
    [Fact]
    public void Constructor_WithRequiredFields_SetsExpectedProperties()
    {
        var value = new Pagination(Page: 1, PerPage: 1);

        Assert.Equal(1, value.Page);
        Assert.Equal(1, value.PerPage);
    }
}
