package library_book_service.cqrs.projections;

import static library_book_service.support.MapSupport._datrixOrderedMap;

import java.time.LocalDateTime;
import library_book_service.cqrs.views.BookCatalogViewRepository;
import library_book_service.enums.BookStatus;
import library_book_service.repositories.book_db.BookRepository;
import library_book_service.repositories.book_db.BookTagRepository;
import library_book_service.repositories.book_db.CategoryRepository;
import library_book_service.repositories.book_db.TagRepository;
import library_book_service.repositories.book_db.UserRepository;
import org.springframework.stereotype.Component;

/**
 * Projection that updates BookCatalogView from domain events.
 *
 * <p>Projections are idempotent: processing the same event twice produces the same result.
 * Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Component
public class BookCatalogProjection {

  private final CategoryRepository categoryRepository;
  private final UserRepository userRepository;
  private final TagRepository tagRepository;
  private final BookTagRepository bookTagRepository;
  private final BookRepository bookRepository;
  private final BookCatalogViewRepository bookCatalogViewRepository;

  public BookCatalogProjection(
      CategoryRepository categoryRepository,
      UserRepository userRepository,
      TagRepository tagRepository,
      BookTagRepository bookTagRepository,
      BookRepository bookRepository,
      BookCatalogViewRepository bookCatalogViewRepository) {
    this.categoryRepository = categoryRepository;
    this.userRepository = userRepository;
    this.tagRepository = tagRepository;
    this.bookTagRepository = bookTagRepository;
    this.bookRepository = bookRepository;
    this.bookCatalogViewRepository = bookCatalogViewRepository;
  }

  /** Update BookCatalogView when BookAdded occurs. */
  public void onBookAdded(Object bookId, Object title) {
    var book = bookRepository.findById(bookId).orElse(null);
    bookCatalogViewRepository.save(
        bookCatalogViewRepository
            .findByBookId(bookId)
            .orElseGet(
                () ->
                    new BookCatalogView(
                        _datrixOrderedMap(
                            "id",
                            bookId,
                            "title",
                            title,
                            "author",
                            book.getAuthor(),
                            "publicationYear",
                            book.getPublicationYear(),
                            "status",
                            BookStatus.AVAILABLE,
                            "lastUpdated",
                            LocalDateTime.now()))));
  }

  /** Update BookCatalogView when BookStatusChanged occurs. */
  public void onBookStatusChanged(Object bookId, Object oldStatus, Object newStatus) {
    var view = bookCatalogViewRepository.findById(bookId).orElse(null);
    view.setStatus(newStatus);
    view.setLastUpdated(LocalDateTime.now());
    view.save();
  }
}
