// MemberComputedTests.cs -- generated xUnit.v3 computed-field getter tests.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using MemberService.Models.MemberDb;
using Xunit;

namespace MemberService.Tests.ComputedTests.MemberDb;

public sealed class MemberComputedTests
{
    [Fact]
    public void FullName_FormatsCorrectly()
    {
        var instance = new Member { FirstName = "test_value", LastName = "test_value" };

        Assert.Equal("test_value test_value", instance.FullName);
    }
}
