package library_book_service.enums;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

/**
 * Generated tests for BookStatus: member count, declaration order, and (when applicable)
 * explicit-value round-trip via the code accessor.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class BookStatusTest {

  @Test
  void valuesContainsExactlyDeclaredMembersInOrder() {
    BookStatus[] values = BookStatus.values();
    assertEquals(4, values.length);
    assertEquals(BookStatus.AVAILABLE, values[0]);
    assertEquals(BookStatus.CHECKED_OUT, values[1]);
    assertEquals(BookStatus.RESERVED, values[2]);
    assertEquals(BookStatus.MAINTENANCE, values[3]);
  }

  @Test
  void valueOfMember0ReturnsDeclaredMember() {
    assertEquals(BookStatus.AVAILABLE, BookStatus.valueOf("AVAILABLE"));
  }

  @Test
  void valueOfMember1ReturnsDeclaredMember() {
    assertEquals(BookStatus.CHECKED_OUT, BookStatus.valueOf("CHECKED_OUT"));
  }

  @Test
  void valueOfMember2ReturnsDeclaredMember() {
    assertEquals(BookStatus.RESERVED, BookStatus.valueOf("RESERVED"));
  }

  @Test
  void valueOfMember3ReturnsDeclaredMember() {
    assertEquals(BookStatus.MAINTENANCE, BookStatus.valueOf("MAINTENANCE"));
  }
}
