package library_member_service.api;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import java.util.Optional;
import java.util.UUID;
import library_member_service.model.member_db.Member;
import library_member_service.model.member_db.MemberTestFactory;
import library_member_service.services.member_db.MemberService;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated direct-service-layer CRUD test for Member -- bypasses HTTP, exercises {@link
 * MemberService} against a real DB.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
@Rollback
class MemberRouteHandlersTest {

  @Autowired private MemberService memberService;

  @Test
  void crudLifecycleThroughTheServiceLayer() {
    Member created = this.memberService.create(MemberTestFactory.create());
    UUID id = created.getId();
    assertTrue(id != null, "created entity must have a generated id");

    Optional<Member> found = this.memberService.get(id);
    assertTrue(found.isPresent(), "created entity must be retrievable by id");

    List<Member> all = this.memberService.list();
    assertFalse(all.isEmpty(), "list must include the created entity");

    Member updated = this.memberService.update(created);
    assertEquals(id, updated.getId(), "update must preserve the entity's id");

    this.memberService.delete(id);
    assertTrue(this.memberService.get(id).isEmpty(), "entity must be gone after delete");
  }
}
