package library_member_service.health;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import java.util.LinkedHashMap;
import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Health, readiness, and liveness endpoints (D8) -- a hand-rolled {@code @RestController},
 * deliberately NOT Spring Boot Actuator (which would change the response contract the wget
 * healthcheck and deployment tests assert on).
 *
 * <ul>
 *   <li>{@code GET /live} -- process liveness; 200 always, no dependency checks.
 *   <li>{@code GET /ready} -- 503 when any readiness-blocking dependency is down.
 *   <li>{@code GET /health} -- per-dependency {@code checks} map; 503 only when a REQUIRED
 *       dependency is down.
 * </ul>
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@RestController
public class HealthController {

  private static final Logger logger = LoggerFactory.getLogger(HealthController.class);
  private static final String STATUS_UP = "up";
  private static final String STATUS_DOWN = "down";
  private static final String STATUS_DEGRADED = "degraded";
  private static final String SERVICE_NAME = "library_member_service";

  @PersistenceContext private EntityManager entityManager;

  private boolean isDatabaseUp() {
    try {
      entityManager.createNativeQuery("SELECT 1").getSingleResult();
      return true;
    } catch (RuntimeException ex) {
      logger.warn("database_health_probe_failed error={}", ex.getMessage());
      return false;
    }
  }

  @GetMapping("/live")
  public Map<String, Object> live() {
    Map<String, Object> body = new LinkedHashMap<>();
    body.put("status", STATUS_UP);
    body.put("service", SERVICE_NAME);
    return body;
  }

  @GetMapping("/ready")
  @Transactional(readOnly = true)
  public ResponseEntity<Map<String, Object>> ready() {
    Map<String, String> blockers = new LinkedHashMap<>();
    if (!isDatabaseUp()) {
      blockers.put("database", STATUS_DOWN);
    }
    Map<String, Object> body = new LinkedHashMap<>();
    body.put("service", SERVICE_NAME);
    body.put("blockers", blockers);
    if (!blockers.isEmpty()) {
      body.put("status", STATUS_DOWN);
      logger.warn("readiness_not_ready service={} blockers={}", SERVICE_NAME, blockers);
      return ResponseEntity.status(HttpStatus.SERVICE_UNAVAILABLE).body(body);
    }
    body.put("status", STATUS_UP);
    return ResponseEntity.ok(body);
  }

  @GetMapping("/health")
  @Transactional(readOnly = true)
  public ResponseEntity<Map<String, Object>> health() {
    Map<String, Object> checks = new LinkedHashMap<>();
    boolean requiredDown = false;
    boolean degraded = false;
    Map<String, Object> databaseCheck = new LinkedHashMap<>();
    boolean databaseUp = isDatabaseUp();
    databaseCheck.put("status", databaseUp ? STATUS_UP : STATUS_DOWN);
    databaseCheck.put("required", true);
    checks.put("database", databaseCheck);
    if (!databaseUp) {
      requiredDown = true;
    }

    String overall;
    if (requiredDown) {
      overall = STATUS_DOWN;
    } else if (degraded) {
      overall = STATUS_DEGRADED;
    } else {
      overall = STATUS_UP;
    }

    Map<String, Object> body = new LinkedHashMap<>();
    body.put("status", overall);
    body.put("service", SERVICE_NAME);
    body.put("checks", checks);
    if (requiredDown) {
      return ResponseEntity.status(HttpStatus.SERVICE_UNAVAILABLE).body(body);
    }
    return ResponseEntity.ok(body);
  }
}
