"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "user_role" AS ENUM (\'admin\', \'manager\', \'member\', \'viewer\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "user_status" AS ENUM (\'active\', \'inactive\', \'invited\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "users",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "username",
            sa.String(50),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "email",
            sa.String(320),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "display_name",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "role",
            sa.Enum('admin', 'manager', 'member', 'viewer', name='user_role', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum('active', 'inactive', 'invited', name='user_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "avatar_url",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "last_login_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.create_index("ix_users_username", "users", ["username"], unique=False)
    op.create_index("ix_users_email", "users", ["email"], unique=False)
    op.create_index("ix_users_status_role", "users", ["status", "role"], unique=False)
    op.create_index("ix_users_username_display_name", "users", ["username", "display_name"], unique=False)


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_index("ix_users_username_display_name", table_name="users")
    op.drop_index("ix_users_status_role", table_name="users")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users")
