// BookService.cs -- generated entity service class (EF Core CRUD).
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
//
// Additive service layer: real EF Core CRUD against Book's own
// persistence set (Books) on the project's single
// BookServiceDbContext. NOT yet wired into any controller -- existing
// controller-embedded CRUD (generators/api/_endpoint_crud_body.py) is untouched
// by this domain. Controller delegation (Option B) is a separately scoped,
// deferred future change.
using System.Collections.Generic;
using System.Threading.Tasks;
using BookService.Data;
using Microsoft.EntityFrameworkCore;

namespace BookService.Services.BookDb;

public sealed class BookService
{
    private readonly BookServiceDbContext _context;

    public BookService(BookServiceDbContext context)
    {
        _context = context;
    }

    public async Task<global::BookService.Models.BookDb.Book?> GetByIdAsync(Guid id)
    {
        return await _context.Books.FindAsync(id);
    }

    public async Task<List<global::BookService.Models.BookDb.Book>> GetAllAsync()
    {
        return await _context.Books.ToListAsync();
    }

    public async Task<global::BookService.Models.BookDb.Book> CreateAsync(
        global::BookService.Models.BookDb.Book entity
    )
    {
        _context.Books.Add(entity);
        await _context.SaveChangesAsync();
        return entity;
    }

    public async Task<global::BookService.Models.BookDb.Book?> UpdateAsync(
        Guid id,
        global::BookService.Models.BookDb.Book updated
    )
    {
        var existing = await _context.Books.FindAsync(id);
        if (existing is null)
        {
            return null;
        }

        _context.Entry(existing).CurrentValues.SetValues(updated);
        await _context.SaveChangesAsync();
        return existing;
    }

    public async Task<bool> DeleteAsync(Guid id)
    {
        var existing = await _context.Books.FindAsync(id);
        if (existing is null)
        {
            return false;
        }

        _context.Books.Remove(existing);
        await _context.SaveChangesAsync();
        return true;
    }
}
