test:
  tags: [api, payments, v1]

  meta: { team: payments }

  healthCheck: { type: http, path: /health, interval: 10s }

development:
  tags: [api, payments, v1]

  meta: { team: payments }

  healthCheck: { type: http, path: /health, interval: 10s }

production:
  tags: [api, payments, v1]

  meta: { team: payments }

  healthCheck: { type: http, path: /health, interval: 10s }
