// Loan.cs -- generated POCO entity model.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using LoanService.Enums;

namespace LoanService.Models.LoanDb;

public class Loan : BaseEntity
{
    public Guid BookId { get; set; }
    public Guid MemberId { get; set; }
    public LoanStatus Status { get; set; }
    public DateTimeOffset DueDate { get; set; }
    public DateTimeOffset? ReturnedAt { get; set; }
    public bool IsOverdue =>
        (
            (this.Status == LoanStatus.Overdue)
            || ((this.Status == LoanStatus.Active) && (DateTimeOffset.UtcNow > this.DueDate))
        );
}
