test:
  pubsub:
    engine: kafka
    partitions: 3
    replicationFactor: 1
    brokers:
    - localhost:9092
    topics:
      CourseEvents:
        partitions: 3
        retention: 7d
    port: 9092
    docker_image: confluentinc/cp-kafka:7.8.0
    volume_path: /var/lib/kafka/data
    controllerPort: 9093
    platform: container
development:
  pubsub:
    engine: kafka
    partitions: 3
    replicationFactor: 1
    brokers:
    - localhost:9092
    topics:
      CourseEvents:
        partitions: 3
        retention: 7d
    port: 9092
    docker_image: confluentinc/cp-kafka:7.8.0
    volume_path: /var/lib/kafka/data
    controllerPort: 9093
    platform: container
production:
  pubsub:
    engine: kafka
    partitions: 3
    replicationFactor: 1
    brokers:
    - ${KAFKA_BROKER_1}
    - ${KAFKA_BROKER_2}
    - ${KAFKA_BROKER_3}
    topics:
      CourseEvents:
        partitions: 6
        retention: 30d
    port: 9092
    docker_image: confluentinc/cp-kafka:7.8.0
    volume_path: /var/lib/kafka/data
    controllerPort: 9093
    platform: managed
