package library_notification_service.gateway;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;

/**
 * Generated test asserting the gateway's rate-limit and CORS configuration (D8, shared {@code
 * gateway_test_facts} predicate).
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class GatewayConfigTest {

  @Test
  void rateLimitRequestsPerMinuteIsPositive() {
    int rpm = 100;
    assertTrue(rpm > 0, "gateway rate limit rpm must be positive");
  }

  @Test
  void corsOriginsOrMethodsAreDefined() {
    int originCount = 1;
    int methodCount = 5;
    assertTrue(originCount > 0 || methodCount > 0, "expected at least one CORS origin or method");
    assertFalse(originCount < 0);
    assertEquals(1, originCount);
  }
}
