// remoteConfig.ts -- runtime config-store client (dynamic API + typed constants)
//
// Auto-generated by datrix-codegen-typescript. Do not edit manually.
//
// The client exposes a dynamic, typed API over the application's runtime config
// store (feature flags, kill switches, tuning values). Its cache is initialized
// from the generated `remoteDefaults.json` artifact and remote profile
// values are merged over those defaults profile-by-profile on each refresh.
//
// Behavior (parity with the Python client):
// - unknown namespace/key access throws immediately;
// - scalar `get*` accessors throw immediately for keys declared with a secret
//   reference (use `getSecretRef` for their non-sensitive metadata);
// - remote type mismatches are logged and ignored when `failOpen` is true, and
//   throw on refresh when `failOpen` is false;
// - a failed refresh keeps the previous cache when `failOpen` is true; a failed
//   initial refresh throws when `failOpen` is false;
// - a single background poll timer per process refreshes on an interval; logs
//   include profile names and changed key names, never values.

import { readFileSync } from 'node:fs';
import { join } from 'node:path';
import { FileConfigBackend } from './backends/fileBackend';

/** Backend contract: return decoded scalar values for one profile. */
export interface ConfigBackend {
  fetchProfile(profile: string): Promise<Record<string, unknown>>;
}

/** Non-sensitive reference to a secret resolved elsewhere by secret access code.
 *
 * `handle` is the logical secret handle declared in the config store DSL
 * (e.g. `payment-gateway-key`). The runtime secret-backend accessor resolves
 * the handle to the actual secret value; this carries only the handle. */
export interface SecretRef {
  readonly handle: string;
}

/** Thrown on unknown namespace/key access or non-fail-open refresh failures. */
export class RemoteConfigError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'RemoteConfigError';
  }
}

// ---------------------------------------------------------------------------
// Typed namespace / key constants (`as const`). The dynamic API remains the
// contract; these provide editor-discoverable names and derived literal types
// for known namespaces and keys. No per-key accessor methods are generated.
// ---------------------------------------------------------------------------

/** Key-name constants for the freeform namespace `settings`. */
export const SettingsKeys = {
  NAMESPACE: 'settings',
  DEBUG_MODE: 'debugMode',
} as const;

export type SettingsKeysType = (typeof SettingsKeys)[keyof typeof SettingsKeys];

/** Declared namespaces (profiles) in the config store. */
export const PROFILE_NAMES = [
  'settings',
] as const;

export type ProfileName = (typeof PROFILE_NAMES)[number];

/**
 * Keys declared with a secret reference: namespace -> key -> SecretRef.
 * Scalar accessors throw for these; `getSecretRef` returns the metadata.
 */
const SECRET_REFS: Record<string, Record<string, SecretRef>> = {
};

/**
 * Declared scalar keys: namespace -> key -> ConfigValueType string.
 * Includes default-less keys so remote values can be accepted and validated.
 */
const DECLARED_VALUE_TYPES: Record<string, Record<string, string>> = {
  'settings': {
    'debugMode': 'Boolean',
  },
};

type ProfileValues = Record<string, unknown>;
type Cache = Record<string, ProfileValues>;

function loadDefaults(): Cache {
  const path = join(__dirname, 'remoteDefaults.json');
  const data: unknown = JSON.parse(readFileSync(path, 'utf-8'));
  if (typeof data !== 'object' || data === null || Array.isArray(data)) {
    throw new RemoteConfigError(
      `Defaults artifact 'remoteDefaults.json' must be a JSON object of ` +
        `profile -> key -> value; got ${typeof data}.`,
    );
  }
  return data as Cache;
}

function cloneCache(source: Cache): Cache {
  const copy: Cache = {};
  for (const [profile, values] of Object.entries(source)) {
    copy[profile] = { ...values };
  }
  return copy;
}

/**
 * Return the runtime kind used to compare a remote value against a default.
 * `bool` is distinct from numbers; integers and floats are both JS `number`.
 */
function runtimeKind(value: unknown): string {
  if (typeof value === 'boolean') {
    return 'boolean';
  }
  if (typeof value === 'number') {
    return 'number';
  }
  if (typeof value === 'string') {
    return 'string';
  }
  return typeof value;
}

function declaredValueType(namespace: string, key: string): string | undefined {
  return DECLARED_VALUE_TYPES[namespace]?.[key];
}

function valueMatchesDeclaredType(declaredType: string, value: unknown): boolean {
  if (declaredType === 'Boolean') {
    return typeof value === 'boolean';
  }
  if (declaredType === 'Integer') {
    return typeof value === 'number' && Number.isInteger(value);
  }
  if (declaredType === 'Float') {
    return typeof value === 'number';
  }
  if (declaredType === 'String') {
    return typeof value === 'string';
  }
  return false;
}

function unknownNamespaceMessage(namespace: string): string {
  const valid = [...PROFILE_NAMES].sort();
  return (
    `Unknown config-store namespace '${namespace}'. ` +
    `Valid namespaces: ${JSON.stringify(valid)}.`
  );
}

function unknownKeyMessage(namespace: string, key: string): string {
  return (
    `Unknown config-store key ${namespace}/${key}. The key is not declared in ` +
    `namespace '${namespace}'; check the configStore profile definition.`
  );
}

function missingValueMessage(namespace: string, key: string): string {
  return (
    `Config-store key ${namespace}/${key} is declared but has no current value. ` +
    'It has no generated default and no accepted remote value has been loaded yet.'
  );
}

function typeMessage(
  namespace: string,
  key: string,
  accessor: string,
  value: unknown,
): string {
  return (
    `Config-store key ${namespace}/${key} accessed via ${accessor} but its value ` +
    `has type ${runtimeKind(value)}. Use the accessor matching the declared key type.`
  );
}

/** Typed client over the runtime config store with background polling. */
export class RemoteConfigClient {
  private readonly backend: ConfigBackend;
  private readonly failOpen: boolean;
  private readonly pollSeconds: number;
  private readonly defaults: Cache;
  private cache: Cache;
  private pollTimer: ReturnType<typeof setInterval> | null = null;

  constructor(
    backend: ConfigBackend,
    defaults: Cache,
    options: { failOpen: boolean; pollSeconds: number },
  ) {
    this.backend = backend;
    this.failOpen = options.failOpen;
    this.pollSeconds = options.pollSeconds;
    // Cache starts as a copy of generated defaults; remote values merge over it.
    this.defaults = cloneCache(defaults);
    this.cache = cloneCache(defaults);
  }

  // -- lifecycle ------------------------------------------------------------

  /**
   * Perform the initial refresh and start the single background poll timer.
   *
   * A failed initial refresh keeps generated defaults when `failOpen` is true,
   * and re-throws when `failOpen` is false. Polling starts only after the
   * initial refresh is accepted.
   */
  async start(): Promise<void> {
    try {
      await this.refresh();
    } catch (err) {
      if (!this.failOpen) {
        throw err;
      }
      console.warn('remote_config_initial_refresh_failed fail_open=true');
    }
    if (this.pollTimer !== null) {
      return;
    }
    this.pollTimer = setInterval(() => {
      void this.refresh().catch((err: unknown) => {
        console.warn(`remote_config_poll_refresh_failed error=${String(err)}`);
      });
    }, this.pollSeconds!* 1000);
    // Do not keep the event loop alive solely for config polling.
    if (typeof this.pollTimer.unref === 'function') {
      this.pollTimer.unref();
    }
    console.info(`remote_config_started poll_seconds=${this.pollSeconds}`);
  }

  /** Stop the background poll timer. */
  stop(): void {
    if (this.pollTimer !== null) {
      clearInterval(this.pollTimer);
      this.pollTimer = null;
    }
    console.info('remote_config_stopped');
  }

  // -- refresh --------------------------------------------------------------

  /**
   * Fetch every configured profile once and merge remote values over defaults.
   *
   * On any backend or validation failure: when `failOpen` is true the previous
   * cache is preserved and the error is logged; when `failOpen` is false a
   * `RemoteConfigError` is thrown.
   */
  async refresh(): Promise<void> {
    const newCache: Cache = {};
    for (const profile of PROFILE_NAMES) {
      let merged: ProfileValues = { ...(this.defaults[profile] ?? {}) };
      let remote: Record<string, unknown>;
      try {
        remote = await this.backend.fetchProfile(profile);
      } catch (err) {
        if (!this.failOpen) {
          throw new RemoteConfigError(
            `Config-store refresh failed for profile '${profile}': ${String(err)}. ` +
              'Set failOpen: true to fall back to the last good cache.',
          );
        }
        console.warn(
          `remote_config_profile_fetch_failed profile=${profile} error=${String(err)}`,
        );
        merged = { ...(this.cache[profile] ?? merged) };
        newCache[profile] = merged;
        continue;
      }
      this.mergeRemote(profile, merged, remote);
      newCache[profile] = merged;
    }

    const changed = this.changedKeys(this.cache, newCache);
    this.cache = newCache;
    if (changed.length > 0) {
      console.info(`remote_config_refreshed changed_keys=${JSON.stringify(changed)}`);
    }
  }

  private mergeRemote(
    profile: string,
    merged: ProfileValues,
    remote: Record<string, unknown>,
  ): void {
    for (const [key, value] of Object.entries(remote)) {
      const declaredType = declaredValueType(profile, key);
      if (declaredType === undefined) {
        console.warn(`remote_config_unknown_remote_key profile=${profile} key=${key}`);
        continue;
      }
      if (!valueMatchesDeclaredType(declaredType, value)) {
        if (!this.failOpen) {
          throw new RemoteConfigError(
            `Config-store key ${profile}/${key} has remote type ${runtimeKind(value)} ` +
              `but the declared type is ${declaredType}. Fix the stored ` +
              'value, or set failOpen: true to ignore type mismatches.',
          );
        }
        console.warn(
          `remote_config_type_mismatch profile=${profile} key=${key} ` +
            `expected=${declaredType}`,
        );
        continue;
      }
      merged[key] = value;
    }
  }

  private changedKeys(oldCache: Cache, newCache: Cache): string[] {
    const changed: string[] = [];
    for (const [profile, values] of Object.entries(newCache)) {
      const oldValues = oldCache[profile] ?? {};
      for (const [key, value] of Object.entries(values)) {
        if (oldValues[key] !== value) {
          changed.push(`${profile}/${key}`);
        }
      }
    }
    return changed.sort();
  }

  // -- accessors ------------------------------------------------------------

  /**
   * Return the current scalar value for `namespace`/`key`.
   *
   * Throws for unknown namespaces/keys and for keys declared with a secret
   * reference (use `getSecretRef` for those).
   */
  get(namespace: string, key: string): unknown {
    this.rejectSecretRef(namespace, key);
    if (!(PROFILE_NAMES as readonly string[]).includes(namespace)) {
      throw new RemoteConfigError(unknownNamespaceMessage(namespace));
    }
    if (declaredValueType(namespace, key) === undefined) {
      throw new RemoteConfigError(unknownKeyMessage(namespace, key));
    }
    const profile = this.cache[namespace] ?? {};
    if (!(key in profile)) {
      throw new RemoteConfigError(missingValueMessage(namespace, key));
    }
    return profile[key];
  }

  getBool(namespace: string, key: string): boolean {
    const value = this.get(namespace, key);
    if (typeof value !== 'boolean') {
      throw new RemoteConfigError(typeMessage(namespace, key, 'getBool', value));
    }
    return value;
  }

  getInt(namespace: string, key: string): number {
    const value = this.get(namespace, key);
    if (typeof value !== 'number' || !Number.isInteger(value)) {
      throw new RemoteConfigError(typeMessage(namespace, key, 'getInt', value));
    }
    return value;
  }

  getFloat(namespace: string, key: string): number {
    const value = this.get(namespace, key);
    if (typeof value !== 'number') {
      throw new RemoteConfigError(typeMessage(namespace, key, 'getFloat', value));
    }
    return value;
  }

  getString(namespace: string, key: string): string {
    const value = this.get(namespace, key);
    if (typeof value !== 'string') {
      throw new RemoteConfigError(typeMessage(namespace, key, 'getString', value));
    }
    return value;
  }

  /** Return a copy of all current scalar values for `namespace`. */
  getNamespace(namespace: string): Record<string, unknown> {
    const profile = this.cache[namespace];
    if (profile === undefined) {
      throw new RemoteConfigError(unknownNamespaceMessage(namespace));
    }
    return { ...profile };
  }

  /** Return the non-sensitive secret reference for a `secretRef` key. */
  getSecretRef(namespace: string, key: string): SecretRef {
    const refs = SECRET_REFS[namespace];
    if (refs === undefined || !(key in refs)) {
      throw new RemoteConfigError(
        `Config-store key ${namespace}/${key} is not declared with a secretRef. ` +
          'Use get/get* for scalar values; getSecretRef is only valid for ' +
          'secret-reference keys.',
      );
    }
    return refs[key];
  }

  private rejectSecretRef(namespace: string, key: string): void {
    const refs = SECRET_REFS[namespace];
    if (refs !== undefined && key in refs) {
      throw new RemoteConfigError(
        `Config-store key ${namespace}/${key} is declared with a secretRef and ` +
          'carries no scalar value. Use getSecretRef(namespace, key) to obtain ' +
          'its non-sensitive reference metadata.',
      );
    }
  }
}

/** Construct the client from the generated defaults and the selected backend. */
export function buildClient(): RemoteConfigClient {
  const backend: ConfigBackend = new FileConfigBackend();
  return new RemoteConfigClient(backend, loadDefaults(), {
    failOpen: false,
    pollSeconds: 30,
  });
}
