test:
  rdbms:
    engine: postgres
    host: localhost
    port: 5432
    database: shared_aviation_ref
    poolSize: 10
    docker_image: postgres:17-alpine
    volume_path: /var/lib/postgresql/data
    asyncDriver: postgresql+asyncpg
    syncDriver: postgresql+psycopg2
    healthCheckSql: SELECT 1
    defaultUser: postgres
    platform: container
development:
  rdbms:
    engine: postgres
    host: localhost
    port: 5432
    database: shared_aviation_ref
    poolSize: 10
    docker_image: postgres:17-alpine
    volume_path: /var/lib/postgresql/data
    asyncDriver: postgresql+asyncpg
    syncDriver: postgresql+psycopg2
    healthCheckSql: SELECT 1
    defaultUser: postgres
    platform: container
production:
  rdbms:
    engine: postgres
    host: ${DB_HOST}
    port: 5432
    database: shared_aviation_ref
    poolSize: 20
    ssl: true
    docker_image: postgres:17-alpine
    volume_path: /var/lib/postgresql/data
    asyncDriver: postgresql+asyncpg
    syncDriver: postgresql+psycopg2
    healthCheckSql: SELECT 1
    defaultUser: postgres
    platform: rds
