/**
 * Serverless endpoint handler: stripe_webhook.
 * Handles POST /webhooks/stripe.
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */

export async function stripe_webhook(payload: unknown): Promise<void> {
  console.info('stripe_webhook_received');
}
