"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "student_status" AS ENUM (\'active\', \'graduated\', \'suspended\', \'withdrawn\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "students",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "first_name",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "last_name",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(320),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "student_number",
            sa.String(20),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "status",
            sa.Enum('active', 'graduated', 'suspended', 'withdrawn', name='student_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "enrollment_date",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "date_of_birth",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "avatar_url",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "bio",
            sa.String(500),
            nullable=True,
        ),
        sa.Column(
            "phone",
            sa.String(20),
            nullable=True,
        ),
        sa.Column(
            "course_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "completed_course_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "gpa",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
    )
    op.create_index("ix_students_email", "students", ["email"], unique=False)
    op.create_index("ix_students_student_number", "students", ["student_number"], unique=False)
    op.create_index("ix_students_status", "students", ["status"], unique=False)
    op.create_index("ix_students_first_name_last_name_email", "students", ["first_name", "last_name", "email"], unique=False)


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_index("ix_students_first_name_last_name_email", table_name="students")
    op.drop_index("ix_students_status", table_name="students")
    op.drop_index("ix_students_student_number", table_name="students")
    op.drop_index("ix_students_email", table_name="students")
    op.drop_table("students")
