// MemberDtoTests.cs -- generated xUnit.v3 DataAnnotations validation tests.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using System.ComponentModel.DataAnnotations;
using MemberService.Dtos.MemberDb;
using MemberService.Tests.Factories.MemberDb;
using Xunit;

namespace MemberService.Tests.DtoTests.MemberDb;

public sealed class MemberDtoTests
{
    [Fact]
    public void CreateRequest_FromFactoryValues_PassesValidation()
    {
        var entity = MemberFactory.Create();
        var request = new CreateMemberRequest
        {
            FirstName = entity.FirstName,
            LastName = entity.LastName,
            Email = entity.Email,
            MembershipNumber = entity.MembershipNumber,
            MembershipType = entity.MembershipType,
        };

        var context = new ValidationContext(request);
        var results = new List<ValidationResult>();
        var isValid = Validator.TryValidateObject(
            request,
            context,
            results,
            validateAllProperties: true
        );

        Assert.True(isValid, string.Join("; ", results.Select(r => r.ErrorMessage)));
    }

    [Fact]
    public void UpdateRequest_FromFactoryValues_PassesValidation()
    {
        var entity = MemberFactory.Create();
        var request = new UpdateMemberRequest
        {
            FirstName = entity.FirstName,
            LastName = entity.LastName,
            Email = entity.Email,
            MembershipNumber = entity.MembershipNumber,
            MembershipType = entity.MembershipType,
        };

        var context = new ValidationContext(request);
        var results = new List<ValidationResult>();
        var isValid = Validator.TryValidateObject(
            request,
            context,
            results,
            validateAllProperties: true
        );

        Assert.True(isValid, string.Join("; ", results.Select(r => r.ErrorMessage)));
    }
}
