openapi: 3.1.0
info:
  title: social.NotificationService API
  version: 1.0.0
paths:
  /api/v1/notifications/notifications:
    get:
      operationId: list_notifications
      summary: list_notifications
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
    post:
      operationId: create_notification
      summary: create_notification
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
  /api/v1/notifications/notifications/:id:
    get:
      operationId: get_notification
      summary: get_notification
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
    put:
      operationId: update_notification
      summary: update_notification
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
    delete:
      operationId: delete_notification
      summary: delete_notification
      security:
      - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
components:
  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        userId:
          type: string
          format: uuid
        title:
          type: string
          maxLength: 200
        body:
          $ref: '#/components/schemas/Text?'
        read:
          type: boolean
      required:
      - id
      - createdAt
      - updatedAt
      - userId
      - title
      - read
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
