package library_book_service.gateway;

import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.RemoteKeySourceException;
import com.nimbusds.jose.jwk.source.JWKSource;
import com.nimbusds.jose.jwk.source.JWKSourceBuilder;
import com.nimbusds.jose.proc.BadJOSEException;
import com.nimbusds.jose.proc.JWSVerificationKeySelector;
import com.nimbusds.jose.proc.SecurityContext;
import com.nimbusds.jose.util.DefaultResourceRetriever;
import com.nimbusds.jose.util.JSONObjectUtils;
import com.nimbusds.jose.util.Resource;
import com.nimbusds.jwt.JWTClaimsSet;
import com.nimbusds.jwt.JWTParser;
import com.nimbusds.jwt.SignedJWT;
import com.nimbusds.jwt.proc.ConfigurableJWTProcessor;
import com.nimbusds.jwt.proc.DefaultJWTProcessor;
import jakarta.servlet.FilterChain;
import jakarta.servlet.ServletException;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;
import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.text.ParseException;
import java.time.Instant;
import java.util.Date;
import java.util.List;
import java.util.Locale;
import java.util.Set;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Component;
import org.springframework.web.filter.OncePerRequestFilter;

/**
 * Gateway-scoped JWT verification filter for library.BookService.
 *
 * <p>Validates against ONE issuer/audience/algorithm declared directly in {@code
 * GatewayProfileConfig.auth.jwt} -- a separate, simpler surface from the multi-provider JWKS
 * resource server ({@code DatrixJwtDecoder}). On success, publishes a verified {@link
 * GatewayPrincipal} as a request attribute for downstream handlers; on failure, writes an opaque
 * RFC 7807 401 body and stops the chain -- reason codes are logged, never returned to the client.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Component
public class GatewayJwtVerifier extends OncePerRequestFilter {

  private static final Logger LOG = LoggerFactory.getLogger(GatewayJwtVerifier.class);

  /** Request attribute key the verified {@link GatewayPrincipal} is published under. */
  public static final String PRINCIPAL_ATTRIBUTE = "datrix.gateway.principal";

  private static final String SYMMETRIC_ALG_PREFIX = "HS";
  private static final String ALG_NONE = "none";
  private static final String ISSUER = "library";

  /**
   * OIDC discovery document for the declared gateway issuer. The signing keys are resolved from
   * this document's {@code jwks_uri} rather than from a hard-coded JWKS path, because the JWKS
   * location is provider-specific (it is discoverable, never a fixed suffix).
   */
  private static final String OIDC_DISCOVERY_URL = "library/.well-known/openid-configuration";

  /**
   * JWKS HTTP fetch timeouts. {@link JWKSourceBuilder}'s own defaults ({@code
   * DEFAULT_HTTP_CONNECT_TIMEOUT}/{@code DEFAULT_HTTP_READ_TIMEOUT}) are 500ms each -- too tight
   * for a real network round-trip under load, which would incorrectly fail-closed a valid token. 5
   * seconds matches this generator's other external-service connect timeouts (e.g. Consul).
   */
  private static final int JWKS_CONNECT_TIMEOUT_MS = 5000;

  private static final int JWKS_READ_TIMEOUT_MS = 5000;

  /**
   * Resolved on first verification, not at construction: building it requires an OIDC discovery
   * fetch, and a provider that is briefly unreachable must never prevent this service from
   * starting. Only a SUCCESSFUL resolution is cached, so a discovery failure fails the request
   * closed ({@code jwks_refresh_failed}) and is retried on the next one.
   */
  private volatile ConfigurableJWTProcessor<SecurityContext> processor;

  private ConfigurableJWTProcessor<SecurityContext> processor() {
    ConfigurableJWTProcessor<SecurityContext> resolved = this.processor;
    if (resolved != null) {
      return resolved;
    }
    synchronized (this) {
      if (this.processor == null) {
        this.processor = buildProcessor(resolveJwksUri());
      }
      return this.processor;
    }
  }

  private static ConfigurableJWTProcessor<SecurityContext> buildProcessor(URL jwksUri) {
    JWKSource<SecurityContext> jwkSource =
        JWKSourceBuilder.create(
                jwksUri,
                new DefaultResourceRetriever(JWKS_CONNECT_TIMEOUT_MS, JWKS_READ_TIMEOUT_MS))
            .build();
    JWSAlgorithm algorithm = JWSAlgorithm.parse("RS256");
    ConfigurableJWTProcessor<SecurityContext> proc = new DefaultJWTProcessor<>();
    proc.setJWSKeySelector(new JWSVerificationKeySelector<>(Set.of(algorithm), jwkSource));
    proc.setJWTClaimsSetVerifier((claims, context) -> {});
    return proc;
  }

  /**
   * Fetch the issuer's OIDC discovery document and return its {@code jwks_uri}. Fail-closed: any
   * fetch/parse failure, or a document with no usable {@code jwks_uri}, raises {@code
   * jwks_refresh_failed} rather than accepting the token.
   */
  private static URL resolveJwksUri() {
    try {
      Resource document =
          new DefaultResourceRetriever(JWKS_CONNECT_TIMEOUT_MS, JWKS_READ_TIMEOUT_MS)
              .retrieveResource(toUrl(OIDC_DISCOVERY_URL));
      String jwksUri =
          JSONObjectUtils.getString(JSONObjectUtils.parse(document.getContent()), "jwks_uri");
      if (jwksUri == null || jwksUri.isBlank()) {
        throw new JwtVerificationException(
            "jwks_refresh_failed",
            "OIDC discovery document at " + OIDC_DISCOVERY_URL + " declares no 'jwks_uri'.");
      }
      return toUrl(jwksUri);
    } catch (IOException | ParseException ex) {
      throw new JwtVerificationException(
          "jwks_refresh_failed",
          "OIDC discovery failed for " + OIDC_DISCOVERY_URL + ": " + ex.getMessage());
    }
  }

  private static URL toUrl(String uri) {
    try {
      return URI.create(uri).toURL();
    } catch (Exception ex) {
      throw new IllegalStateException(
          "Malformed gateway JWKS URI '" + uri + "': " + ex.getMessage(), ex);
    }
  }

  @Override
  protected boolean shouldNotFilter(HttpServletRequest request) {
    String path = request.getRequestURI();
    String method = request.getMethod();
    if (pathMatches(path, "/health")) {
      return true;
    }
    if (pathMatches(path, "/actuator/**")) {
      return true;
    }
    if (pathMatches(path, "/v3/api-docs/**")) {
      return true;
    }
    if (pathMatches(path, "/swagger-ui/**")) {
      return true;
    }
    if (pathMatches(path, "/swagger-ui.html")) {
      return true;
    }
    return false;
  }

  /**
   * Matches a concrete request path against a possibly-{@code {param}}/{@code **}-suffixed pattern.
   */
  private static boolean pathMatches(String actual, String pattern) {
    if (pattern.endsWith("/**")) {
      String prefix = pattern.substring(0, pattern.length() - 3);
      return actual.equals(prefix) || actual.startsWith(prefix + "/");
    }
    if (!pattern.contains("{")) {
      return actual.equals(pattern);
    }
    String regex = pattern.replaceAll("\\{[^/]+\\}", "[^/]+");
    return actual.matches(regex);
  }

  @Override
  protected void doFilterInternal(
      HttpServletRequest request, HttpServletResponse response, FilterChain chain)
      throws ServletException, IOException {
    String authHeader = request.getHeader("Authorization");
    if (authHeader == null || !authHeader.startsWith("Bearer ")) {
      LOG.warn(
          "gateway_jwt_auth_failed path={} reason_code={}",
          request.getRequestURI(),
          "missing_token");
      writeUnauthorized(response, request.getRequestURI());
      return;
    }
    String token = authHeader.substring("Bearer ".length()).trim();
    GatewayPrincipal principal;
    try {
      principal = verify(token);
    } catch (JwtVerificationException ex) {
      LOG.warn(
          "gateway_jwt_auth_failed path={} reason_code={}",
          request.getRequestURI(),
          ex.reasonCode());
      writeUnauthorized(response, request.getRequestURI());
      return;
    }
    request.setAttribute(PRINCIPAL_ATTRIBUTE, principal);
    chain.doFilter(request, response);
  }

  private GatewayPrincipal verify(String token) {
    SignedJWT signedJwt;
    try {
      com.nimbusds.jwt.JWT parsed = JWTParser.parse(token);
      if (!(parsed instanceof SignedJWT sj)) {
        throw new JwtVerificationException("bad_signature", "Rejected token: not a signed JWT.");
      }
      signedJwt = sj;
    } catch (ParseException ex) {
      throw new JwtVerificationException(
          "malformed_token", "Token could not be decoded: " + ex.getMessage());
    }
    String tokenAlg = signedJwt.getHeader().getAlgorithm().getName();
    assertAsymmetricAlgorithm(tokenAlg);

    JWTClaimsSet claims;
    try {
      claims = processor().process(token, null);
    } catch (ParseException | BadJOSEException | com.nimbusds.jose.JOSEException ex) {
      if (isJwksFetchFailure(ex)) {
        throw new JwtVerificationException(
            "jwks_refresh_failed", "JWKS refresh failed: " + ex.getMessage());
      }
      throw new JwtVerificationException(
          "bad_signature", "Token signature is invalid: " + ex.getMessage());
    }

    Date expiresAt = claims.getExpirationTime();
    if (expiresAt == null || expiresAt.toInstant().isBefore(Instant.now())) {
      throw new JwtVerificationException("expired_token", "Token has expired.");
    }
    String tokenIssuer = claims.getIssuer();
    if (tokenIssuer == null || !tokenIssuer.equals(ISSUER)) {
      throw new JwtVerificationException(
          "issuer_mismatch", "Token issuer does not match the configured gateway issuer.");
    }
    return new GatewayPrincipal(claims.getSubject(), extractRoles(claims), token);
  }

  private static List<String> extractRoles(JWTClaimsSet claims) {
    try {
      Object raw = claims.getClaim("roles");
      if (raw instanceof List<?> list) {
        return list.stream().map(String::valueOf).toList();
      }
    } catch (Exception ex) {
      LOG.debug("gateway_jwt_roles_unreadable reason={}", ex.getMessage());
    }
    return List.of();
  }

  private static void assertAsymmetricAlgorithm(String alg) {
    if (alg == null || alg.equalsIgnoreCase(ALG_NONE) || alg.startsWith(SYMMETRIC_ALG_PREFIX)) {
      throw new JwtVerificationException(
          "bad_signature",
          "Rejected algorithm '"
              + alg
              + "': symmetric algorithms (HS*) and 'none' are not permitted. "
              + "Use an asymmetric algorithm (RS*, ES*, PS*).");
    }
  }

  private static boolean isJwksFetchFailure(Throwable ex) {
    for (Throwable cause = ex; cause != null; cause = cause.getCause()) {
      if (cause instanceof RemoteKeySourceException) {
        return true;
      }
      String message = cause.getMessage();
      if (message != null && message.toLowerCase(Locale.ROOT).contains("jwk set")) {
        return true;
      }
    }
    return false;
  }

  private void writeUnauthorized(HttpServletResponse response, String path) throws IOException {
    response.setStatus(HttpStatus.UNAUTHORIZED.value());
    response.setContentType(MediaType.APPLICATION_PROBLEM_JSON_VALUE);
    response
        .getWriter()
        .write(
            "{\"type\":\"urn:datrix:error:unauthorized\",\"title\":\"Unauthorized\",\"instance\":\""
                + path
                + "\"}");
  }

  /**
   * Raised when gateway-scoped JWT validation fails. Reason codes are logged only -- never
   * client-visible.
   */
  static class JwtVerificationException extends RuntimeException {
    private final String reasonCode;

    JwtVerificationException(String reasonCode, String message) {
      super(message);
      this.reasonCode = reasonCode;
    }

    String reasonCode() {
      return this.reasonCode;
    }
  }
}
