// BookStatusTests.cs -- generated xUnit.v3 enum member-set/value tests.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using BookService.Enums;
using Xunit;

namespace BookService.Tests.EnumTests;

public sealed class BookStatusTests
{
    [Fact]
    public void MemberCount_MatchesDeclaredValues()
    {
        var members = Enum.GetValues<BookStatus>();

        Assert.Equal(4, members.Length);
    }

    [Fact]
    public void MemberSet_ContainsAvailable()
    {
        var members = Enum.GetValues<BookStatus>();

        Assert.Contains(BookStatus.Available, members);
    }

    [Fact]
    public void MemberSet_ContainsCheckedOut()
    {
        var members = Enum.GetValues<BookStatus>();

        Assert.Contains(BookStatus.CheckedOut, members);
    }

    [Fact]
    public void MemberSet_ContainsReserved()
    {
        var members = Enum.GetValues<BookStatus>();

        Assert.Contains(BookStatus.Reserved, members);
    }

    [Fact]
    public void MemberSet_ContainsMaintenance()
    {
        var members = Enum.GetValues<BookStatus>();

        Assert.Contains(BookStatus.Maintenance, members);
    }
}
