// UserRoleTests.cs -- generated xUnit.v3 enum member-set/value tests.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using BookService.Enums;
using Xunit;

namespace BookService.Tests.EnumTests;

public sealed class UserRoleTests
{
    [Fact]
    public void MemberCount_MatchesDeclaredValues()
    {
        var members = Enum.GetValues<UserRole>();

        Assert.Equal(3, members.Length);
    }

    [Fact]
    public void MemberSet_ContainsMember()
    {
        var members = Enum.GetValues<UserRole>();

        Assert.Contains(UserRole.Member, members);
    }

    [Fact]
    public void MemberSet_ContainsLibrarian()
    {
        var members = Enum.GetValues<UserRole>();

        Assert.Contains(UserRole.Librarian, members);
    }

    [Fact]
    public void MemberSet_ContainsAdmin()
    {
        var members = Enum.GetValues<UserRole>();

        Assert.Contains(UserRole.Admin, members);
    }
}
