// <auto-generated>
// Generated by datrix-codegen-dotnet. Do not edit by hand.
// </auto-generated>
#nullable enable

namespace MemberService.Errors;

/// <summary>Framework builtin domain exception (HTTP 422).</summary>
public sealed class ValidationException : Exception
{
    public int Status => 422;
    public object? Detail { get; }

    public ValidationException(object? detail = null)
        : base(detail?.ToString() ?? "ValidationException.")
    {
        Detail = detail;
    }
}

/// <summary>Framework builtin domain exception (HTTP 401).</summary>
public sealed class AuthenticationException : Exception
{
    public int Status => 401;
    public object? Detail { get; }

    public AuthenticationException(object? detail = null)
        : base(detail?.ToString() ?? "AuthenticationException.")
    {
        Detail = detail;
    }
}

/// <summary>Framework builtin domain exception (HTTP 403).</summary>
public sealed class AuthorizationException : Exception
{
    public int Status => 403;
    public object? Detail { get; }

    public AuthorizationException(object? detail = null)
        : base(detail?.ToString() ?? "AuthorizationException.")
    {
        Detail = detail;
    }
}

