package library_member_service.security;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * Resolves a logical secret handle (e.g. {@code trusted_caller_secret}, {@code
 * stripe_webhook_secret}) to its value through the deployment-configured backend ({@code
 * docker-secret}), baked at generation time from {@code SecretBackendPolicy}.
 *
 * <p>Fail-closed (design principle 15): {@link #getSecret(String)} never returns {@code null}/blank
 * and never falls back to an unauthenticated client -- a missing or unresolvable secret THROWS
 * {@link SecretResolutionException} before any client construction. Resolved values are cached for
 * the process lifetime (never logged, never included in an exception message).
 *
 * <p>{@code @Component}-managed -- {@code TrustedCallerFilter} and every webhook controller
 * constructor-inject this class.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Component
public class SecretsResolver {

  private static final Logger LOG = LoggerFactory.getLogger(SecretsResolver.class);
  private static final String BACKEND = "docker-secret";

  // Handle -> backend-specific rendered name, baked at generation time from the
  // reconciled SecretReferenceManifest. Never derived at runtime.
  private static final Map<String, String> RENDERED_NAMES =
      Map.ofEntries(
          Map.entry("member_db_password", "member_db_password"),
          Map.entry("trusted_caller_secret", "trusted_caller_secret"));

  // In-process cache: handle -> resolved value. Cached for the process lifetime
  // (never a resolved value in a log statement or exception message).
  private final ConcurrentHashMap<String, String> cache = new ConcurrentHashMap<>();

  private static final String SECRETS_DIR_PATH = "/run/secrets";

  /**
   * Read {@code renderedName} from the mounted secrets directory ({@link #SECRETS_DIR_PATH}). File
   * read only -- no environment variables are consulted.
   *
   * @return the file's contents (trimmed), or {@code null} when the file is absent.
   */
  private String fetchFromBackend(String renderedName) {
    Path secretPath = Path.of(SECRETS_DIR_PATH, renderedName);
    try {
      return Files.readString(secretPath).strip();
    } catch (IOException e) {
      return null;
    }
  }

  /**
   * Resolve {@code handle} to its value, caching the result for the process lifetime.
   *
   * @param handle logical secret handle (lower_snake_case), declared in the generated secrets
   *     manifest.
   * @return the resolved secret value. Never {@code null}, never blank.
   * @throws SecretResolutionException when {@code handle} is not declared in the generated
   *     manifest, or the backend has no value for it. The exception message names the handle only.
   */
  public String getSecret(String handle) {
    String cached = cache.get(handle);
    if (cached != null) {
      return cached;
    }
    String renderedName = RENDERED_NAMES.get(handle);
    if (renderedName == null) {
      LOG.error("secret_resolution_failed reason=handle_not_declared handle={}", handle);
      throw new SecretResolutionException(handle, "not declared in the generated secrets manifest");
    }
    String value = fetchFromBackend(renderedName);
    if (value == null || value.isBlank()) {
      LOG.error(
          "secret_resolution_failed reason=not_found_in_backend backend={} handle={}",
          BACKEND,
          handle);
      throw new SecretResolutionException(handle, "not found in backend '" + BACKEND + "'");
    }
    cache.put(handle, value);
    LOG.info("secret_resolved backend={} handle={}", BACKEND, handle);
    return value;
  }

  /**
   * Fail-closed secret-resolution failure (design principle 15): thrown before any client
   * construction or comparison. The message carries the logical HANDLE only -- never a resolved
   * value.
   */
  public static final class SecretResolutionException extends RuntimeException {
    public SecretResolutionException(String handle, String reason) {
      super("Secret handle '" + handle + "' could not be resolved: " + reason + ".");
    }
  }
}
