#!/usr/bin/env bash
# library-book-service development scripts
# Auto-generated by datrix-codegen-dotnet. Do not edit manually.

set -e

case "$1" in
    restore)
        dotnet restore
        ;;
    build)
        dotnet build --nologo
        ;;
    run)
        dotnet run --project "src/BookService"
        ;;
    test)
        dotnet test --nologo "${@:2}"
        ;;
    format)
        dotnet format
        ;;
    db-migrate-book-db)
        dotnet run --project "src/BookService" -- --datrix-run migrate:book-db
        ;;
    docker-build)
        docker build -t library-book-service:latest .
        ;;
    docker-run)
        docker run -p 8080:8080 library-book-service:latest
        ;;
    clean)
        dotnet clean
        find . -type d \( -name bin -o -name obj \) -prune -exec rm -rf {} +
        ;;
    help|*)
        echo "Usage: ./scripts.sh <command>"
        echo "Commands: restore build run test format db-migrate-book-db docker-build docker-run clean"
        ;;
esac
