package warehouse_warehouse_service.model.warehouse_db;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import java.util.Set;
import org.hibernate.validator.HibernateValidator;
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator;
import org.junit.jupiter.api.Test;
import warehouse_warehouse_service.dto.warehouse_db.DeliveryZoneCreateRequest;

/**
 * Generated tests for DeliveryZone: field round-trip, update-assertion, relationship navigation,
 * and (when the entity's CreateRequest DTO carries at least one @NotNull field) Bean Validation
 * constraint-violation tests.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class DeliveryZoneTest {

  @Test
  void fieldRoundTripAssignsAndReturnsSameValue() {
    DeliveryZone instance = DeliveryZoneTestFactory.create();
    instance.setName("test_value");
    assertEquals("test_value", instance.getName());
    instance.setZoneCode("test_value");
    assertEquals("test_value", instance.getZoneCode());
    instance.setCoverageArea(
        new org.locationtech.jts.geom.GeometryFactory()
            .createPoint(new org.locationtech.jts.geom.Coordinate(0, 0)));
    assertEquals(
        new org.locationtech.jts.geom.GeometryFactory()
            .createPoint(new org.locationtech.jts.geom.Coordinate(0, 0)),
        instance.getCoverageArea());
    instance.setRadiusNm(1.0);
    assertEquals(1.0, instance.getRadiusNm());
  }

  @Test
  void fieldUpdateAssignsDistinctValue() {
    DeliveryZone instance = DeliveryZoneTestFactory.create();
    instance.setName("test_value");
    instance.setZoneCode("test_value");
    instance.setCoverageArea(
        new org.locationtech.jts.geom.GeometryFactory()
            .createPoint(new org.locationtech.jts.geom.Coordinate(0, 0)));
    instance.setRadiusNm(1.0);
    instance.setName("alt_value");
    assertEquals("alt_value", instance.getName());
    instance.setZoneCode("alt_value");
    assertEquals("alt_value", instance.getZoneCode());
    instance.setCoverageArea(
        new org.locationtech.jts.geom.GeometryFactory()
            .createPoint(new org.locationtech.jts.geom.Coordinate(1, 1)));
    assertEquals(
        new org.locationtech.jts.geom.GeometryFactory()
            .createPoint(new org.locationtech.jts.geom.Coordinate(1, 1)),
        instance.getCoverageArea());
    instance.setRadiusNm(2.0);
    assertEquals(2.0, instance.getRadiusNm());
  }

  private static Validator buildValidator() {
    return Validation.byProvider(HibernateValidator.class)
        .configure()
        .messageInterpolator(new ParameterMessageInterpolator())
        .buildValidatorFactory()
        .getValidator();
  }

  @Test
  void requiredFieldLeftNullFailsBeanValidation() {
    Validator validator = buildValidator();
    DeliveryZoneCreateRequest invalid =
        new DeliveryZoneCreateRequest(
            null,
            "test_value",
            new org.locationtech.jts.geom.GeometryFactory()
                .createPoint(new org.locationtech.jts.geom.Coordinate(0, 0)),
            1.0);
    Set<ConstraintViolation<DeliveryZoneCreateRequest>> violations = validator.validate(invalid);
    assertFalse(violations.isEmpty(), "expected a violation for a null required field");
  }

  @Test
  void allRequiredFieldsPresentPassesBeanValidation() {
    Validator validator = buildValidator();
    DeliveryZoneCreateRequest valid =
        new DeliveryZoneCreateRequest(
            "test_value",
            "test_value",
            new org.locationtech.jts.geom.GeometryFactory()
                .createPoint(new org.locationtech.jts.geom.Coordinate(0, 0)),
            1.0);
    Set<ConstraintViolation<DeliveryZoneCreateRequest>> violations = validator.validate(valid);
    assertTrue(violations.isEmpty(), "expected no violations, got: " + violations);
  }
}
