package library_member_service.dto.member_db;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;

/**
 * Member create-request DTO.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record MemberCreateRequest(
    @NotNull @Size(max = 100) String name,
    @NotNull @Email String email,
    String emailVerificationToken) {}
