/**
 * Serverless job handler: WeeklyDataPull.
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */

export async function weekly_data_pull(): Promise<void> {
  console.info('weekly_data_pull_started');
}
