test:
  jobs:
    ReleaseExpiredReservations:
      schedule: '* * * * *'
      retry: { maxAttempts: 1, backoff: fixed }
      timeout: 30s
    UpdatePopularProducts:
      schedule: '0 * * * *'
      retry: { maxAttempts: 1, backoff: fixed }
      timeout: 30s

development:
  jobs:
    ReleaseExpiredReservations:
      schedule: '* * * * *'
      retry: { maxAttempts: 1, backoff: fixed }
      timeout: 30s
    UpdatePopularProducts:
      schedule: '0 * * * *'
      retry: { maxAttempts: 1, backoff: fixed }
      timeout: 30s

production:
  jobs:
    ReleaseExpiredReservations:
      schedule: '* * * * *'
      retry: { maxAttempts: 3, backoff: exponential }
      timeout: 2m
    UpdatePopularProducts:
      schedule: '0 * * * *'
      retry: { maxAttempts: 3, backoff: exponential }
      timeout: 5m
