package warehouse_warehouse_service.schemas;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

/**
 * Generated tests for Pagination: canonical-constructor round-trip and (when applicable)
 * computed-accessor assertions.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class PaginationTest {

  @Test
  void canonicalConstructorRoundTripsEveryComponent() {
    Pagination instance = new Pagination(1, 1);
    assertEquals(1, instance.page());
    assertEquals(1, instance.perPage());
  }

  @Test
  void computedAccessorOffsetIsAccessible() {
    Pagination instance = new Pagination(1, 1);
    assertNotNull(instance.offset());
  }
}
