test:
  email:
    provider: sendgrid
    fromEmail: noreply@library.example.com
    fromName: Library Book Service
    templates:
      bookAvailable: d-book-available
      overdueNotice: d-overdue-notice

development:
  email:
    provider: sendgrid
    fromEmail: noreply@library.example.com
    fromName: Library Book Service
    templates:
      bookAvailable: d-book-available
      overdueNotice: d-overdue-notice

production:
  email:
    provider: sendgrid
    fromEmail: ${BOOK_SERVICE_FROM_EMAIL}
    fromName: Library Book Service
    templates:
      bookAvailable: ${BOOK_AVAILABLE_TEMPLATE_ID}
      overdueNotice: ${OVERDUE_NOTICE_TEMPLATE_ID}
