# Run Tests -- PowerShell wrapper for unit and deploy test projects.
# Auto-generated by datrix-codegen-dotnet. Do not edit manually.
#
# Usage:
#   ./tests/run-tests.ps1            # Run both unit and deploy tests
#   ./tests/run-tests.ps1 -Unit      # Run unit tests only
#   ./tests/run-tests.ps1 -Deploy    # Run deploy tests only

param(
    [switch]$Unit,
    [switch]$Deploy
)

$ErrorActionPreference = "Stop"

$runUnit = -not $Deploy -or $Unit
$runDeploy = -not $Unit -or $Deploy

if ($runUnit) {
    Write-Host "Running unit tests..." -ForegroundColor Cyan
    $unitExit = 0
    Push-Location library_book_service/tests/BookService.Tests
    try {
        dotnet test
        if ($LASTEXITCODE -ne 0) { $unitExit = $LASTEXITCODE }
    } finally {
        Pop-Location
    }
    Push-Location library_member_service/tests/MemberService.Tests
    try {
        dotnet test
        if ($LASTEXITCODE -ne 0) { $unitExit = $LASTEXITCODE }
    } finally {
        Pop-Location
    }
    Push-Location library_loan_service/tests/LoanService.Tests
    try {
        dotnet test
        if ($LASTEXITCODE -ne 0) { $unitExit = $LASTEXITCODE }
    } finally {
        Pop-Location
    }
    if ($unitExit -ne 0) { exit $unitExit }
}

if ($runDeploy) {
    Write-Host "Running deploy tests..." -ForegroundColor Cyan
    Write-Host "Starting compose stack (build + up, waiting for healthy)..." -ForegroundColor Cyan
    docker compose up -d --build --wait --wait-timeout 300
    if ($LASTEXITCODE -ne 0) { exit $LASTEXITCODE }
    $deployExit = 0
    try {
        # Resolve each reachable service's REAL host-published port.
        $hostPort = (docker compose port library-book-service 8000 2>$null) -replace '^.*:', ''
        if ($hostPort) { $env:BOOK_SERVICE_BASE_URL = "http://localhost:$hostPort" }
        $hostPort = (docker compose port library-member-service 8002 2>$null) -replace '^.*:', ''
        if ($hostPort) { $env:MEMBER_SERVICE_BASE_URL = "http://localhost:$hostPort" }
        $hostPort = (docker compose port library-loan-service 8001 2>$null) -replace '^.*:', ''
        if ($hostPort) { $env:LOAN_SERVICE_BASE_URL = "http://localhost:$hostPort" }
        Push-Location tests/DeployTests
        try {
            dotnet test
            $deployExit = $LASTEXITCODE
        } finally {
            Pop-Location
        }
    } finally {
        Write-Host "Stopping compose stack..." -ForegroundColor Cyan
        docker compose down -v --remove-orphans
    }
    if ($deployExit -ne 0) { exit $deployExit }
}
