package library_member_service.security;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.nimbusds.jose.JOSEException;
import com.nimbusds.jose.JWSAlgorithm;
import com.nimbusds.jose.RemoteKeySourceException;
import com.nimbusds.jose.jwk.source.JWKSource;
import com.nimbusds.jose.jwk.source.JWKSourceBuilder;
import com.nimbusds.jose.proc.BadJOSEException;
import com.nimbusds.jose.proc.JWSVerificationKeySelector;
import com.nimbusds.jose.proc.SecurityContext;
import com.nimbusds.jose.util.DefaultResourceRetriever;
import com.nimbusds.jwt.JWTClaimsSet;
import com.nimbusds.jwt.JWTParser;
import com.nimbusds.jwt.SignedJWT;
import com.nimbusds.jwt.proc.ConfigurableJWTProcessor;
import com.nimbusds.jwt.proc.DefaultJWTProcessor;
import java.io.IOException;
import java.io.InputStream;
import java.net.URI;
import java.text.ParseException;
import java.time.Instant;
import java.util.AbstractMap;
import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ClassPathResource;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtDecoder;
import org.springframework.security.oauth2.jwt.JwtException;
import org.springframework.stereotype.Component;

/**
 * Multi-provider JWKS-based {@link JwtDecoder} for library.MemberService.
 *
 * <p>Mirrors the verification semantics of datrix-codegen-python's {@code
 * identity.py.j2::validate_token_claims}: asymmetric-only algorithms (symmetric HS* and {@code alg:
 * none} are REJECTED before any signature verification is attempted), audience-enforced,
 * fail-closed JWKS refresh (a JWKS fetch/parse failure never silently accepts a token), and
 * issuer+audience provider disambiguation for multiple providers that share one issuer (D9).
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Component
public class DatrixJwtDecoder implements JwtDecoder {

  private static final Logger LOG = LoggerFactory.getLogger(DatrixJwtDecoder.class);

  /** Classpath resource path for the bundled plan artifact. */
  private static final String PLAN_RESOURCE_PATH = "config/identity-provider-plan.json";

  /**
   * JWKS HTTP fetch timeouts. {@link JWKSourceBuilder}'s own defaults ({@code
   * DEFAULT_HTTP_CONNECT_TIMEOUT}/{@code DEFAULT_HTTP_READ_TIMEOUT}) are 500ms each -- too tight
   * for a real network round-trip under load (cold JIT, GC pause, a momentarily slow-but-healthy
   * identity provider), which would incorrectly fail-closed a valid token with {@code
   * JWKS_REFRESH_FAILED}. 5 seconds matches this generator's other external-service connect
   * timeouts (e.g. Consul).
   */
  private static final int JWKS_CONNECT_TIMEOUT_MS = 5000;

  private static final int JWKS_READ_TIMEOUT_MS = 5000;

  /** Symmetric JWS algorithm prefixes -- always REJECTED (asymmetric-only). */
  private static final String SYMMETRIC_ALG_PREFIX = "HS";

  private static final String ALG_NONE = "none";

  private final Map<String, Object> providers;

  /**
   * Effective audience allow-list per provider name: the provider's static {@code allowedAudiences}
   * UNION the resolved values of every environment variable named in its {@code
   * allowedAudienceRefs}. Resolved ONCE at construction (see {@link
   * #resolveEffectiveAudiences(Map)}) so that a missing deploy-time value fails the bean -- and
   * therefore application startup -- rather than surfacing per-request on whichever token happens
   * to arrive first.
   */
  private final Map<String, List<String>> effectiveAudiences;

  private final Map<String, ConfigurableJWTProcessor<SecurityContext>> processors =
      new ConcurrentHashMap<>();

  public DatrixJwtDecoder() {
    this.providers = loadProviderPlanProviders();
    this.effectiveAudiences = resolveEffectiveAudiences(this.providers);
  }

  /**
   * Load and cache the {@code providers} map from the bundled identity provider plan (classpath
   * resource -- CWD-independent on any deployment target, the Java equivalent of python's
   * module-relative resolution).
   */
  @SuppressWarnings("unchecked")
  private static Map<String, Object> loadProviderPlanProviders() {
    ClassPathResource resource = new ClassPathResource(PLAN_RESOURCE_PATH);
    if (!resource.exists()) {
      throw new IllegalStateException(
          "Identity provider plan not found on the classpath at '"
              + PLAN_RESOURCE_PATH
              + "'. The plan must be bundled at src/main/resources/config/"
              + "identity-provider-plan.json (wheel-deployed targets) or mounted at a "
              + "baked path (LOCAL). Regenerate the service.");
    }
    try (InputStream in = resource.getInputStream()) {
      ObjectMapper mapper = new ObjectMapper();
      JsonNode root = mapper.readTree(in);
      JsonNode providersNode = root.get("providers");
      Map<String, Object> result = new LinkedHashMap<>();
      if (providersNode != null) {
        Iterator<String> names = providersNode.fieldNames();
        while (names.hasNext()) {
          String name = names.next();
          result.put(name, mapper.convertValue(providersNode.get(name), Map.class));
        }
      }
      LOG.debug("identity_plan_loaded providers={}", result.keySet());
      return result;
    } catch (IOException ex) {
      throw new IllegalStateException(
          "Identity provider plan at '"
              + PLAN_RESOURCE_PATH
              + "' could not be read: "
              + ex.getMessage(),
          ex);
    }
  }

  /**
   * Resolve the effective audience allow-list for every provider in the plan.
   *
   * <p>Effective audiences are {@code allowedAudiences} UNION the value of {@code
   * System.getenv(name)} for every name in {@code allowedAudienceRefs} (plan schema v2). A ref
   * exists because the accepted {@code aud} is assigned by the identity provider at provisioning
   * time and cannot be baked into a static plan -- the Entra v2 access-token case, whose {@code
   * aud} is the app registration's client-ID GUID assigned by Microsoft Graph at deploy time.
   *
   * <p><b>Fail-closed:</b> a declared ref whose environment variable is unset or blank raises,
   * naming both the provider and the variable. It must NEVER degrade to an empty allow-list, which
   * every audience check in this class reads as "no audience constraint" -- i.e. accept a token
   * minted for ANY audience. Failing construction is precisely what prevents that silent downgrade.
   */
  @SuppressWarnings("unchecked")
  private static Map<String, List<String>> resolveEffectiveAudiences(
      Map<String, Object> providers) {
    Map<String, List<String>> resolved = new LinkedHashMap<>();
    for (Map.Entry<String, Object> entry : providers.entrySet()) {
      String providerName = entry.getKey();
      Map<String, Object> provider = (Map<String, Object>) entry.getValue();
      List<String> audiences = new ArrayList<>(stringList(provider.get("allowedAudiences")));
      for (String envVarName : stringList(provider.get("allowedAudienceRefs"))) {
        String value = System.getenv(envVarName);
        if (value == null || value.isBlank()) {
          throw new IllegalStateException(
              "Identity provider '"
                  + providerName
                  + "' declares the late-bound audience "
                  + "reference '"
                  + envVarName
                  + "' in 'allowedAudienceRefs', but that "
                  + "environment variable is unset or empty. The audience cannot be "
                  + "resolved, and an unresolved reference must never be treated as "
                  + "'no audience constraint' (fail-closed). Fix: ensure the deployment "
                  + "platform delivers '"
                  + envVarName
                  + "' as an application setting "
                  + "carrying the provider's deploy-time-assigned audience.");
        }
        if (!audiences.contains(value)) {
          audiences.add(value);
        }
      }
      LOG.debug(
          "identity_effective_audiences provider={} count={}", providerName, audiences.size());
      resolved.put(providerName, audiences);
    }
    return resolved;
  }

  /**
   * Effective audience allow-list for *providerName* (never null -- every plan provider is resolved
   * at construction).
   */
  private List<String> effectiveAudiencesFor(String providerName) {
    List<String> audiences = this.effectiveAudiences.get(providerName);
    return audiences == null ? List.of() : audiences;
  }

  /** Raise when {@code alg} is symmetric or {@code none} (asymmetric-only guard). */
  private static void assertAsymmetricAlgorithm(String alg, String providerName) {
    if (alg == null || alg.equalsIgnoreCase(ALG_NONE) || alg.startsWith(SYMMETRIC_ALG_PREFIX)) {
      throw new JwksValidationException(
          AuthReasonCode.BAD_SIGNATURE,
          "Rejected algorithm '"
              + alg
              + "' for provider '"
              + providerName
              + "': symmetric algorithms (HS*) and 'none' are not permitted. "
              + "Use an asymmetric algorithm (RS*, ES*, PS*).");
    }
  }

  @SuppressWarnings("unchecked")
  private static Set<String> tokenAudiences(JWTClaimsSet claims) {
    Set<String> result = new HashSet<>();
    try {
      List<String> aud = claims.getAudience();
      if (aud != null) {
        result.addAll(aud);
      }
    } catch (Exception ex) {
      LOG.debug("identity_token_audience_unreadable reason={}", ex.getMessage());
    }
    return result;
  }

  @SuppressWarnings("unchecked")
  private static List<String> stringList(Object raw) {
    List<String> result = new ArrayList<>();
    if (raw instanceof List<?> list) {
      for (Object item : list) {
        result.add(String.valueOf(item));
      }
    }
    return result;
  }

  /**
   * Select the provider plan entry matching the token's issuer and audience -- the SAME 5-step
   * algorithm as python's {@code _select_provider} (identity.py.j2:399-449): (1) gather every
   * provider whose issuer matches, (2) a single match wins outright, (3) prefer one whose EFFECTIVE
   * audiences intersect the token audience, (4) else prefer one with no audience constraint, (5)
   * else fall back to the first issuer match so validation still fails closed with a deterministic
   * audience_mismatch.
   *
   * <p>Steps (3) and (4) read the EFFECTIVE audiences (static UNION resolved refs), never the raw
   * {@code allowedAudiences}. A late-bound provider carries an empty static list, so reading the
   * raw field would misclassify it at step (4) as "no audience constraint" and select it as the
   * catch-all -- the exact silent downgrade plan schema v2 exists to prevent.
   */
  @SuppressWarnings("unchecked")
  private Map.Entry<String, Map<String, Object>> selectProvider(
      String tokenIssuer, Set<String> tokenAudiences) {
    List<Map.Entry<String, Map<String, Object>>> issuerMatches = new ArrayList<>();
    for (Map.Entry<String, Object> entry : this.providers.entrySet()) {
      Map<String, Object> provider = (Map<String, Object>) entry.getValue();
      Object issuer = provider.get("issuer");
      if (issuer != null && issuer.equals(tokenIssuer)) {
        issuerMatches.add(new AbstractMap.SimpleEntry<>(entry.getKey(), provider));
      }
    }
    if (issuerMatches.isEmpty()) {
      return null;
    }
    if (issuerMatches.size() == 1) {
      return issuerMatches.get(0);
    }
    for (Map.Entry<String, Map<String, Object>> candidate : issuerMatches) {
      Set<String> allowed = new HashSet<>(effectiveAudiencesFor(candidate.getKey()));
      allowed.retainAll(tokenAudiences);
      if (!allowed.isEmpty()) {
        return candidate;
      }
    }
    for (Map.Entry<String, Map<String, Object>> candidate : issuerMatches) {
      if (effectiveAudiencesFor(candidate.getKey()).isEmpty()) {
        return candidate;
      }
    }
    return issuerMatches.get(0);
  }

  /** Return the logical provider name owning *claims* (post-verification attribution). */
  public String resolveProviderName(JWTClaimsSet claims) {
    String issuer = claims.getIssuer() == null ? "" : claims.getIssuer();
    Map.Entry<String, Map<String, Object>> selection =
        selectProvider(issuer, tokenAudiences(claims));
    return selection == null ? null : selection.getKey();
  }

  /**
   * Cached {@link ConfigurableJWTProcessor} for *providerName* (signature-only -- no claim-set
   * verifier is installed, so exp/iss/aud are checked manually in {@link #decode(String)},
   * mirroring python's manual jwt.decode(...) claim checks precisely). Keyed by provider name + its
   * allowed-algorithm set so a (hypothetical) plan reload with a widened allow-list never reuses a
   * stale, narrower key selector.
   */
  private ConfigurableJWTProcessor<SecurityContext> processorFor(
      String providerName, String jwksUri, List<String> allowedAlgorithms) {
    String cacheKey = providerName + "|" + String.join(",", allowedAlgorithms);
    return this.processors.computeIfAbsent(
        cacheKey,
        key -> {
          JWKSource<SecurityContext> jwkSource =
              JWKSourceBuilder.create(
                      toUrl(jwksUri),
                      new DefaultResourceRetriever(JWKS_CONNECT_TIMEOUT_MS, JWKS_READ_TIMEOUT_MS))
                  .build();
          Set<JWSAlgorithm> algorithms = new HashSet<>();
          for (String alg : allowedAlgorithms) {
            algorithms.add(JWSAlgorithm.parse(alg));
          }
          ConfigurableJWTProcessor<SecurityContext> processor = new DefaultJWTProcessor<>();
          processor.setJWSKeySelector(new JWSVerificationKeySelector<>(algorithms, jwkSource));
          processor.setJWTClaimsSetVerifier((claims, context) -> {});
          return processor;
        });
  }

  private static java.net.URL toUrl(String uri) {
    try {
      return URI.create(uri).toURL();
    } catch (Exception ex) {
      throw new IllegalStateException("Malformed JWKS URI '" + uri + "': " + ex.getMessage(), ex);
    }
  }

  @Override
  @SuppressWarnings("unchecked")
  public Jwt decode(String token) throws JwtException {
    SignedJWT signedJwt = parseSignedJwt(token);
    JWTClaimsSet unverifiedClaims = readClaims(signedJwt);
    String tokenIssuer = unverifiedClaims.getIssuer() == null ? "" : unverifiedClaims.getIssuer();
    Set<String> tokenAudiences = tokenAudiences(unverifiedClaims);

    Map.Entry<String, Map<String, Object>> selection = selectProvider(tokenIssuer, tokenAudiences);
    if (selection == null) {
      LOG.warn(
          "identity_provider_mismatch issuer={} reason_code={}",
          tokenIssuer,
          AuthReasonCode.PROVIDER_MISMATCH);
      throw new JwksValidationException(
          AuthReasonCode.PROVIDER_MISMATCH,
          "No configured provider matches the token issuer. Ensure the provider plan "
              + "includes a provider with issuer matching the token's 'iss' claim.");
    }
    String providerName = selection.getKey();
    Map<String, Object> provider = selection.getValue();

    String tokenAlg = signedJwt.getHeader().getAlgorithm().getName();
    List<String> allowedAlgorithms = stringList(provider.get("allowedAlgorithms"));
    for (String alg : allowedAlgorithms) {
      assertAsymmetricAlgorithm(alg, providerName);
    }
    if (!allowedAlgorithms.contains(tokenAlg)) {
      throw new JwksValidationException(
          AuthReasonCode.BAD_SIGNATURE,
          "Token algorithm '"
              + tokenAlg
              + "' is not in the provider '"
              + providerName
              + "' allow-list "
              + allowedAlgorithms
              + ".");
    }
    assertAsymmetricAlgorithm(tokenAlg, providerName);

    String jwksUri = String.valueOf(provider.getOrDefault("jwksUri", ""));
    JWTClaimsSet verifiedClaims = verifySignature(token, providerName, jwksUri, allowedAlgorithms);

    Date expiresAt = verifiedClaims.getExpirationTime();
    if (expiresAt == null || expiresAt.toInstant().isBefore(Instant.now())) {
      throw new JwksValidationException(AuthReasonCode.EXPIRED_TOKEN, "Token has expired.");
    }
    String verifiedIssuer = verifiedClaims.getIssuer();
    if (verifiedIssuer == null || !verifiedIssuer.equals(tokenIssuer)) {
      throw new JwksValidationException(
          AuthReasonCode.ISSUER_MISMATCH, "Token issuer does not match the configured issuer.");
    }
    List<String> allowedAudiences = effectiveAudiencesFor(providerName);
    if (!allowedAudiences.isEmpty()) {
      Set<String> verifiedAudiences = tokenAudiences(verifiedClaims);
      verifiedAudiences.retainAll(allowedAudiences);
      if (verifiedAudiences.isEmpty()) {
        throw new JwksValidationException(
            AuthReasonCode.AUDIENCE_MISMATCH,
            "Token audience does not match the expected audience.");
      }
    }

    List<String> roles = extractRoles(verifiedClaims, provider);

    Map<String, Object> headers = new HashMap<>();
    headers.put("alg", tokenAlg);
    Map<String, Object> claims = new HashMap<>(verifiedClaims.getClaims());
    claims.put("roles", roles);
    claims.put("providerName", providerName);
    return Jwt.withTokenValue(token)
        .headers(h -> h.putAll(headers))
        .claims(c -> c.putAll(claims))
        .issuedAt(
            verifiedClaims.getIssueTime() == null
                ? Instant.now()
                : verifiedClaims.getIssueTime().toInstant())
        .expiresAt(expiresAt.toInstant())
        .build();
  }

  private SignedJWT parseSignedJwt(String token) {
    try {
      com.nimbusds.jwt.JWT parsed = JWTParser.parse(token);
      if (!(parsed instanceof SignedJWT signedJwt)) {
        // alg=none (or an encrypted JWE) parses to a non-SignedJWT type --
        // reject before any further processing (asymmetric-only guard).
        throw new JwksValidationException(
            AuthReasonCode.BAD_SIGNATURE,
            "Rejected token: not a signed JWT (alg=none or unsupported token type).");
      }
      return signedJwt;
    } catch (ParseException ex) {
      throw new JwksValidationException(
          AuthReasonCode.MALFORMED_TOKEN, "Token could not be decoded: " + ex.getMessage());
    }
  }

  private JWTClaimsSet readClaims(SignedJWT signedJwt) {
    try {
      return signedJwt.getJWTClaimsSet();
    } catch (ParseException ex) {
      throw new JwksValidationException(
          AuthReasonCode.MALFORMED_TOKEN, "Token payload could not be decoded: " + ex.getMessage());
    }
  }

  /**
   * Verify the token's signature via the cached per-provider JWKS processor. Fail-closed JWKS
   * refresh (D9): Nimbus's underlying {@code JWKSourceBuilder}-produced source already refreshes
   * its cache on an unknown {@code kid} (no explicit cache override is installed here, which is the
   * one configuration that disables that default refresh); a {@link RemoteKeySourceException} on
   * the refreshed fetch (network failure, malformed JWK set) is wrapped as {@code
   * JWKS_REFRESH_FAILED} rather than ever allowing an unverifiable token through.
   */
  private JWTClaimsSet verifySignature(
      String token, String providerName, String jwksUri, List<String> allowedAlgorithms) {
    try {
      ConfigurableJWTProcessor<SecurityContext> processor =
          processorFor(providerName, jwksUri, allowedAlgorithms);
      return processor.process(token, null);
    } catch (ParseException | BadJOSEException | JOSEException ex) {
      if (isJwksFetchFailure(ex)) {
        LOG.warn(
            "identity_jwks_refresh_failed provider={} reason_code={}",
            providerName,
            AuthReasonCode.JWKS_REFRESH_FAILED);
        throw new JwksValidationException(
            AuthReasonCode.JWKS_REFRESH_FAILED,
            "JWKS refresh failed for provider '"
                + providerName
                + "': "
                + ex.getMessage()
                + ". The token cannot be verified (fail-closed).");
      }
      throw new JwksValidationException(
          AuthReasonCode.BAD_SIGNATURE, "Token signature is invalid: " + ex.getMessage());
    }
  }

  /**
   * True when *ex* (or any exception in its cause chain) represents a JWKS-endpoint FETCH/PARSE
   * failure rather than a genuine signature mismatch -- distinguishes "the remote key material
   * could not be retrieved/parsed" (fail-closed, {@code JWKS_REFRESH_FAILED}) from "the signature
   * genuinely did not verify against a successfully-retrieved key" ({@code BAD_SIGNATURE}).
   *
   * <p>Checks BOTH the exception type ({@link RemoteKeySourceException}, anywhere in the cause
   * chain -- {@code DefaultJWTProcessor} does not consistently preserve it as the top-level
   * exception) AND the message text (Nimbus's JWK-set-retrieval failure messages consistently
   * mention "JWK set" regardless of exact exception type/version, which is a more version-stable
   * signal than the exact wrapper class).
   */
  private static boolean isJwksFetchFailure(Throwable ex) {
    for (Throwable cause = ex; cause != null; cause = cause.getCause()) {
      if (cause instanceof RemoteKeySourceException) {
        return true;
      }
      String message = cause.getMessage();
      if (message != null && message.toLowerCase(java.util.Locale.ROOT).contains("jwk set")) {
        return true;
      }
    }
    return false;
  }

  /**
   * Extract Datrix role strings from verified claims using the provider's roleSource -- mirrors
   * python's {@code _extract_roles} (identity.py.j2: 337-370): map-shape (role KEYS are role names,
   * e.g. Zitadel's default {@code urn:zitadel:iam:org:project:roles} claim) or array-shape (a flat
   * list of role-name strings). Every raw role name is normalized through {@code roleMappings};
   * unmapped names pass through unchanged.
   */
  @SuppressWarnings("unchecked")
  private static List<String> extractRoles(JWTClaimsSet claims, Map<String, Object> provider) {
    Map<String, Object> roleSource = (Map<String, Object>) provider.get("roleSource");
    String claimPath =
        roleSource == null || roleSource.get("claimPath") == null
            ? "roles"
            : String.valueOf(roleSource.get("claimPath"));
    Object rawClaim = resolveClaimPath(claims.getClaims(), claimPath);
    List<String> rawRoles = new ArrayList<>();
    if (rawClaim instanceof Map<?, ?> map) {
      for (Object key : map.keySet()) {
        rawRoles.add(String.valueOf(key));
      }
    } else if (rawClaim instanceof List<?> list) {
      for (Object item : list) {
        rawRoles.add(String.valueOf(item));
      }
    }
    Map<String, Object> roleMappingsRaw = (Map<String, Object>) provider.get("roleMappings");
    Map<String, String> roleMappings = new HashMap<>();
    if (roleMappingsRaw != null) {
      for (Map.Entry<String, Object> entry : roleMappingsRaw.entrySet()) {
        roleMappings.put(entry.getKey(), String.valueOf(entry.getValue()));
      }
    }
    List<String> result = new ArrayList<>();
    for (String raw : rawRoles) {
      result.add(roleMappings.getOrDefault(raw, raw));
    }
    return result;
  }

  /**
   * Resolve a (possibly dotted) claim path against decoded claims -- mirrors python's {@code
   * _resolve_claim_path}.
   */
  @SuppressWarnings("unchecked")
  private static Object resolveClaimPath(Map<String, Object> claims, String claimPath) {
    Object cursor = claims;
    for (String segment : claimPath.split("\\.")) {
      if (!(cursor instanceof Map<?, ?> map)) {
        return null;
      }
      cursor = map.get(segment);
    }
    return cursor;
  }

  /**
   * Raised when JWKS-based token validation fails. {@link #reasonCode} identifies the failure
   * category (one of {@link AuthReasonCode}) -- NEVER exposed in client HTTP responses
   * (logged/metriced only, RFC 7807 opacity, D9).
   */
  public static class JwksValidationException extends JwtException {

    private final AuthReasonCode reasonCode;

    public JwksValidationException(AuthReasonCode reasonCode, String message) {
      super(message);
      this.reasonCode = reasonCode;
    }

    public AuthReasonCode reasonCode() {
      return this.reasonCode;
    }
  }
}
