package library_notification_service.clients;

import java.time.Duration;
import org.springframework.http.client.SimpleClientHttpRequestFactory;
import org.springframework.stereotype.Component;
import org.springframework.web.client.RestClient;

/**
 * Shared resilient-client infrastructure for this service's dependency clients.
 *
 * <p>Default timeout: 10.0s (default retry: max 2 attempts, exponential backoff). Auto-generated by
 * datrix-codegen-java. Do not edit manually.
 */
@Component
public class ResilientClientSupport {

  /** Default per-request timeout when a dependency declares no override. */
  public static final Duration DEFAULT_TIMEOUT = Duration.ofMillis(10000);

  /**
   * Resolve a dependency's base URL from the environment.
   *
   * @throws IllegalStateException when {@code envVar} is unset or blank.
   */
  public String resolveServiceUrl(String envVar) {
    String url = System.getenv(envVar);
    if (url == null || url.isBlank()) {
      throw new IllegalStateException(
          "Environment variable "
              + envVar
              + " is required to resolve a "
              + "dependency service URL, but was not set.");
    }
    return url;
  }

  /**
   * Build a {@link RestClient.Builder} for {@code baseUrl} with {@code timeout} applied to both
   * connect and read.
   */
  public RestClient.Builder newBuilder(String baseUrl, Duration timeout) {
    SimpleClientHttpRequestFactory factory = new SimpleClientHttpRequestFactory();
    factory.setConnectTimeout((int) timeout.toMillis());
    factory.setReadTimeout((int) timeout.toMillis());
    return RestClient.builder().baseUrl(baseUrl).requestFactory(factory);
  }
}
