package library_book_service.repositories.book_db;

import java.util.Optional;
import java.util.UUID;
import library_book_service.model.book_db.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

/**
 * User Spring Data JPA repository.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public interface UserRepository extends JpaRepository<User, UUID>, JpaSpecificationExecutor<User> {

  Optional<User> findByEmail(String email);
}
