package library_book_service.model.book_db;

import static org.junit.jupiter.api.Assertions.*;

import java.lang.reflect.Method;
import org.junit.jupiter.api.Test;

/**
 * Generated tests for Book's entity-level functions: proves, via reflection, that each declared
 * ``fn`` transpiled to a real method with the expected parameter count/types and return type.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class BookFunctionTest {

  @Test
  void getStatusLabelExistsWithExpectedSignature() throws Exception {
    Method method = Book.class.getDeclaredMethod("getStatusLabel");
    assertEquals(0, method.getParameterCount());
    assertEquals(String.class, method.getReturnType());
  }

  @Test
  void isRecentlyPublishedExistsWithExpectedSignature() throws Exception {
    Method method = Book.class.getDeclaredMethod("isRecentlyPublished");
    assertEquals(0, method.getParameterCount());
    assertEquals(Boolean.class, method.getReturnType());
  }
}
