"""Project-level test fixtures for deployed service testing.

Auto-generated by datrix-codegen-python. Do not edit manually.
"""

from __future__ import annotations

import logging
import os
import time
from collections.abc import Callable, Generator

import httpx
import pytest

logger = logging.getLogger(__name__)

_TRANSPORT_RETRIES = 2
_DEPLOY_RETRIES = 3
_DEPLOY_RETRY_DELAY_SECONDS = 2.0
_DEPLOY_REQUEST_TIMEOUT_SECONDS = 10.0


def _service_base_url(env_key: str) -> str:
    """Get base URL for a service from environment variable (required).

    Raises:
        ValueError: If the environment variable is not set.
    """
    url = os.environ.get(env_key)
    if not url:
        raise ValueError(f"Service URL required: set environment variable {env_key!r}.")
    return url


def _deploy_get_with_retry(client: httpx.Client, url: str) -> httpx.Response:
    """GET request with retry for transient Docker networking failures.

    Retries on ReadTimeout, ReadError, and ConnectError -- transient TCP
    port-forwarding failures at the Docker Desktop NAT layer where the
    service is healthy but the connection is dropped or reset.

    Args:
        client: httpx.Client configured with transport-level retries.
        url: Full URL to GET.

    Returns:
        httpx.Response on success.

    Raises:
        httpx.ReadTimeout: If all retries exhausted on read timeout.
        httpx.ReadError: If all retries exhausted on read error.
        httpx.ConnectError: If all retries exhausted on connect error.
    """
    last_exc: httpx.ReadTimeout | httpx.ReadError | httpx.ConnectError | None = None
    for attempt in range(1 + _DEPLOY_RETRIES):
        try:
            return client.get(url)
        except (httpx.ReadTimeout, httpx.ReadError, httpx.ConnectError) as exc:
            last_exc = exc
            if attempt < _DEPLOY_RETRIES:
                logger.warning(
                    "deploy_get_retry url=%s attempt=%d/%d error=%s",
                    url,
                    attempt + 1,
                    _DEPLOY_RETRIES,
                    exc,
                )
                time.sleep(_DEPLOY_RETRY_DELAY_SECONDS)
    assert last_exc is not None  # noqa: S101
    raise last_exc


@pytest.fixture
def http_client() -> Generator[httpx.Client, None, None]:
    """Synchronous HTTP client for deployed service testing."""
    transport = httpx.HTTPTransport(retries=_TRANSPORT_RETRIES)
    with httpx.Client(
        transport=transport, timeout=_DEPLOY_REQUEST_TIMEOUT_SECONDS
    ) as client:
        yield client


@pytest.fixture
def deploy_get(http_client: httpx.Client) -> Callable[[str], httpx.Response]:
    """GET callable with retry for transient Docker networking failures."""

    def _get(url: str) -> httpx.Response:
        return _deploy_get_with_retry(http_client, url)

    return _get


@pytest.fixture
def library_book_service_url() -> str:
    """Base URL for library.BookService."""
    return _service_base_url("LIBRARY_BOOK_SERVICE_URL")
