/**
 * Deployment test for examples.IngestionService.
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */
import { fetchWithRetry, httpRequest, waitForHealth, httpGetJson, makeTestJwt } from './helpers';

const SERVICE_PORT = 8002;
const BASE_URL = `http://localhost:${SERVICE_PORT}`;
const HEALTH_TIMEOUT_MS = 120_000;
const JWT_ISSUER = 'library';

describe('IngestionService Deployment', () => {
  it('health check returns 200 with healthy status', async () => {
    const healthy = await waitForHealth(BASE_URL, HEALTH_TIMEOUT_MS);
    expect(healthy).toBe(true);

    const data = await httpGetJson(`${BASE_URL}/health`);
    expect(data).toBeDefined();
    expect(['healthy', 'ok']).toContain(data.status);
  }, HEALTH_TIMEOUT_MS + 10_000);

  it('responds to GET /', async () => {
    const response = await fetchWithRetry(BASE_URL);
    expect(response.status).toBeLessThan(500);
  });

  it('OpenAPI docs endpoint /docs is accessible', async () => {
    const response = await fetchWithRetry(`${BASE_URL}/docs`);
    expect(response.status).toBe(200);
  });

  it('OpenAPI JSON schema /openapi.json is valid', async () => {
    const data = await httpGetJson(`${BASE_URL}/openapi.json`);
    expect(data).toBeDefined();
    expect(data.openapi).toBeDefined();
  }, 35_000);
});
