#!/usr/bin/env node
/**
 * Run Unit Tests (Without Deployment).
 *
 * Runs unit tests directly against code without Docker deployment.
 * For integration/spec tests that require a database, use deploy-test.js instead.
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 *
 * Usage:
 *   node tests/unit-tests.js                  # Run unit tests (minimal output by default)
 *   node tests/unit-tests.js --verbose        # Show detailed test output
 *   node tests/unit-tests.js --no-save        # Don't save output to files
 *   node tests/unit-tests.js --output-dir X   # Custom output directory
 *   node tests/unit-tests.js --parallel       # Run service tests in parallel
 *   node tests/unit-tests.js --coverage       # Run with coverage report
 */
'use strict';

const { execSync, spawn, spawnSync } = require('child_process');
const fs = require('fs');
const path = require('path');

/**
 * One ``pnpm install`` at the TypeScript workspace root (``.generated/typescript/``); all services share
 * ``typescript/node_modules``. Jest is run via ``node …/jest/bin/jest.js`` so we never per-service install.
 */
const PNPM_CMD = 'pnpm';

const SERVICES = [
  { name: 'examples.IngestionService', dir: 'examples_ingestion_service', port: 8002 },
  { name: 'examples.OrderService', dir: 'examples_order_service', port: 8001 },
];

// ANSI colour helpers
const GREEN = '\x1b[92m';
const CYAN = '\x1b[96m';
const YELLOW = '\x1b[93m';
const RED = '\x1b[91m';
const RESET = '\x1b[0m';

let summaryLogPath = null;

function log(colour, msg) {
  console.log(`${colour}${msg}${RESET}`);
  if (summaryLogPath) {
    fs.appendFileSync(summaryLogPath, msg + '\n', 'utf-8');
  }
}

function printSuccess(msg) { log(GREEN, msg); }
function printInfo(msg)    { log(CYAN, msg); }
function printWarning(msg) { log(YELLOW, `WARNING: ${msg}`); }
function printError(msg)   { log(RED, `ERROR: ${msg}`); }

function stripAnsi(str) {
  return str.replace(/\x1b\[[0-9;]*m/g, '');
}

/**
 * Load optional test-config.json.
 */
function loadTestConfig(configPath) {
  if (!fs.existsSync(configPath)) return null;
  try {
    return JSON.parse(fs.readFileSync(configPath, 'utf-8'));
  } catch (err) {
    printWarning(`Failed to load test config from ${configPath}: ${err.message}`);
    return null;
  }
}

/**
 * Parse test statistics from Jest output.
 * Looks for patterns like:
 *   Test Suites: 1 failed, 50 passed, 51 total
 *   Tests:       2 failed, 35 passed, 37 total
 *
 * suiteFailures counts suites that did not pass; it is reported separately from
 * `errors` so agents are not misled (one failing suite with N assertions is not
 * "N failed + 1 unrelated error").
 */
function parseTestStatistics(output) {
  const result = {
    passed: 0,
    failed: 0,
    errors: 0,
    skipped: 0,
    suiteFailures: 0,
  };
  if (!output) return result;

  const suitesLine = output.match(/Test Suites:\s+(.+total)/);
  let suitesFailed = 0;
  if (suitesLine) {
    const suiteFailedMatch = suitesLine[1].match(/(\d+) failed/);
    if (suiteFailedMatch) {
      suitesFailed = parseInt(suiteFailedMatch[1], 10);
    }
  }
  result.suiteFailures = suitesFailed;

  const testsLine = output.match(/Tests:\s+(.+total)/);
  if (testsLine) {
    const tail = testsLine[1];
    const passedMatch = tail.match(/(\d+) passed/);
    const failedMatch = tail.match(/(\d+) failed/);
    const skippedMatch = tail.match(/(\d+) skipped/);
    const totalMatch = tail.match(/(\d+)\s*total/);
    if (passedMatch) result.passed = parseInt(passedMatch[1], 10);
    if (failedMatch) result.failed = parseInt(failedMatch[1], 10);
    if (skippedMatch) result.skipped = parseInt(skippedMatch[1], 10);
    const total = totalMatch
      ? parseInt(totalMatch[1], 10)
      : result.passed + result.failed + result.skipped;
    // Only treat suite failures as `errors` when no tests executed (compile/setup).
    if (total === 0 && suitesFailed > 0) {
      result.errors = suitesFailed;
    }
    return result;
  }

  if (suitesFailed > 0) {
    result.errors = suitesFailed;
  }

  const totalPassed = output.match(/Total Passed:\s*(\d+)/);
  if (totalPassed) result.passed = parseInt(totalPassed[1], 10);
  const totalFailed = output.match(/Total Failed:\s*(\d+)/);
  if (totalFailed) result.failed = parseInt(totalFailed[1], 10);
  const totalErrors = output.match(/Total Errors:\s*(\d+)/);
  if (totalErrors) result.errors = parseInt(totalErrors[1], 10);
  const totalSkipped = output.match(/Total Skipped:\s*(\d+)/);
  if (totalSkipped) result.skipped = parseInt(totalSkipped[1], 10);

  return result;
}

function stripKnownLogNoise(text) {
  return text
    .split('\n')
    .filter(
      (line) => !line.includes('Local package.json exists, but node_modules missing'),
    )
    .join('\n');
}

function getPnpmVersion() {
  try {
    const pnpmCmd = PNPM_CMD;
    return execSync(`${pnpmCmd} --version`, { encoding: 'utf-8' }).trim();
  } catch (_) {
    return null;
  }
}

function resolveDatrixRepoSha() {
  const raw = process.env.DATRIX_REPO_SHA || process.env.DATRIX_CODEGEN_SHA;
  if (!raw) return null;
  const s = String(raw).trim();
  return s || null;
}

function writeEnvironmentJson(outputDir, projectPath) {
  const payload = {
    project: projectPath,
    generatedAt: new Date().toISOString(),
    nodeVersion: process.version,
    pnpmVersion: getPnpmVersion(),
    platform: process.platform,
    arch: process.arch,
    logNotes: [
      'Dependencies are installed once at the TypeScript workspace root (.generated/typescript); services do not each get a full node_modules copy.',
      'Triage: read failures.json first for structured failures; open per-service jest-results.json for full stacks.',
    ],
  };
  const sha = resolveDatrixRepoSha();
  if (sha) {
    payload.datrixRepoSha = sha;
  }
  fs.writeFileSync(
    path.join(outputDir, 'environment.json'),
    `${JSON.stringify(payload, null, 2)}\n`,
    'utf-8',
  );
}

function collectFailuresFromJestJson(jsonPath, serviceDirName) {
  if (!fs.existsSync(jsonPath)) return [];
  let data;
  try {
    data = JSON.parse(fs.readFileSync(jsonPath, 'utf-8'));
  } catch (_) {
    return [];
  }
  const out = [];
  const results = data.testResults || [];
  for (const tr of results) {
    const testFile = tr.name || '';
    for (const ar of tr.assertionResults || []) {
      if (ar.status === 'failed') {
        const msg = (ar.failureMessages && ar.failureMessages[0]) || '';
        out.push({
          service: serviceDirName,
          testFilePath: testFile,
          fullName: ar.fullName || ar.title,
          line: ar.location ? ar.location.line : undefined,
          column: ar.location ? ar.location.column : undefined,
          message: msg.trim(),
        });
      }
    }
  }
  return out;
}

function buildFailuresOnlyText(failuresForService) {
  if (!failuresForService.length) return '';
  const blocks = failuresForService.map((f) => {
    const loc = f.line ? `:${f.line}` : '';
    const head = `${f.testFilePath}${loc} — ${f.fullName}`;
    const body = (f.message || '').split('\n').slice(0, 12).join('\n');
    return `${head}\n${body}`;
  });
  return `${blocks.join('\n\n---\n\n')}\n`;
}

function writeFailuresJson(outputDir, projectPath, failures) {
  const payload = {
    project: projectPath,
    generatedAt: new Date().toISOString(),
    failures,
  };
  fs.writeFileSync(
    path.join(outputDir, 'failures.json'),
    `${JSON.stringify(payload, null, 2)}\n`,
    'utf-8',
  );
}

function appendFailureIndexToSummary(summaryPath, failures) {
  if (!failures.length || !summaryPath) return;
  const lines = [
    '',
    '='.repeat(40),
    'Failure index (machine-oriented triage)',
    '='.repeat(40),
  ];
  for (const f of failures) {
    const loc = f.line ? `:${f.line}` : '';
    const oneLine = (f.message || '').split('\n')[0].slice(0, 400);
    lines.push(`- [${f.service}] ${f.fullName}`);
    lines.push(`    file: ${f.testFilePath}${loc}`);
    if (oneLine) lines.push(`    message: ${oneLine}`);
  }
  fs.appendFileSync(summaryPath, `${lines.join('\n')}\n`, 'utf-8');
}

/**
 * Ensure pnpm is available by checking if it exists, and enabling corepack if needed.
 * Returns true if pnpm is available, false if it could not be made available.
 */
function ensurePnpmAvailable() {
  try {
    const pnpmCmd = PNPM_CMD;
    execSync(`${pnpmCmd} --version`, { stdio: 'pipe' });
    return true; // pnpm already available
  } catch (err) {
    // pnpm not found, try enabling corepack
    try {
      printInfo('pnpm not found, enabling corepack...');
      execSync('corepack enable', { stdio: 'pipe' });
      // Verify it worked
      const pnpmCmd = PNPM_CMD;
      execSync(`${pnpmCmd} --version`, { stdio: 'pipe' });
      printSuccess('corepack enabled successfully');
      return true;
    } catch (corepackErr) {
      printError('Failed to enable corepack or pnpm is still unavailable');
      printError(`Error: ${corepackErr.message}`);
      printError('Please run: corepack enable');
      return false;
    }
  }
}

function parseArgs() {
  const args = {
    noSave: false,
    outputDir: '',
    parallel: false,
    maxWorkers: 4,
    coverage: false,
    verbose: false,
  };
  for (let i = 2; i < process.argv.length; i++) {
    const arg = process.argv[i];
    if (arg === '--no-save') args.noSave = true;
    else if (arg === '--parallel') args.parallel = true;
    else if (arg === '--coverage') args.coverage = true;
    else if (arg === '--verbose') args.verbose = true;
    else if (arg === '--output-dir' && process.argv[i + 1]) {
      args.outputDir = process.argv[++i];
    } else if (arg === '--max-workers' && process.argv[i + 1]) {
      args.maxWorkers = parseInt(process.argv[++i], 10);
    }
  }
  return args;
}

/**
 * Run Jest in a service directory using the workspace ``node_modules`` (no per-service pnpm install).
 * Returns { output, exitCode }.
 *
 * @param {string} workspaceRoot - absolute path to ``.generated/typescript`` (pnpm workspace root)
 * @param {string} serviceDir - absolute path to the service directory (Jest cwd)
 * @param {object} args - parsed CLI arguments
 * @param {string|null} jestConfigFile - Jest config file name, or null for default ``jest.config.ts``
 * @param {string|null} jsonOutputFile - if set, Jest writes JSON results here (--json --outputFile)
 */
function runServiceTests(workspaceRoot, serviceDir, args, jestConfigFile, jsonOutputFile) {
  const jestJs = path.join(workspaceRoot, 'node_modules', 'jest', 'bin', 'jest.js');
  if (!fs.existsSync(jestJs)) {
    const msg = `jest CLI not found at ${jestJs}. Run pnpm install in ${workspaceRoot}.`;
    return Promise.resolve({ output: msg, exitCode: 1 });
  }

  const jestArgv = ['--forceExit', '--detectOpenHandles', '--no-cache'];
  if (jestConfigFile) {
    jestArgv.push('--config', jestConfigFile);
  } else {
    jestArgv.push('--config', 'jest.config.ts');
  }

  if (jsonOutputFile) {
    fs.mkdirSync(path.dirname(jsonOutputFile), { recursive: true });
    jestArgv.push('--json', `--outputFile=${jsonOutputFile}`, '--testLocationInResults');
  }

  if (args.coverage) {
    jestArgv.push('--coverage');
  }

  const env = envWithWorkspaceBin(workspaceRoot, { ...process.env, NODE_ENV: 'test', CI: 'true' });

  return new Promise((resolve) => {
    const proc = spawn(process.execPath, [jestJs, ...jestArgv], {
      cwd: serviceDir,
      stdio: ['pipe', 'pipe', 'pipe'],
      shell: false,
      env,
    });

    const chunks = [];
    proc.stdout.on('data', (data) => {
      chunks.push(data);
      process.stdout.write(data);
    });
    proc.stderr.on('data', (data) => {
      chunks.push(data);
      process.stderr.write(data);
    });

    proc.on('close', (code) => {
      const output = Buffer.concat(chunks).toString('utf-8');
      resolve({ output, exitCode: code ?? 1 });
    });
  });
}

/**
 * Retry a function with exponential backoff.
 * @param {Function} fn - Function to retry (should throw on failure)
 * @param {number} maxAttempts - Maximum number of attempts (default: 3)
 * @param {number} initialDelayMs - Initial delay in milliseconds (default: 2000)
 * @returns {boolean} - true if succeeded, false if all attempts failed
 */
function retryWithBackoff(fn, maxAttempts = 3, initialDelayMs = 2000) {
  for (let attempt = 1; attempt <= maxAttempts; attempt++) {
    try {
      fn();
      return true;
    } catch (err) {
      if (attempt === maxAttempts) {
        // Last attempt failed, give up
        throw err;
      }
      // Calculate delay with exponential backoff: 2s, 4s, 8s
      const delayMs = initialDelayMs * Math.pow(2, attempt - 1);
      printWarning(`  Attempt ${attempt}/${maxAttempts} failed, retrying in ${delayMs}ms...`);
      // Synchronous sleep using busy-wait (not ideal but works for short delays)
      const start = Date.now();
      while (Date.now() - start < delayMs) {
        // Busy wait
      }
    }
  }
  return false;
}

/**
 * Walk up from *projectPath* until we find the TypeScript pnpm workspace root
 * (``pnpm-workspace.yaml`` and ``package.json`` — typically ``.generated/typescript``).
 */
function findTypescriptWorkspaceRoot(projectPath) {
  let dir = path.resolve(projectPath);
  const fsRoot = path.parse(dir).root;
  while (dir !== fsRoot) {
    const ws = path.join(dir, 'pnpm-workspace.yaml');
    const pkg = path.join(dir, 'package.json');
    if (fs.existsSync(ws) && fs.existsSync(pkg)) {
      return dir;
    }
    dir = path.dirname(dir);
  }
  return null;
}

function envWithWorkspaceBin(workspaceRoot, baseEnv) {
  const env = { ...baseEnv };
  const bin = path.join(workspaceRoot, 'node_modules', '.bin');
  if (!fs.existsSync(bin)) {
    return env;
  }
  const sep = process.platform === 'win32' ? ';' : ':';
  const pathKey = Object.keys(process.env).find((k) => k.toUpperCase() === 'PATH') || 'PATH';
  env[pathKey] = `${bin}${sep}${env[pathKey] || ''}`;
  return env;
}

/**
 * Run ``pnpm install`` once at the workspace root if Jest is not present yet.
 */
function ensureWorkspaceInstall(workspaceRoot, opts) {
  opts = opts || {};
  if (!workspaceRoot) {
    return false;
  }
  const jestJs = path.join(workspaceRoot, 'node_modules', 'jest', 'bin', 'jest.js');
  if (fs.existsSync(jestJs)) {
    return true;
  }

  printInfo(`  Installing workspace dependencies under ${workspaceRoot} ...`);
  try {
    const runInstall = () => {
      const r = spawnSync(`${PNPM_CMD} install`, {
        cwd: workspaceRoot,
        encoding: 'utf-8',
        maxBuffer: 50 * 1024 * 1024,
        shell: true,
        stdio: ['ignore', 'pipe', 'pipe'],
        env: { ...process.env, CI: 'true' },
      });
      const combined = [r.stdout || '', r.stderr || ''].join('');
      if (opts.installLogPath) {
        fs.writeFileSync(opts.installLogPath, combined, 'utf-8');
      }
      if (r.error) {
        throw r.error;
      }
      if (r.status !== 0 && r.status !== null) {
        const tail = combined.trim().slice(-4000);
        throw new Error(`pnpm install exited with code ${r.status}${tail ? `\n${tail}` : ''}`);
      }
    };
    retryWithBackoff(runInstall, 3, 2000);
  } catch (err) {
    printError(`  Workspace pnpm install failed after 3 attempts: ${err.message}`);
    return false;
  }
  return fs.existsSync(jestJs);
}

async function main() {
  const args = parseArgs();
  const scriptDir = __dirname;
  const projectPath = path.resolve(scriptDir, '..');

  // Ensure pnpm is available (enable corepack if needed)
  if (!ensurePnpmAvailable()) {
    printError('Cannot proceed without pnpm. Exiting.');
    process.exit(1);
  }

  // Load test configuration
  const configPath = path.join(scriptDir, 'test-config.json');
  const config = loadTestConfig(configPath);

  // Setup output directory
  let saveOutput = !args.noSave;
  let outputDir = null;

  if (saveOutput) {
    const now = new Date();
    const pad = (n) => String(n).padStart(2, '0');
    const timestamp = `${now.getFullYear()}${pad(now.getMonth() + 1)}${pad(now.getDate())}-${pad(now.getHours())}${pad(now.getMinutes())}${pad(now.getSeconds())}`;
    outputDir = args.outputDir
      ? path.resolve(args.outputDir)
      : path.join(projectPath, '.test_results', `unit-tests-${timestamp}`);
    fs.mkdirSync(outputDir, { recursive: true });
    summaryLogPath = path.join(outputDir, 'unit-tests-summary.log');
    fs.writeFileSync(summaryLogPath, [
      '='.repeat(40),
      'Unit Tests Summary Log',
      '='.repeat(40),
      `Project: ${projectPath}`,
      `Timestamp: ${new Date().toISOString()}`,
      '='.repeat(40),
      '',
      '',
    ].join('\n'), 'utf-8');
    printInfo(`Test output will be saved to: ${outputDir}`);
    writeEnvironmentJson(outputDir, projectPath);
  }

  printInfo('='.repeat(40));
  printInfo(`Running Tests: ${projectPath}`);
  printInfo('='.repeat(40));

  // Resolve service directories
  const serviceDirs = SERVICES
    .map((svc) => ({ ...svc, fullPath: path.join(projectPath, svc.dir) }))
    .filter((svc) => {
      const pkgPath = path.join(svc.fullPath, 'package.json');
      return fs.existsSync(pkgPath);
    });

  if (serviceDirs.length === 0) {
    printError('No services with package.json found in project.');
    process.exit(1);
  }

  printInfo(`Found ${serviceDirs.length} services: ${serviceDirs.map((s) => s.dir).join(', ')}`);
  printInfo('');
  printInfo('Running tests...');
  printInfo('='.repeat(40));

  const workspaceRoot = findTypescriptWorkspaceRoot(projectPath);
  if (!workspaceRoot) {
    printError('Could not find TypeScript workspace root (pnpm-workspace.yaml next to package.json).');
    printError('Regenerate TypeScript output so .generated/typescript/ contains the workspace files.');
    process.exit(1);
  }
  const workspaceInstallLog = saveOutput && outputDir
    ? path.join(outputDir, 'pnpm-workspace-install.log')
    : null;
  if (!ensureWorkspaceInstall(workspaceRoot, { installLogPath: workspaceInstallLog })) {
    printError('Workspace dependency install failed; fix errors above then retry.');
    process.exit(1);
  }

  let totalPassed = 0;
  let totalFailed = 0;
  let totalErrors = 0;
  let totalSkipped = 0;
  const failedServices = [];
  const allFailures = [];

  for (const svc of serviceDirs) {
    printInfo('');
    printInfo(`Testing: ${svc.dir}`);
    printInfo('-'.repeat(40));

    const jestJsonPath = saveOutput && outputDir
      ? path.join(outputDir, svc.dir, 'jest-results.json')
      : null;

    const { output, exitCode } = await runServiceTests(
      workspaceRoot,
      svc.fullPath,
      args,
      null,
      jestJsonPath,
    );
    const stats = parseTestStatistics(output);
    totalPassed += stats.passed;
    totalFailed += stats.failed;
    totalErrors += stats.errors;
    totalSkipped += stats.skipped;

    const svcFailed = exitCode !== 0 || stats.failed > 0 || stats.errors > 0;

    if (!svcFailed && stats.passed > 0) {
      printSuccess(`  PASSED: ${stats.passed} tests (${stats.skipped} skipped)`);
    } else if (stats.failed > 0 || stats.errors > 0 || stats.suiteFailures > 0) {
      const parts = [`${stats.passed} passed`, `${stats.failed} failed`];
      if (stats.suiteFailures > 0) {
        parts.push(`${stats.suiteFailures} suiteFailures`);
      }
      if (stats.errors > 0) {
        parts.push(`${stats.errors} errors`);
      }
      printError(`  FAILED: ${parts.join(', ')}`);
    } else if (exitCode !== 0 && stats.passed === 0) {
      printError('  FAILED: Test suite failed to run (exitCode: ' + exitCode + ')');
    } else if (stats.passed === 0) {
      printWarning('  No tests were collected or run');
    }

    if (saveOutput && outputDir) {
      const logFile = path.join(outputDir, `${svc.dir}-unit-tests.log`);
      fs.writeFileSync(logFile, stripKnownLogNoise(stripAnsi(output)), 'utf-8');
    }

    const svcFailures = jestJsonPath
      ? collectFailuresFromJestJson(jestJsonPath, svc.dir)
      : [];
    allFailures.push(...svcFailures);
    if (saveOutput && outputDir && svcFailures.length) {
      const fo = path.join(outputDir, `${svc.dir}-failures-only.log`);
      fs.writeFileSync(fo, buildFailuresOnlyText(svcFailures), 'utf-8');
    }

    if (svcFailed) {
      failedServices.push(svc.dir);
    }
  }

  // Summary
  printInfo('');
  printInfo('='.repeat(40));
  printInfo('Test Summary');
  printInfo('='.repeat(40));
  printInfo(`Total Passed:  ${totalPassed}`);
  if (totalFailed > 0) printError(`Total Failed:  ${totalFailed}`);
  if (totalErrors > 0) printError(`Total Errors:  ${totalErrors}`);
  if (totalSkipped > 0) printInfo(`Total Skipped: ${totalSkipped}`);

  if (failedServices.length > 0) {
    printError('');
    printError(`Failed services: ${failedServices.join(', ')}`);
  }

  if (saveOutput && outputDir && allFailures.length) {
    writeFailuresJson(outputDir, projectPath, allFailures);
    appendFailureIndexToSummary(summaryLogPath, allFailures);
  }

  const totalIssues = totalFailed + totalErrors;
  if (totalIssues > 0 || failedServices.length > 0) {
    printError('');
    printError('Tests FAILED!');
    process.exit(1);
  } else if (totalPassed === 0) {
    printError('');
    printError('NO TESTS COLLECTED — nothing passed!');
    process.exit(1);
  } else {
    printSuccess('');
    printSuccess('All tests PASSED!');
    process.exit(0);
  }
}

main().catch((err) => {
  printError(`Unexpected error: ${err.message}`);
  process.exit(1);
});
