base:
  rdbms:
    aviation_db:
      engine: postgres
      host: localhost
      port: 5432
      database: shared_aviation_ref
      poolSize: 10
      docker_image: postgres:17-alpine
      volume_path: /var/lib/postgresql/data
      asyncDriver: postgresql+asyncpg
      syncDriver: postgresql+psycopg2
      healthCheckSql: SELECT 1
      defaultUser: postgres
      platform: container
production:
  rdbms:
    aviation_db:
      engine: postgres
      host: ${DB_HOST}
      port: 5432
      database: shared_aviation_ref
      poolSize: 20
      docker_image: postgres:17-alpine
      volume_path: /var/lib/postgresql/data
      asyncDriver: postgresql+asyncpg
      syncDriver: postgresql+psycopg2
      healthCheckSql: SELECT 1
      defaultUser: postgres
      platform: rds
      ssl: true
      _replace: true
