// MemberServiceDbContext.cs -- generated EF Core DbContext (project persistence root).
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
// Registers a DbSet<T> + fluent IEntityTypeConfiguration<T> for every
// concrete entity across every RDBMS block this service declares (design
// 037 Section 4 D3). Schema DDL and migrations are NOT owned here -- design
// 040 scope.
using Microsoft.EntityFrameworkCore;

namespace MemberService.Data;

public class MemberServiceDbContext : DbContext
{
    public MemberServiceDbContext(DbContextOptions<MemberServiceDbContext> options)
        : base(options) { }

    public DbSet<MemberService.Models.MemberDb.Member> Members =>
        Set<MemberService.Models.MemberDb.Member>();

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);
        modelBuilder.ApplyConfiguration(
            new MemberService.Data.Configurations.MemberDb.MemberConfiguration()
        );
    }
}
