"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "device_update_status" AS ENUM (\'pending\', \'downloading\', \'installing\', \'completed\', \'failed\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "rollout_status" AS ENUM (\'planned\', \'in_progress\', \'paused\', \'completed\', \'failed\', \'cancelled\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "firmware_versions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "version",
            sa.String(50),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "release_notes",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "file_url",
            sa.String(500),
            nullable=False,
        ),
        sa.Column(
            "file_size",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "checksum",
            sa.String(64),
            nullable=False,
        ),
        sa.Column(
            "released_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "is_stable",
            sa.Boolean(),
            nullable=False,
        ),
    )
    op.create_table(
        "firmware_rollouts",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "rollout_code",
            sa.String(30),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "target_device_group_id",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum('planned', 'in_progress', 'paused', 'completed', 'failed', 'cancelled', name='rollout_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "total_devices",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "updated_devices",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "failed_devices",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "firmware_version_id",
            sa.Uuid,
            nullable=False,
        ),
    )
    op.create_table(
        "rollout_logs",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "device_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum('pending', 'downloading', 'installing', 'completed', 'failed', name='device_update_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "error_message",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "firmware_rollout_id",
            sa.Uuid,
            nullable=False,
        ),
    )
    op.create_index("ix_firmware_versions_version", "firmware_versions", ["version"], unique=False)
    op.create_index("ix_firmware_versions_is_stable", "firmware_versions", ["is_stable"], unique=False)
    op.create_index("ix_firmware_rollouts_status", "firmware_rollouts", ["status"], unique=False)
    op.create_index("ix_firmware_rollouts_firmware_version_id_status", "firmware_rollouts", ["firmware_version_id", "status"], unique=False)
    op.create_index("ix_rollout_logs_firmware_rollout_id_device_id", "rollout_logs", ["firmware_rollout_id", "device_id"], unique=True)
    op.create_index("ix_rollout_logs_firmware_rollout_id_status", "rollout_logs", ["firmware_rollout_id", "status"], unique=False)


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_index("ix_rollout_logs_firmware_rollout_id_status", table_name="rollout_logs")
    op.drop_index("ix_rollout_logs_firmware_rollout_id_device_id", table_name="rollout_logs")
    op.drop_index("ix_firmware_rollouts_firmware_version_id_status", table_name="firmware_rollouts")
    op.drop_index("ix_firmware_rollouts_status", table_name="firmware_rollouts")
    op.drop_index("ix_firmware_versions_is_stable", table_name="firmware_versions")
    op.drop_index("ix_firmware_versions_version", table_name="firmware_versions")
    op.drop_table("rollout_logs")
    op.drop_table("firmware_rollouts")
    op.drop_table("firmware_versions")
