test:
  email:
    provider: smtp
    fromEmail: noreply@ecommerce.example.com
    fromName: Ecommerce Demo

development:
  email:
    provider: smtp
    fromEmail: noreply@ecommerce.example.com
    fromName: Ecommerce Demo

production:
  email:
    provider: ses
    fromEmail: noreply@ecommerce.example.com
    fromName: Ecommerce Store
