test:
  tags: [api, notifications, ecommerce, v1]

  meta: { team: platform }

  healthCheck: { type: http, path: /health, interval: 10s }

development:
  tags: [api, notifications, ecommerce, v1]

  meta: { team: platform }

  healthCheck: { type: http, path: /health, interval: 10s }

production:
  tags: [api, notifications, ecommerce, v1]

  meta: { team: platform }

  healthCheck: { type: http, path: /health, interval: 10s }
