package library_book_service.model.book_db;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.validation.ConstraintViolation;
import jakarta.validation.Validation;
import jakarta.validation.Validator;
import java.util.Set;
import java.util.UUID;
import library_book_service.dto.book_db.BookTagCreateRequest;
import org.hibernate.validator.HibernateValidator;
import org.hibernate.validator.messageinterpolation.ParameterMessageInterpolator;
import org.junit.jupiter.api.Test;

/**
 * Generated tests for BookTag: field round-trip, update-assertion, relationship navigation, and
 * (when the entity's CreateRequest DTO carries at least one @NotNull field) Bean Validation
 * constraint-violation tests.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class BookTagTest {

  @Test
  void bookNavigationSetAndGetReturnsSameInstance() {
    BookTag instance = BookTagTestFactory.create();
    Book related = BookTestFactory.create();
    instance.setBook(related);
    assertSame(related, instance.getBook());
  }

  @Test
  void tagNavigationSetAndGetReturnsSameInstance() {
    BookTag instance = BookTagTestFactory.create();
    Tag related = TagTestFactory.create();
    instance.setTag(related);
    assertSame(related, instance.getTag());
  }

  private static Validator buildValidator() {
    return Validation.byProvider(HibernateValidator.class)
        .configure()
        .messageInterpolator(new ParameterMessageInterpolator())
        .buildValidatorFactory()
        .getValidator();
  }

  @Test
  void requiredFieldLeftNullFailsBeanValidation() {
    Validator validator = buildValidator();
    BookTagCreateRequest invalid =
        new BookTagCreateRequest(null, UUID.fromString("550e8400-e29b-41d4-a716-446655440000"));
    Set<ConstraintViolation<BookTagCreateRequest>> violations = validator.validate(invalid);
    assertFalse(violations.isEmpty(), "expected a violation for a null required field");
  }

  @Test
  void allRequiredFieldsPresentPassesBeanValidation() {
    Validator validator = buildValidator();
    BookTagCreateRequest valid =
        new BookTagCreateRequest(
            UUID.fromString("550e8400-e29b-41d4-a716-446655440000"),
            UUID.fromString("550e8400-e29b-41d4-a716-446655440000"));
    Set<ConstraintViolation<BookTagCreateRequest>> violations = validator.validate(valid);
    assertTrue(violations.isEmpty(), "expected no violations, got: " + violations);
  }
}
