package library_book_service.model.book_db;

import static org.junit.jupiter.api.Assertions.*;

import org.junit.jupiter.api.Test;

/**
 * Generated lifecycle-hook tests for User, invoking {@link UserLifecycleListener}'s real callback
 * methods directly (no persistence context is needed -- JPA lifecycle callbacks are ordinary public
 * methods once generated).
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class UserLifecycleTest {

  @Test
  void onPrePersistHookSetsExpectedFieldValues() throws Exception {
    User target = UserTestFactory.create();
    new UserLifecycleListener().onPrePersist(target);
    assertNotNull(target.getPasswordHash());
  }
}
