package library_notification_service.model.notif_db;

import jakarta.persistence.Column;
import jakarta.persistence.Id;
import jakarta.persistence.MappedSuperclass;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * BaseEntity JPA entity.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@MappedSuperclass
public abstract class BaseEntity {

  @Id
  @Column(name = "id", columnDefinition = "uuid", nullable = false)
  private UUID id = java.util.UUID.randomUUID();

  @Column(name = "createdAt", columnDefinition = "timestamptz", nullable = false)
  private OffsetDateTime createdAt = OffsetDateTime.now();

  @Column(name = "updatedAt", columnDefinition = "timestamptz", nullable = false)
  private OffsetDateTime updatedAt = OffsetDateTime.now();

  public UUID getId() {
    return this.id;
  }

  public void setId(UUID id) {
    this.id = id;
  }

  public OffsetDateTime getCreatedAt() {
    return this.createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }

  public OffsetDateTime getUpdatedAt() {
    return this.updatedAt;
  }

  public void setUpdatedAt(OffsetDateTime updatedAt) {
    this.updatedAt = updatedAt;
  }
}
