test:
  platform: compose
  port: 8001
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 640Mi
  healthCheck:
    path: /health
    initialDelay: 10s
development:
  platform: compose
  port: 8001
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 640Mi
  healthCheck:
    path: /health
    initialDelay: 10s
production:
  platform: ecs-fargate
  port: 8001
  strategy:
    rolling:
      maxUnavailable: 25%
  replicas: 2
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
  healthCheck:
    path: /health
    initialDelay: 10s
