/**
 * Container serverless consumer entrypoint for block 'event-handlers'.
 *
 * Runs as: node dist/serverless/event-handlers/consumer.js
 *
 * Standalone process that binds ONLY this serverless block's subscriptions,
 * reusing the SAME connection classes the in-process pubsub consumer uses.
 * Each handler invocation is bounded by a timeout race with the handler's
 * merged timeout; a handler that times out or throws leaves its message
 * uncommitted/nacked-with-requeue so it is redelivered, matching the
 * in-process consumer's at-least-once crash-safety contract. The consumer
 * group / queue name is namespaced under 'serverless' so this standalone
 * consumer never steals messages from the in-process one.
 *
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */
import type { EachMessagePayload } from 'kafkajs';
import { bootstrapRuntime, shutdownRuntime } from '../_runtime';
import { order_events_order_cancelled } from './handlers/order-events-order-cancelled';
import { order_events_order_placed } from './handlers/order-events-order-placed';
import { KafkaConnection } from '../../mq/connection';

const GROUP_ID = 'examples-order-service.serverless.event-handlers';

interface DispatchEntry {
  handler: (payload: Record<string, unknown>) => Promise<void>;
  timeoutMs: number;
}

const DISPATCH_0: Record<string, DispatchEntry> = {
  'examples_order_service.mq.order_events:OrderPlaced': { handler: order_events_order_placed, timeoutMs: 300000 },
  'OrderPlaced': { handler: order_events_order_placed, timeoutMs: 300000 },
  'examples_order_service.mq.order_events:OrderCancelled': { handler: order_events_order_cancelled, timeoutMs: 300000 },
  'OrderCancelled': { handler: order_events_order_cancelled, timeoutMs: 300000 },
};


async function invoke(
  dispatch: Record<string, DispatchEntry>,
  topic: string,
  eventType: string,
  payload: Record<string, unknown>,
): Promise<boolean> {
  const key = `${topic}:${eventType}`;
  const entry = dispatch[key] ?? dispatch[eventType];
  if (!entry) {
    console.warn(`serverless_consumer_unknown_event event_type=${eventType} topic=${topic}`);
    return true;
  }
  try {
    await Promise.race([
      entry.handler(payload),
      new Promise<never>((_, reject) => {
        setTimeout(() => reject(new Error('serverless_consumer_timeout')), entry.timeoutMs);
      }),
    ]);
    return true;
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    if (message === 'serverless_consumer_timeout') {
      console.error(`serverless_consumer_timeout key=${key} timeout_ms=${entry.timeoutMs}`);
      return false;
    }
    console.error(`serverless_consumer_dispatch_failed key=${key} error=${message}`);
    return true;
  }
}

function decodeEnvelope(raw: string): { eventType: string; payload: Record<string, unknown> } {
  const envelope = JSON.parse(raw) as { eventType?: string; payload?: unknown };
  const payload = envelope.payload;
  return {
    eventType: String(envelope.eventType ?? ''),
    payload: payload && typeof payload === 'object' ? (payload as Record<string, unknown>) : {},
  };
}

async function consumeMq(): Promise<void> {
  const connection = new KafkaConnection();
  const consumer = await connection.getConsumer(GROUP_ID, [
    'examples_order_service.mq.order_events',
  ]);
  await consumer.run({
    autoCommit: false,
    eachMessage: async ({ topic, partition, message }: EachMessagePayload) => {
      const raw = message.value?.toString();
      if (!raw) {
        return;
      }
      const { eventType, payload } = decodeEnvelope(raw);
      const committable = await invoke(DISPATCH_0, topic, eventType, payload);
      if (committable) {
        await consumer.commitOffsets([
          { topic, partition, offset: (BigInt(message.offset) + BigInt(1)).toString() },
        ]);
      }
    },
  });
}

async function main(): Promise<void> {
  await bootstrapRuntime();
  await Promise.all([
    consumeMq(),
  ]);
  console.log(`serverless_consumer_started block=event-handlers group=${GROUP_ID}`);
}

main().catch((err) => {
  console.error('Container serverless consumer failed to start', err);
  void shutdownRuntime();
  process.exit(1);
});
