package warehouse_warehouse_service.warehouse_db;

import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import java.util.HashMap;
import java.util.Map;
import javax.sql.DataSource;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.data.jpa.repository.config.EnableJpaRepositories;
import org.springframework.orm.jpa.JpaTransactionManager;
import org.springframework.orm.jpa.JpaVendorAdapter;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.orm.jpa.SharedEntityManagerCreator;
import org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter;
import org.springframework.transaction.PlatformTransactionManager;

/**
 * JPA {@code EntityManagerFactory} + {@code PlatformTransactionManager} for the 'warehouseDb' RDBMS
 * block (postgres). {@code visit_transaction}/ {@code visit_commit} lower to programmatic {@code
 * TransactionTemplate} blocks against the {@code PlatformTransactionManager} bean exposed here --
 * never {@code @Transactional} annotation magic (design principle 7).
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Configuration
@EnableJpaRepositories(
    basePackages = "warehouse_warehouse_service.repositories.warehouse_db",
    entityManagerFactoryRef = "warehouse_dbEntityManagerFactory",
    transactionManagerRef = "warehouse_dbTransactionManager")
public class WarehouseDbJpaConfig {

  @Bean(name = "warehouse_dbEntityManagerFactory")
  public LocalContainerEntityManagerFactoryBean warehouse_dbEntityManagerFactory(
      @Qualifier("warehouse_dbDataSource") DataSource dataSource) {
    LocalContainerEntityManagerFactoryBean emf = new LocalContainerEntityManagerFactoryBean();
    emf.setDataSource(dataSource);
    emf.setPackagesToScan("warehouse_warehouse_service.model.warehouse_db");
    emf.setPersistenceUnitName("warehouse_db");
    JpaVendorAdapter vendorAdapter = new HibernateJpaVendorAdapter();
    emf.setJpaVendorAdapter(vendorAdapter);

    // spring.jpa.hibernate.ddl-auto=none -- rendered literal "none", NEVER a
    // template variable (schema is owned by migrations).
    Map<String, Object> jpaProperties = new HashMap<>();
    jpaProperties.put("hibernate.hbm2ddl.auto", "none");
    // A hand-rolled LocalContainerEntityManagerFactoryBean (chosen over Boot's
    // auto-configured entityManagerFactory so multiple RDBMS blocks each get
    // their own explicitly-named bean) never picks up Boot's own camelCase ->
    // snake_case column-naming convention -- Hibernate's own DEFAULT physical
    // naming strategy leaves Java field names unconverted, which Postgres then
    // silently lowercases (`customerEmail` -> `customeremail`, never matching a
    // migration-created `customer_email` column). Hibernate's own (Spring-
    // independent) CamelCaseToUnderscoresNamingStrategy performs the same
    // conversion migrations already assume.
    jpaProperties.put(
        "hibernate.physical_naming_strategy",
        "org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy");
    emf.setJpaPropertyMap(jpaProperties);

    return emf;
  }

  @Bean(name = "warehouse_dbTransactionManager")
  public PlatformTransactionManager warehouse_dbTransactionManager(
      @Qualifier("warehouse_dbEntityManagerFactory") EntityManagerFactory entityManagerFactory) {
    return new JpaTransactionManager(entityManagerFactory);
  }

  /**
   * Request-scoped {@code EntityManager} unit of work: a thread-bound, self-scoping proxy (Spring's
   * {@code SharedEntityManagerCreator}) that transparently delegates to the CURRENT
   * transaction-bound {@code EntityManager}, creating a fresh one per unit of work -- the same
   * delegate {@code @PersistenceContext} injection resolves to under the hood.
   */
  @Bean(name = "warehouse_dbEntityManager")
  public EntityManager warehouse_dbEntityManager(
      @Qualifier("warehouse_dbEntityManagerFactory") EntityManagerFactory entityManagerFactory) {
    return SharedEntityManagerCreator.createSharedEntityManager(entityManagerFactory);
  }
}
