"""JWT authentication dependencies.

Auto-generated by datrix-codegen-python from gateway.yaml config.
Do not edit manually.

Provider: library
Algorithm allow-list: from identity provider plan.
"""

from __future__ import annotations

import contextvars
import logging
from typing import Any

from fastapi import Depends, HTTPException, Request, status
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer

from library_book_service.identity import (
    JwksValidationError,
    local_user_id,
    resolve_provider_name,
    validate_token_claims,
)

logger = logging.getLogger(__name__)

# Set by get_current_user when invoked; read by get_current_user_id() in model trait hooks.
# _current_user_id_ctx holds the RESOLVED local id (profile_id when projection is enabled,
# raw subject otherwise).  _current_user_subject_ctx always holds the raw provider sub.
# HANDOFF: the JWT middleware may pre-populate request.state.user_id for pre-auth tenant
# extraction, but the auth dependency (get_current_user) MUST overwrite request.state.user_id
# with the resolved local id before any endpoint handler code runs.  Do not reinstate
# claims.get("sub") as the final value — that was the 500-causing bug this resolves.
_current_user_id_ctx: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "current_user_id", default=None
)
_current_user_subject_ctx: contextvars.ContextVar[str | None] = contextvars.ContextVar(
    "current_user_subject", default=None
)
_current_user_token_ctx: contextvars.ContextVar[str] = contextvars.ContextVar(
    "current_user_token", default=""
)

# Infra paths bypass JWT auth for ALL HTTP methods (health, docs, JWKS, etc.).
_EXCLUDE_INFRA_PATHS: frozenset[str] = frozenset(
    {
        "/.well-known/jwks.json",
        "/docs",
        "/health",
        "/openapi.json",
        "/redoc",
    }
)

# DSL public paths bypass JWT auth only for the exact HTTP method declared PUBLIC.
# Using (method, path) pairs ensures a mixed-access path (e.g. public GET,
# protected POST) is NOT excluded for the protected method.
_EXCLUDE_PUBLIC_METHOD_PATHS: frozenset[tuple[str, str]] = frozenset({})

security = HTTPBearer(auto_error=False)


class _ClaimsProxy:
    """Attribute-access shim over a JWT claims dict.

    Enables ``Auth.identity.<claimPath>`` DSL expressions to work as Python
    attribute access on the verified claims dict.  Missing claims return ``None``
    rather than raising ``AttributeError``, matching DSL null-safety semantics.

    Example::

        # DSL: Auth.identity.email
        # Generated: current_user.identity.email
        claims_proxy = _ClaimsProxy({"email": "alice@example.com"})
        assert claims_proxy.email == "alice@example.com"
        assert claims_proxy.missing is None
    """

    __slots__ = ("_data",)

    def __init__(self, data: dict[str, Any]) -> None:
        object.__setattr__(self, "_data", data)

    def __getattr__(self, name: str) -> Any:  # noqa: ANN401
        return object.__getattribute__(self, "_data").get(name)

    def get(self, key: str, default: Any = None) -> Any:  # noqa: ANN401
        """Dict-compatible get so identity_websocket.py.j2 callers work unchanged."""
        return object.__getattribute__(self, "_data").get(key, default)


class UserClaims:
    """Authenticated user claims extracted from JWT token.

    Attributes:
        profile_id: Resolved local user id — the projected IdentityProfile.profileId when
            projection is enabled for the provider, otherwise the raw JWT ``sub`` claim.
            This is the canonical user id for all application-layer lookups.
        id: Compatibility alias for ``profile_id`` (resolved local id, NOT the raw sub).
        subject: Raw JWT ``sub`` claim (provider-issued principal identifier).
        sub: Raw JWT ``sub`` claim; kept for backwards compatibility.
        profile: Projected IdentityProfile row dict when projection is enabled and the
            profile was loaded, otherwise ``None``.  Exposes the full profile document
            so ``Auth.profile.<field>`` DSL access works without a second DB lookup.
        identity: Attribute-access proxy over the raw JWT claims dict.  Enables
            ``Auth.identity.<claimPath>`` DSL expressions (e.g. ``Auth.identity.email``).
            Returns ``None`` for missing claims — never raises ``AttributeError``.
        roles: List of role names from the JWT.
        token: Raw JWT token string.
        plan: Subscription plan id from ``plan``, ``planId``, or ``plan_id`` claim (may be empty).
        provider: Logical provider name the verified token is attributed to
            (issuer AND audience resolved); empty when not attributable (e.g. a
            service token, excluded path, or anonymous principal).
    """

    __slots__ = (
        "profile_id",
        "id",
        "subject",
        "sub",
        "profile",
        "identity",
        "roles",
        "token",
        "plan",
        "provider",
    )

    def __init__(
        self,
        sub: str,
        roles: list[str],
        token: str,
        plan: str,
        provider: str,
        profile_id: str | None = None,
        profile: dict[str, Any] | None = None,
        identity: dict[str, Any] | None = None,
    ) -> None:
        # profile_id is the resolved local id: projected IdentityProfile.profileId when
        # projection is enabled, raw sub otherwise.  id aliases profile_id for compatibility.
        self.profile_id: str | None = (
            profile_id if profile_id is not None else (sub or None)
        )
        self.id: str | None = self.profile_id
        self.subject: str = sub
        self.sub: str = sub
        self.profile: dict[str, Any] | None = profile
        self.identity: _ClaimsProxy = _ClaimsProxy(
            identity if identity is not None else {}
        )
        self.roles = roles
        self.token = token
        self.plan = plan
        self.provider = provider


def _public_path_matches(pattern: str, request_path: str) -> bool:
    """Return True when request_path matches the DSL-declared public path pattern.

    Segment-level match only: the pattern must describe the exact path depth.
    Segments prefixed with ``:`` are path parameters that match any non-empty
    segment.  No prefix matching — ``/api/v1/books`` does NOT match
    ``/api/v1/books/{id}/sub-resource``, preventing protected sub-resource
    endpoints from being accidentally excluded by a shorter public pattern.

    Args:
        pattern: DSL path pattern, e.g. ``"/api/v1/books/:id"`` or
            ``"/api/v1/books"``.
        request_path: Actual URL path from the request.
    """
    pattern_parts = pattern.split("/")
    request_parts = request_path.split("/")
    if len(pattern_parts) != len(request_parts):
        return False
    return all(
        p.startswith(":") or p == r for p, r in zip(pattern_parts, request_parts)
    )


def is_path_excluded(request_method: str, request_path: str) -> bool:
    """Return True if this request should bypass JWT auth.

    Infra paths (``_EXCLUDE_INFRA_PATHS``) bypass auth for every HTTP method
    using prefix matching (sub-paths of infra routes are also infra).
    DSL public paths (``_EXCLUDE_PUBLIC_METHOD_PATHS``) bypass auth only for the
    exact HTTP method declared ``auth(public)`` in the DSL, and only when the
    request path matches the declared pattern at segment level (``:``: prefix
    segments match any single path segment).  No prefix matching is applied to
    public routes, so ``/api/v1/books`` does not accidentally exclude
    ``/api/v1/books/{id}/book_tags``.

    Args:
        request_method: HTTP method string (e.g. ``"GET"``); compared
            case-insensitively.
        request_path: URL path from the request (e.g. ``"/api/v1/books"``).
    """
    for pattern in _EXCLUDE_INFRA_PATHS:
        if request_path == pattern or request_path.startswith(pattern + "/"):
            return True
    method = request_method.lower()
    for path_method, pattern in _EXCLUDE_PUBLIC_METHOD_PATHS:
        if method == path_method and _public_path_matches(pattern, request_path):
            return True
    return False


def _role_value(role: object) -> str:
    return str(role.value if hasattr(role, "value") else role)


async def get_current_user(
    request: Request,
    credentials: HTTPAuthorizationCredentials | None = Depends(security),
) -> UserClaims:
    """Extract and validate current user from JWT Bearer token via JWKS.

    Skips validation for paths matched by ``is_path_excluded`` — infra paths for
    all methods; DSL ``auth(public)`` endpoints for their declared HTTP method only.
    Resolves signing key from provider JWKS; refreshes on unknown kid (DN38).
    Algorithm allow-list is provider-plan-driven; HS*/none are always rejected.

    Args:
        request: FastAPI request object for path checking.
        credentials: Bearer token credentials.

    Returns:
        UserClaims with id, sub, roles, and token attributes.

    Raises:
        HTTPException: 401 if credentials are missing or JWT is invalid.
    """
    if is_path_excluded(request.method, request.url.path):
        return UserClaims(sub="", roles=[], token="", plan="", provider="")

    if credentials is None:
        logger.warning("identity_auth_failed reason_code=%s", "missing_token")
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Not authenticated",
            headers={"WWW-Authenticate": "Bearer"},
        )

    token = credentials.credentials
    try:
        claims = await validate_token_claims(token)
    except JwksValidationError as exc:
        logger.warning(
            "identity_auth_failed reason_code=%s",
            exc.reason_code,
        )
        raise HTTPException(
            status_code=status.HTTP_401_UNAUTHORIZED,
            detail="Invalid or expired token",
            headers={"WWW-Authenticate": "Bearer"},
        ) from exc

    sub = str(claims.get("sub", ""))
    plan_raw: Any = claims.get("plan")
    if plan_raw is None:
        plan_raw = claims.get("planId")
    if plan_raw is None:
        plan_raw = claims.get("plan_id")
    plan = str(plan_raw).strip() if plan_raw is not None else ""
    _current_user_token_ctx.set(token)
    logger.debug(
        "identity_validated sub_hash=%s plan=%s", _hash_sub(sub), plan or "(none)"
    )
    raw_roles: Any = claims.get("roles", [])
    roles: list[str] = (
        [str(r) for r in raw_roles] if isinstance(raw_roles, list) else []
    )
    # Attribute the verified token to its true provider by issuer AND audience
    # (the same selection the validator used) so per-surface provider allow-list
    # enforcement (``require_providers``) can distinguish providers that share one
    # IdP instance — e.g. workforce vs customer on a single Zitadel server.
    provider = resolve_provider_name(claims) or ""
    # resolved_id is the single user id for all application-layer surfaces (Auth.userId(),
    # Request.userId(), get_current_user_id()).  Resolve deterministically from the plan;
    # NEVER default to the raw sub (a non-UUID subject in a UUID column causes runtime errors).
    # NOTE: local_user_id() intentionally raises for projected-mode providers — do NOT call it
    # unconditionally.  For projected providers resolved_id is set below after the profile upsert.
    resolved_id: str | None = None
    profile_id: str | None = None
    _profile_doc: dict[str, Any] | None = None
    # No projection in this service: always compute the deterministic local id.
    resolved_id = local_user_id(provider, sub) if sub else None
    # Propagate the resolved local id to all three user-id surfaces:
    #   1. _current_user_id_ctx  (get_current_user_id() — model trait hooks)
    #   2. request.state.user_id (Request.userId() — handler DSL)
    #   3. UserClaims.profile_id / UserClaims.id  (Auth.userId() — transpiler surface)
    # The raw provider subject is kept separately in _current_user_subject_ctx / .subject.
    _current_user_id_ctx.set(resolved_id)
    _current_user_subject_ctx.set(sub or None)
    request.state.user_id = resolved_id
    return UserClaims(
        sub=sub,
        roles=roles,
        token=token,
        plan=plan,
        provider=provider,
        profile_id=resolved_id,
        profile=_profile_doc,
        identity=claims,
    )


async def get_optional_current_user(
    request: Request,
    credentials: HTTPAuthorizationCredentials | None = Depends(security),
) -> UserClaims | None:
    """Return current user claims if a valid token is present, otherwise None.

    Used for public endpoints that optionally inspect Auth context
    (e.g. ``Auth.user()?.id`` in the DSL).
    """
    if credentials is None:
        return None
    try:
        return await get_current_user(request, credentials)
    except HTTPException:
        return None


def get_current_user_id() -> str | None:
    """Return the resolved local user id from request context.

    Returns the projected IdentityProfile.profileId when projection is enabled for the
    provider, or the raw JWT sub otherwise.  Used by model trait hooks that call
    Auth.userId() or get_current_user_id() outside of a FastAPI dependency context.
    """
    return _current_user_id_ctx.get()


def get_current_user_subject() -> str | None:
    """Return the raw provider subject (JWT sub) from request context.

    Always returns the raw provider-issued sub, regardless of projection state.
    Use this when you need the unresolved provider identity (e.g. for audit logs).
    """
    return _current_user_subject_ctx.get()


def get_current_user_token() -> str:
    """Return the current user token from request context (for model trait hooks using Auth.token())."""
    return _current_user_token_ctx.get()


def require_roles(required: list[str]) -> Any:
    """Create a dependency that checks the current user has one of the required roles.

    Flat any-of semantics: user must hold at least one of the literally-listed
    roles.  No transitive hierarchy.

    Args:
        required: List of role names. User must have at least one.

    Returns:
        FastAPI dependency function.
    """

    async def _check_roles(
        current_user: UserClaims = Depends(get_current_user),
    ) -> UserClaims:
        user_roles = [_role_value(r) for r in current_user.roles]
        if not any(role in user_roles for role in required):
            logger.warning("identity_role_denied reason_code=%s", "role_denied")
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Insufficient permissions",
            )
        return current_user

    return _check_roles


def require_providers(allowed: list[str]) -> Any:
    """Create a dependency enforcing a surface's provider allow-list.

    The token has already been validated and attributed to its true provider
    (by issuer AND audience, via ``identity.resolve_provider_name``, exposed as
    ``UserClaims.provider``).  A genuine token whose provider is not in
    ``allowed`` is an authorization denial (403), NOT a validation failure
    (401): the token is valid but its identity source is not permitted on this
    route — e.g. a workforce token on a customer-only surface.  Resolving the
    provider by issuer alone cannot make this distinction when several providers
    share one IdP instance (identical issuer, distinct audiences), so allow-list
    membership is enforced here against the audience-disambiguated provider.

    Args:
        allowed: Logical provider names permitted on the surface (known at
            generation time from the surface ``providers`` allow-list).

    Returns:
        FastAPI dependency function.
    """

    async def _check_providers(
        current_user: UserClaims = Depends(get_current_user),
    ) -> UserClaims:
        if current_user.provider not in allowed:
            logger.warning(
                "identity_provider_denied reason_code=%s",
                "provider_not_allowed",
            )
            raise HTTPException(
                status_code=status.HTTP_403_FORBIDDEN,
                detail="Insufficient permissions",
            )
        return current_user

    return _check_providers


def _hash_sub(sub: str) -> str:
    """Return a truncated SHA-256 hex digest of the subject for safe logging."""
    import hashlib

    return hashlib.sha256(sub.encode()).hexdigest()[:16]
