package library_loan_service.api;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.junit.jupiter.api.Test;

/**
 * Generated proof that LoanAPI's decorated endpoints lower to the generated resilience/rate-limit
 * layer -- never a {@code @Retryable}/{@code @RateLimiter}/{@code @Cacheable} annotation on the
 * controller method (decorator semantics stay DSL-owned, D8).
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class LoanApiDecoratorsTest {

  private static String controllerSource() throws IOException {
    return Files.readString(
        Path.of("src/main/java/library_loan_service/api/LoanApiController.java"));
  }

  @Test
  void controllerNeverUsesSpringOrResilience4jDecoratorAnnotations() throws IOException {
    String source = controllerSource();
    assertFalse(
        source.contains("@Retryable"),
        "must not use @Retryable -- decorator semantics stay DSL-owned");
    assertFalse(
        source.contains("@RateLimiter"),
        "must not use @RateLimiter -- decorator semantics stay DSL-owned");
    assertFalse(
        source.contains("@Cacheable"),
        "must not use @Cacheable -- decorator semantics stay DSL-owned");
  }

  @Test
  void postApiV1LoansRetryLowersToResilienceDecorators() throws IOException {
    String source = controllerSource();
    assertTrue(
        source.contains("ResilienceDecorators.retry(")
            || source.contains("ResilienceDecorators.retryVoid("),
        "expected a ResilienceDecorators.retry(...)/retryVoid(...) call site for 'post api v1"
            + " loans'");
    assertTrue(
        source.contains("3"),
        "expected the declared maxAttempts literal 3 in the generated controller");
  }
}
