package library_book_service.nosql.docdb.models;

import com.fasterxml.jackson.databind.JsonNode;
import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;
import org.bson.codecs.pojo.annotations.BsonProperty;

/**
 * Document model for ReadingActivity (collection, mongodb). Maps to the _id primary key.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public class ReadingActivityDocument {

  private UUID bookId;
  private UUID memberId;
  private String action;
  private JsonNode metadata;
  private OffsetDateTime timestamp;

  public ReadingActivityDocument() {}

  /** Builds a document from a raw field map (transpiled DSL {@code insert()} payload). */
  @SuppressWarnings("unchecked")
  public ReadingActivityDocument(Map<String, Object> data) {
    if (data.containsKey("bookId")) {
      this.bookId = (UUID) data.get("bookId");
    }
    if (data.containsKey("memberId")) {
      this.memberId = (UUID) data.get("memberId");
    }
    if (data.containsKey("action")) {
      this.action = (String) data.get("action");
    }
    if (data.containsKey("metadata")) {
      this.metadata = (JsonNode) data.get("metadata");
    }
    if (data.containsKey("timestamp")) {
      this.timestamp = (OffsetDateTime) data.get("timestamp");
    }
  }

  @BsonProperty("bookId")
  public UUID getBookId() {
    return this.bookId;
  }

  public void setBookId(UUID bookId) {
    this.bookId = bookId;
  }

  @BsonProperty("memberId")
  public UUID getMemberId() {
    return this.memberId;
  }

  public void setMemberId(UUID memberId) {
    this.memberId = memberId;
  }

  public String getAction() {
    return this.action;
  }

  public void setAction(String action) {
    this.action = action;
  }

  public JsonNode getMetadata() {
    return this.metadata;
  }

  public void setMetadata(JsonNode metadata) {
    this.metadata = metadata;
  }

  public OffsetDateTime getTimestamp() {
    return this.timestamp;
  }

  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }
}
