"""Structured logging configuration.

Auto-generated by datrix-codegen-python. Do not edit manually.
Provides JSON logging in production and plain console in development.
"""

from __future__ import annotations

import json
import logging
import sys
from datetime import UTC, datetime

from opentelemetry import trace

from library_book_service.config import _bootstrap

logger = logging.getLogger(__name__)


class JsonFormatter(logging.Formatter):
    """Render log records as JSON with merged context fields."""

    def format(self, record: logging.LogRecord) -> str:
        payload: dict[str, object] = {
            "timestamp": datetime.now(UTC).isoformat(),
            "level": record.levelname,
            "logger": record.name,
            "message": record.getMessage(),
        }
        context = getattr(record, "context", None)
        if isinstance(context, dict):
            payload.update(context)
        if record.exc_info and not record.exc_text:
            record.exc_text = self.formatException(record.exc_info)
        if record.exc_text:
            payload["exception"] = record.exc_text
        if record.stack_info:
            payload["stack"] = self.formatStack(record.stack_info)
        return json.dumps(payload, default=str)


class ConsoleFormatter(logging.Formatter):
    """Render readable console logs with inline key=value context."""

    def format(self, record: logging.LogRecord) -> str:
        line = f"{record.levelname} {record.name} {record.getMessage()}"
        context = getattr(record, "context", None)
        if isinstance(context, dict) and context:
            context_text = " ".join(f"{key}={value}" for key, value in context.items())
            line = f"{line} {context_text}"
        if record.exc_info and not record.exc_text:
            record.exc_text = self.formatException(record.exc_info)
        if record.exc_text:
            line = f"{line}\n{record.exc_text}"
        if record.stack_info:
            line = f"{line}\n{self.formatStack(record.stack_info)}"
        return line


class BoundLogger(logging.LoggerAdapter):
    """Logger adapter that supports context binding."""

    def bind(self, **context: object) -> "BoundLogger":
        merged = dict(self.extra)
        merged.update(context)
        return BoundLogger(self.logger, merged)

    def process(
        self, msg: str, kwargs: dict[str, object]
    ) -> tuple[str, dict[str, object]]:
        merged_context = dict(self.extra)
        provided_extra = kwargs.pop("extra", None)
        if isinstance(provided_extra, dict):
            provided_context = provided_extra.get("context")
            if isinstance(provided_context, dict):
                merged_context.update(provided_context)
        kwargs["extra"] = {"context": merged_context}
        return msg, kwargs


def _is_production() -> bool:
    """Detect production environment from the baked bootstrap constant."""
    env = (_bootstrap.ENVIRONMENT or "test").lower()
    return env in ("production", "prod", "staging")


def _trace_context() -> dict[str, str]:
    """Return active OpenTelemetry trace IDs when available."""
    span = trace.get_current_span()
    ctx = span.get_span_context()
    if not ctx.trace_id:
        return {}
    return {
        "trace_id": format(ctx.trace_id, "032x"),
        "span_id": format(ctx.span_id, "016x"),
    }


def setup_logging(service_name: str = "library_book_service") -> None:
    """Configure standard logging with environment-based formatting."""
    is_prod = _is_production()
    log_level = getattr(logging, "INFO", logging.INFO)

    root_logger = logging.getLogger()
    root_logger.handlers.clear()
    root_logger.setLevel(log_level)

    handler = logging.StreamHandler(stream=sys.stdout)
    if is_prod:
        handler.setFormatter(JsonFormatter())
    else:
        handler.setFormatter(ConsoleFormatter())
    root_logger.addHandler(handler)

    for uvicorn_logger_name in ("uvicorn", "uvicorn.access", "uvicorn.error"):
        uvicorn_logger = logging.getLogger(uvicorn_logger_name)
        uvicorn_logger.handlers.clear()
        uvicorn_logger.propagate = True

    # aiokafka logs every poll/heartbeat fetch response at DEBUG, which floods
    # stdout once the application log level is DEBUG. Floor its loggers at INFO
    # (never below the app level) so useful lifecycle events -- group join,
    # partition assignment, connection up/down -- survive while the per-poll
    # FetchResponse/HeartbeatResponse spam is dropped.
    kafka_log_level = max(log_level, logging.INFO)
    for noisy_logger_name in ("aiokafka", "aiokafka.conn"):
        logging.getLogger(noisy_logger_name).setLevel(kafka_log_level)

    if log_level > logging.DEBUG:
        logging.getLogger("sqlalchemy.engine").setLevel(logging.WARNING)

    log = get_logger(__name__, service=service_name)
    log.info(
        "logging_configured",
        extra={
            "context": {
                "level": "info",
                "mode": "production" if is_prod else "development",
            }
        },
    )


def get_logger(name: str | None = None, **initial_context: object) -> BoundLogger:
    """Get a bound logger with optional initial context."""
    base_logger = logging.getLogger(name) if name else logging.getLogger()
    log = BoundLogger(base_logger, dict(initial_context))
    if initial_context:
        return log.bind(**_trace_context())
    return log.bind(**_trace_context())
