"""OpenTelemetry tracing setup.

Auto-generated by datrix-codegen-python. Do not edit manually.
Provider: jaeger
Endpoint: resolved at startup from AppSettings when configured.
Sampling rate: 0.1
"""

from __future__ import annotations

import logging

from fastapi import FastAPI

logger = logging.getLogger(__name__)

_TRACING_AVAILABLE = True


def setup_tracing(
    app: FastAPI,
    service_name: str = "library_book_service",
    endpoint: str | None = None,
    connection_string: str | None = None,
) -> None:
    """Configure OpenTelemetry tracing with jaeger exporter.

    All OpenTelemetry imports are deferred to this function so that
    importing this module never triggers heavy third-party import chains.
    If OpenTelemetry packages are unavailable or incompatible, tracing
    is silently skipped with a warning.

    Args:
        app: FastAPI application to instrument.
        service_name: Name of the service for trace identification.
        endpoint: OTLP exporter endpoint resolved from AppSettings.
            Ignored by the Azure Monitor exporter, which keys off
            connection_string.
        connection_string: Azure Monitor connection string resolved from AppSettings.
    """
    global _TRACING_AVAILABLE  # noqa: PLW0603
    try:
        from opentelemetry import trace
        from opentelemetry.exporter.otlp.proto.grpc.trace_exporter import (
            OTLPSpanExporter,
        )
        from opentelemetry.instrumentation.fastapi import FastAPIInstrumentor
        from opentelemetry.instrumentation.sqlalchemy import SQLAlchemyInstrumentor
        from opentelemetry.sdk.resources import Resource
        from opentelemetry.sdk.trace import TracerProvider
        from opentelemetry.sdk.trace.export import BatchSpanProcessor
        from opentelemetry.sdk.trace.sampling import TraceIdRatioBased
    except ImportError:
        logger.warning(
            "tracing_setup_skipped reason=opentelemetry_packages_unavailable "
            "service=%s",
            service_name,
        )
        _TRACING_AVAILABLE = False
        return

    resource = Resource.create({"service.name": service_name})

    sampler = TraceIdRatioBased(0.1)
    provider = TracerProvider(resource=resource, sampler=sampler)

    if not endpoint:
        logger.info(
            "trace export disabled reason=no_otlp_endpoint service=%s",
            service_name,
        )
        return
    try:
        exporter = OTLPSpanExporter(endpoint=endpoint)
        provider.add_span_processor(BatchSpanProcessor(exporter))
        trace.set_tracer_provider(provider)
    except Exception as e:
        logger.warning(
            "tracing_setup_failed reason=%s endpoint=%s tracing_disabled=1",
            str(e),
            endpoint,
        )
        return

    FastAPIInstrumentor.instrument_app(app)
    SQLAlchemyInstrumentor().instrument()
    logger.info("tracing_instrumented library=sqlalchemy")

    logger.info(
        "tracing_setup_complete provider=%s endpoint=%s sampling_rate=%s",
        "jaeger",
        endpoint,
        0.1,
    )


def get_tracer(name: str) -> object:
    """Get a tracer instance for creating custom spans.

    Args:
        name: Name of the tracer (typically __name__).

    Returns:
        An OpenTelemetry Tracer, or a no-op proxy if tracing is unavailable.
    """
    from opentelemetry import trace

    return trace.get_tracer(name)
