"""Shared pytest fixtures for specification tests (library_book_service).

Auto-generated by datrix-codegen-python. Do not edit manually.
"""

from __future__ import annotations

import decimal
import logging

import pytest

try:
    from library_book_service.mq import producer as _mq_producer_module
except ImportError:
    _mq_producer_module = None

logger = logging.getLogger(__name__)


class EventSpy:
    """Captures published events for assertions in spec tests."""

    def __init__(self) -> None:
        self._records: list[tuple[str, dict[str, object]]] = []

    def record(self, event_name: str, **kwargs: object) -> None:
        self._records.append((event_name, dict(kwargs)))

    def has(self, event_name: str, **kwargs: object) -> bool:
        """Return True if an event with matching name and payload was recorded."""
        for name, payload in self._records:
            if name != event_name:
                continue
            if _event_payload_matches(payload, kwargs):
                return True
        return False

    def reset(self) -> None:
        self._records.clear()


def _event_payload_matches(
    payload: dict[str, object],
    expected: dict[str, object],
) -> bool:
    if payload.keys() != expected.keys():
        return False
    return all(_event_value_matches(payload[key], expected[key]) for key in payload)


def _event_value_matches(actual: object, expected: object) -> bool:
    if isinstance(actual, decimal.Decimal) and isinstance(expected, int | float):
        return actual == decimal.Decimal(str(expected))
    if isinstance(expected, decimal.Decimal) and isinstance(actual, int | float):
        return decimal.Decimal(str(actual)) == expected
    return actual == expected


_EVENT_SPY_PUBLISH_PARAM_MAP: dict[str, tuple[str, tuple[str, ...]]] = {
    "publish_book_added": ("BookAdded", ("book_id", "title")),
    "publish_book_status_changed": (
        "BookStatusChanged",
        ("book_id", "old_status", "new_status"),
    ),
}


class _EventSpyProducer:
    """Async producer double that records publish_* calls in EventSpy."""

    def __init__(self, spy: EventSpy) -> None:
        self._spy = spy

    def __getattr__(self, name: str) -> object:
        if name not in _EVENT_SPY_PUBLISH_PARAM_MAP:
            raise AttributeError(name)
        event_name, param_names = _EVENT_SPY_PUBLISH_PARAM_MAP[name]

        async def _publish(*args: object) -> None:
            payload = dict(zip(param_names, args, strict=False))
            self._spy.record(event_name, **payload)

        return _publish


def _patch_event_producers(monkeypatch: pytest.MonkeyPatch, spy: EventSpy) -> None:
    producer = _EventSpyProducer(spy)
    if _mq_producer_module is not None:
        monkeypatch.setattr(_mq_producer_module, "producer_instance", producer)


class QueueSpy:
    """Captures dispatched queue tasks for assertions in spec tests."""

    def __init__(self) -> None:
        self._records: list[tuple[str, dict[str, object]]] = []

    def record(self, task_name: str, **kwargs: object) -> None:
        self._records.append((task_name, dict(kwargs)))

    def has(self, task_name: str, **kwargs: object) -> bool:
        """Return True if a task with matching name and payload was recorded."""
        for name, payload in self._records:
            if name != task_name:
                continue
            if payload == kwargs:
                return True
        return False

    def reset(self) -> None:
        self._records.clear()


@pytest.fixture
def event_spy(monkeypatch: pytest.MonkeyPatch) -> EventSpy:
    """Isolated event spy per test."""
    spy = EventSpy()
    _patch_event_producers(monkeypatch, spy)
    logger.debug("event_spy_created")
    return spy
