package warehouse_warehouse_service.services.warehouse_db;

import java.util.List;
import java.util.Optional;
import java.util.UUID;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import warehouse_warehouse_service.model.warehouse_db.DeliveryZone;
import warehouse_warehouse_service.repositories.warehouse_db.DeliveryZoneRepository;
import warehouse_warehouse_service.services.ServiceBase;

/**
 * DeliveryZone service -- request-scoped unit-of-work wrapper over {@link DeliveryZoneRepository }.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Service
public class DeliveryZoneService extends ServiceBase {

  private final DeliveryZoneRepository deliveryZoneRepository;

  public DeliveryZoneService(DeliveryZoneRepository deliveryZoneRepository) {
    this.deliveryZoneRepository = deliveryZoneRepository;
  }

  public Optional<DeliveryZone> get(UUID id) {
    return this.deliveryZoneRepository.findById(id);
  }

  public List<DeliveryZone> list() {
    return this.deliveryZoneRepository.findAll();
  }

  public Optional<DeliveryZone> getByZoneCode(String zoneCode) {
    return this.deliveryZoneRepository.findByZoneCode(zoneCode);
  }

  @Transactional
  public DeliveryZone create(DeliveryZone entity) {
    return this.deliveryZoneRepository.save(entity);
  }

  @Transactional
  public DeliveryZone update(DeliveryZone entity) {
    return this.deliveryZoneRepository.save(entity);
  }

  @Transactional
  public void delete(UUID id) {
    this.deliveryZoneRepository.deleteById(id);
  }
}
