package library_loan_service.errors;

import java.util.List;

/**
 * Business-rule validation failure raised from service-layer logic (as opposed to declarative
 * {@code @Valid}/Bean Validation, which {@link
 * GlobalExceptionHandler#handleMethodArgumentNotValid}/ {@link
 * GlobalExceptionHandler#handleConstraintViolation} already cover). Real, reachable infrastructure
 * ready for a future service-layer generator to throw -- no java service-layer generator raises it
 * yet (python's manual-validation business-rule throw has no java analog currently), the same "spec
 * ahead of consumer" shape the cache-probe plumbing uses.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public class ServiceValidationError extends DatrixBusinessException {

  private final List<String> errors;

  public ServiceValidationError(List<String> errors) {
    super("urn:datrix:error:validation", "Validation Error", "Request validation failed.", 422);
    this.errors = errors;
  }

  public List<String> getErrors() {
    return errors;
  }
}
