// CacheMetrics.cs -- shared prometheus-net metric definitions, rendered
// through the shared infra-client metrics seam.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.

using Prometheus;

namespace BookService.Cache;

public static class CacheMetrics
{
    public static readonly Gauge ConnectionUp = Metrics.CreateGauge(
        "dotnet_cache_connection_up",
        "1 when the cache block's connection health probe last succeeded, 0 otherwise, labeled by cache block.",
        "block"
    );
}
