// RedisCacheHealthCheck.cs -- generated IHealthCheck for cache block "redis".
// Pings the connection this block's CacheConnection.cs
// already registered as a DI singleton -- never a second, independently-
// derived connection. Refreshes CacheMetrics.ConnectionUp on every probe.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.

using Microsoft.Extensions.Diagnostics.HealthChecks;
using StackExchange.Redis;

namespace BookService.Cache;

public sealed class RedisCacheHealthCheck : IHealthCheck
{
    private readonly IConnectionMultiplexer _connection;

    public RedisCacheHealthCheck(IConnectionMultiplexer connection)
    {
        _connection = connection;
    }

    public async Task<HealthCheckResult> CheckHealthAsync(
        HealthCheckContext context,
        CancellationToken cancellationToken = default
    )
    {
        try
        {
            await _connection.GetDatabase().PingAsync().WaitAsync(cancellationToken);
            CacheMetrics.ConnectionUp.WithLabels("redis").Set(1);
            return HealthCheckResult.Healthy();
        }
        catch (Exception ex)
        {
            CacheMetrics.ConnectionUp.WithLabels("redis").Set(0);
            return HealthCheckResult.Unhealthy(ex.Message);
        }
    }
}
