package library_book_service.api;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.delete;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.math.BigDecimal;
import java.util.List;
import java.util.UUID;
import library_book_service.dto.book_db.BookCreateRequest;
import library_book_service.dto.book_db.BookUpdateRequest;
import library_book_service.enums.BookFormat;
import library_book_service.enums.BookStatus;
import library_book_service.model.book_db.Category;
import library_book_service.model.book_db.CategoryTestFactory;
import library_book_service.services.book_db.CategoryService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.WebApplicationContext;

/**
 * Generated HTTP CRUD round-trip test for Book -- real requests via {@link MockMvc} against the
 * real Spring context and DB.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
@Rollback
class BookRoutesTest {

  @Autowired private WebApplicationContext webApplicationContext;

  @Autowired private ObjectMapper objectMapper;

  @Autowired private CategoryService categoryService;

  private MockMvc mockMvc;

  @BeforeEach
  void setUpMockMvc() {
    this.mockMvc = MockMvcBuilders.webAppContextSetup(this.webApplicationContext).build();
  }

  @Test
  void crudLifecycleThroughHttp() throws Exception {
    Category categoryParent = this.categoryService.create(CategoryTestFactory.create());
    BookCreateRequest createBody =
        new BookCreateRequest(
            "test_value",
            "test_value",
            "test_value",
            1,
            BookStatus.AVAILABLE,
            BookFormat.HARDCOVER,
            "test_value",
            List.of(),
            new BigDecimal("10.50"),
            categoryParent.getId());
    MvcResult createResult =
        this.mockMvc
            .perform(
                post("/api/v1/books")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content(this.objectMapper.writeValueAsString(createBody)))
            .andExpect(status().isCreated())
            .andReturn();
    JsonNode created = this.objectMapper.readTree(createResult.getResponse().getContentAsString());
    UUID id = UUID.fromString(created.get("id").asText());

    this.mockMvc.perform(get("/api/v1/books/" + id)).andExpect(status().isOk());

    this.mockMvc.perform(get("/api/v1/books")).andExpect(status().isOk());

    Category categoryAltParent = this.categoryService.create(CategoryTestFactory.create());

    BookUpdateRequest updateBody =
        new BookUpdateRequest(
            "alt_value",
            "alt_value",
            "alt_value",
            2,
            BookStatus.CHECKED_OUT,
            BookFormat.PAPERBACK,
            "alt_value",
            List.of(),
            new BigDecimal("20.75"),
            categoryAltParent.getId());
    this.mockMvc
        .perform(
            put("/api/v1/books/" + id)
                .contentType(MediaType.APPLICATION_JSON)
                .content(this.objectMapper.writeValueAsString(updateBody)))
        .andExpect(status().isOk());

    this.mockMvc.perform(delete("/api/v1/books/" + id)).andExpect(status().isNoContent());

    this.mockMvc.perform(get("/api/v1/books/" + id)).andExpect(status().isNotFound());
  }
}
