test:
  rdbms:
    engine: postgres
    host: localhost
    port: 5432
    database: ecommerce_products
    poolSize: 15
    docker_image: postgres:17-alpine
    volume_path: /var/lib/postgresql/data
    asyncDriver: postgresql+asyncpg
    syncDriver: postgresql+psycopg2
    healthCheckSql: SELECT 1
    defaultUser: postgres
    platform: container
  nosql:
    engine: mongodb
    port: 27017
    uri: mongodb://localhost:27017
    database: ecommerce_product_reviews
    docker_image: mongo:8.0
    volume_path: /data/db
    healthCheckCmd: '["CMD", "mongosh", "--eval", "db.runCommand(\"ping\").ok"]'
    platform: container
development:
  rdbms:
    engine: postgres
    host: localhost
    port: 5432
    database: ecommerce_products
    poolSize: 15
    docker_image: postgres:17-alpine
    volume_path: /var/lib/postgresql/data
    asyncDriver: postgresql+asyncpg
    syncDriver: postgresql+psycopg2
    healthCheckSql: SELECT 1
    defaultUser: postgres
    platform: container
  nosql:
    engine: mongodb
    port: 27017
    uri: mongodb://localhost:27017
    database: ecommerce_product_reviews
    docker_image: mongo:8.0
    volume_path: /data/db
    healthCheckCmd: '["CMD", "mongosh", "--eval", "db.runCommand(\"ping\").ok"]'
    platform: container
production:
  rdbms:
    engine: postgres
    host: ${PRODUCT_DB_HOST}
    port: 5432
    database: ecommerce_products
    poolSize: 40
    ssl: true
    docker_image: postgres:17-alpine
    volume_path: /var/lib/postgresql/data
    asyncDriver: postgresql+asyncpg
    syncDriver: postgresql+psycopg2
    healthCheckSql: SELECT 1
    defaultUser: postgres
    platform: rds
  nosql:
    engine: mongodb
    port: 27017
    uri: ${PRODUCT_NOSQL_URI}
    database: ecommerce_product_reviews
    docker_image: mongo:8.0
    volume_path: /data/db
    healthCheckCmd: '["CMD", "mongosh", "--eval", "db.runCommand(\"ping\").ok"]'
    platform: managed
