/**
 * Minimal structured logging for generated queue clients and workers.
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */
export const logger = {
  info(msg: string): void {
    console.info(msg);
  },
  error(msg: string): void {
    console.error(msg);
  },
};
