package library_member_service.dto.member_db;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import library_member_service.enums.MembershipType;

/**
 * Member create-request DTO.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record MemberCreateRequest(
    @NotNull @Size(max = 100) String firstName,
    @NotNull @Size(max = 100) String lastName,
    @NotNull @Email String email,
    @NotNull @Size(max = 20) String membershipNumber,
    MembershipType membershipType) {}
