// Unit tests for background job configuration.
//
// Auto-generated by datrix-codegen-typescript. Do not edit manually.

describe('Job Configuration', () => {
  describe('DailyOrderReport', () => {
    it('should have a valid cron schedule', () => {
      const schedule = '0 6 * * *';
      const parts = schedule.trim().split(/\s+/);
      expect(parts.length).toBeGreaterThanOrEqual(5);
      expect(parts.length).toBeLessThanOrEqual(6);
    });

    it('should have a positive timeout', () => {
      expect(600).toBeGreaterThan(0);
    });

    it('should have positive max attempts', () => {
      expect(1).toBeGreaterThan(0);
    });

    it('should have positive concurrency', () => {
      expect(1).toBeGreaterThan(0);
    });
  });

  describe('ReconcileOrders', () => {
    it('should have a valid cron schedule', () => {
      const schedule = '0 2 * * *';
      const parts = schedule.trim().split(/\s+/);
      expect(parts.length).toBeGreaterThanOrEqual(5);
      expect(parts.length).toBeLessThanOrEqual(6);
    });

    it('should have a positive timeout', () => {
      expect(300).toBeGreaterThan(0);
    });

    it('should have positive max attempts', () => {
      expect(1).toBeGreaterThan(0);
    });

    it('should have positive concurrency', () => {
      expect(1).toBeGreaterThan(0);
    });
  });

});
