package library_book_service.pubsub.mq;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Profile;
import org.springframework.kafka.annotation.KafkaListener;
import org.springframework.stereotype.Component;

/**
 * Typed Kafka event consumer for the library_book_service.pubsub.mq pubsub block.
 *
 * <p>Dispatches each received envelope's {@code eventType} field to the matching typed handler
 * method.
 *
 * <p>{@code @Profile}-gated to {@code (!isolated-run) | event-consumer- mq}: active in the default
 * web-app boot (no explicit profile -- {@code isolated-run} is unset, matching this service's
 * existing in-process consumption story -- UNLESS this service's {@code runtime.consumers} resolves
 * to {@code decoupled}, in which case {@code Application.java}'s default branch activates {@code
 * isolated-run} too) and in this block's own {@code --datrix.run=event- consumer:mq} container, but
 * NEVER in migrate/seed/ search-init/job-runner/queue-worker/serverless containers (all of which
 * explicitly activate {@code isolated-run}) and never in a SIBLING block's event-consumer container
 * (which activates {@code isolated-run} together with only ITS OWN block's profile) -- closing the
 * latent duplicate- consumption bug where this `@KafkaListener` previously activated
 * unconditionally on every non-web container boot.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Component
@Profile("(!isolated-run) | event-consumer-mq")
public class MqKafkaEventConsumer {

  private static final Logger logger = LoggerFactory.getLogger(MqKafkaEventConsumer.class);

  private final ObjectMapper objectMapper;

  @PersistenceContext private EntityManager entityManager;

  public MqKafkaEventConsumer(ObjectMapper objectMapper) {
    this.objectMapper = objectMapper;
  }

  @KafkaListener(
      topics = {"library_book_service.mq.book_events"},
      groupId = "library-book-service.mq")
  public void onMessage(ConsumerRecord<String, byte[]> record) {
    String eventType = null;
    try {
      JsonNode envelope = objectMapper.readTree(record.value());
      eventType = envelope.path("eventType").asText();
      JsonNode payloadNode = envelope.path("payload");
      switch (eventType) {
        case "BookAdded" ->
            handleBookEventsBookAdded(objectMapper.treeToValue(payloadNode, BookAdded.class));
        case "BookStatusChanged" ->
            handleBookEventsBookStatusChanged(
                objectMapper.treeToValue(payloadNode, BookStatusChanged.class));
        default ->
            logger.warn("unknown_event_type eventType={} topic={}", eventType, record.topic());
      }
    } catch (Exception e) {
      logger.error("event_dispatch_failed eventType={} error={}", eventType, e.getMessage(), e);
    }
  }

  private void handleBookEventsBookAdded(BookAdded payload) {
    logger.info(
        "event_received event={} topic={}", "BookAdded", "library_book_service.mq.book_events");
    var bookId = payload.bookId();
    var title = payload.title();
    logger.info("New book added");
  }

  private void handleBookEventsBookStatusChanged(BookStatusChanged payload) {
    logger.info(
        "event_received event={} topic={}",
        "BookStatusChanged",
        "library_book_service.mq.book_events");
    var bookId = payload.bookId();
    var oldStatus = payload.oldStatus();
    var newStatus = payload.newStatus();
    logger.info("Book %s status changed from %s to %s".formatted(bookId, oldStatus, newStatus));
  }
}
