package library_book_service.services.book_db;

import jakarta.persistence.EntityManager;
import jakarta.persistence.PersistenceContext;
import java.util.List;
import java.util.Optional;
import java.util.UUID;
import library_book_service.model.book_db.Book;
import library_book_service.model.book_db.Category;
import library_book_service.repositories.book_db.BookRepository;
import library_book_service.services.ServiceBase;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Book service -- request-scoped unit-of-work wrapper over {@link BookRepository }.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Service
public class BookService extends ServiceBase {

  private final BookRepository bookRepository;

  @PersistenceContext private EntityManager entityManager;

  public BookService(BookRepository bookRepository) {
    this.bookRepository = bookRepository;
  }

  public Optional<Book> get(UUID id) {
    return this.bookRepository.findById(id);
  }

  public List<Book> list() {
    return this.bookRepository.findAll();
  }

  public List<Book> getByCategoryId(UUID categoryId) {
    return this.bookRepository.findByCategoryId(categoryId);
  }

  public Page<Book> listByCategory(UUID categoryId, Pageable pageable) {
    return this.bookRepository.findByCategoryId(categoryId, pageable);
  }

  public Category getCategoryReference(UUID id) {
    return this.entityManager.getReference(Category.class, id);
  }

  @Transactional
  public Book create(Book entity) {
    return this.bookRepository.save(entity);
  }

  @Transactional
  public Book update(Book entity) {
    return this.bookRepository.save(entity);
  }

  @Transactional
  public void delete(UUID id) {
    this.bookRepository.deleteById(id);
  }
}
