package library_book_service.model.book_db;

import jakarta.persistence.CheckConstraint;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.FetchType;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PostLoad;
import jakarta.persistence.Table;
import jakarta.persistence.Transient;
import java.math.BigDecimal;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import library_book_service.enums.BookFormat;
import library_book_service.enums.BookStatus;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

/**
 * Book JPA entity.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@EntityListeners({BookLifecycleListener.class})
@Entity
@Table(
    name = "books",
    indexes = {},
    uniqueConstraints = {},
    check = {
      @CheckConstraint(name = "ck_books_title_max_length", constraint = "length(title) <= 200"),
      @CheckConstraint(name = "ck_books_isbn_min_length", constraint = "length(isbn) >= 10"),
      @CheckConstraint(name = "ck_books_isbn_max_length", constraint = "length(isbn) <= 13"),
      @CheckConstraint(name = "ck_books_author_max_length", constraint = "length(author) <= 100"),
      @CheckConstraint(
          name = "ck_books_catalog_number_max_length",
          constraint = "length(catalog_number) <= 50")
    })
public class Book extends BaseEntity {

  @Column(name = "title", columnDefinition = "varchar(200)", nullable = false)
  private String title;

  @Column(name = "isbn", columnDefinition = "varchar(13)", nullable = false)
  private String isbn;

  @Column(name = "author", columnDefinition = "varchar(100)", nullable = false)
  private String author;

  @Column(name = "publicationYear", columnDefinition = "integer", nullable = false)
  private Integer publicationYear;

  @Column(name = "status", columnDefinition = "varchar(255)", nullable = false)
  private BookStatus status = BookStatus.AVAILABLE;

  @Column(name = "format", columnDefinition = "varchar(255)", nullable = false)
  private BookFormat format = BookFormat.HARDCOVER;

  @Column(name = "catalogNumber", columnDefinition = "varchar(50)", nullable = true)
  private String catalogNumber;

  @JdbcTypeCode(SqlTypes.JSON)
  @Column(name = "keywords", nullable = false)
  private List<String> keywords = List.of();

  @Column(name = "rating", columnDefinition = "numeric(3, 2)", nullable = false)
  private BigDecimal rating = BigDecimal.valueOf(0.0);

  @ManyToOne(fetch = FetchType.LAZY)
  @JoinColumn(name = "category_id", nullable = false)
  private Category category;

  /**
   * Snapshot of tracked field values captured at load time, read by this entity's {@link
   * BookLifecycleListener} to answer {@code isChanged}/{@code oldValue}.
   *
   * <p>JPA has no direct "original entity before this flush" hook outside {@code @PostLoad} (unlike
   * an ORM change-set view captured at update time), so this snapshot is captured ONCE PER LOAD and
   * carried forward across the managed entity's lifetime instead. Never populated from Hibernate's
   * dirty-tracking or interceptor SPI -- always this explicit map.
   */
  @Transient private Map<String, Object> datrixOldValues;

  @PostLoad
  private void snapshotDatrixOldValues() {
    this.datrixOldValues = new HashMap<>();
    this.datrixOldValues.put("id", this.getId());
    this.datrixOldValues.put("createdAt", this.getCreatedAt());
    this.datrixOldValues.put("updatedAt", this.getUpdatedAt());
    this.datrixOldValues.put("title", this.title);
    this.datrixOldValues.put("isbn", this.isbn);
    this.datrixOldValues.put("author", this.author);
    this.datrixOldValues.put("publicationYear", this.publicationYear);
    this.datrixOldValues.put("status", this.status);
    this.datrixOldValues.put("format", this.format);
    this.datrixOldValues.put("catalogNumber", this.catalogNumber);
    this.datrixOldValues.put("keywords", this.keywords);
    this.datrixOldValues.put("rating", this.rating);
  }

  public Map<String, Object> getDatrixOldValues() {
    return this.datrixOldValues;
  }

  public String getTitle() {
    return this.title;
  }

  public void setTitle(String title) {
    this.title = title;
  }

  public String getIsbn() {
    return this.isbn;
  }

  public void setIsbn(String isbn) {
    this.isbn = isbn;
  }

  public String getAuthor() {
    return this.author;
  }

  public void setAuthor(String author) {
    this.author = author;
  }

  public Integer getPublicationYear() {
    return this.publicationYear;
  }

  public void setPublicationYear(Integer publicationYear) {
    this.publicationYear = publicationYear;
  }

  public BookStatus getStatus() {
    return this.status;
  }

  public void setStatus(BookStatus status) {
    this.status = status;
  }

  public BookFormat getFormat() {
    return this.format;
  }

  public void setFormat(BookFormat format) {
    this.format = format;
  }

  public String getCatalogNumber() {
    return this.catalogNumber;
  }

  public void setCatalogNumber(String catalogNumber) {
    this.catalogNumber = catalogNumber;
  }

  public List<String> getKeywords() {
    return this.keywords;
  }

  public void setKeywords(List<String> keywords) {
    this.keywords = keywords;
  }

  public BigDecimal getRating() {
    return this.rating;
  }

  public void setRating(BigDecimal rating) {
    this.rating = rating;
  }

  public Category getCategory() {
    return this.category;
  }

  public void setCategory(Category category) {
    this.category = category;
  }

  /** Computed: (Objects.equals(this.getStatus(), BookStatus.AVAILABLE)) */
  @Transient
  public Boolean getIsAvailable() {
    return (Objects.equals(this.getStatus(), BookStatus.AVAILABLE));
  }

  /** Computed: "%s (%s)".formatted(this.getTitle(), this.getPublicationYear()) */
  @Transient
  public String getDisplayTitle() {
    return "%s (%s)".formatted(this.getTitle(), this.getPublicationYear());
  }

  /**
   * Build a new {@link Book} from a DSL object-literal map, setting only the keys present in {@code
   * data} (a key absent from {@code data} leaves the corresponding field at its normal Java default
   * -- {@code null} unless the field declares its own initializer above). Keys are the AS-AUTHORED
   * DSL field name (Java's own object-literal emission, {@code _datrixOrderedMap(...)}, preserves
   * author-declared spelling -- no case conversion), which for a camelCase-authored DSL field is
   * identical to this entity's own camelCase Java field name.
   *
   * <p>Backs {@code db.Book.create({...})} lowering (`transpiler/
   * _entity_query_dispatch.py::transpile_entity_create`) -- entities have no `Map`-consuming
   * constructor, so the transpiled object literal is fed through this static factory instead of
   * `new Book(...)`.
   */
  public static Book fromMap(java.util.Map<String, Object> data) {
    Book result = new Book();
    if (data.containsKey("title")) {
      Object __v = data.get("title");
      result.setTitle((String) __v);
    }
    if (data.containsKey("isbn")) {
      Object __v = data.get("isbn");
      result.setIsbn((String) __v);
    }
    if (data.containsKey("author")) {
      Object __v = data.get("author");
      result.setAuthor((String) __v);
    }
    if (data.containsKey("publicationYear")) {
      Object __v = data.get("publicationYear");
      result.setPublicationYear(__v instanceof Integer __n ? __n : ((Number) __v).intValue());
    }
    if (data.containsKey("status")) {
      Object __v = data.get("status");
      result.setStatus((BookStatus) __v);
    }
    if (data.containsKey("format")) {
      Object __v = data.get("format");
      result.setFormat((BookFormat) __v);
    }
    if (data.containsKey("catalogNumber")) {
      Object __v = data.get("catalogNumber");
      result.setCatalogNumber((String) __v);
    }
    if (data.containsKey("keywords")) {
      Object __v = data.get("keywords");
      result.setKeywords((List<String>) __v);
    }
    if (data.containsKey("rating")) {
      Object __v = data.get("rating");
      result.setRating(
          __v instanceof java.math.BigDecimal __n ? __n : new java.math.BigDecimal(__v.toString()));
    }
    return result;
  }
}
