// <auto-generated>
// Generated by datrix-codegen-dotnet. Do not edit by hand.
// </auto-generated>
#nullable enable
// CQRS command/query bus -- a self-contained, hand-generated dispatch
// implementation with no external command/query dispatch library dependency.
// Every ICommandHandler<TCommand, TResult>/IQueryHandler<TQuery, TResult> is
// resolved via a CLOSED generic DI registration (below), so dispatch stays
// fully compile-time-checked -- no reflection-based type construction, no
// runtime type resolution tricks.

using System;
using System.Threading.Tasks;
using Microsoft.Extensions.DependencyInjection;
using BookService.Cqrs.Commands;
using BookService.Cqrs.Queries;
using BookService.Cqrs.Views;
using BookService.Data;
using BookService.Enums;
using BookService.Models.BookDb;

namespace BookService.Cqrs;

public interface ICommand<TResult> { }

public interface IQuery<TResult> { }

public interface ICommandHandler<TCommand, TResult> where TCommand : ICommand<TResult>
{
    Task<TResult> HandleAsync(TCommand command);
}

public interface IQueryHandler<TQuery, TResult> where TQuery : IQuery<TResult>
{
    Task<TResult> HandleAsync(TQuery query);
}

public interface ICommandBus
{
    Task<TResult> SendAsync<TCommand, TResult>(TCommand command) where TCommand : ICommand<TResult>;
}

public interface IQueryBus
{
    Task<TResult> SendAsync<TQuery, TResult>(TQuery query) where TQuery : IQuery<TResult>;
}

public sealed class CqrsCommandBus : ICommandBus
{
    private readonly IServiceProvider services;

    public CqrsCommandBus(IServiceProvider services)
    {
        this.services = services;
    }

    public Task<TResult> SendAsync<TCommand, TResult>(TCommand command) where TCommand : ICommand<TResult>
    {
        var handler = services.GetRequiredService<ICommandHandler<TCommand, TResult>>();
        return handler.HandleAsync(command);
    }
}

public sealed class CqrsQueryBus : IQueryBus
{
    private readonly IServiceProvider services;

    public CqrsQueryBus(IServiceProvider services)
    {
        this.services = services;
    }

    public Task<TResult> SendAsync<TQuery, TResult>(TQuery query) where TQuery : IQuery<TResult>
    {
        var handler = services.GetRequiredService<IQueryHandler<TQuery, TResult>>();
        return handler.HandleAsync(query);
    }
}

public static class CqrsRegistration
{
    public static IServiceCollection AddCqrs(this IServiceCollection services)
    {
        services.AddScoped<ICommandBus, CqrsCommandBus>();
        services.AddScoped<IQueryBus, CqrsQueryBus>();
        services.AddScoped<ICommandHandler<UpdateBookStatus, Book>, UpdateBookStatusHandler>();
        services.AddScoped<IQueryHandler<GetAvailableBooks, List<BookCatalogView>>, GetAvailableBooksHandler>();
        services.AddScoped<IQueryHandler<SearchCatalog, List<BookCatalogView>>, SearchCatalogHandler>();
        return services;
    }
}
