package library_member_service.repositories.member_db;

import java.util.Optional;
import java.util.UUID;
import library_member_service.model.member_db.Member;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

/**
 * Member Spring Data JPA repository.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public interface MemberRepository
    extends JpaRepository<Member, UUID>, JpaSpecificationExecutor<Member> {

  Optional<Member> findByEmail(String email);

  Optional<Member> findByMembershipNumber(String membershipNumber);
}
