package library_book_service.enums;

/**
 * BookFormat enum.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public enum BookFormat {
  HARDCOVER,
  PAPERBACK,
  E_BOOK,
  AUDIOBOOK;
}
