"""Book ORM model.
Database: bookDb (postgres)
Auto-generated by datrix-codegen-python. Do not edit manually.
"""

from __future__ import annotations

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import CheckConstraint, Enum, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from library_book_service.enums.book_status import BookStatus

if TYPE_CHECKING:
    from library_book_service.models.book_db.category import Category

from library_book_service.models.book_db.base_entity import BaseEntity


class Book(BaseEntity):
    """Book ORM model."""

    __tablename__ = "books"

    title: Mapped[str] = mapped_column(
        String(200),
    )
    author: Mapped[str] = mapped_column(
        String(100),
    )
    publication_year: Mapped[int] = mapped_column(
        Integer,
    )
    status: Mapped[BookStatus] = mapped_column(
        Enum(BookStatus, name="book_status", _create_events=False),
        default=BookStatus.available,
    )

    category_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("categories.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
    )
    category: Mapped["Category"] = relationship(
        "Category",
        back_populates="books",
    )

    __table_args__ = (
        CheckConstraint("length(title) <= 200", name="ck_books_title_max_length"),
        CheckConstraint("length(author) <= 100", name="ck_books_author_max_length"),
    )
