"""Category ORM model.
Database: bookDb (postgres)
Auto-generated by datrix-codegen-python. Do not edit manually.
"""

from __future__ import annotations

from typing import TYPE_CHECKING

from sqlalchemy import CheckConstraint, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

if TYPE_CHECKING:
    from library_book_service.models.book_db.book import Book

from library_book_service.models.book_db.base_entity import BaseEntity


class Category(BaseEntity):
    """Category ORM model."""

    __tablename__ = "categories"

    name: Mapped[str] = mapped_column(
        String(100),
        unique=True,
    )

    books: Mapped[list["Book"]] = relationship(
        "Book",
        back_populates="category",
    )

    __table_args__ = (
        CheckConstraint("length(name) <= 100", name="ck_categories_name_max_length"),
    )
