package library_member_service.security;

import java.util.Map;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.http.HttpHeaders;
import org.springframework.http.HttpStatus;
import org.springframework.http.server.ServerHttpRequest;
import org.springframework.http.server.ServerHttpResponse;
import org.springframework.security.oauth2.jwt.Jwt;
import org.springframework.security.oauth2.jwt.JwtException;
import org.springframework.web.socket.CloseStatus;
import org.springframework.web.socket.TextMessage;
import org.springframework.web.socket.WebSocketHandler;
import org.springframework.web.socket.WebSocketSession;
import org.springframework.web.socket.config.annotation.EnableWebSocket;
import org.springframework.web.socket.config.annotation.WebSocketConfigurer;
import org.springframework.web.socket.config.annotation.WebSocketHandlerRegistry;
import org.springframework.web.socket.handler.TextWebSocketHandler;
import org.springframework.web.socket.server.HandshakeInterceptor;

/**
 * Identity WebSocket endpoint for library_member_service.security (D9).
 *
 * <p>Registers the identity WS handler behind {@link AuthHandshakeInterceptor}, which validates
 * every upgrade request through the SAME generated {@link DatrixJwtDecoder} the REST {@code
 * SecurityFilterChainConfig} uses -- one auth contract, two transports. A missing or invalid token
 * rejects the handshake (401) BEFORE the protocol ever switches to WebSocket; there is no
 * unauthenticated WS session, even transiently.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Configuration
@EnableWebSocket
public class IdentityWebSocketConfig implements WebSocketConfigurer {

  private static final Logger LOG = LoggerFactory.getLogger(IdentityWebSocketConfig.class);

  /**
   * Fixed identity WebSocket route. Data-driven from the SAME identity declaration that gates
   * emission of this file at all (service_validates_via_jwks) -- the route name itself is a
   * framework-owned convention, the SAME "framework-owned infra paths are the ONLY exception" rule
   * the REST {@code SecurityFilterChainConfig} follows for {@code /health}, {@code /actuator/**},
   * etc.
   */
  public static final String IDENTITY_WS_PATH = "/ws/identity";

  private final DatrixJwtDecoder datrixJwtDecoder;

  public IdentityWebSocketConfig(DatrixJwtDecoder datrixJwtDecoder) {
    this.datrixJwtDecoder = datrixJwtDecoder;
  }

  @Override
  public void registerWebSocketHandlers(WebSocketHandlerRegistry registry) {
    registry
        .addHandler(identityWebSocketHandler(), IDENTITY_WS_PATH)
        .addInterceptors(new AuthHandshakeInterceptor(this.datrixJwtDecoder));
  }

  @Bean
  public WebSocketHandler identityWebSocketHandler() {
    return new IdentityWebSocketHandler();
  }

  /**
   * Handshake-time authentication -- the SAME verification semantics as {@code DatrixJwtDecoder}
   * (asymmetric-only, audience-enforced, fail-closed JWKS refresh). Extracts the bearer token from
   * the {@code Authorization} header of the upgrade request (the SAME source Spring Security's own
   * JWT resource-server filter reads for REST requests); a missing or invalid token sets 401 and
   * declines the handshake -- {@link #beforeHandshake} is solely responsible for the response
   * status on rejection, per the {@link HandshakeInterceptor} contract.
   */
  static class AuthHandshakeInterceptor implements HandshakeInterceptor {

    /** Handshake attribute key carrying the authenticated principal's subject. */
    static final String ATTR_PRINCIPAL = "identityPrincipal";

    /** Handshake attribute key carrying the authenticated principal's roles. */
    static final String ATTR_ROLES = "identityRoles";

    private static final String BEARER_PREFIX = "Bearer ";

    private final DatrixJwtDecoder datrixJwtDecoder;

    AuthHandshakeInterceptor(DatrixJwtDecoder datrixJwtDecoder) {
      this.datrixJwtDecoder = datrixJwtDecoder;
    }

    @Override
    public boolean beforeHandshake(
        ServerHttpRequest request,
        ServerHttpResponse response,
        WebSocketHandler wsHandler,
        Map<String, Object> attributes) {
      String token = extractToken(request);
      if (token == null) {
        return reject(response, AuthReasonCode.MISSING_TOKEN);
      }
      try {
        Jwt jwt = this.datrixJwtDecoder.decode(token);
        attributes.put(ATTR_PRINCIPAL, jwt.getSubject());
        attributes.put(ATTR_ROLES, jwt.getClaim("roles"));
        return true;
      } catch (DatrixJwtDecoder.JwksValidationException ex) {
        return reject(response, ex.reasonCode());
      } catch (JwtException ex) {
        return reject(response, AuthReasonCode.MALFORMED_TOKEN);
      }
    }

    @Override
    public void afterHandshake(
        ServerHttpRequest request,
        ServerHttpResponse response,
        WebSocketHandler wsHandler,
        Exception exception) {
      if (exception != null) {
        LOG.warn("identity_ws_handshake_error error={}", exception.getMessage());
      }
    }

    private static String extractToken(ServerHttpRequest request) {
      String header = request.getHeaders().getFirst(HttpHeaders.AUTHORIZATION);
      if (header != null && header.startsWith(BEARER_PREFIX)) {
        return header.substring(BEARER_PREFIX.length()).trim();
      }
      return null;
    }

    /**
     * Reject the handshake: set 401 and return {@code false}. The reason code is LOGGED ONLY --
     * never written into the response, the SAME RFC 7807 opacity rule {@code
     * SecurityFilterChainConfig}'s {@code OpaqueAuthenticationEntryPoint} follows for REST 401s.
     */
    private static boolean reject(ServerHttpResponse response, AuthReasonCode reasonCode) {
      LOG.warn("identity_ws_upgrade_rejected reason_code={}", reasonCode);
      response.setStatusCode(HttpStatus.UNAUTHORIZED);
      return false;
    }
  }

  /**
   * Minimal identity WS session handler. By the time a session reaches this handler the upgrade has
   * already been authenticated by {@link AuthHandshakeInterceptor} -- there is no unauthenticated
   * session, even transiently.
   */
  static class IdentityWebSocketHandler extends TextWebSocketHandler {

    private static final String CONNECTED_MESSAGE = "{\"status\":\"authenticated\"}";

    @Override
    public void afterConnectionEstablished(WebSocketSession session) throws Exception {
      Object principal = session.getAttributes().get(AuthHandshakeInterceptor.ATTR_PRINCIPAL);
      LOG.info("identity_ws_connected sessionId={} principal={}", session.getId(), principal);
      session.sendMessage(new TextMessage(CONNECTED_MESSAGE));
    }

    @Override
    public void afterConnectionClosed(WebSocketSession session, CloseStatus status) {
      LOG.debug("identity_ws_disconnected sessionId={} status={}", session.getId(), status);
    }
  }
}
