package library_loan_service.api;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.post;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.put;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.status;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.time.OffsetDateTime;
import java.util.UUID;
import library_loan_service.dto.loan_db.LoanCreateRequest;
import library_loan_service.dto.loan_db.LoanUpdateRequest;
import library_loan_service.enums.LoanStatus;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.http.MediaType;
import org.springframework.test.annotation.Rollback;
import org.springframework.test.context.ActiveProfiles;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.MvcResult;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.WebApplicationContext;

/**
 * Generated HTTP CRUD round-trip test for Loan -- real requests via {@link MockMvc} against the
 * real Spring context and DB.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@SpringBootTest
@ActiveProfiles("test")
@Transactional
@Rollback
class LoanRoutesTest {

  @Autowired private WebApplicationContext webApplicationContext;

  @Autowired private ObjectMapper objectMapper;

  private MockMvc mockMvc;

  @BeforeEach
  void setUpMockMvc() {
    this.mockMvc = MockMvcBuilders.webAppContextSetup(this.webApplicationContext).build();
  }

  @Test
  void crudLifecycleThroughHttp() throws Exception {
    LoanCreateRequest createBody =
        new LoanCreateRequest(
            UUID.fromString("550e8400-e29b-41d4-a716-446655440000"),
            UUID.fromString("550e8400-e29b-41d4-a716-446655440000"),
            LoanStatus.ACTIVE,
            OffsetDateTime.parse("2025-01-15T12:00:00Z"),
            OffsetDateTime.parse("2025-01-15T12:00:00Z"));
    MvcResult createResult =
        this.mockMvc
            .perform(
                post("/api/v1/loans/loans")
                    .contentType(MediaType.APPLICATION_JSON)
                    .content(this.objectMapper.writeValueAsString(createBody)))
            .andExpect(status().isCreated())
            .andReturn();
    JsonNode created = this.objectMapper.readTree(createResult.getResponse().getContentAsString());
    UUID id = UUID.fromString(created.get("id").asText());

    this.mockMvc.perform(get("/api/v1/loans/loans/" + id)).andExpect(status().isOk());

    LoanUpdateRequest updateBody =
        new LoanUpdateRequest(
            UUID.fromString("650e8400-e29b-41d4-a716-446655440001"),
            UUID.fromString("650e8400-e29b-41d4-a716-446655440001"),
            LoanStatus.RETURNED,
            OffsetDateTime.parse("2025-06-20T09:15:00Z"),
            OffsetDateTime.parse("2025-06-20T09:15:00Z"));
    this.mockMvc
        .perform(
            put("/api/v1/loans/loans/" + id)
                .contentType(MediaType.APPLICATION_JSON)
                .content(this.objectMapper.writeValueAsString(updateBody)))
        .andExpect(status().isOk());
  }
}
