package library_member_service;

/**
 * Constants -- service-level constants.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public final class Constants {

  private Constants() {}

  // From datrix.foundation
  public static final int MAX_PAGE_SIZE = 100;
  public static final int DEFAULT_PAGE_SIZE = 20;
}
