package library_book_service.nosql.docdb.models;

import java.time.OffsetDateTime;
import java.util.Map;
import java.util.UUID;
import org.bson.codecs.pojo.annotations.BsonProperty;

/**
 * Document model for BookRating (collection, mongodb). Maps to the _id primary key.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public class BookRatingDocument {

  private UUID bookId;
  private UUID memberId;
  private Integer rating;
  private String review;
  private OffsetDateTime createdAt;

  public BookRatingDocument() {}

  /** Builds a document from a raw field map (transpiled DSL {@code insert()} payload). */
  @SuppressWarnings("unchecked")
  public BookRatingDocument(Map<String, Object> data) {
    if (data.containsKey("bookId")) {
      this.bookId = (UUID) data.get("bookId");
    }
    if (data.containsKey("memberId")) {
      this.memberId = (UUID) data.get("memberId");
    }
    if (data.containsKey("rating")) {
      this.rating = (Integer) data.get("rating");
    }
    if (data.containsKey("review")) {
      this.review = (String) data.get("review");
    }
    if (data.containsKey("createdAt")) {
      this.createdAt = (OffsetDateTime) data.get("createdAt");
    }
  }

  @BsonProperty("bookId")
  public UUID getBookId() {
    return this.bookId;
  }

  public void setBookId(UUID bookId) {
    this.bookId = bookId;
  }

  @BsonProperty("memberId")
  public UUID getMemberId() {
    return this.memberId;
  }

  public void setMemberId(UUID memberId) {
    this.memberId = memberId;
  }

  public Integer getRating() {
    return this.rating;
  }

  public void setRating(Integer rating) {
    this.rating = rating;
  }

  public String getReview() {
    return this.review;
  }

  public void setReview(String review) {
    this.review = review;
  }

  @BsonProperty("createdAt")
  public OffsetDateTime getCreatedAt() {
    return this.createdAt;
  }

  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }
}
