// BookTagFactory.cs -- generated test-data factory.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using BookService.Models.BookDb;

namespace BookService.Tests.Factories.BookDb;

internal static class BookTagFactory
{
    internal static BookTag Create(Action<BookTag>? configure = null)
    {
        var entity = new BookTag
        {
            Id = Guid.NewGuid(),
            CreatedAt = new DateTimeOffset(2025, 1, 15, 12, 0, 0, TimeSpan.Zero),
            UpdatedAt = new DateTimeOffset(2025, 1, 15, 12, 0, 0, TimeSpan.Zero),
            BookId = Guid.NewGuid(),
            TagId = Guid.NewGuid(),
        };
        configure?.Invoke(entity);
        return entity;
    }
}
