// Book.cs -- generated DTO records (Create/Update/Response) with
// System.ComponentModel.DataAnnotations validation attributes.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using System.ComponentModel.DataAnnotations;
using BookService.Enums;

namespace BookService.Dtos.BookDb;

public sealed record CreateBookRequest
{
    [Required]
    [MaxLength(200)]
    public required string Title { get; init; }

    [Required]
    [MaxLength(13)]
    public required string Isbn { get; init; }

    [Required]
    [MaxLength(100)]
    public required string Author { get; init; }

    [Required]
    public required int PublicationYear { get; init; }

    [Required]
    public required BookStatus Status { get; init; }

    [Required]
    public required BookFormat Format { get; init; }

    [MaxLength(50)]
    public string? CatalogNumber { get; init; }

    [Required]
    public required List<string> Keywords { get; init; }

    [Required]
    public required decimal Rating { get; init; }

    [Required]
    public required Guid CategoryId { get; init; }
}

public sealed record UpdateBookRequest
{
    [MaxLength(200)]
    public string? Title { get; init; }

    [MaxLength(13)]
    public string? Isbn { get; init; }

    [MaxLength(100)]
    public string? Author { get; init; }

    public int? PublicationYear { get; init; }

    public BookStatus? Status { get; init; }

    public BookFormat? Format { get; init; }

    [MaxLength(50)]
    public string? CatalogNumber { get; init; }

    public List<string>? Keywords { get; init; }

    public decimal? Rating { get; init; }

    public Guid? CategoryId { get; init; }
}

public sealed record BookResponse
{
    [Required]
    public required Guid Id { get; init; }

    [Required]
    public required DateTimeOffset CreatedAt { get; init; }

    [Required]
    public required DateTimeOffset UpdatedAt { get; init; }

    [Required]
    [MaxLength(200)]
    public required string Title { get; init; }

    [Required]
    [MaxLength(13)]
    public required string Isbn { get; init; }

    [Required]
    [MaxLength(100)]
    public required string Author { get; init; }

    [Required]
    public required int PublicationYear { get; init; }

    [Required]
    public required BookStatus Status { get; init; }

    [Required]
    public required BookFormat Format { get; init; }

    [MaxLength(50)]
    public string? CatalogNumber { get; init; }

    [Required]
    public required List<string> Keywords { get; init; }

    [Required]
    public required decimal Rating { get; init; }

    [Required]
    public required Guid CategoryId { get; init; }

    [Required]
    public required bool IsAvailable { get; init; }

    [Required]
    public required string DisplayTitle { get; init; }

    [Required]
    public required bool IsOldBook { get; init; }

    [Required]
    public required string TitleLower { get; init; }

    [Required]
    public required int TitleLength { get; init; }

    [Required]
    public required List<string> TitleWords { get; init; }

    [Required]
    public required int KeywordCount { get; init; }

    [Required]
    public required string KeywordsJoined { get; init; }

    [Required]
    public required decimal RatingRounded { get; init; }
}
