// Tag.cs -- generated DTO records (Create/Update/Response) with
// System.ComponentModel.DataAnnotations validation attributes.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using System.ComponentModel.DataAnnotations;

namespace BookService.Dtos.BookDb;

public sealed record CreateTagRequest
{
    [Required]
    [MaxLength(50)]
    public required string Name { get; init; }

    [MaxLength(200)]
    public string? Description { get; init; }
}

public sealed record UpdateTagRequest
{
    [MaxLength(50)]
    public string? Name { get; init; }

    [MaxLength(200)]
    public string? Description { get; init; }
}

public sealed record TagResponse
{
    [Required]
    public required Guid Id { get; init; }

    [Required]
    public required DateTimeOffset CreatedAt { get; init; }

    [Required]
    public required DateTimeOffset UpdatedAt { get; init; }

    [Required]
    [MaxLength(50)]
    public required string Name { get; init; }

    [MaxLength(200)]
    public string? Description { get; init; }
}
