#!/usr/bin/env python3
"""Deploy this application with Docker Compose.

Generated by Datrix -- do not edit manually.

Run it through the generated shell entrypoints, which activate the project
virtual environment first::

    scripts/deploy.sh      # bash / zsh
    .\\scripts\\deploy.ps1   # PowerShell

This module is the ONE implementation of the deployment; both entrypoints are
thin wrappers around it, so a bash operator and a PowerShell operator run
byte-identical logic. It uses only the Python standard library and drives
``docker`` as a subprocess.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path
from typing import NamedTuple, Sequence

# ---------------------------------------------------------------------------
# Project root anchor
# ---------------------------------------------------------------------------
# This script lives in <project-root>/scripts, and the compose file, the
# environment file and the base image's build context are all relative to the
# project root. Anchoring here makes the deployment behave identically however
# it was launched.
PROJECT_ROOT = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Generated configuration
# ---------------------------------------------------------------------------

#: Shared per-system base image every service Dockerfile is FROM. ``None`` when
#: the system has no shared base image, in which case compose builds everything.
BASE_IMAGE_TAG = "library-system-python-base:138a7c14f0ab"
BASE_IMAGE_DIR = "python-base"

#: Compose reads secrets and configuration from this file. It must exist before
#: deploying, and the generated template names every value it expects.
ENV_FILE = ".env"
ENV_TEMPLATE = ".env.example"


class DeployError(RuntimeError):
    """A fatal, operator-actionable deployment failure."""


class CommandResult(NamedTuple):
    """Outcome of one external command."""

    returncode: int
    output: str

    @property
    def succeeded(self) -> bool:
        """True when the command exited zero."""
        return self.returncode == 0


def step(message: str) -> None:
    """Announce a new phase of the deployment."""
    print(f"==> {message}", flush=True)


def resolve_docker() -> str:
    """Return the absolute path of the docker executable, or fail loud.

    Raises:
        DeployError: If docker is not on PATH.
    """
    resolved = shutil.which("docker")
    if resolved is None:
        raise DeployError("'docker' not found. Install Docker.")
    return resolved


def docker(*args: str, capture: bool = True) -> CommandResult:
    """Run one ``docker`` invocation from the project root."""
    completed = subprocess.run(
        [resolve_docker(), *args],
        capture_output=capture,
        text=True,
        encoding="utf-8",
        errors="replace",
        cwd=PROJECT_ROOT,
    )
    if not capture:
        return CommandResult(returncode=completed.returncode, output="")
    parts = (completed.stdout or "", completed.stderr or "")
    return CommandResult(
        returncode=completed.returncode,
        output="\n".join(part.strip() for part in parts if part.strip()),
    )


def require_compose() -> None:
    """Fail loud unless Docker Compose v2 is available.

    Raises:
        DeployError: If the compose plugin is missing.
    """
    if docker("compose", "version").succeeded:
        return
    raise DeployError(
        "'docker compose' is not available. Install Docker Compose v2 (it ships "
        "with Docker Desktop and as the 'docker-compose-plugin' package)."
    )


def require_env_file() -> None:
    """Fail loud unless the compose environment file exists.

    Raises:
        DeployError: If it is missing, naming the template to copy when there
            is one.
    """
    if (PROJECT_ROOT / ENV_FILE).is_file():
        return
    if (PROJECT_ROOT / ENV_TEMPLATE).is_file():
        raise DeployError(
            f"'{ENV_FILE}' not found. Create it from the template and fill in "
            f"the required values:\n  cp {ENV_TEMPLATE} {ENV_FILE}"
        )
    raise DeployError(
        f"'{ENV_FILE}' not found, and there is no '{ENV_TEMPLATE}' to copy from."
    )


def build_base_image() -> None:
    """Build the shared base image when the local daemon does not have it.

    Every service Dockerfile is ``FROM`` this tag, and compose never builds a
    ``FROM`` image -- so the base must exist locally BEFORE the services build.
    The tag is a content hash of the dependency union, so this rebuilds only
    when that union changes, which makes it idempotent.

    Raises:
        DeployError: If the build failed.
    """
    if BASE_IMAGE_TAG is None or BASE_IMAGE_DIR is None:
        return
    if docker("image", "inspect", BASE_IMAGE_TAG).succeeded:
        return
    step(f"Building shared base image {BASE_IMAGE_TAG}")
    result = docker("build", "-t", BASE_IMAGE_TAG, f"./{BASE_IMAGE_DIR}", capture=False)
    if not result.succeeded:
        raise DeployError(
            f"Building the shared base image '{BASE_IMAGE_TAG}' failed (docker "
            f"exited {result.returncode}). Every service image is FROM this tag, "
            f"so the deployment cannot proceed."
        )


def compose_up() -> None:
    """Build and start every service, then report their status.

    Raises:
        DeployError: If compose could not bring the services up.
    """
    step("Building and starting services")
    result = docker("compose", "up", "-d", "--build", capture=False)
    if not result.succeeded:
        raise DeployError(
            f"'docker compose up' failed (exit {result.returncode}). Review the "
            f"build and startup output above."
        )
    step("Service status")
    docker("compose", "ps", capture=False)


def main(argv: Sequence[str] | None = None) -> int:
    """Entry point: check the prerequisites, then bring the stack up.

    Returns:
        Process exit code -- 0 on success, 1 on any operator-actionable failure.
    """
    try:
        resolve_docker()
        require_compose()
        require_env_file()
        build_base_image()
        compose_up()
    except DeployError as error:
        print(f"ERROR: {error}", file=sys.stderr)
        return 1
    except KeyboardInterrupt:
        print("\nInterrupted.", file=sys.stderr)
        return 130
    print("Deployment complete. Follow logs with:  docker compose logs -f")
    return 0


if __name__ == "__main__":
    sys.exit(main())
