<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <OutputType>Exe</OutputType>
    <RootNamespace>DeployTests</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" Version="2.3.2" />
    <PackageReference Include="xunit.v3.mtp-v2" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../library_book_service/src/BookService/BookService.csproj" />
    <ProjectReference Include="../../library_member_service/src/MemberService/MemberService.csproj" />
    <ProjectReference Include="../../library_loan_service/src/LoanService/LoanService.csproj" />
  </ItemGroup>

</Project>
