package library_book_service.spec;

import library_book_service.EventSpyRecorder;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;

/**
 * Test-only Spring configuration providing the {@link EventSpyRecorder} bean.
 *
 * <p>Imported via {@code @Import(BookServiceSpecTestSupport.class)} on the generated spec test
 * class -- JUnit 5 + Spring Boot Test has no direct {@code conftest.py} equivalent,
 * {@code @TestConfiguration} + {@code @Import} is the idiomatic replacement.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@TestConfiguration
public class BookServiceSpecTestSupport {

  @Bean
  public EventSpyRecorder eventSpyRecorder() {
    return new EventSpyRecorder();
  }
}
