/**
 * Queue message payload types for OrderService.
 *
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */

export interface ProcessShipmentPayload {
  readonly orderId: string;
}

