// AlertMetrics.cs -- shared prometheus-net metric definitions, rendered
// through the shared infra-client metrics seam.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.

using Prometheus;

namespace BookService.Observability;

public static class AlertMetrics
{
    public static readonly Histogram BookDbQueryDuration = Metrics.CreateHistogram(
        "book_db_query_duration",
        "queryDuration metric for bookDb.",
        new HistogramConfiguration
        {
            LabelNames = new[] { "service" },
            Buckets = new[] { 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0 },
        }
    );

    public static readonly Gauge BookDbConnectionPool = Metrics.CreateGauge(
        "book_db_connection_pool",
        "connectionPool metric for bookDb.",
        "service"
    );

    public static readonly Gauge RedisHitRatio = Metrics.CreateGauge(
        "redis_hit_ratio",
        "hitRatio metric for redis.",
        "service"
    );

    public static readonly Gauge MqConsumerLag = Metrics.CreateGauge(
        "mq_consumer_lag",
        "consumerLag metric for mq.",
        "service"
    );
}
