// <auto-generated>
// Generated by datrix-codegen-dotnet. Do not edit by hand.
// </auto-generated>
#nullable enable

namespace BookService.Observability;

/// <summary>
/// Records HttpMetrics for every request. Registered FIRST in the
/// pipeline (immediately after app.UseCors(), before any trusted-caller/
/// gateway/auth middleware) so every request -- including ones rejected by
/// a later middleware -- is counted, mirroring python's earliest-middleware
/// placement for MetricsMiddleware.
/// </summary>
public sealed class HttpMetricsMiddleware : IMiddleware
{
    public async Task InvokeAsync(HttpContext context, RequestDelegate next)
    {
        var method = context.Request.Method;
        var endpoint = context.Request.Path.Value ?? string.Empty;

        HttpMetrics.RequestsInProgress.WithLabels(method, endpoint).Inc();
        var stopwatch = System.Diagnostics.Stopwatch.StartNew();
        try
        {
            await next(context);
            stopwatch.Stop();
            var statusCode = context.Response.StatusCode.ToString();

            HttpMetrics.RequestsTotal.WithLabels(method, endpoint, statusCode).Inc();
            HttpMetrics.RequestDuration.WithLabels(method, endpoint).Observe(stopwatch.Elapsed.TotalSeconds);

            if (context.Response.StatusCode >= 400)
            {
                HttpMetrics.ErrorsTotal.WithLabels(method, endpoint, statusCode).Inc();
            }
        }
        finally
        {
            HttpMetrics.RequestsInProgress.WithLabels(method, endpoint).Dec();
        }
    }
}
