/**
 * Managed machine-identity credential for inter-service calls.
 *
 * Acquires the platform machine-identity credential at request time.
 * Generated TypeScript never signs a service token with a locally held key
 * (anti-pattern 4.10 replaced by managed machine identity).
 *
 * Strategy: oidc-client-credentials
 *
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */
import { Injectable, Logger } from '@nestjs/common';
import { acquireServiceCredential } from './service-credential';

const SERVICE_NAME = 'examples-ingestion-service';

@Injectable()
export class ServiceIdentity {
  private readonly logger = new Logger(ServiceIdentity.name);

  /**
   * Acquire the platform-managed machine-identity credential for outbound
   * inter-service requests to the given audience service.
   *
   * @param audience - The target service name (used as the credential audience
   *   for token-based strategies). Ignored for shared-secret strategy.
   * @returns The credential value to attach as Authorization: Bearer.
   */
  async getCredential(audience: string): Promise<string> {
    this.logger.debug(
      `service_credential_acquiring service=${SERVICE_NAME} audience=${audience}`,
    );
    const credential = await acquireServiceCredential(audience);
    this.logger.debug(
      `service_credential_acquired service=${SERVICE_NAME} audience=${audience}`,
    );
    return credential;
  }
}
