"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "membership_type" AS ENUM (\'standard\', \'premium\', \'student\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "members",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "first_name",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "last_name",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(320),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "password_hash",
            sa.String(255),
            nullable=True,
        ),
        sa.Column(
            "membership_number",
            sa.String(20),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "membership_type",
            sa.Enum('standard', 'premium', 'student', name='membership_type', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "date_of_birth",
            sa.Date(),
            nullable=True,
        ),
        sa.Column(
            "ssn",
            sa.String(11),
            nullable=True,
        ),
        sa.Column(
            "library_card_number",
            sa.String(16),
            nullable=True,
        ),
        sa.Column(
            "last_login_ip",
            sa.String(45),
            nullable=True,
        ),
    )
    op.create_table(
        "member_preferences",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "language",
            sa.String(10),
            nullable=False,
        ),
        sa.Column(
            "timezone",
            sa.String(50),
            nullable=False,
        ),
        sa.Column(
            "email_notifications",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "sms_notifications",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "preferences",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "member_id",
            sa.Uuid,
            nullable=False,
        ),
    )
    op.create_index("ix_members_first_name_last_name", "members", ["first_name", "last_name"], unique=False)


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_index("ix_members_first_name_last_name", table_name="members")
    op.drop_table("member_preferences")
    op.drop_table("members")
