package warehouse_warehouse_service.warehouse_db;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import javax.sql.DataSource;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import warehouse_warehouse_service.config.RemoteConfig;
import warehouse_warehouse_service.security.SecretsResolver;

/**
 * HikariCP {@code DataSource} configuration for the 'warehouseDb' RDBMS block (postgres). Every
 * RDBMS block gets its own explicitly-named bean -- no {@code @Primary} guess across multi-block
 * services.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Configuration
public class WarehouseDbDataSourceConfig {

  @Bean(name = "warehouse_dbDataSource")
  public DataSource warehouse_dbDataSource(
      RemoteConfig remoteConfig, SecretsResolver secretsResolver) {
    String host = remoteConfig.getWarehouseDbHost();
    int port = remoteConfig.getWarehouseDbPort();
    String database = remoteConfig.getWarehouseDbDatabase();
    String username = remoteConfig.getWarehouseDbUser();

    String jdbcUrl = "jdbc:postgresql://" + host + ":" + port + "/" + database;

    HikariConfig hikariConfig = new HikariConfig();
    hikariConfig.setJdbcUrl(jdbcUrl);
    hikariConfig.setDriverClassName("org.postgresql.Driver");
    hikariConfig.setUsername(username);
    hikariConfig.setPassword(secretsResolver.getSecret("warehouse_db_password"));
    hikariConfig.setMaximumPoolSize(20);

    return new HikariDataSource(hikariConfig);
  }
}
