// TagFactoryTests.cs -- generated xUnit.v3 test-data factory tests.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
using BookService.Tests.Factories.BookDb;
using Xunit;

namespace BookService.Tests.FactoryTests.BookDb;

public sealed class TagFactoryTests
{
    [Fact]
    public void Create_ReturnsNonNullInstance()
    {
        var entity = TagFactory.Create();

        Assert.NotNull(entity);
    }

    [Fact]
    public void Create_CalledTwice_ReturnsDistinctInstances()
    {
        var first = TagFactory.Create();
        var second = TagFactory.Create();

        Assert.NotSame(first, second);
    }
}
