package library_book_service.cqrs.commands;

import java.util.UUID;
import library_book_service.enums.BookStatus;

/**
 * UpdateBookStatus command payload.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record UpdateBookStatus(UUID bookId, BookStatus newStatus) {}
