package library_book_service.cqrs.commands;

import java.util.UUID;
import library_book_service.EventSpyRecorder;
import library_book_service.SpringContextHolder;
import library_book_service.cqrs.views.BookCatalogViewRepository;
import library_book_service.enums.BookStatus;
import library_book_service.pubsub.mq.BookStatusChanged;
import library_book_service.pubsub.mq.MqKafkaEventProducer;
import library_book_service.repositories.book_db.BookRepository;
import library_book_service.repositories.book_db.BookTagRepository;
import library_book_service.repositories.book_db.CategoryRepository;
import library_book_service.repositories.book_db.TagRepository;
import library_book_service.repositories.book_db.UserRepository;
import org.springframework.stereotype.Component;

/**
 * Handles UpdateBookStatus commands.
 *
 * <p>Validates the command, executes business logic, and persists state changes. Auto-generated by
 * datrix-codegen-java. Do not edit manually.
 */
@Component
public class UpdateBookStatusHandler {

  private final CategoryRepository categoryRepository;
  private final UserRepository userRepository;
  private final TagRepository tagRepository;
  private final BookTagRepository bookTagRepository;
  private final BookRepository bookRepository;
  private final BookCatalogViewRepository bookCatalogViewRepository;

  public UpdateBookStatusHandler(
      CategoryRepository categoryRepository,
      UserRepository userRepository,
      TagRepository tagRepository,
      BookTagRepository bookTagRepository,
      BookRepository bookRepository,
      BookCatalogViewRepository bookCatalogViewRepository) {
    this.categoryRepository = categoryRepository;
    this.userRepository = userRepository;
    this.tagRepository = tagRepository;
    this.bookTagRepository = bookTagRepository;
    this.bookRepository = bookRepository;
    this.bookCatalogViewRepository = bookCatalogViewRepository;
  }

  /** Execute the UpdateBookStatus command. */
  public UUID handle(UUID bookId, BookStatus newStatus) {
    var book = bookRepository.findById(bookId).orElse(null);
    var oldStatus = book.getStatus();
    book.setStatus(newStatus);
    book.save();
    SpringContextHolder.getBean(MqKafkaEventProducer.class)
        .publishBookStatusChanged(bookId, oldStatus, newStatus);
    SpringContextHolder.getOptionalBean(EventSpyRecorder.class)
        .ifPresent(__spy -> __spy.record(new BookStatusChanged(bookId, oldStatus, newStatus)));
    return book;
  }
}
