package library_notification_service.integrations;

import jakarta.mail.Message.RecipientType;
import jakarta.mail.PasswordAuthentication;
import jakarta.mail.Session;
import jakarta.mail.Transport;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import java.util.List;
import java.util.Map;
import java.util.Properties;
import library_notification_service.security.SecretsResolver;
import org.springframework.stereotype.Component;

/**
 * Email client for the smtp provider (vendor token: smtp). Credentials and endpoint config are
 * resolved from {@link SecretsResolver} (no environment reads).
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Component
public class SmtpEmailClient {

  // Static self-registration: the ONLY per-service EmailClient bean, exposed
  // statically so EmailHelpers.java (a plain static utility backing the
  // Email.send(...)/sendTemplate(...)/sendBulk(...) builtins -- no Spring DI
  // available at that call site) can reach this Spring-managed instance
  // without a second, duplicated implementation of the vendor branches below.
  private static volatile SmtpEmailClient INSTANCE;

  private final SecretsResolver secretsResolver;
  private final String fromEmail = "noreply@example.com";
  private final String fromName = "Application";

  public SmtpEmailClient(SecretsResolver secretsResolver) {
    this.secretsResolver = secretsResolver;
    INSTANCE = this;
  }

  /** The Spring-managed singleton instance, for static call sites (EmailHelpers.java). */
  public static SmtpEmailClient instance() {
    SmtpEmailClient instance = INSTANCE;
    if (instance == null) {
      throw new IllegalStateException(
          "SmtpEmailClient bean not yet initialized -- Email.send(...) was called "
              + "before Spring finished constructing the application context.");
    }
    return instance;
  }

  public void sendEmail(String to, String subject, String body) {
    try {
      Properties props = new Properties();
      props.put("mail.smtp.auth", "true");
      props.put("mail.smtp.starttls.enable", "true");
      props.put("mail.smtp.host", secretsResolver.getSecret("smtp_host"));
      props.put("mail.smtp.port", secretsResolver.getSecret("smtp_port"));
      String username = secretsResolver.getSecret("smtp_username");
      String password = secretsResolver.getSecret("smtp_password");
      Session session =
          Session.getInstance(
              props,
              new jakarta.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication() {
                  return new PasswordAuthentication(username, password);
                }
              });
      MimeMessage message = new MimeMessage(session);
      message.setFrom(new InternetAddress(fromEmail, fromName));
      message.setRecipient(RecipientType.TO, new InternetAddress(to));
      message.setSubject(subject);
      message.setText(body);
      Transport.send(message);
    } catch (Exception e) {
      throw new RuntimeException("SMTP send failed: " + e.getMessage(), e);
    }
  }

  /**
   * Send a provider-native templated email. {@code data} supplies the template's substitution
   * variables. Vendors with no server-side templating API (ACS, SMTP) fall back to composing a
   * readable body from the template id and data -- an honest, documented degrade, never a silent
   * drop of the template/data arguments.
   */
  public void sendTemplate(String to, String subject, String templateId, Map<String, Object> data) {
    sendEmail(to, subject, "Template: " + templateId + ", Data: " + data);
  }

  /** Send the same subject/body to every recipient in {@code to}. */
  public void sendBulk(List<String> to, String subject, String body) {
    for (String recipient : to) {
      sendEmail(recipient, subject, body);
    }
  }

  private static String toJsonData(Map<String, Object> data) {
    try {
      return new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(data);
    } catch (com.fasterxml.jackson.core.JsonProcessingException e) {
      throw new RuntimeException("Failed to serialize template data to JSON: " + e.getMessage(), e);
    }
  }
}
