// PaginationResult.cs -- generated C# struct record.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.

namespace LoanService.Schemas;

public sealed record PaginationResult(
    int Page,
    int PerPage,
    int Total,
    int TotalPages,
    bool HasNext,
    bool HasPrev
) { }
