// MqConsumerService.cs -- in-process Kafka consumer loop.
// Dispatches on the "eventType" message header (a topic may
// carry more than one distinct event type), not the topic name alone.
// Hosting/scaling (worker count, DI scope per message, graceful shutdown
// tuning) is left to the caller; this class is the `BackgroundService` + its
// `AddHostedService<T>()` registration only.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.

using System.Text;
using System.Text.Json;
using BookService.Data;
using BookService.Enums;
using BookService.Models.BookDb;
using Confluent.Kafka;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using Microsoft.Extensions.Options;
using Prometheus;

namespace BookService.Messaging.Mq;

public sealed class MqConsumerService : BackgroundService
{
    private readonly IConsumer<Null, string> _consumer;
    private readonly IServiceScopeFactory _scopeFactory;

    public MqConsumerService(
        IOptions<MqConnectionSettings> options,
        IServiceScopeFactory scopeFactory
    )
    {
        var config = new ConsumerConfig
        {
            BootstrapServers = options.Value.BootstrapServers,
            GroupId = "mq-consumer",
            AutoOffsetReset = AutoOffsetReset.Earliest,
        };
        _consumer = new ConsumerBuilder<Null, string>(config).Build();
        _scopeFactory = scopeFactory;
    }

    protected override async Task ExecuteAsync(CancellationToken stoppingToken)
    {
        _consumer.Subscribe(new[] { "library_book_service.mq.book_events" });

        await Task.Yield();
        while (!stoppingToken.IsCancellationRequested)
        {
            ConsumeResult<Null, string>? result;
            try
            {
                result = _consumer.Consume(stoppingToken);
            }
            catch (OperationCanceledException)
            {
                break;
            }
            if (result?.Message is null)
            {
                continue;
            }
            string? eventType = null;
            if (
                result.Message.Headers is not null
                && result.Message.Headers.TryGetLastBytes("eventType", out var eventTypeBytes)
            )
            {
                eventType = Encoding.UTF8.GetString(eventTypeBytes);
            }
            switch (eventType)
            {
                case "BookAdded":
                {
                    var payload =
                        JsonSerializer.Deserialize<BookAddedPayload>(result.Message.Value)
                        ?? throw new InvalidOperationException(
                            "Failed to deserialize BookAddedPayload."
                        );
                    MqMetrics.EventsConsumedTotal.WithLabels(result.Topic).Inc();
                    using ((MqMetrics.ConsumeDurationSeconds.WithLabels(result.Topic)).NewTimer())
                    {
                        await HandleBookAddedAsync(payload);
                    }
                    break;
                }
                case "BookStatusChanged":
                {
                    var payload =
                        JsonSerializer.Deserialize<BookStatusChangedPayload>(result.Message.Value)
                        ?? throw new InvalidOperationException(
                            "Failed to deserialize BookStatusChangedPayload."
                        );
                    MqMetrics.EventsConsumedTotal.WithLabels(result.Topic).Inc();
                    using ((MqMetrics.ConsumeDurationSeconds.WithLabels(result.Topic)).NewTimer())
                    {
                        await HandleBookStatusChangedAsync(payload);
                    }
                    break;
                }
                default:
                    break;
            }
        }
    }

    // Extracted (rather than inlined in the switch above) so the generated
    // pubsub behavior test can invoke this handler's real transpiled logic
    // directly via reflection (`internal` is enough -- reflection's Invoke
    // does not enforce compile-time accessibility, no InternalsVisibleTo
    // needed, mirroring generators/cross_cutting/lifecycle_hook_test_generator.py's
    // own established precedent).
    internal async Task HandleBookAddedAsync(BookAddedPayload payload)
    {
        var bookId = payload.BookId;
        var title = payload.Title;
        Console.WriteLine("New book added");
    }

    // Extracted (rather than inlined in the switch above) so the generated
    // pubsub behavior test can invoke this handler's real transpiled logic
    // directly via reflection (`internal` is enough -- reflection's Invoke
    // does not enforce compile-time accessibility, no InternalsVisibleTo
    // needed, mirroring generators/cross_cutting/lifecycle_hook_test_generator.py's
    // own established precedent).
    internal async Task HandleBookStatusChangedAsync(BookStatusChangedPayload payload)
    {
        var bookId = payload.BookId;
        var oldStatus = payload.OldStatus;
        var newStatus = payload.NewStatus;
        using var scope = _scopeFactory.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<BookServiceDbContext>();
        var book = await db.Books.FindAsync(bookId);
        if ((book != null))
        {
            Console.WriteLine(
                $"Book '{book.Title}' status changed from {oldStatus} to {newStatus}"
            );
        }
    }

    public override void Dispose()
    {
        _consumer.Close();
        _consumer.Dispose();
        base.Dispose();
    }
}
