// Constants.cs -- generated C# constants for library.BookService.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.

namespace BookService;

public static class Constants
{
    // --- from datrix.foundation ---
    public const int MaxPageSize = 100;
    public const int DefaultPageSize = 20;
}
