"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "prescription_status" AS ENUM (\'active\', \'completed\', \'cancelled\', \'on_hold\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "record_status" AS ENUM (\'draft\', \'final\', \'amended\', \'voided\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "record_type" AS ENUM (\'diagnosis\', \'prescription\', \'lab_result\', \'imaging\', \'note\', \'procedure\', \'referral\', \'discharge\', \'consultation\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "medical_records",
        sa.Column(
            "created_by",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "updated_by",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "change_reason",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "is_confidential",
            sa.Boolean(),
            nullable=False,
        ),
        sa.Column(
            "access_level",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "patient_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "appointment_id",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "provider_id",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "provider_name",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum('diagnosis', 'prescription', 'lab_result', 'imaging', 'note', 'procedure', 'referral', 'discharge', 'consultation', name='record_type', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum('draft', 'final', 'amended', 'voided', name='record_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "title",
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            "content",
            sa.Text(),
            nullable=False,
        ),
        sa.Column(
            "record_date",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "attachments",
            sa.JSON(),
            nullable=False,
        ),
    )
    op.create_table(
        "prescriptions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "patient_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "appointment_id",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "provider_id",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "prescribing_doctor",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "medication_name",
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            "dosage",
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            "frequency",
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            "route",
            sa.String(100),
            nullable=True,
        ),
        sa.Column(
            "instructions",
            sa.String(500),
            nullable=True,
        ),
        sa.Column(
            "quantity",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "refills_allowed",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "refills_used",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "start_date",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "end_date",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "status",
            sa.Enum('active', 'completed', 'cancelled', 'on_hold', name='prescription_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "pharmacy_name",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "pharmacy_phone",
            sa.String(20),
            nullable=True,
        ),
        sa.Column(
            "discontinuation_reason",
            sa.String(),
            nullable=True,
        ),
    )
    op.create_table(
        "attachments",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "filename",
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            "content_type",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "file_size",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "storage_path",
            sa.String(500),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "record_id",
            sa.Uuid,
            nullable=False,
        ),
    )
    op.create_index("ix_medical_records_patient_id_record_date", "medical_records", ["patient_id", "record_date"], unique=False)
    op.create_index("ix_medical_records_patient_id_type", "medical_records", ["patient_id", "type"], unique=False)
    op.create_index("ix_medical_records_appointment_id", "medical_records", ["appointment_id"], unique=False)
    op.create_index("ix_medical_records_provider_id_record_date", "medical_records", ["provider_id", "record_date"], unique=False)
    op.create_index("ix_medical_records_title_content", "medical_records", ["title", "content"], unique=False)
    op.create_index("ix_prescriptions_patient_id_start_date", "prescriptions", ["patient_id", "start_date"], unique=False)
    op.create_index("ix_prescriptions_patient_id_status", "prescriptions", ["patient_id", "status"], unique=False)
    op.create_index("ix_prescriptions_medication_name", "prescriptions", ["medication_name"], unique=False)


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_index("ix_prescriptions_medication_name", table_name="prescriptions")
    op.drop_index("ix_prescriptions_patient_id_status", table_name="prescriptions")
    op.drop_index("ix_prescriptions_patient_id_start_date", table_name="prescriptions")
    op.drop_index("ix_medical_records_title_content", table_name="medical_records")
    op.drop_index("ix_medical_records_provider_id_record_date", table_name="medical_records")
    op.drop_index("ix_medical_records_appointment_id", table_name="medical_records")
    op.drop_index("ix_medical_records_patient_id_type", table_name="medical_records")
    op.drop_index("ix_medical_records_patient_id_record_date", table_name="medical_records")
    op.drop_table("attachments")
    op.drop_table("prescriptions")
    op.drop_table("medical_records")
