// MemberService.cs -- generated entity service class (EF Core CRUD).
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
//
// Additive service layer: real EF Core CRUD against Member's own
// persistence set (Members) on the project's single
// MemberServiceDbContext. NOT yet wired into any controller -- existing
// controller-embedded CRUD (generators/api/_endpoint_crud_body.py) is untouched
// by this domain. Controller delegation (Option B) is a separately scoped,
// deferred future change.
using System.Collections.Generic;
using System.Threading.Tasks;
using MemberService.Data;
using Microsoft.EntityFrameworkCore;

namespace MemberService.Services.MemberDb;

public sealed class MemberService
{
    private readonly MemberServiceDbContext _context;

    public MemberService(MemberServiceDbContext context)
    {
        _context = context;
    }

    public async Task<global::MemberService.Models.MemberDb.Member?> GetByIdAsync(Guid id)
    {
        return await _context.Members.FindAsync(id);
    }

    public async Task<List<global::MemberService.Models.MemberDb.Member>> GetAllAsync()
    {
        return await _context.Members.ToListAsync();
    }

    public async Task<global::MemberService.Models.MemberDb.Member> CreateAsync(
        global::MemberService.Models.MemberDb.Member entity
    )
    {
        _context.Members.Add(entity);
        await _context.SaveChangesAsync();
        return entity;
    }

    public async Task<global::MemberService.Models.MemberDb.Member?> UpdateAsync(
        Guid id,
        global::MemberService.Models.MemberDb.Member updated
    )
    {
        var existing = await _context.Members.FindAsync(id);
        if (existing is null)
        {
            return null;
        }

        _context.Entry(existing).CurrentValues.SetValues(updated);
        await _context.SaveChangesAsync();
        return existing;
    }

    public async Task<bool> DeleteAsync(Guid id)
    {
        var existing = await _context.Members.FindAsync(id);
        if (existing is null)
        {
            return false;
        }

        _context.Members.Remove(existing);
        await _context.SaveChangesAsync();
        return true;
    }
}
