test:
  defaults:
    timeout: 10s
    retry: { maxAttempts: 2, backoff: { type: exponential, initial: 100ms, multiplier: 2 } }

development:
  defaults:
    timeout: 10s
    retry: { maxAttempts: 2, backoff: { type: exponential, initial: 100ms, multiplier: 2 } }

production:
  defaults:
    timeout: 10s
    retry: { maxAttempts: 2, backoff: { type: exponential, initial: 100ms, multiplier: 2 } }
