// LoanService.cs -- generated entity service class (EF Core CRUD).
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.
//
// Additive service layer: real EF Core CRUD against Loan's own
// persistence set (Loans) on the project's single
// LoanServiceDbContext. NOT yet wired into any controller -- existing
// controller-embedded CRUD (generators/api/_endpoint_crud_body.py) is untouched
// by this domain. Controller delegation (Option B) is a separately scoped,
// deferred future change.
using System.Collections.Generic;
using System.Threading.Tasks;
using LoanService.Data;
using Microsoft.EntityFrameworkCore;

namespace LoanService.Services.LoanDb;

public sealed class LoanService
{
    private readonly LoanServiceDbContext _context;

    public LoanService(LoanServiceDbContext context)
    {
        _context = context;
    }

    public async Task<global::LoanService.Models.LoanDb.Loan?> GetByIdAsync(Guid id)
    {
        return await _context.Loans.FindAsync(id);
    }

    public async Task<List<global::LoanService.Models.LoanDb.Loan>> GetAllAsync()
    {
        return await _context.Loans.ToListAsync();
    }

    public async Task<global::LoanService.Models.LoanDb.Loan> CreateAsync(
        global::LoanService.Models.LoanDb.Loan entity
    )
    {
        _context.Loans.Add(entity);
        await _context.SaveChangesAsync();
        return entity;
    }

    public async Task<global::LoanService.Models.LoanDb.Loan?> UpdateAsync(
        Guid id,
        global::LoanService.Models.LoanDb.Loan updated
    )
    {
        var existing = await _context.Loans.FindAsync(id);
        if (existing is null)
        {
            return null;
        }

        _context.Entry(existing).CurrentValues.SetValues(updated);
        await _context.SaveChangesAsync();
        return existing;
    }

    public async Task<bool> DeleteAsync(Guid id)
    {
        var existing = await _context.Loans.FindAsync(id);
        if (existing is null)
        {
            return false;
        }

        _context.Loans.Remove(existing);
        await _context.SaveChangesAsync();
        return true;
    }
}
