"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "enrollment_status" AS ENUM (\'pending\', \'active\', \'completed\', \'dropped\', \'expired\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "grade_status" AS ENUM (\'not_submitted\', \'submitted\', \'graded\', \'returned\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "enrollments",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "student_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "course_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum('pending', 'active', 'completed', 'dropped', 'expired', name='enrollment_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "enrolled_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "dropped_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "progress",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "drop_reason",
            sa.String(),
            nullable=True,
        ),
        sa.Column(
            "average_score",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "grade_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "last_accessed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
    )
    op.create_table(
        "grade_records",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "module_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "score",
            sa.Numeric(precision=5, scale=2),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum('not_submitted', 'submitted', 'graded', 'returned', name='grade_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "feedback",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "graded_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "graded_by",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "enrollment_id",
            sa.Uuid,
            nullable=False,
        ),
    )
    op.create_table(
        "enrollment_activities",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "enrollment_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "activity_type",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "metadata",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )
    op.create_index("ix_enrollments_student_id_course_id", "enrollments", ["student_id", "course_id"], unique=True)
    op.create_index("ix_enrollments_student_id_status", "enrollments", ["student_id", "status"], unique=False)
    op.create_index("ix_enrollments_course_id_status", "enrollments", ["course_id", "status"], unique=False)
    op.create_index("ix_enrollments_status_enrolled_at", "enrollments", ["status", "enrolled_at"], unique=False)
    op.create_index("ix_grade_records_enrollment_id_module_id", "grade_records", ["enrollment_id", "module_id"], unique=True)
    op.create_index("ix_enrollment_activities_enrollment_id_occurred_at", "enrollment_activities", ["enrollment_id", "occurred_at"], unique=False)


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_index("ix_enrollment_activities_enrollment_id_occurred_at", table_name="enrollment_activities")
    op.drop_index("ix_grade_records_enrollment_id_module_id", table_name="grade_records")
    op.drop_index("ix_enrollments_status_enrolled_at", table_name="enrollments")
    op.drop_index("ix_enrollments_course_id_status", table_name="enrollments")
    op.drop_index("ix_enrollments_student_id_status", table_name="enrollments")
    op.drop_index("ix_enrollments_student_id_course_id", table_name="enrollments")
    op.drop_table("enrollment_activities")
    op.drop_table("grade_records")
    op.drop_table("enrollments")
