// BookAvailabilityResponse.cs -- generated C# struct record.
// Auto-generated by datrix-codegen-dotnet. Do not edit manually.

namespace BookService.Schemas;

public sealed record BookAvailabilityResponse(bool Available) { }
