#!/usr/bin/env pwsh
<#
.SYNOPSIS
 Regression gate: cmd_bless's single-process multi-language generation must
 match generating each language in a fully isolated process.

.DESCRIPTION
 cmd_bless (reference_example_parity.py) generates one example once per
 registered language, all in a single process. A shared, non-process-isolated
 scratch/cache path let two concurrent invocations interleave writes into the
 same directory, silently truncating the manifest for whichever language lost
 the race -- with exit code 0. That corrupted at least seven committed parity
 baselines before anyone compared a suspiciously-small blessed manifest
 against a fresh isolated regeneration by hand. Nothing had ever compared the
 two blessing modes automatically, which is why it went undetected for as
 long as it did.

 This gate is that comparison, made permanent: it generates ONE example two
 ways -- combined (every registered language, one process, mirrors cmd_bless
 exactly) and isolated (each language generated by its own freshly-spawned
 process) -- and asserts the manifests are byte-identical per language.

 Generates real output (like reference-example-parity-gate.ps1); this is not
 a pytest suite (the showcase repo hosts none) -- a script under
 scripts/test, run through this wrapper like every other repo-level gate.

.PARAMETER Example
 Path relative to datrix/examples/. Defaults to the parity gate's own corpus
 example (01-foundation) -- cheap and known to generate in every registered
 language.

.EXAMPLE
 .\parity-bless-mode-parity-gate.ps1
 Compare combined vs isolated blessing for the corpus example.

.EXAMPLE
 .\parity-bless-mode-parity-gate.ps1 -Example "02-features/03-infrastructure-blocks/queue"
 Compare combined vs isolated blessing for a specific example (e.g. one that
 previously exhibited the corruption, as a targeted regression check).
#>

[CmdletBinding()]
param(
    [Parameter()]
    [string]$Example
)

$ErrorActionPreference = "Stop"

$scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$scriptsRoot = Split-Path -Parent $scriptDir
$libraryDir = Join-Path $scriptsRoot "library"
$commonDir = Join-Path $scriptsRoot "common"
$runnerScript = Join-Path $libraryDir "test\parity_bless_mode_check.py"

Import-Module (Join-Path $commonDir "DatrixScriptCommon.psm1") -Force
. (Join-Path $commonDir "venv.ps1")

if (-not (Test-Path -LiteralPath $runnerScript)) {
    Write-Error "Error: parity_bless_mode_check.py not found at: $runnerScript"
    exit 1
}

function Invoke-Cleanup {
    Disable-DatrixVenv
}

trap {
    Invoke-Cleanup
    break
}

Ensure-DatrixVenv

try {
    Ensure-DatrixPackagesInstalled -SkipIfInstalled

    $pythonArgs = @($runnerScript)
    if ($Example) {
        $pythonArgs += "--example"
        $pythonArgs += $Example
    }

    Write-Host "Running bless-mode parity gate (combined vs isolated generation)" -ForegroundColor Cyan
    python @pythonArgs
    $exitCode = $LASTEXITCODE

    if ($exitCode -ne 0) {
        Write-Host "Bless-mode parity gate failed with exit code $exitCode" -ForegroundColor Red
        exit $exitCode
    }

    Write-Host "Bless-mode parity gate passed" -ForegroundColor Green
    exit 0
} finally {
    Invoke-Cleanup
}
