package library_book_service.pubsub.mq;

import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.Timer;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.TimeUnit;
import org.springframework.stereotype.Component;

/**
 * Micrometer publish/consume metrics for the mq pubsub block.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@Component
public class MqPubsubMetrics {

  private static final String PUBLISH_TOTAL_METRIC = "pubsub.publish.total";
  private static final String PUBLISH_DURATION_METRIC = "pubsub.publish.duration";
  private static final String CONSUME_TOTAL_METRIC = "pubsub.consume.total";
  private static final String EVENT_TAG = "event";
  private static final String TOPIC_TAG = "topic";
  private static final String STATUS_TAG = "status";

  private final MeterRegistry registry;
  private final ConcurrentHashMap<String, Counter> publishCounters = new ConcurrentHashMap<>();
  private final ConcurrentHashMap<String, Timer> publishTimers = new ConcurrentHashMap<>();
  private final ConcurrentHashMap<String, Counter> consumeCounters = new ConcurrentHashMap<>();

  public MqPubsubMetrics(MeterRegistry registry) {
    this.registry = registry;
  }

  public void recordPublish(String eventName, String topic, long elapsedNanos) {
    String key = eventName + ":" + topic;
    publishCounters
        .computeIfAbsent(
            key,
            k ->
                Counter.builder(PUBLISH_TOTAL_METRIC)
                    .tag(EVENT_TAG, eventName)
                    .tag(TOPIC_TAG, topic)
                    .tag(STATUS_TAG, "success")
                    .register(registry))
        .increment();
    publishTimers
        .computeIfAbsent(
            key,
            k ->
                Timer.builder(PUBLISH_DURATION_METRIC)
                    .tag(EVENT_TAG, eventName)
                    .tag(TOPIC_TAG, topic)
                    .register(registry))
        .record(elapsedNanos, TimeUnit.NANOSECONDS);
  }

  public void recordConsume(String eventName, String topic, String status) {
    String key = eventName + ":" + topic + ":" + status;
    consumeCounters
        .computeIfAbsent(
            key,
            k ->
                Counter.builder(CONSUME_TOTAL_METRIC)
                    .tag(EVENT_TAG, eventName)
                    .tag(TOPIC_TAG, topic)
                    .tag(STATUS_TAG, status)
                    .register(registry))
        .increment();
  }
}
