package library_loan_service.schemas;

import static org.junit.jupiter.api.Assertions.*;

import java.util.UUID;
import org.junit.jupiter.api.Test;

/**
 * Generated tests for CreateLoanRequest: canonical-constructor round-trip and (when applicable)
 * computed-accessor assertions.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
class CreateLoanRequestTest {

  @Test
  void canonicalConstructorRoundTripsEveryComponent() {
    CreateLoanRequest instance =
        new CreateLoanRequest(
            UUID.fromString("550e8400-e29b-41d4-a716-446655440000"),
            UUID.fromString("550e8400-e29b-41d4-a716-446655440000"));
    assertEquals(UUID.fromString("550e8400-e29b-41d4-a716-446655440000"), instance.bookId());
    assertEquals(UUID.fromString("550e8400-e29b-41d4-a716-446655440000"), instance.memberId());
  }
}
