"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "alert_severity" AS ENUM (\'low\', \'medium\', \'high\', \'critical\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "alert_status" AS ENUM (\'open\', \'under_review\', \'resolved\', \'escalated\', \'false_positive\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "alert_type" AS ENUM (\'large_transaction\', \'suspicious_pattern\', \'velocity_exceeded\', \'geographic_anomaly\', \'account_behavior_change\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "compliance_alerts",
        sa.Column(
            "performed_by",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "audit_note",
            sa.String(500),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "account_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "type",
            sa.Enum('large_transaction', 'suspicious_pattern', 'velocity_exceeded', 'geographic_anomaly', 'account_behavior_change', name='alert_type', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "severity",
            sa.Enum('low', 'medium', 'high', 'critical', name='alert_severity', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum('open', 'under_review', 'resolved', 'escalated', 'false_positive', name='alert_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.String(500),
            nullable=False,
        ),
        sa.Column(
            "transaction_amount",
            sa.Numeric(19, 4),
            nullable=True,
        ),
        sa.Column(
            "transaction_id",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "detected_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "reviewed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "resolved_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "resolved_by",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "resolution",
            sa.String(1000),
            nullable=True,
        ),
        sa.Column(
            "escalated_to",
            sa.String(500),
            nullable=True,
        ),
    )
    op.create_table(
        "audit_trails",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "entity_type",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "entity_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "action",
            sa.String(50),
            nullable=False,
        ),
        sa.Column(
            "changes",
            sa.JSON(),
            nullable=False,
        ),
        sa.Column(
            "performed_by",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "performed_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "ip_address",
            sa.String(45),
            nullable=True,
        ),
        sa.Column(
            "user_agent",
            sa.String(500),
            nullable=True,
        ),
    )
    op.create_table(
        "compliance_reports",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "report_date",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "report_type",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "total_alerts",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "open_alerts",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "resolved_alerts",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "escalated_alerts",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "critical_alerts",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "large_transaction_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "large_transaction_total",
            sa.Numeric(19, 4),
            nullable=False,
        ),
        sa.Column(
            "report_data",
            sa.JSON(),
            nullable=True,
        ),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
    )
    op.create_index("ix_compliance_alerts_account_id_detected_at", "compliance_alerts", ["account_id", "detected_at"], unique=False)
    op.create_index("ix_compliance_alerts_severity_status", "compliance_alerts", ["severity", "status"], unique=False)
    op.create_index("ix_compliance_alerts_status_detected_at", "compliance_alerts", ["status", "detected_at"], unique=False)
    op.create_index("ix_compliance_alerts_type_status", "compliance_alerts", ["type", "status"], unique=False)
    op.create_index("ix_audit_trails_entity_id_performed_at", "audit_trails", ["entity_id", "performed_at"], unique=False)
    op.create_index("ix_audit_trails_entity_type_entity_id", "audit_trails", ["entity_type", "entity_id"], unique=False)
    op.create_index("ix_audit_trails_performed_by_performed_at", "audit_trails", ["performed_by", "performed_at"], unique=False)
    op.create_index("ix_audit_trails_performed_at", "audit_trails", ["performed_at"], unique=False)
    op.create_index("ix_compliance_reports_report_date_report_type", "compliance_reports", ["report_date", "report_type"], unique=False)


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_index("ix_compliance_reports_report_date_report_type", table_name="compliance_reports")
    op.drop_index("ix_audit_trails_performed_at", table_name="audit_trails")
    op.drop_index("ix_audit_trails_performed_by_performed_at", table_name="audit_trails")
    op.drop_index("ix_audit_trails_entity_type_entity_id", table_name="audit_trails")
    op.drop_index("ix_audit_trails_entity_id_performed_at", table_name="audit_trails")
    op.drop_index("ix_compliance_alerts_type_status", table_name="compliance_alerts")
    op.drop_index("ix_compliance_alerts_status_detected_at", table_name="compliance_alerts")
    op.drop_index("ix_compliance_alerts_severity_status", table_name="compliance_alerts")
    op.drop_index("ix_compliance_alerts_account_id_detected_at", table_name="compliance_alerts")
    op.drop_table("compliance_reports")
    op.drop_table("audit_trails")
    op.drop_table("compliance_alerts")
