test:
  tags: [api, shipping, fulfillment, v1]

  meta: { team: fulfillment }

  healthCheck: { type: http, path: /health, interval: 10s }

development:
  tags: [api, shipping, fulfillment, v1]

  meta: { team: fulfillment }

  healthCheck: { type: http, path: /health, interval: 10s }

production:
  tags: [api, shipping, fulfillment, v1]

  meta: { team: fulfillment }

  healthCheck: { type: http, path: /health, interval: 10s }
