"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "restaurant_status" AS ENUM (\'active\', \'closed\', \'suspended\', \'pending_approval\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "restaurants",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "name",
            sa.String(200),
            nullable=False,
        ),
        sa.Column(
            "description",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "cuisine_type",
            sa.String(100),
            nullable=False,
        ),
        sa.Column(
            "address",
            sa.String(500),
            nullable=False,
        ),
        sa.Column(
            "phone",
            sa.String(20),
            nullable=False,
        ),
        sa.Column(
            "email",
            sa.String(320),
            nullable=False,
        ),
        sa.Column(
            "rating",
            sa.Numeric(precision=3, scale=2),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum('active', 'closed', 'suspended', 'pending_approval', name='restaurant_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "opening_hours",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "latitude",
            sa.Numeric(precision=10, scale=6),
            nullable=True,
        ),
        sa.Column(
            "longitude",
            sa.Numeric(precision=10, scale=6),
            nullable=True,
        ),
    )
    op.create_table(
        "restaurant_reviews",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "customer_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "rating",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "comment",
            sa.Text(),
            nullable=True,
        ),
        sa.Column(
            "restaurant_id",
            sa.Uuid,
            nullable=False,
        ),
    )
    op.create_index("ix_restaurants_name_description_cuisine_type", "restaurants", ["name", "description", "cuisine_type"], unique=False)
    op.create_index("ix_restaurants_status", "restaurants", ["status"], unique=False)
    op.create_index("ix_restaurants_cuisine_type", "restaurants", ["cuisine_type"], unique=False)
    op.create_index("ix_restaurants_name", "restaurants", ["name"], unique=False)
    op.create_index("ix_restaurant_reviews_restaurant_id_created_at", "restaurant_reviews", ["restaurant_id", "created_at"], unique=False)


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_index("ix_restaurant_reviews_restaurant_id_created_at", table_name="restaurant_reviews")
    op.drop_index("ix_restaurants_name", table_name="restaurants")
    op.drop_index("ix_restaurants_cuisine_type", table_name="restaurants")
    op.drop_index("ix_restaurants_status", table_name="restaurants")
    op.drop_index("ix_restaurants_name_description_cuisine_type", table_name="restaurants")
    op.drop_table("restaurant_reviews")
    op.drop_table("restaurants")
