/**
 * Application configuration. Uses getSecret() for sensitive values.
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */

import { getSecret } from '../examples_ingestion_service/secrets';

export default () => ({
  port: parseInt(process.env.PORT ?? '8002', 10),
  nodeEnv: process.env.NODE_ENV ?? 'development',
  jwtSecret: (() => {
    const raw = getSecret('jwt_secret_key');
    if (!raw) throw new Error('JWT_SECRET environment variable is required');
    return raw.replace(/\\n/g, '\n');
  })(),
  jwtExpiresIn: process.env.JWT_EXPIRES_IN ?? '1d',
  jwtSecretRotationIntervalSeconds: parseInt(
    process.env.JWT_SECRET_ROTATION_INTERVAL ?? '86400',
    10,
  ),
  serviceJwtSecret: process.env.SERVICE_JWT_SECRET ?? '',
  serviceJwtExpiry: parseInt(process.env.SERVICE_JWT_EXPIRY ?? '3600', 10),
});
