/**
 * Standalone runtime bootstrap for this service's container serverless processes.
 *
 * Every container serverless entrypoint (consumer.ts, scheduler.ts,
 * queue_worker.ts, http_app.ts) runs as its OWN process, outside the NestJS
 * `AppModule`. Yet a handler body compiled with a `dispatch` statement
 * imports the SAME module-level `producerInstance` singleton the in-process
 * app publishes through -- without this bootstrap that singleton stays
 * `null` forever and every dispatch from a standalone process silently
 * no-ops. `bootstrapRuntime()` wires it; `shutdownRuntime()` tears it back
 * down. Idempotent, so an entrypoint may call it unconditionally at startup.
 *
 * Auto-generated by datrix-codegen-typescript. Do not edit manually.
 */

let _bootstrapped = false;

export async function bootstrapRuntime(): Promise<void> {
  if (_bootstrapped) {
    return;
  }
  _bootstrapped = true;
}

export async function shutdownRuntime(): Promise<void> {
  if (!_bootstrapped) {
    return;
  }
  _bootstrapped = false;
}
