// <auto-generated>
// Generated by datrix-codegen-dotnet. Do not edit by hand.
// </auto-generated>
#nullable enable
// Updates the BookCatalogView view model in response to domain events.
// Projections are idempotent: processing the same event twice produces the
// same result.

using System;
using System.Threading.Tasks;
using BookService.Cqrs.Views;
using BookService.Data;
using BookService.Enums;
using BookService.Messaging.Mq;
using BookService.Models.BookDb;
using Microsoft.EntityFrameworkCore;

namespace BookService.Cqrs.Projections;

public sealed class BookCatalogProjection
{
    private readonly BookServiceDbContext bookServiceDbContext;

    public BookCatalogProjection(BookServiceDbContext bookServiceDbContext)
    {
        this.bookServiceDbContext = bookServiceDbContext;
    }

    public async Task OnBookAddedAsync(BookAddedPayload payload)
    {
                var bookId = payload.BookId;
                var title = payload.Title;
                    var book = await bookServiceDbContext.Books.FindAsync(bookId);
                    await bookServiceDbContext.Database.ExecuteSqlInterpolatedAsync($"INSERT INTO book_catalog_views (id, title, author, publication_year, status, last_updated) VALUES ({bookId}, {title}, {book.Author}, {book.PublicationYear}, {BookStatus.Available}, {DateTimeOffset.UtcNow}) ON CONFLICT (book_id) DO UPDATE SET id = EXCLUDED.id, title = EXCLUDED.title, author = EXCLUDED.author, publication_year = EXCLUDED.publication_year, status = EXCLUDED.status, last_updated = EXCLUDED.last_updated");
    }

    public async Task OnBookStatusChangedAsync(BookStatusChangedPayload payload)
    {
                var bookId = payload.BookId;
                var oldStatus = payload.OldStatus;
                var newStatus = payload.NewStatus;
                    var view = await bookServiceDbContext.BookCatalogViews.FindAsync(bookId);
                    view.Status = newStatus;
                    view.LastUpdated = DateTimeOffset.UtcNow;
                    await bookServiceDbContext.SaveChangesAsync();
    }
}
