"""Database connection configuration for postgres engine.

Auto-generated by datrix-codegen-python. Do not edit manually.
Engine is initialized from AppSettings during lifespan startup; no
environment variables are read at any point.
"""

from __future__ import annotations

import datetime
import json
import logging
import uuid
from typing import TYPE_CHECKING

from sqlalchemy.ext.asyncio import AsyncEngine, create_async_engine

import library_book_service.config._secrets_resolver as _secrets_resolver
from library_book_service.config.settings import DB_MAX_OVERFLOW, DB_POOL_SIZE, DEBUG

if TYPE_CHECKING:
    from library_book_service.config.settings import AppSettings

logger = logging.getLogger(__name__)

from sqlalchemy import event

from library_book_service.rdbms_metrics import (
    sqlalchemy_pool_checked_out,
    sqlalchemy_pool_size,
)

_BLOCK_LABEL = "book_db"


def _update_sqlalchemy_pool_gauges(pool: object) -> None:
    """Sync pool gauges from the live SQLAlchemy pool (sync API)."""
    checked = int(pool.checkedout())  # type: ignore[union-attr]
    capacity = int(DB_POOL_SIZE + DB_MAX_OVERFLOW)
    sqlalchemy_pool_size.labels(block=_BLOCK_LABEL).set(capacity)
    sqlalchemy_pool_checked_out.labels(block=_BLOCK_LABEL).set(checked)


def _wire_sqlalchemy_pool_metrics(async_engine: AsyncEngine) -> None:
    """Attach pool event listeners so Prometheus gauges stay current."""
    pool = async_engine.sync_engine.pool

    def _on_pool_event(*_args: object) -> None:
        _update_sqlalchemy_pool_gauges(pool)

    event.listen(pool, "checkout", _on_pool_event)
    event.listen(pool, "checkin", _on_pool_event)
    event.listen(pool, "connect", _on_pool_event)
    event.listen(pool, "invalidate", _on_pool_event)
    _update_sqlalchemy_pool_gauges(pool)


class _ExtendedJSONEncoder(json.JSONEncoder):
    """JSON encoder that handles date, datetime, and UUID types for JSON columns."""

    def default(self, o: object) -> object:
        if isinstance(o, datetime.datetime):
            return o.isoformat()
        if isinstance(o, datetime.date):
            return o.isoformat()
        if isinstance(o, uuid.UUID):
            return str(o)
        return super().default(o)


def _json_serializer(obj: object) -> str:
    return json.dumps(obj, cls=_ExtendedJSONEncoder)


def _create_engine(url: str, *, ssl: bool = False, **kwargs: object) -> AsyncEngine:
    """Create the async SQLAlchemy engine with config-driven pool settings.

    Args:
        url: Database connection URL (composed at startup from AppSettings).
        ssl: Whether to enable SSL for the connection.
        **kwargs: Additional engine kwargs to override defaults.

    Returns:
        Configured AsyncEngine instance.
    """
    engine_kwargs: dict[str, object] = {
        "echo": DEBUG,
        "json_serializer": _json_serializer,
    }
    engine_kwargs["pool_size"] = DB_POOL_SIZE
    engine_kwargs["max_overflow"] = DB_MAX_OVERFLOW
    connect_args: dict[str, object] = {}
    if ssl:
        connect_args["ssl"] = True
    if connect_args:
        engine_kwargs["connect_args"] = connect_args
    engine_kwargs.update(kwargs)

    logger.info(
        "database_engine_created engine=postgres url=%s pool_size=%s",
        url.split("@")[-1] if "@" in url else url,
        engine_kwargs.get("pool_size", "default"),
    )
    eng = create_async_engine(url, **engine_kwargs)
    _wire_sqlalchemy_pool_metrics(eng)
    return eng


_engine: AsyncEngine | None = None
# Non-secret connection components captured from AppSettings at init_engine time.
# The password is NEVER stored here; it lives only in the secrets resolver cache.
_conn_user: str = ""
_conn_host: str = ""
_conn_port: int = 0
_conn_database: str = ""
_conn_driver: str = ""
# Logical password handle resolved through the secrets resolver (REBUILD_ON_REFRESH).
_password_handle: str = ""
# Last resolved password value, kept ONLY to detect a rotation (value changed) so the
# engine can be rebuilt. Never logged, never exposed through AppSettings.
_last_password: str | None = None

# Definitive DB authentication SQLSTATE codes. A caught error is treated as a
# credential failure ONLY when its SQLSTATE is in this allow-list; transient
# network/timeout errors must NOT invalidate the secret.
_DB_AUTH_SQLSTATES: frozenset[str] = frozenset({"28P01", "28000"})


def _compose_url(password: str) -> str:
    """Compose the async DB URL from captured components and a resolved password.

    The password is interpolated at call time and never persisted into a frozen
    setting."""
    return f"{_conn_driver}://{_conn_user}:{password}@{_conn_host}:{_conn_port}/{_conn_database}"


def _is_definitive_db_auth_error(exc: BaseException) -> bool:
    """Return True only for a DEFINITIVE DB authentication failure.

    Classification is allow-listed by SQLSTATE (``28P01`` invalid password,
    ``28000`` invalid authorization). Transient network errors, timeouts, and
    every other DB error return False so the credential is NOT invalidated.
    """
    sqlstate = getattr(exc, "sqlstate", None) or getattr(
        getattr(exc, "orig", None), "sqlstate", None
    )
    if sqlstate in _DB_AUTH_SQLSTATES:
        return True
    pgcode = getattr(getattr(exc, "orig", None), "pgcode", None)
    return pgcode in _DB_AUTH_SQLSTATES


async def init_engine(app_settings: "AppSettings") -> None:
    """Initialize the database engine from assembled AppSettings.

    Captures the non-secret connection components and the logical password
    handle, resolves the password through the secrets resolver, and builds the
    engine. Must be called during the lifespan startup phase (async) before any
    request handler or background task calls :func:`get_current_engine`. Raises
    if called more than once without a matching dispose.

    Args:
        app_settings: Fully assembled AppSettings (produced by assemble_settings).

    Raises:
        RuntimeError: If the engine has already been initialized.
    """
    global _engine, _conn_user, _conn_host, _conn_port, _conn_database
    global _conn_driver, _password_handle, _last_password
    if _engine is not None:
        raise RuntimeError(
            "Database engine for block 'book_db' has already been initialized. "
            "init_engine() must be called exactly once during lifespan startup. "
            "Dispose the previous engine before re-initializing."
        )
    _conn_user = str(app_settings.book_db_user)
    _conn_host = str(app_settings.book_db_host)
    _conn_port = int(app_settings.book_db_port)
    _conn_database = str(app_settings.book_db_database)
    _conn_driver = str(app_settings.book_db_async_driver)
    _password_handle = str(app_settings.book_db_password_handle)
    _last_password = await _secrets_resolver.get_secret(_password_handle)
    url = _compose_url(_last_password)
    _engine = _create_engine(url)
    logger.info("database_engine_initialized block=book_db")


async def ensure_engine_current() -> AsyncEngine:
    """Return the engine, rebuilding it if the resolved password rotated.

    Re-resolves the password handle through the secrets resolver (which serves a
    cached value until its TTL expires, then re-reads the backend). When the
    resolved value differs from the value the live engine was built with, the
    existing engine is disposed and rebuilt so a rotated credential propagates
    after TTL expiry.
    Returns:
        The current :class:`AsyncEngine` (possibly rebuilt).

    Raises:
        RuntimeError: If :func:`init_engine` has not been called yet.
    """
    global _engine, _last_password
    if _engine is None:
        raise RuntimeError(
            "Database engine for block 'book_db' has not been initialized. "
            "Call init_engine(app_settings) during the lifespan startup phase before "
            "accessing the engine."
        )
    resolved = await _secrets_resolver.get_secret(_password_handle)
    if resolved != _last_password:
        logger.info("database_engine_rebuild_on_rotation block=book_db")
        old = _engine
        _engine = _create_engine(_compose_url(resolved))
        _last_password = resolved
        await old.dispose()
    return _engine


async def rebuild_engine_after_auth_failure() -> AsyncEngine:
    """Invalidate the password handle, re-resolve, and rebuild the engine ONCE.

    Called by a runtime DB access path that caught a DEFINITIVE auth failure
    (see :func:`_is_definitive_db_auth_error`). Evicts the cached credential via
    ``invalidate_secret`` (throttled, no loop), forces one refetch, and rebuilds
    the engine. The caller retries the original operation at most once.

    Returns:
        The rebuilt :class:`AsyncEngine`.

    Raises:
        RuntimeError: If :func:`init_engine` has not been called yet.
    """
    global _engine, _last_password
    if _engine is None:
        raise RuntimeError(
            "Database engine for block 'book_db' has not been initialized."
        )
    _secrets_resolver.invalidate_secret(_password_handle, "db_auth_failed")
    resolved = await _secrets_resolver.get_secret(_password_handle)
    old = _engine
    _engine = _create_engine(_compose_url(resolved))
    _last_password = resolved
    await old.dispose()
    logger.warning("database_engine_rebuilt_after_auth_failure block=book_db")
    return _engine


def get_engine() -> AsyncEngine:
    """Return the initialized database engine.  Raises if called before init_engine.

    Synchronous accessor for callers that do not need a rotation check (e.g.
    shutdown dispose). Runtime access paths that must observe a rotated
    credential call :func:`ensure_engine_current` (async) instead.

    Returns:
        Initialized :class:`AsyncEngine` instance.

    Raises:
        RuntimeError: If :func:`init_engine` has not been called yet.
    """
    if _engine is None:
        raise RuntimeError(
            "Database engine for block 'book_db' has not been initialized. "
            "Call init_engine(app_settings) during the lifespan startup phase before "
            "accessing the engine. Ensure the startup lifespan handler runs before "
            "any request handler or background task that calls get_engine()."
        )
    return _engine
