package library_book_service.dto.book_db;

import java.util.UUID;

/**
 * BookTag update-request DTO. Every field is optional-to-provide (PATCH semantics) -- no field
 * carries a not-null requirement.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record BookTagUpdateRequest(UUID bookId, UUID tagId) {}
