package library_book_service.dto.book_db;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import java.time.OffsetDateTime;
import java.util.UUID;

/**
 * Tag response DTO. Hidden/sensitive fields are absent.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
public record TagResponse(
    @NotNull UUID id,
    @NotNull OffsetDateTime createdAt,
    @NotNull OffsetDateTime updatedAt,
    @NotNull @Size(max = 50) String name,
    @Size(max = 200) String description) {}
