"""Book service.
Database: bookDb (postgres)
Auto-generated by datrix-codegen-python. Do not edit manually.
"""

from __future__ import annotations

import logging
import uuid

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from library_book_service.models.book_db.book import Book
from library_book_service.schemas.book_db.book import BookCreate, BookUpdate
from library_book_service.services._base import EntityNotFoundError

logger = logging.getLogger(__name__)


class BookService:
    """Business logic for Book entity.

    Provides CRUD operations with lifecycle hook integration.
    """

    def __init__(self, book_db: AsyncSession) -> None:
        self.book_db = book_db

    async def create(self, data: BookCreate, *, _commit: bool = True) -> Book:
        """Create a new Book.

        ``_commit`` defaults to True so each call is its own unit of work. A
        bulk caller inside a ``transaction(db) { ... }`` scope passes
        ``_commit=False`` so the row flushes into the shared transaction and the
        enclosing scope commits all rows once instead of once per row.
        """
        entity = Book(**data.model_dump())
        self.book_db.add(entity)
        if _commit:
            await self.book_db.commit()
        else:
            await self.book_db.flush()
        await self.book_db.refresh(entity)
        logger.info("entity_created entity=%s id=%s", "Book", str(entity.id))
        return entity

    async def get(self, entity_id: uuid.UUID) -> Book:
        """Get Book by ID."""
        entity = await self.book_db.get(Book, entity_id)
        if entity is None:
            raise EntityNotFoundError(f"Book with id '{entity_id}' not found.")
        return entity

    async def get_all(
        self,
        skip: int = 0,
        limit: int = 100,
    ) -> list[Book]:
        """Get all Book entities with pagination."""
        stmt = select(Book)
        stmt = stmt.offset(skip).limit(limit)
        result = await self.book_db.execute(stmt)
        return list(result.scalars().all())

    async def update(
        self,
        entity_id: uuid.UUID,
        data: BookUpdate,
        *,
        _commit: bool = True,
    ) -> Book:
        """Update an existing Book.

        ``_commit=False`` (used by bulk callers inside a ``transaction(db)``
        scope) flushes the change into the shared transaction instead of
        committing per row; the enclosing scope owns the single commit.
        """
        entity = await self.get(entity_id)
        update_data = data.model_dump(exclude_unset=True)
        for field, value in update_data.items():
            setattr(entity, field, value)
        if _commit:
            await self.book_db.commit()
        else:
            await self.book_db.flush()
        await self.book_db.refresh(entity)
        logger.info("entity_updated entity=%s id=%s", "Book", str(entity.id))
        return entity

    async def delete(self, entity_id: uuid.UUID, *, _commit: bool = True) -> None:
        """Delete a Book.

        ``_commit=False`` (bulk callers inside a ``transaction(db)`` scope)
        flushes the delete into the shared transaction; the enclosing scope
        owns the single commit.
        """
        entity = await self.get(entity_id)
        await self.book_db.delete(entity)
        if _commit:
            await self.book_db.commit()
        else:
            await self.book_db.flush()
        logger.info("entity_deleted entity=%s id=%s", "Book", str(entity_id))

    async def search_by_title(
        self, query: str, skip: int = 0, limit: int = 100
    ) -> list[Book]:
        """Find Book entities by title (case-insensitive substring match)."""
        stmt = select(Book).where(Book.title.ilike(f"%{query}%"))
        stmt = stmt.offset(skip).limit(limit)
        result = await self.book_db.execute(stmt)
        return list(result.scalars().all())

    async def find_by_category_id(
        self, category_id: uuid.UUID, skip: int = 0, limit: int = 100
    ) -> list[Book]:
        """Find Book entities by category_id."""
        stmt = select(Book).where(Book.category_id == category_id)
        stmt = stmt.offset(skip).limit(limit)
        result = await self.book_db.execute(stmt)
        return list(result.scalars().all())

    async def get_by_category(
        self,
        category_id: uuid.UUID,
        skip: int = 0,
        limit: int = 100,
    ) -> list[Book]:
        """Get all Book entities belonging to Category with given ID."""
        stmt = select(Book).where(Book.category_id == category_id)
        stmt = stmt.offset(skip).limit(limit)
        result = await self.book_db.execute(stmt)
        return list(result.scalars().all())
