// <auto-generated>
// Generated by datrix-codegen-dotnet. Do not edit by hand.
// Cross-service response models: caller-owned POCO records/enums a dependency's
// inter-service endpoints decode into. Deserialized via System.Text.Json
// (case-insensitive Web defaults), so property names need no wire-name aliasing.
// </auto-generated>
#nullable enable

using System;
using System.Collections.Generic;

namespace LoanService.Clients;

public enum BookStatus
{
    Available,
    CheckedOut,
    Reserved,
    Maintenance,
}

public enum BookFormat
{
    Hardcover,
    Paperback,
    EBook,
    Audiobook,
}

public sealed record BookAvailabilityResponse(
    bool Available
);

public sealed record Book(
    Guid Id,
    DateTimeOffset CreatedAt,
    DateTimeOffset UpdatedAt,
    string Title,
    string Isbn,
    string Author,
    int PublicationYear,
    BookStatus Status,
    BookFormat Format,
    string? CatalogNumber,
    List<string> Keywords,
    decimal Rating,
    Guid CategoryId,
    bool? IsAvailable,
    string? DisplayTitle,
    bool? IsOldBook,
    string? TitleLower,
    int? TitleLength,
    List<string>? TitleWords,
    int? KeywordCount,
    string? KeywordsJoined,
    decimal? RatingRounded
);
