test:
  rdbms:
    engine: postgres
    host: localhost
    port: 5432
    database: hostdemo_users
    poolSize: 10
    docker_image: postgres:17-alpine
    volume_path: /var/lib/postgresql/data
    asyncDriver: postgresql+asyncpg
    syncDriver: postgresql+psycopg2
    healthCheckSql: SELECT 1
    defaultUser: postgres
    platform: container

development:
  rdbms:
    engine: postgres
    host: localhost
    port: 5432
    database: hostdemo_users
    poolSize: 10
    docker_image: postgres:17-alpine
    volume_path: /var/lib/postgresql/data
    asyncDriver: postgresql+asyncpg
    syncDriver: postgresql+psycopg2
    healthCheckSql: SELECT 1
    defaultUser: postgres
    platform: container

staging:
  rdbms:
    engine: postgres
    platform: external
    host: host.docker.internal
    port: 5432
    defaultUser: postgres
    database: hostdemo_users
    poolSize: 10
    asyncDriver: postgresql+asyncpg
    syncDriver: postgresql+psycopg2
    healthCheckSql: SELECT 1

production:
  rdbms:
    engine: postgres
    platform: rds
    host: ${POSTGRES_HOST}
    database: hostdemo_users
    poolSize: 15
    ssl: true
    asyncDriver: postgresql+asyncpg
    syncDriver: postgresql+psycopg2
