test:
  email:
    provider: smtp
    host: localhost
    port: 1025
    fromEmail: noreply@hostdemo.example
    fromName: HostDemo
    templates:
      welcome: templates/welcome.html

development:
  email:
    provider: smtp
    host: localhost
    port: 1025
    fromEmail: noreply@hostdemo.example
    fromName: HostDemo
    templates:
      welcome: templates/welcome.html

staging:
  email:
    provider: smtp
    host: localhost
    port: 1025
    fromEmail: noreply@hostdemo.example
    fromName: HostDemo
    templates:
      welcome: templates/welcome.html

production:
  email:
    provider: ses
    region: us-east-1
    fromEmail: noreply@hostdemo.example
    fromName: HostDemo
    templates:
      welcome: templates/welcome.html
