"""Initial schema (explicit DDL).

Revision ID: 0001_initial
Revises:
Create Date: (auto-generated)

Auto-generated by datrix-codegen-python. Do not edit manually.
Creates tables with op.create_table / op.create_index (no ORM metadata imports).
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "0001_initial"
down_revision: str | None = None
branch_labels: str | None = None
depends_on: str | None = None


def upgrade() -> None:
    """Create all tables and indexes."""
    op.execute('DO $$ BEGIN CREATE TYPE "department" AS ENUM (\'engineering\', \'marketing\', \'sales\', \'hr\', \'finance\', \'operations\', \'legal\', \'customer_support\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "pay_period" AS ENUM (\'weekly\', \'bi_weekly\', \'monthly\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')
    op.execute('DO $$ BEGIN CREATE TYPE "payroll_status" AS ENUM (\'pending\', \'processing\', \'completed\', \'failed\'); EXCEPTION WHEN duplicate_object OR unique_violation THEN null; END $$;')

    op.create_table(
        "payroll_runs",
        sa.Column(
            "performed_by",
            sa.Uuid,
            nullable=True,
        ),
        sa.Column(
            "audit_note",
            sa.String(500),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "payroll_ref",
            sa.String(30),
            nullable=False,
            unique=True,
        ),
        sa.Column(
            "pay_period",
            sa.Enum('weekly', 'bi_weekly', 'monthly', name='pay_period', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "period_start",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "period_end",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum('pending', 'processing', 'completed', 'failed', name='payroll_status', native_enum=True, _create_events=False),
            nullable=False,
        ),
        sa.Column(
            "total_gross",
            sa.Numeric(19, 4),
            nullable=False,
        ),
        sa.Column(
            "total_deductions",
            sa.Numeric(19, 4),
            nullable=False,
        ),
        sa.Column(
            "total_net",
            sa.Numeric(19, 4),
            nullable=False,
        ),
        sa.Column(
            "entry_count",
            sa.Integer(),
            nullable=False,
        ),
        sa.Column(
            "processed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "failure_reason",
            sa.String(500),
            nullable=True,
        ),
    )
    op.create_table(
        "payroll_entries",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "id",
            sa.Uuid,
            primary_key=True,
            nullable=False,
        ),
        sa.Column(
            "employee_id",
            sa.Uuid,
            nullable=False,
        ),
        sa.Column(
            "gross_pay",
            sa.Numeric(19, 4),
            nullable=False,
        ),
        sa.Column(
            "deductions",
            sa.Numeric(19, 4),
            nullable=False,
        ),
        sa.Column(
            "net_pay",
            sa.Numeric(19, 4),
            nullable=False,
        ),
        sa.Column(
            "hours_worked",
            sa.Numeric(),
            nullable=False,
        ),
        sa.Column(
            "department",
            sa.Enum('engineering', 'marketing', 'sales', 'hr', 'finance', 'operations', 'legal', 'customer_support', name='department', native_enum=True, _create_events=False),
            nullable=True,
        ),
        sa.Column(
            "payroll_run_id",
            sa.Uuid,
            nullable=False,
        ),
    )
    op.create_index("ix_payroll_runs_pay_period_status", "payroll_runs", ["pay_period", "status"], unique=False)
    op.create_index("ix_payroll_runs_status_period_start", "payroll_runs", ["status", "period_start"], unique=False)
    op.create_index("ix_payroll_runs_period_start_period_end", "payroll_runs", ["period_start", "period_end"], unique=False)
    op.create_index("ix_payroll_entries_payroll_run_id_employee_id", "payroll_entries", ["payroll_run_id", "employee_id"], unique=False)
    op.create_index("ix_payroll_entries_employee_id_created_at", "payroll_entries", ["employee_id", "created_at"], unique=False)


def downgrade() -> None:
    """Drop indexes then tables (reverse dependency order)."""
    op.drop_index("ix_payroll_entries_employee_id_created_at", table_name="payroll_entries")
    op.drop_index("ix_payroll_entries_payroll_run_id_employee_id", table_name="payroll_entries")
    op.drop_index("ix_payroll_runs_period_start_period_end", table_name="payroll_runs")
    op.drop_index("ix_payroll_runs_status_period_start", table_name="payroll_runs")
    op.drop_index("ix_payroll_runs_pay_period_status", table_name="payroll_runs")
    op.drop_table("payroll_entries")
    op.drop_table("payroll_runs")
