package library_member_service.model.member_db;

import jakarta.persistence.CheckConstraint;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EntityListeners;
import jakarta.persistence.Table;

/**
 * Member JPA entity.
 *
 * <p>Auto-generated by datrix-codegen-java. Do not edit manually.
 */
@EntityListeners({MemberLifecycleListener.class})
@Entity
@Table(
    name = "members",
    indexes = {},
    uniqueConstraints = {},
    check = {
      @CheckConstraint(name = "ck_members_name_max_length", constraint = "length(name) <= 100")
    })
public class Member extends BaseEntity {

  @Column(name = "name", columnDefinition = "varchar(100)", nullable = false)
  private String name;

  @Column(name = "email", columnDefinition = "varchar(320)", nullable = false, unique = true)
  private String email;

  @Column(name = "emailVerificationToken", columnDefinition = "text", nullable = true)
  private String emailVerificationToken;

  public String getName() {
    return this.name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public String getEmail() {
    return this.email;
  }

  public void setEmail(String email) {
    this.email = email;
  }

  public String getEmailVerificationToken() {
    return this.emailVerificationToken;
  }

  public void setEmailVerificationToken(String emailVerificationToken) {
    this.emailVerificationToken = emailVerificationToken;
  }

  /**
   * Build a new {@link Member} from a DSL object-literal map, setting only the keys present in
   * {@code data} (a key absent from {@code data} leaves the corresponding field at its normal Java
   * default -- {@code null} unless the field declares its own initializer above). Keys are the
   * AS-AUTHORED DSL field name (Java's own object-literal emission, {@code _datrixOrderedMap(...)},
   * preserves author-declared spelling -- no case conversion), which for a camelCase-authored DSL
   * field is identical to this entity's own camelCase Java field name.
   *
   * <p>Backs {@code db.Member.create({...})} lowering (`transpiler/
   * _entity_query_dispatch.py::transpile_entity_create`) -- entities have no `Map`-consuming
   * constructor, so the transpiled object literal is fed through this static factory instead of
   * `new Member(...)`.
   */
  public static Member fromMap(java.util.Map<String, Object> data) {
    Member result = new Member();
    if (data.containsKey("name")) {
      Object __v = data.get("name");
      result.setName((String) __v);
    }
    if (data.containsKey("email")) {
      Object __v = data.get("email");
      result.setEmail((String) __v);
    }
    if (data.containsKey("emailVerificationToken")) {
      Object __v = data.get("emailVerificationToken");
      result.setEmailVerificationToken((String) __v);
    }
    return result;
  }
}
