test:
  jobs:
    CheckOverdueBooks:
      schedule: "0 */2 * * *"
      timeout: 300s
      retries: 1
      concurrency: 1
development:
  jobs:
    CheckOverdueBooks:
      schedule: "0 */2 * * *"
      timeout: 300s
      retries: 1
      concurrency: 1
production:
  jobs:
    CheckOverdueBooks:
      schedule: "0 */1 * * *"
      timeout: 600s
      retries: 3
      concurrency: 1
      alertOnFailure: true
