// <auto-generated>
// Generated by datrix-codegen-dotnet. Do not edit by hand.
// </auto-generated>
#nullable enable

using System.Net.Http;
using BookService.Config;
using Microsoft.EntityFrameworkCore;
using BookService.Data;
using BookService.Data.BookDb;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Hosting;
using FluentMigrator.Runner;
using Quartz;
using BookService.Jobs;
using Microsoft.AspNetCore.Diagnostics.HealthChecks;
using BookService.Health;
using StackExchange.Redis;
using BookService.RateLimit;
using BookService.Cache;
using BookService.Nosql.Docdb;
using Prometheus;
using BookService.Observability;
using BookService.Identity;
using BookService.Hubs;
using BookService.Gateway;
using BookService.Messaging.Mq;
using BookService.Messaging;
using BookService.Cqrs;

const string RunModeFlag = "--datrix-run";
const string HealthcheckUrlFlag = "--url";

// Persistence mode literals -- named constants (single source of truth the
// unit tests assert against). Two other runtime modes are DELIBERATELY
// ABSENT from this file entirely (never mentioned, not even in fail-loud
// form): one belongs to a future increment (its own generator does not
// exist yet), the other to a runtime host that does not exist yet. A
// negative-check guard requires ZERO occurrences of either mode's own
// literal string anywhere in generated Program.cs until that host lands,
// conditionally, per-service.
const string ModeMigratePrefix = "migrate:";
const string ModeSeed = "seed";
const string ModeReadiness = "readiness";
const string ModeJobRunner = "job-runner";
const string ModeJobPrefix = "job:";
const string ModeServerlessJobPrefix = "serverless:job:";

string? mode = ParseRunMode(args);

if (mode is not null)
{
    if (mode == "healthcheck")
    {
        return await RunHealthcheckSelfProbeAsync(args);
    }
    if (mode.StartsWith(ModeMigratePrefix, StringComparison.Ordinal))
    {
        return await RunMigrateAsync(mode[ModeMigratePrefix.Length..], args);
    }
    if (mode == ModeSeed)
    {
        return await RunSeedAsync(args);
    }
    if (mode == ModeReadiness)
    {
        return await RunReadinessAsync();
    }
    if (mode == ModeJobRunner)
    {
        return await RunJobRunnerHostAsync(args);
    }
    if (mode.StartsWith(ModeJobPrefix, StringComparison.Ordinal))
    {
        var jobName = mode[ModeJobPrefix.Length..];
        return await RunOneShotJobAsync(jobName, args);
    }
    if (mode.StartsWith(ModeServerlessJobPrefix, StringComparison.Ordinal))
    {
        var serverlessJobName = mode[ModeServerlessJobPrefix.Length..];
        return await RunOneShotServerlessJobAsync(serverlessJobName, args);
    }
    FailUnknownMode(mode);
    return 1;
}

var builder = WebApplication.CreateBuilder(args);
// Zero-env deployment config sources: connection scalars live in the mounted
// config-store.json ("connections" namespace) and credentials in docker secrets
// (one file per handle under /run/secrets, surfaced as flat config keys by
// AddKeyPerFile) -- never environment variables. Both are optional so local
// development without them falls back to appsettings.json + baked defaults.
builder.Configuration.AddJsonFile("/app/config/config-store.json", optional: true, reloadOnChange: false);
if (Directory.Exists("/run/secrets"))
{
    builder.Configuration.AddKeyPerFile("/run/secrets", optional: true);
}
// Bind Kestrel to the container-injected PORT (dockerfile_builder.py's own
// env_vars = {"PORT": str(port), ...} -- the SAME cross-language convention
// python's own container_command honors via its shell-form CMD's
// "--bind=0.0.0.0:$PORT"). Dotnet's own Dockerfile CMD is EXEC form (a JSON
// array), which unlike python's "sh -c exec ..." wrapper performs NO shell
// variable substitution -- so PORT must be read explicitly here, or Kestrel
// falls back to its own container default (8080), never the service's
// actually-configured/published port (finding: a real live compose
// deployment's HEALTHCHECK/published port target nothing without this).
var portEnv = Environment.GetEnvironmentVariable("PORT");
if (!string.IsNullOrEmpty(portEnv))
{
    builder.WebHost.UseUrls($"http://+:{portEnv}");
}
// A pubsub/queue consumer BackgroundService that cannot reach its broker
// (transient outage, broker not yet up) must not take down this whole web
// host -- .NET's own default (BackgroundServiceExceptionBehavior.StopHost)
// would stop EVERY hosted service, including Kestrel itself, on the FIRST
// unhandled exception from ANY ONE of them. The failure is still logged via
// the standard IHostApplicationLifetime/ILogger path either way; this only
// changes whether the rest of the API (health checks, REST/GraphQL/CQRS
// surfaces, other brokers) keeps serving traffic while one broker is down.
builder.Services.Configure<HostOptions>(
    options => options.BackgroundServiceExceptionBehavior = BackgroundServiceExceptionBehavior.Ignore);
builder.Logging.AddDatrixJsonConsoleLogging();
builder.Services.AddDatrixOpenTelemetryTracing();
builder.Services.AddControllers();
builder.Services.AddOpenApi();
builder.Services.Configure<AppOptions>(builder.Configuration.GetSection(AppOptions.SectionName));
builder.Services.Configure<CorsOptions>(builder.Configuration.GetSection(CorsOptions.SectionName));
builder.Services.AddCors(corsBuilder => corsBuilder.AddDefaultPolicy(policy =>
{
    var corsOptions = builder.Configuration.GetSection(CorsOptions.SectionName).Get<CorsOptions>()
        ?? throw new InvalidOperationException("Cors configuration section is missing.");
    policy.WithOrigins(corsOptions.AllowedOrigins.ToArray())
          .WithMethods(corsOptions.AllowedMethods.ToArray())
          .WithHeaders(corsOptions.AllowedHeaders.ToArray());
}));
builder.Services.AddProblemDetails();
builder.Services.AddExceptionHandler<BookService.Errors.GlobalExceptionHandler>();
builder.Services.AddDbContext<BookServiceDbContext>(options =>
    options.UseNpgsql(BookDbConnectionOptions.BuildConnectionString(builder.Configuration))
        .AddInterceptors(new BookDbQueryDurationInterceptor()));
builder.Services.AddHealthChecks()
    .AddCheck<BookDbDatabaseHealthCheck>("rdbms.bookDb", tags: new[] { "ready" })
    .AddCheck<RedisCacheHealthCheck>("cache.redis", tags: new[] { "ready" })
    .AddCheck<DocdbNosqlHealthCheck>("nosql.docdb", tags: new[] { "ready" });
builder.Services.AddSingleton<IConnectionMultiplexer>(_ =>
    ConnectionMultiplexer.Connect(
        builder.Configuration.GetConnectionString("Redis") ?? "localhost:6379"));
builder.Services.AddSingleton<RedisRateLimiter>();
builder.AddDatrixJwtBearerAuthentication();
builder.Services.AddAuthorization(options => options.AddDatrixAuthorizationPolicies());
// HTTP metrics middleware -- IMiddleware requires explicit DI registration
// (AddTransient) alongside app.UseMiddleware<T>() below; the
// convention-based constructor-injection middleware pattern does not apply
// to IMiddleware-implementing classes.
builder.Services.AddTransient<HttpMetricsMiddleware>();
// SignalR identity hub -- server-side SignalR ships in the
// Microsoft.AspNetCore.App shared framework, no extra PackageReference. The
// hub's own [Authorize(Policy = "DatrixIdentityHub")] requires
// builder.Services.AddAuthorization(...) above to already carry that policy
// (identity_service_registration).
builder.Services.AddSignalR();
// Cache: one typed access-class singleton per declared cache entry. Every
// `{cacheBlock}.{Entry}.{method}(...)` DSL call resolves its class from here
// through AppServiceLocator (see Messaging/AppServiceLocator.cs) -- the same
// bridge `dispatch Event(...)` uses from a body with no injection surface.
builder.Services.AddSingleton<BookCache>();
builder.Services.AddSingleton<BookViewCountCache>();
// NoSQL: per-block client DI registration -- makes {Block}NosqlClient
// resolvable through AppServiceLocator.GetRequiredService<T>() from any body
// surface (transpiler._nosql_query_dispatch's where()/insert()/findById()
// lowering), the same locator-based resolution cache access uses.
builder.Services.AddSingleton<DocdbNosqlClient>();
// Pub/sub: per-block engine settings + in-process BackgroundService consumers.
builder.Services.Configure<MqConnectionSettings>(
    builder.Configuration.GetSection("Pubsub:Mq"));
builder.Services.AddSingleton<MqProducer>();
builder.Services.AddHostedService<MqConsumerService>();
// CQRS command/query bus + per-command/query handler registrations -- see
// Cqrs/CqrsBus.cs for the dispatch implementation.
builder.Services.AddCqrs();

var app = builder.Build();
// Dispatch-from-function-domain fix: module/service-level `fn`
// bodies render as `public static` methods on Functions.cs with no
// constructor/field-injection surface -- a `dispatch Event(...)` statement
// inside one resolves its producer through AppServiceLocator instead.
// Initialized here, immediately after the host's IServiceProvider is built,
// before any request can reach a controller that might call into Functions.
AppServiceLocator.Initialize(app.Services);
app.UseCors();
// HTTP metrics middleware -- registered FIRST in the pipeline (immediately
// after UseCors(), before any trusted-caller/ gateway/auth middleware) so
// every request, including ones rejected by a later middleware, is
// counted. This is the ONE unconditional /metrics mapping for this service
// -- exactly one app.MapMetrics() call exists in generated output, ever,
// even for a service that also declares an rdbms block (whose own
// query-duration metrics stay functional, unduplicated).
app.UseMiddleware<HttpMetricsMiddleware>();
app.UseHttpMetrics();
app.MapMetrics();
// Gateway JWT verification middleware -- runs BEFORE the user-JWT layer,
// mirroring TrustedCallerMiddleware's own placement.
app.UseMiddleware<GatewayAuthMiddleware>();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();
// Identity hub route -- authenticated via the "DatrixIdentityHub"
// AuthorizationPolicy (identity_service_registration above),
// JWKS-validated token in the SignalR connection handshake, no bypass
// path.
app.MapHub<IdentityHub>("/hubs/identity");
app.MapOpenApi();
app.UseExceptionHandler();
app.MapHealthChecks("/live", new HealthCheckOptions
{
    Predicate = _ => false,
});
app.MapHealthChecks("/ready", new HealthCheckOptions
{
    Predicate = check => check.Tags.Contains("ready"),
});
app.MapHealthChecks("/health", new HealthCheckOptions
{
    ResponseWriter = HealthCheckResponseWriter.WriteResponseAsync,
});
app.MapRuntimeReadiness();

app.Run();
return 0;

static string? ParseRunMode(string[] args)
{
    foreach (var arg in args)
    {
        if (arg == RunModeFlag)
        {
            var index = Array.IndexOf(args, arg);
            return index + 1 < args.Length ? args[index + 1] : null;
        }
    }
    return null;
}

static void FailUnknownMode(string mode)
{
    Console.Error.WriteLine(
        $"--datrix-run {mode} is not a recognized mode. " +
        "Supported modes today: default (web host), healthcheck --url <u>, " +
        "migrate:<block>, " +
        "job-runner, job:<name>, serverless:job:<name>, " +
        "readiness, " +
        "seed.");
}

static async Task<int> RunHealthcheckSelfProbeAsync(string[] args)
{
    var urlIndex = Array.IndexOf(args, HealthcheckUrlFlag);
    if (urlIndex < 0 || urlIndex + 1 >= args.Length)
    {
        Console.Error.WriteLine(
            $"--datrix-run healthcheck requires {HealthcheckUrlFlag} <url> " +
            "(the aspnet runtime image ships neither wget nor curl -- this " +
            "self-probe is the container HEALTHCHECK command).");
        return 1;
    }
    var url = args[urlIndex + 1];
    using var client = new HttpClient { Timeout = TimeSpan.FromSeconds(5) };
    try
    {
        var response = await client.GetAsync(url);
        return response.IsSuccessStatusCode ? 0 : 1;
    }
    catch (Exception ex)
    {
        Console.Error.WriteLine($"Healthcheck probe to {url} failed: {ex.Message}");
        return 1;
    }
}


static async Task<int> RunJobRunnerHostAsync(string[] args)
{
    // Non-web host -- no WebApplication.CreateBuilder, no Kestrel binding
    // (negative: a job-runner container never listens on a port -- G2/G4
    // distinguish it from the web-host container at the Compose layer).
    // Registers Quartz (AddQuartz + AddQuartzHostedService, cron triggers
    // from BookService.Jobs.JobsRegistration) AND the pubsub/queue
    // consumer BackgroundServices in the SAME host, so one job-runner
    // container per service covers both scheduled jobs and long-running
    // consumers (dotnet's per-service Quartz host is an INTENTIONAL
    // divergence from python's per-job runner shape, see runtime_spec.py's
    // own job_runner_command docstring).
    var host = Host.CreateDefaultBuilder(args)
        .ConfigureServices((context, services) =>
        {
            // Quartz/BackgroundService job and consumer classes resolve their
            // own constructor-injected DbContext from THIS host's own DI
            // container (Quartz.Extensions.Hosting's AddJob<T> instantiates
            // via the container passed to ConfigureServices, not the web
            // host's) -- registered here even though this host binds no
            // Kestrel port. Uses the services/context.Configuration-receiver
            // rendering (this scope has no "builder" identifier at all).
                        services.AddDbContext<BookServiceDbContext>(options =>
                options.UseNpgsql(BookDbConnectionOptions.BuildConnectionString(context.Configuration))
                    .AddInterceptors(new BookDbQueryDurationInterceptor()));
                        services.AddDotnetJobs();
                        services.Configure<MqConnectionSettings>(
                context.Configuration.GetSection("Pubsub:Mq"));
            services.AddSingleton<MqProducer>();
            services.AddHostedService<MqConsumerService>();
        })
        .Build();
    // Same AppServiceLocator initialization the web host performs above --
    // this non-web host also registers pubsub producer singletons
    // (consumer_service_registration), so a Functions.cs dispatch reached
    // from THIS host's own consumer/job code needs the SAME bridge live.
    AppServiceLocator.Initialize(host.Services);
    await host.RunAsync();
    return 0;
}

static async Task<int> RunOneShotJobAsync(string jobName, string[] args)
{
    // Runs exactly ONE job by name and exits -- never starts the Quartz
    // scheduler (negative: the one-shot entrypoint is not an always-on
    // host). Local/dev invocation shape; the platform-invoked shape is
    // RunOneShotServerlessJobAsync below.
        switch (jobName)
    {
        case "CheckOverdueBooks":
        {
            using var scope = BuildRuntimeServiceProvider().CreateScope();
            var job = ActivatorUtilities.CreateInstance<CheckOverdueBooksJob>(scope.ServiceProvider);
            await job.RunAsync();
            return 0;
        }
        case "RefreshBookCache":
        {
            using var scope = BuildRuntimeServiceProvider().CreateScope();
            var job = ActivatorUtilities.CreateInstance<RefreshBookCacheJob>(scope.ServiceProvider);
            await job.RunAsync();
            return 0;
        }
        default:
            Console.Error.WriteLine($"--datrix-run job:{jobName} does not name a declared job for this service. Declared jobs: CheckOverdueBooks, RefreshBookCache.");
            return 1;
    }
}

static async Task<int> RunOneShotServerlessJobAsync(string jobName, string[] args)
{
    // Platform-invoked shape (ACA Jobs Schedule trigger / EventBridge
    // Scheduler -> ECS RunTask, scope) -- same one-shot semantics as
    // RunOneShotJobAsync, addressed by JOB NAME for the service-level
    // jobs_block (a dotnet service has at most one, so there is no separate
    // "block" identifier to discriminate on for that case), OR by a
    // CONTAINER-platform serverless scheduler block's own SNAKE NAME:
    // `datrix-codegen-docker` always addresses
    // `serverless_entrypoint_command("scheduler", ...)` with the block's
    // snake name, never an individual job's own name, so
    // `job_class_names`/`one_shot_serverless_job_dispatch_body` carries a
    // `(block_snake, class_name)` entry for each such block alongside the
    // service-level `(job_name, class_name)` entries -- both switch on the
    // SAME `jobName` parameter here, by construction never colliding names.
        switch (jobName)
    {
        case "CheckOverdueBooks":
        {
            using var scope = BuildRuntimeServiceProvider().CreateScope();
            var job = ActivatorUtilities.CreateInstance<CheckOverdueBooksJob>(scope.ServiceProvider);
            await job.RunAsync();
            return 0;
        }
        case "RefreshBookCache":
        {
            using var scope = BuildRuntimeServiceProvider().CreateScope();
            var job = ActivatorUtilities.CreateInstance<RefreshBookCacheJob>(scope.ServiceProvider);
            await job.RunAsync();
            return 0;
        }
        default:
            Console.Error.WriteLine($"--datrix-run job:{jobName} does not name a declared job for this service. Declared jobs: CheckOverdueBooks, RefreshBookCache.");
            return 1;
    }
}




// Minimal, Kestrel-free DI container for one-shot migrate / seed / job /
// readiness CLI invocations. The guard above must cover EVERY caller of this
// helper, not just the migrate/seed pair it was first written for: the
// one-shot job dispatch (`RunOneShotJobAsync`, guarded by `has_jobs or
// has_container_scheduler_jobs`) and `RunReadinessAsync` (guarded by
// `has_runtime_readiness`) also call it, so a service whose only feature
// needing this provider is the readiness surface -- no rdbms block, no seed,
// no jobs -- emitted the call while this definition was guarded out, which is
// CS0103 at build time.
// Host.CreateApplicationBuilder() builds the SAME
// configuration sources (appsettings.json + environment variables) as
// WebApplication.CreateBuilder() without ever binding a socket, so these
// one-shot commands never open the service's HTTP port. Scoped to just the
// persistence/seed services this dispatch needs -- never AddControllers/
// AddOpenApi/CORS/health-check registrations, which belong to the web host
// path only.
static IServiceProvider BuildRuntimeServiceProvider()
{
    var builder = Host.CreateApplicationBuilder();
    // Same zero-env config sources as the web host (see WebApplication.CreateBuilder
    // above) so one-shot migrate/seed commands resolve the SAME database
    // connection from the config-store + /run/secrets, not a bare localhost.
    builder.Configuration.AddJsonFile("/app/config/config-store.json", optional: true, reloadOnChange: false);
    if (Directory.Exists("/run/secrets"))
    {
        builder.Configuration.AddKeyPerFile("/run/secrets", optional: true);
    }
    builder.Services.AddDbContext<BookServiceDbContext>(options =>
    options.UseNpgsql(BookDbConnectionOptions.BuildConnectionString(builder.Configuration))
        .AddInterceptors(new BookDbQueryDurationInterceptor()));
    builder.Services.AddFluentMigratorCore()
        .ConfigureRunner(rb =>
        {
            // FluentMigrator discovers this service's [Migration] classes by
            // ASSEMBLY SCAN of its own assembly -- never a compile-time
            // reference to a specific migration class or the Migrations
            // namespace, so Program.cs compiles standalone even before any
            // [Migration] class has been rendered (an empty scan is valid).
            // The migration adapter renders the [Migration] classes
            // into Migrations/BookDb/ over time; this
            // runtime scan finds them.
            var bookDbMigrationConnectionString =
                BookDbConnectionOptions.BuildConnectionString(builder.Configuration);
            rb.AddPostgres()
                .WithGlobalConnectionString(bookDbMigrationConnectionString)
                .ScanIn(typeof(Program).Assembly).For.Migrations();
        })
        .AddLogging(lb => lb.AddFluentMigratorConsole());
    return builder.Build().Services;
}

static Task<int> RunMigrateAsync(string blockKebab, string[] args)
{
    _ = args;
    switch (blockKebab)
    {
        case "book-db":
        {
            try
            {
                using var scope = BuildRuntimeServiceProvider().CreateScope();
                var runner = scope.ServiceProvider.GetRequiredService<IMigrationRunner>();
                runner.MigrateUp();
                return Task.FromResult(0);
            }
            catch (Exception ex)
            {
                Console.Error.WriteLine($"--datrix-run migrate:{blockKebab} failed: {ex.Message}");
                return Task.FromResult(1);
            }
        }
        default:
            Console.Error.WriteLine(
                $"--datrix-run migrate:{blockKebab} does not name a declared rdbms block " +
                "for this service. Declared blocks: book-db.");
            return Task.FromResult(1);
    }
}

static Task<int> RunSeedAsync(string[] args)
{
    _ = args;
    Console.Error.WriteLine("--datrix-run seed: this service declares no SeedDSL seed sets.");
    return Task.FromResult(1);
}

static async Task<int> RunReadinessAsync()
{
    using var scope = BuildRuntimeServiceProvider().CreateScope();
    var configuration = scope.ServiceProvider.GetRequiredService<IConfiguration>();
    var report = await RuntimeReadiness.CheckAsync(configuration);
    foreach (var item in report.Items)
    {
        Console.WriteLine($"{item.Kind}\t{item.LogicalName}\t{item.RenderedName}\t{item.Status}");
    }
    return report.Ok ? 0 : 1;
}


// Exposes the compiler-generated top-level-statements Program class to the
// test project's `WebApplicationFactory<Program>`. Top-level statements always
// generate an `internal partial class Program` in the GLOBAL namespace
// regardless of <RootNamespace> -- without this explicit `public partial class
// Program { }`, `TtlReadinessTests.cs` (emitted into EVERY service's own test
// project) fails a real `dotnet build` with CS0122 ("Program is inaccessible
// due to its protection level"). Standard, official ASP.NET Core
// integration-testing pattern -- see
// https://learn.microsoft.com/en-us/aspnet/core/test/integration-tests.
public partial class Program { }
